### ISSUE TITLE
regression: adds `-mode` to hooks

### ISSUE THREAD

**Issue by ensc** [jwiegley/use-package#1000]
With

```elisp
(use-package some-lib
  :defer 1
  :hook ((other-mode . 'some-lib/conf-fn)))

(message "hook: %s" other-mode-hook)
```

I got with use-package-20210207.1926

```
"hook: (some-lib)"
````

But now with use-package-20220910.25, it is

```
"hook: (some-lib-mode)"
```

This breaks existing configurations when `some-lib` does not define ` -mode` function.

**Comment by doolio** [comment]
Why are you using a quote here? Does the following not work for you?

```emacs-lisp
(use-package some-lib
  :defer 1
  :hook (other-mode . conf-fn))
```

**Comment by ensc** [comment]
without quoting it works; thx
