### ISSUE TITLE
:inherit for :custom-face no more works same way

### ISSUE THREAD

**Issue by tttuuu888** [jwiegley/use-package#1008]
First of all, I would like to appreciate to @jwiegley and every contributors for great effort for this great package.

Recent pull request #1004 has changed how `:custom-face` working.
Previously `:inherit` overwrite all attributes of current face but now `:inherit` merge attributes to current face if the attribute of current face is unspecified.
This matches description of `face-spec-set` but people, including me who were using `:inherit` in previous way lost way to set face using `:custom-face`.

On the other hand, `face-spec-set` has optional argument SPEC-TYPE and if `'face-defface-spec'` is given, it works as same as previous `:custom-face`.
But I couldn't find a way to give this optional SPEC-TYPE argument to `:custom-face`.

So I was wondering if there is already a way to give a SPEC-TYPE argument to `:custom-face`, or if it doesn't, it can support this feature.

Thank you.

**Comment by andreyorst** [comment]
@tttuuu888 IIUUC you can do this:

```emacs-lisp
(use-package foo
  :custom-face
  (foo-face ((t (:inherit unspecified) face-defface-spec))))
```

**Comment by andreyorst** [comment]
Ah, no, my mistake, it won't work this way

**Comment by andreyorst** [comment]
@tttuuu888 Can you check if this patch works for you? https://patch-diff.githubusercontent.com/raw/jwiegley/use-package/pull/1009.patch

Also, if you could provide a minimal example code of what has changed so perhaps we could add a test for this?

**Comment by andreyorst** [comment]
@jwiegley I wonder if instead of supplying the third argument we should just set the `spec-type` to `face-defface-spec` by default. WDYT?

**Comment by jwiegley** [comment]
@andreyorst I've merged in the fix, but open to changes!
