### ISSUE TITLE
How to unset a keybinding in a map locally to a mode?

### ISSUE THREAD

**Issue by stardiviner** [jwiegley/use-package#103]
http://stackoverflow.com/questions/22834506/how-to-unset-a-keybinding-in-a-map-locally-to-a-mode

I found your emacs mode named "bind-key" but it closed issue post. So I post my issue here.

Can you do that (unset a keybinding in a map locally to a mode) ?

**Comment by jwiegley** [comment]
I don't think this is an issue in bind-key.
