### ISSUE TITLE
Is there anything to be learned from leaf?

### ISSUE THREAD

**Issue by dabrahams** [jwiegley/use-package#1038]
I don't know how to evaluate the differences but https://github.com/conao3/leaf.el is perhaps worth noticing and maybe some features or code should be incorporated into use-package(?)

**Comment by doolio** [comment]
Also, [setup.el](https://www.emacswiki.org/emacs/SetupEl).

**Comment by jwiegley** [comment]
@dabrahams Do you have anything you've learned from `leaf.el` to suggest? My cursory review didn't reveal much.

**Comment by dabrahams** [comment]
Not really.  Sorry, this might’ve just been noise.

**Comment by jwiegley** [comment]
No worries, thanks for writing back! I did give the docs a glance myself, and saw a few nice utility functions, like jumping to definition (which of course would require maintaining a hash table on start from package names to positions), but I think I'll leave these for the community to contribute.
