### ISSUE TITLE
Binding `C-[` breaks all meta-keybindings

### ISSUE THREAD

**Issue by adimit** [jwiegley/use-package#1039]
Here's a minimal config:

```emacs-lisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)

(use-package smartparens
  :ensure t
  :bind (("C-]" . sp-forward-slurp-sexp) ; doesn't break
	 ("C-[" . sp-forward-barf-sexp))) ; breaks
```

I'm using Emacs 29 (haven't tried with stable Emacs yet, but I could, if it's not reproducible).

After loading above config, pressing `M-x` will result in user error `M-x is undefined`.

This seems to be a [general problem in Emacs](https://emacs.stackexchange.com/questions/7832/how-to-bind-c-for-real), not necessarily related to `use-package`. Perhaps it's impossible for `use-package` to handle this case :confused:

**Comment by skangas** [comment]
Yes, this seems to be a limitation in Emacs itself. Tested with this in emacs -Q:

```
(global-set-key (kbd "C-[") (lambda () (message "foo")))
```

Unfortunately, I don't think there is anything we can do about this in use-package itself. If this is to be changed, it has to be done in Emacs.

I'm therefore closing this bug.
