### ISSUE TITLE
function opposite of use-package-always-ensure?

### ISSUE THREAD

**Issue by sg-qwt** [jwiegley/use-package#1043]
Hi there,

Wondering if there's any variable setup can do the exact opposite of use-package-always-ensure?
 
Use case: 
I'm using other methods to manage elisp packages, thus I want to completely prevent use-package from downloading packages on its own, even if I accidentally copied some use-package snippet from online with `:ensure t`. 

I only use use-package to manage configs this case. Something like use-package-always-no-install maybe?

Thanks!

**Comment by conao3** [comment]
`:ensure` is handled by `use-package-handler/:ensure` function. So, you can re-define this function as an empty function, `:ensure` should be a no-meaning keyword.

demo
```elisp
(use-package neoemacs :ensure t)
;;=> (error "Package 'neoemacs' is unavailable")

(defalias 'use-package-handler/:ensure 'ignore)
;;=> use-package-handler/:ensure

(use-package neoemacs :ensure t)
;;=> nil
```

hope this helps.

**Comment by sg-qwt** [comment]
> `:ensure` is handled by `use-package-handler/:ensure` function. So, you can re-define this function as an empty function, `:ensure` should be a no-meaning keyword.
> 
> demo
> 
> ```emacs-lisp
> (use-package neoemacs :ensure t)
> ;;=> (error "Package 'neoemacs' is unavailable")
> 
> (defalias 'use-package-handler/:ensure 'ignore)
> ;;=> use-package-handler/:ensure
> 
> (use-package neoemacs :ensure t)
> ;;=> nil
> ```
> 
> hope this helps.

That would do the trick. Thanks for this! Appreciated!
