### ISSUE TITLE
Emacs29 Install From Source with: `package-vc-install`

### ISSUE THREAD

**Issue by bradschwartz** [jwiegley/use-package#1050]
It looks like emacs@29 now has a function `package-vc-install`. It seems like this package *doesn't* want to be a package manager but since it already has support built-in on using package.el, would it make sense to also let it rely on the new package `package-vc` as well? Would make it super simple to use `use-package` for _all_ package loading, even those that aren't published on (M)ELPA. 

It also seems like this is now going to be bundled with emacs 29, so if the mailing threads are a better place to drop this, happy to drop there as well!

**Comment by yassernasc** [comment]
related: https://github.com/slotThe/vc-use-package

**Comment by skangas** [comment]
This feature is already there on Emacs master, and will be part of the next version of use-package. The use-package info manual says:

```
   The ‘:vc’ keyword can be used to control how packages are downloaded
and/or installed.  More specifically, it allows one to fetch and update
packages directly from a version control system.  This is especially
convenient when wanting to install a package that is not on any package
archive.
```

I'm therefore closing this issue.
