### ISSUE TITLE
Allow multiple packages for :ensure

### ISSUE THREAD

**Issue by superbobry** [jwiegley/use-package#111]
Hello, is it possible to make `:ensure` work with multiple packages? For instance, I'd like the following to install and require **both** packages:

```elisp
(use-package yasnippet
  :ensure (yasnippet dropdown-list))
```

**Comment by superbobry** [comment]
@jwiegley was this implemented or you've decided not to complicate the `:ensure` logic?

**Comment by jwiegley** [comment]
I decided not to complicate the `:ensure` logic, but I'm certainly willing to review a PR.
