### ISSUE TITLE
Feature Request - describe-personal-keybindings to show :prefix-map

### ISSUE THREAD

**Issue by peterhoeg** [jwiegley/use-package#113]
It would be super, if `describe-personal-keybindings` would show the prefix-map in use for the bindings in question.

Currently, this is the output:

```text
projectile-rails-mode-goto-map
-------------------------------------------------------------------------------
m                 `projectile-rails-find-current-model'
```

For this configuration:

```elisp
(bind-keys :prefix-map projectile-rails-mode-goto-map
           :prefix "C-x p"
           ("m" . projectile-rails-find-current-model))))
```

Ideally `describe-personal-keybindings` would show the "C-x p" as well somewhere.

**Comment by jwiegley** [comment]
@npostavs Can you turn your patch into a PR? :)
