### ISSUE TITLE
Attach comments to binding

### ISSUE THREAD

**Issue by AdrieanKhisbe** [jwiegley/use-package#114]
When running `describe-personal-bindings` I see there is a column named `Comments`, but nothing happens in it.
> Key name             Command                   Comments
> ----------------- --------------------------------------- ---------------------
> C-x s                     `sr-speedbar-toggle'

*Was wondering if this is for specifying conflicts, keymap or if there was a way one could specify the comments he wants in the bind statement?*

(If it's not used for anything so far, it might be a good feature to enable user to specify such comments. For instance with this syntax:

```emacs-lisp
 (use-package sr-speedbar
               :bind ("C-x s" . sr-speedbar-toggle   "testing" )
```
we could get in `describe-personal-bindings` this:

> Key name             Command                   Comments
> ----------------- --------------------------------------- ---------------------
> C-x s                     `sr-speedbar-toggle'                 testing

**Comment by jwiegley** [comment]
The Comments column is used to communicate details under specific conditions, and not for general use by the user.
