### ISSUE TITLE
Surprising behavior with :mode

### ISSUE THREAD

**Issue by mcandre** [jwiegley/use-package#116]
I want Emacs to treat `.reek` files as yaml-mode. I add the following to my [.emacs](https://github.com/mcandre/dotfiles/blob/master/.emacs):

```
(use-package yaml-mode
  :mode "\\.reek\\'")
```

Strangely, this had no effect on how `.reek` files were treated (they opened as Fundamental).

I wonder if other packages I'm using might be loading the yaml-mode package early, causing `use-package` to skip my code?

Whatever the cause, I'm able to work around this issue by making the mode registration more explicit:

```
(use-package yaml-mode
  :init
  (add-to-list 'auto-mode-alist '("\\.reek\\'" . yaml-mode)))
```

Is there something I can do in my `.emacs`, or `use-package` can fix, so that I can use the shorter form?

**Comment by jwiegley** [comment]
@mcandre Is this still failing for you?
