### ISSUE TITLE
Compile warning when ess-site is use-package'd

### ISSUE THREAD

**Issue by mcandre** [jwiegley/use-package#117]
Two nifty things I have in my [.emacs](https://github.com/mcandre/dotfiles/blob/master/.emacs) are a save-compile hook and an R-mode autoload:

```
;; Compile .emacs on save
(add-hook 'after-save-hook
          (lambda ()
            ;; (interactive)
            ;; (require 'bytecomp)
            (let ((dotemacs (expand-file-name "~/.emacs")))
              (if (string= (buffer-file-name) (file-chase-links dotemacs))
                  (byte-compile-file dotemacs)))))

;; Open .R files as R-mode
(autoload 'R-mode "ess-site.el" "" t)
(add-to-list 'auto-mode-alist '("\\.R\\'" . R-mode))
```

When I try to `use-package`-ify R-mode / ess-site instead, a weird thing happens.

```
;; Open .R files as R-mode
(use-package ess-site
   :mode ("\\.R\\'" . R-mode))
```

R-mode continues to load successfully for `.R` files under `use-package`, as it did before. However, when I save and compile my `~/.emacs`, Emacs shows a warning:

```
~/.emacs:586:1:Warning: the function `poin-max' is not known to be defined.
```

This function should be spelled `point-max`, not `poin-max`. And indeed, I correctly call it `point-max` everywhere I reference it in my `~/.emacs`.

Even stranger, this warning only appears the first time I compile my `~/.emacs`; Repeated saves / compiles do not produce this warning. But the next time I launch Emacs, save and compile, the warning appears again.

I believe this is an issue with the Lisp code that `use-package` generates. Maybe `use-package` is creating a syntax error?

Emacs 24, Mac OS X 10.9.4.

**Comment by jwiegley** [comment]
@mcandre Try this new feature:

``` elisp
;; Open .R files as R-mode
(use-package ess-site
   :functions poin-max
   :mode ("\\.R\\'" . R-mode))
```
