### ISSUE TITLE
How to bind keys with use-package bind in mode maps?

### ISSUE THREAD

**Issue by mcandre** [jwiegley/use-package#121]
I would like to use use-package to bind keys in markdown-mode, but markdown-mode uses a strange markdown-mode-map variable to manage its keybindings. Is there a way to detect this oddity and work around it in use-package?

**Comment by jwiegley** [comment]
@mcandre This feature will be coming shortly, and will probably look like this:

``` elisp
(use-package foo
  :bind (:map markdown-mode-map
            ("<some-key>" . some-function)))
```

Anything before a `:map` is global, anything after a `:map` applies to that keymap, multiple keymaps can be specified.

**Comment by jwiegley** [comment]
The above syntax should now work, as `use-package` is now using `bind-keys` under the hood, rather than just `bind-key`.  It means you can do other nifty stuff too, like create your own prefix maps on the fly.

**Comment by dbordak** [comment]
That syntax doesn't work for me. I get ":bind wants a string, (string . symbol) or list of these."

**Comment by jwiegley** [comment]
Oh, whoops, I didn't extend the normalization check yet.

**Comment by mdorman** [comment]
Also, it's undocumented, as is bind-keymap.

**Comment by bolasblack** [comment]
Because I tried patch use-package to support the `(:map mapname (string . symbol))` but failed. So I wrote an [extension](https://github.com/bolasblack/.emacsrc/blob/master/lisps/use-package_bind-map.el) to support it , you can use it like [this](https://github.com/bolasblack/.emacsrc/blob/master/conf/plugin.el#L54), and when @jwiegley finished the work, you can migrate it easily.

**Comment by belak** [comment]
What is the status on this?

**Comment by dsvensson** [comment]
Perhaps @jwiegley could mentor @bolasblack to get this fixed here upstream?

**Comment by jwiegley** [comment]
I started work on this, then it got shelved due to other pressing matters.  I'd be happy to mentor someone to finish it up.

**Comment by vapniks** [comment]
Would be nice if you could bind multiple keys to the same keymap in one sexp. I have some modes with lots of keybindings that I want autoloaded.

**Comment by vapniks** [comment]
I coult finish it up for you if you can give me some hints..

**Comment by jwiegley** [comment]
Binding multiple keys for a keymap should already work, we just need to fix the validator.

**Comment by jwiegley** [comment]
Actually, for now the easiest solution will be just to disable the validator.  I can do that today.

**Comment by nickalcock** [comment]
This doesn't seem to have happened. I've done the change if you want it, but I suspect you've done it and just forgot to push :)

**Comment by jwiegley** [comment]
can you PR me?  I'm not sure what state my version of this is in anymore.

**Comment by nickalcock** [comment]
Once I get it working, sure :) I thought it was working, but it's, er, not. I'll get back to it later tonight.

**Comment by nickalcock** [comment]
OK, that seems to work. PR#234 created.

**Comment by nickalcock** [comment]
Well, that didn't work at all. Should work better now: PR#235 doesn't break anything I've tried, allows your syntax, and does pretty much what you suggested (though the handler had to change too, to avoid considering non-list-elements to be commands that needed autoloading.)

**Comment by jasonm23** [comment]
```
:bind (:map map (("key" . function)("key" . function)("key" . function))) 
```
Seems to be working for me now.

**Comment by Bost** [comment]
I get
    mapcar: Wrong type argument: listp, :map
when evaluating:
```elisp
  :bind (("key" . function)
         :map map
         (("key" . function)
          ("key" . function)
          ("key" . function)))

**Comment by jasonm23** [comment]
@Bost you would need to separate out your global and :map entries as separate lists.

**Comment by jasonm23** [comment]
@Bost (I think!)

**Comment by glucas** [comment]
To define global and map bindings it looks like you can use multiple :bind entries, like so:

    (use-package counsel
      :bind (("M-x" . counsel-M-x)
                ("C-x C-f" . counsel-find-file))
      :bind (:map help-map
                  ("f" . counsel-describe-function)
                  ("v" . counsel-describe-variable)
                  ("C-l" . counsel-info-lookup-symbol)))

**Comment by jwiegley** [comment]
This is also meant to work (though may not today):

``` elisp
(use-package counsel
  :bind (("M-x" . counsel-M-x)
            ("C-x C-f" . counsel-find-file)
            :map help-map
            ("f" . counsel-describe-function)
            ("v" . counsel-describe-variable)
            ("C-l" . counsel-info-lookup-symbol)))
```

**Comment by manuel-uberti** [comment]
I get `mapcar: Wrong type argument: listp, :map` with a config similar to the one above:
```
(use-package swiper                     ; Isearch with an overview
  :ensure t
  :bind (("C-c s s" . swiper)
         ("C-c s S" . swiper-all)
         :map isearch-mode-map
         ("M-i"     . swiper-from-isearch)))
```

**Comment by jwiegley** [comment]
@manuel-uberti It just hasn't been implemented yet.

**Comment by manuel-uberti** [comment]
Oh I see. Forget my comment, then. :-)

**Comment by IvanMalison** [comment]
@jwiegley is anyone working on this/are there plans to work on this?

**Comment by jwiegley** [comment]
The following now works:

``` elisp
(use-package term
  :bind (:map term-mode-map
         ("M-p" . term-send-up)
         ("M-n" . term-send-down)
         :map term-raw-map
         ("M-o" . other-window)
         ("M-p" . term-send-up)
         ("M-n" . term-send-down)))
```

**Comment by jwiegley** [comment]
Next step is to autoload the keymaps.

**Comment by andschwa** [comment]
@jwiegley Dang you have nice timing. I was just looking for this to setup some `evil-mode` "state" specific bindings :smile:

**Comment by manuel-uberti** [comment]
Thanks a lot, John!

**Comment by matthew-piziak** [comment]
Just what I was looking for. Thanks John!

**Comment by vapniks** [comment]
great work!

**Comment by bolasblack** [comment]
:+1:

**Comment by blaenk** [comment]
@jwiegley 

> Next step is to autoload the keymaps.

I take it that's not done yet? Would that mean that, for example, right now when I try something like this:

``` elisp
(use-package evil
  :bind (:map evil-emacs-state-map
              ("C-w" . evil-window-map))
  ...)
```

I get an error saying that the symbol `evil-emacs-state-map` isn't defined or something. I imagine because it's trying to add it to the map before evil has even loaded? Is that what your quote, once implemented, would resolve?

**Comment by stathissideris** [comment]
I get the same with as @blaenk - it looks like it's trying to add bindings to maps before they are defined. I tried using `:defines` to fix it but it didn't make any difference.

**Comment by carrete** [comment]
Ditto.

    (use-package python
      :bind
      (:map python-mode-map ("C-c C-c" . tvaughan/python-mode-map)))

Does not work.

**Comment by blaenk** [comment]
I forgot to mention that after encountering this issue I found out about [general.el](https://github.com/noctuid/general.el) which is more or less an alternative to bind-key. I suggested to the author of it to implement [use-package integration](https://github.com/noctuid/general.el#use-package-keyword) and he was gracious enough to do so. For my uses general.el is much more useful and indeed handles this situation perfectly.

So something like what @carrete wrote might look like this with general:

``` elisp
(use-package python
  :general
  (:keymaps 'python-mode-map
    "C-c C-c" 'tvaughan/python-mode-map))
```

You can also do the reverse, where you essentially "mount" python's keymap to another bind like `C-x p` for python, i.e. you press `C-x p` and you would then be "within" python-mode-map. The problem there is that python-mode-map won't exist yet because it's deferred/autoloaded. You can make it so that pressing `C-x p` triggers the autoload of python-mode (and thus python-mode-map) on-the-fly by doing something like this:

``` elisp
(use-package python
  :general
  ("C-x p" '(:keymap python-mode-map))
```

**Comment by jwiegley** [comment]
`general.el` sounds like a nice alternative for those who need support that `bind-key` doesn't presently offer.

**Comment by carrete** [comment]
Thanks for the tip @blaenk!

**Comment by lyr3** [comment]
What am I doing wrong? 

```
  :bind (:map company-active-map 
              ("C-n" . company-select-next)
              ("C-p" . company-select-previous))
```

Flycheck:   error           Wrong type argument: sequencep, company-select-next (emacs-lisp)

**Comment by jwiegley** [comment]
I don't know, I don't use flycheck to check emacs-lisp code.
