### ISSUE TITLE
unload features before installing packages with :ensure

### ISSUE THREAD

**Issue by shackra** [jwiegley/use-package#127]
I'm looking to this feature for cases like `org-mode` [that advice you to don't load any org file to avoid issues when updating to 8.x](http://orgmode.org/org.html#Installation), I know that you can [unload features](http://www.gnu.org/software/emacs/manual/html_node/elisp/Unloading.html#Unloading), someone else in the Emacs IRC channel suggested me to use [unintern](https://www.gnu.org/software/emacs/manual/html_node/elisp/Creating-Symbols.html).

I guess that for this feature, simply allow the user to run any elisp code before :ensure does it's job *if, and only if,* a package does not exists and need to be installed.

**Comment by jwiegley** [comment]
Not going to implement in use-package.
