### ISSUE TITLE
Store list of packages invoked by `(use-package ...)

### ISSUE THREAD

**Issue by jleechpe** [jwiegley/use-package#131]
Is there any built-in method to keep track of all packages that are invoked by `(use-package ...)`?

I currently have the following in my `init.el`

```lisp
(defvar my/use-package-packages '())

(defadvice use-package (after list-package activate)
  (add-to-list 'my/use-package-packages name))
```

I've been using this to then compare the packages listed to those that are currently installed/available, so that if any are missing I can install them (`package.el` or `el-get`).  I can also compare this back against the list of packages installed by `el-get` to see which haven't been loaded to track down packages I tested but do not need/want.

**Comment by jwiegley** [comment]
Until others have a need for this, closing, since it can be achieved in the isolation case by `defadvice`.
