### ISSUE TITLE
Right way to handle hook ?

### ISSUE THREAD

**Issue by ctjhoa** [jwiegley/use-package#132]
Hi all,
I'm new to emacs.
I'd like to conditionally load package if I'm in specific mode. Here how I'm doing it now:

```
(use-package rainbow-delimiters
  :ensure
  :init
  (progn
    (add-hook 'emacs-lisp-mode-hook (lambda()
				      (rainbow-delimiters-mode t)))))
```

I've also noticed a " :if " use-package's attribute and i'm wondering if it could be used for that purpose ? If yes how to check if the mode is active ?

So I would like to know what is the best option in the light of your experience?

Thanks.

**Comment by thiagowfx** [comment]
In my experience, `add-hook` is the best option indeed. If you find yourself frequently using `add-hook` with several modes, it might be worth to create a list and iterate over it to avoid duplication of code (it isn't hard to find examples of this out there).

**Comment by ctjhoa** [comment]
Ok thanks @thiagowfx

**Comment by jwiegley** [comment]
Also, I think it should be `:ensure t`.

**Comment by YoungFrog** [comment]
> Also, I think it should be :ensure t.

":ensure" is sufficient since PR #84 was merged.

**Comment by jwiegley** [comment]
Learn something every day. :)
