### ISSUE TITLE
call package-refresh-contents when package can not be found and :ensure was used

### ISSUE THREAD

**Issue by IvanMalison** [jwiegley/use-package#134]
My configuration will occasionally fail to load when I install a package that was not part of the relevant archive when the package archives that live in .emacs.d/elpa/archives were last refreshed.

Perhaps use-package should attempt to refresh the package archive when it encounters this error?

**Comment by jwiegley** [comment]
Not addressing inside use-package unless someone can show me an implementation to solve this.

**Comment by IvanMalison** [comment]
Why wouldn't wrapping the code that retrieves the package with condition-case, and then trying a single refresh if that fails work?

**Comment by jwiegley** [comment]
That doesn't sound unreasonable, would you like to have a crack at it?
