### ISSUE TITLE
Autoloading problems with org-mode

### ISSUE THREAD

**Issue by cubranic** [jwiegley/use-package#135]
When I try to use org-mode with:
```elisp
(use-package org
  :bind ("C-c c" . org-capture))
```

when I press "C-c c", I get the following error message: "Autoloading failed to define function org-capture".

I can solve this in two ways, but both seem kludgey:

1. add `:demand` keyword
2. do the binding as part of `:init`, which works even if I defer the loading of the package:
```elisp
(use-package org
  :defer t
  :init
  (bind-key "C-c c" 'org-capture))
```

Since workaround 2 does not mess up the auto loads, is there a bug in how using `:bind` sets them up?

**Comment by thomasf** [comment]
Mine just look like this

```
(use-package org
  :ensure org-plus-contrib
  :commands (org
             org-capture
             org-mode
             org-store-link
             update-org-hours
             my-term-agenda
             dired-notes
             jump-to-org-agenda)
  :mode (("\\.org_archive\\'" . org-mode)
         ("\\.org\\'" . org-mode))
...
```

**Comment by YoungFrog** [comment]
@thomasf  I'm sorry I'm not sure I followed you. Do I understand right that you are reporting something to work around the initial problem ?

**Comment by thomasf** [comment]
Oh, yes.. I think I misread the situation, followed too many links without checking the context.

**Comment by jwiegley** [comment]
@thomasf Is there still work needing to be done here, or should we close this?  I had to revert @YoungFrog's fix mentioned above, so if that still needs to be addressed, we should open a new issue for it.

**Comment by jwiegley** [comment]
@cubranic `use-package` should not clobber your autoloads anymore, can you please see if this issue is still a problem for you?

**Comment by chuchana** [comment]
@thomasf Thank you!

I had to look through the list of issues until I found this, so it would be nice to add something like this to the readme: 

> If you get an error like `Symbol's value as variable is void: name`, you have probably used the wrong package name. For example, you have to add `org-plus-contrib` like this: 
> ~~~
> (use-package org
>   :ensure org-plus-contrib)
> ~~~

I am not sure where, though. At the bottom, in a new section called `Errors`?
