### ISSUE TITLE
M-x describe-personal-keybindings fails with wrong argument

### ISSUE THREAD

**Issue by xmaillard** [jwiegley/use-package#143]
Hello John,

I am configuring magit via a personnal prefix-map (C-x g) this way:

``` emacslisp
(use-package magit
  :pre-load
  (progn
    (define-prefix-command 'xma-magit-keymap))
  :commands magit-status
  :bind (("C-x g" . xma-magit-keymap))
  :init
  (progn
    (bind-key (vector ?g) 'magit-status 'xma-magit-keymap)
...
))
```
It works as far as I can see but doing M-x dpk produces this:

Debugger entered--Lisp error: (wrong-type-argument symbolp (quote xma-magit-keymap))
  symbol-value((quote xma-magit-keymap))
  (or (symbol-value (cdar binding)) (current-global-map))
  (lookup-key (or (symbol-value (cdar binding)) (current-global-map)) (read-kbd-macro key-name))
  (let* ((key-name (caar binding)) (at-present (lookup-key (or (symbol-value (cdar binding)) (current-global-map)) (read-kbd-macro key-name))) (command (nth 1 binding)) (was-command (nth 2 binding)) (command-desc (get-binding-description command)) (was-command-desc (and was-command (get-binding-description was-command))) (at-present-desc (get-binding-description at-present))) (let ((line (format (format "%%-%ds%%-%ds%%s\n" (car bind-key-column-widths) (cdr bind-key-column-widths)) key-name (format "`%s'" command-desc) (if (string= command-desc at-present-desc) (if (or ... ...) "" (format "was `%s'" was-command-desc)) (format "[now: `%s']" at-present))))) (princ (if (string-match "[ 	]+\n" line) (replace-match "\n" t t line) line))))
  (while --dolist-tail-- (setq binding (car --dolist-tail--)) (if (not (eq (cdar last-binding) (cdar binding))) (princ (format "\n\n%s\n%s\n\n" (cdar binding) (make-string (+ 21 (car bind-key-column-widths) (cdr bind-key-column-widths)) 45))) (if (and last-binding (cdr (compare-keybindings last-binding binding))) (princ "\n"))) (let* ((key-name (caar binding)) (at-present (lookup-key (or (symbol-value (cdar binding)) (current-global-map)) (read-kbd-macro key-name))) (command (nth 1 binding)) (was-command (nth 2 binding)) (command-desc (get-binding-description command)) (was-command-desc (and was-command (get-binding-description was-command))) (at-present-desc (get-binding-description at-present))) (let ((line (format (format "%%-%ds%%-%ds%%s\n" (car bind-key-column-widths) (cdr bind-key-column-widths)) key-name (format "`%s'" command-desc) (if (string= command-desc at-present-desc) (if ... "" ...) (format "[now: `%s']" at-present))))) (princ (if (string-match "[ 	]+\n" line) (replace-match "\n" t t line) line)))) (setq last-binding binding) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- (setq personal-keybindings (sort personal-keybindings (function (lambda (l r) (car ...)))))) binding) (while --dolist-tail-- (setq binding (car --dolist-tail--)) (if (not (eq (cdar last-binding) (cdar binding))) (princ (format "\n\n%s\n%s\n\n" (cdar binding) (make-string (+ 21 (car bind-key-column-widths) (cdr bind-key-column-widths)) 45))) (if (and last-binding (cdr (compare-keybindings last-binding binding))) (princ "\n"))) (let* ((key-name (caar binding)) (at-present (lookup-key (or (symbol-value ...) (current-global-map)) (read-kbd-macro key-name))) (command (nth 1 binding)) (was-command (nth 2 binding)) (command-desc (get-binding-description command)) (was-command-desc (and was-command (get-binding-description was-command))) (at-present-desc (get-binding-description at-present))) (let ((line (format (format "%%-%ds%%-%ds%%s\n" ... ...) key-name (format "`%s'" command-desc) (if ... ... ...)))) (princ (if (string-match "[ 	]+\n" line) (replace-match "\n" t t line) line)))) (setq last-binding binding) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let (last-binding) (let ((--dolist-tail-- (setq personal-keybindings (sort personal-keybindings (function (lambda ... ...))))) binding) (while --dolist-tail-- (setq binding (car --dolist-tail--)) (if (not (eq (cdar last-binding) (cdar binding))) (princ (format "\n\n%s\n%s\n\n" (cdar binding) (make-string (+ 21 ... ...) 45))) (if (and last-binding (cdr (compare-keybindings last-binding binding))) (princ "\n"))) (let* ((key-name (caar binding)) (at-present (lookup-key (or ... ...) (read-kbd-macro key-name))) (command (nth 1 binding)) (was-command (nth 2 binding)) (command-desc (get-binding-description command)) (was-command-desc (and was-command (get-binding-description was-command))) (at-present-desc (get-binding-description at-present))) (let ((line (format ... key-name ... ...))) (princ (if (string-match "[ 	]+\n" line) (replace-match "\n" t t line) line)))) (setq last-binding binding) (setq --dolist-tail-- (cdr --dolist-tail--)))))
  (progn (princ (format "Key name%s Command%s Comments\n%s %s ---------------------\n" (make-string (- (car bind-key-column-widths) 9) 32) (make-string (- (cdr bind-key-column-widths) 8) 32) (make-string (1- (car bind-key-column-widths)) 45) (make-string (1- (cdr bind-key-column-widths)) 45))) (let (last-binding) (let ((--dolist-tail-- (setq personal-keybindings (sort personal-keybindings (function ...)))) binding) (while --dolist-tail-- (setq binding (car --dolist-tail--)) (if (not (eq (cdar last-binding) (cdar binding))) (princ (format "\n\n%s\n%s\n\n" (cdar binding) (make-string ... 45))) (if (and last-binding (cdr ...)) (princ "\n"))) (let* ((key-name (caar binding)) (at-present (lookup-key ... ...)) (command (nth 1 binding)) (was-command (nth 2 binding)) (command-desc (get-binding-description command)) (was-command-desc (and was-command ...)) (at-present-desc (get-binding-description at-present))) (let ((line ...)) (princ (if ... ... line)))) (setq last-binding binding) (setq --dolist-tail-- (cdr --dolist-tail--))))))
  (prog1 (progn (princ (format "Key name%s Command%s Comments\n%s %s ---------------------\n" (make-string (- (car bind-key-column-widths) 9) 32) (make-string (- (cdr bind-key-column-widths) 8) 32) (make-string (1- (car bind-key-column-widths)) 45) (make-string (1- (cdr bind-key-column-widths)) 45))) (let (last-binding) (let ((--dolist-tail-- (setq personal-keybindings (sort personal-keybindings ...))) binding) (while --dolist-tail-- (setq binding (car --dolist-tail--)) (if (not (eq ... ...)) (princ (format "\n\n%s\n%s\n\n" ... ...)) (if (and last-binding ...) (princ "\n"))) (let* ((key-name ...) (at-present ...) (command ...) (was-command ...) (command-desc ...) (was-command-desc ...) (at-present-desc ...)) (let (...) (princ ...))) (setq last-binding binding) (setq --dolist-tail-- (cdr --dolist-tail--)))))) (internal-temp-output-buffer-show buf))
  (let* ((old-dir default-directory) (buf (save-current-buffer (set-buffer (get-buffer-create "*Personal Keybindings*")) (prog1 (current-buffer) (kill-all-local-variables) (setq default-directory old-dir) (setq buffer-read-only nil) (setq buffer-file-name nil) (setq buffer-undo-list t) (let ((inhibit-read-only t) (inhibit-modification-hooks t)) (erase-buffer) (run-hooks (quote temp-buffer-setup-hook)))))) (standard-output buf)) (prog1 (progn (princ (format "Key name%s Command%s Comments\n%s %s ---------------------\n" (make-string (- (car bind-key-column-widths) 9) 32) (make-string (- (cdr bind-key-column-widths) 8) 32) (make-string (1- (car bind-key-column-widths)) 45) (make-string (1- (cdr bind-key-column-widths)) 45))) (let (last-binding) (let ((--dolist-tail-- (setq personal-keybindings ...)) binding) (while --dolist-tail-- (setq binding (car --dolist-tail--)) (if (not ...) (princ ...) (if ... ...)) (let* (... ... ... ... ... ... ...) (let ... ...)) (setq last-binding binding) (setq --dolist-tail-- (cdr --dolist-tail--)))))) (internal-temp-output-buffer-show buf)))
  describe-personal-keybindings()
  funcall-interactively(describe-personal-keybindings)
  call-interactively(describe-personal-keybindings record nil)
  command-execute(describe-personal-keybindings record)
  execute-extended-command(nil "describe-personal-keybindings" nil)
  funcall-interactively(execute-extended-command nil "describe-personal-keybindings" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

(sorry for the large dump).

This happens using use-package from HEAD on GNU Emacs from a home-brew build (devel version).

regards
Xavier

**Comment by YoungFrog** [comment]
> I am configuring magit via a personnal prefix-map (C-x g) this way:
> [...]
>     (bind-key (vector ?g) 'magit-status 'xma-magit-keymap)

As a work around : don't quote the last argument.

The problem is that bind-key (in fact, describe-personal-keybindings)
can't really handle a keymap that's given as a symbol.

To support this, we could change what we store in personal-keybindings
(e.g. store the actual keymap instead of/in addition to a variable
leading to it), or hack describe-personal-keybindings to be smarter in
the exceptionnal cases (i.e. when we don't have a variable but something
else like in this case). Is it worth the trouble ?

**Comment by xmaillard** [comment]
Hello,

Thank you for the workaround, it just works which is the main goal here. I am not sure it is worth the trouble to modify that (or as an enhancement).

I guess we can close this issue now.

Still, thanks a lot.
Xavier
