### ISSUE TITLE
Keybinding with multiple packages. 

### ISSUE THREAD

**Issue by ReneFroger** [jwiegley/use-package#146]
Hi there! Thanks for sharing this awesome plugin!

I have a little question. 

For example, I have this keybinding to toggle comments: 

` (key-chord-define evil-normal-state-map "cc" 'evilnc-comment-or-uncomment-lines)`

So there are 3 plugins used: keychord, evil, and evil-commenter. 

If I do: 
`(use-package .......`
  `:bind ("cc" . evilnc-comment-or-uncomment-lines))`

How would I know which plugin to use on the empty field next to use-package? 

Thanks in advance for your reply.

**Comment by YoungFrog** [comment]
I don't think this will work, because :bind will bind in the global map. Also, I don't think use-package is designed to manage multiple dependencies, so you need to ask yourself what is the behaviour you want. Perhaps this would work ? (totally untested, I use none of these packages)
```emacs-lisp
(use-package evil
  :commands evil-mode)
(use-package keychord)
(use-package evil-commenter
  :config
  (use-package evil
    :config
    (key-chord-define evil-normal-state-map "cc" 'evilnc-comment-or-uncomment-lines)))
```

**Comment by jwiegley** [comment]
@YoungFrog's suggestion is pretty much the only way to go here.
