### ISSUE TITLE
Some packages can't be loaded: "Could not load package XYZ"

### ISSUE THREAD

**Issue by abingham** [jwiegley/use-package#147]
I'm trying to figure out why `use-package` fails with the message "Could not load package" sometimes. From what I can tell, the packages in question are installable. In fact, if I manually use `package-install` they install properly (and subsequent `use-package` calls work.) 

This simple emacs config produces the problem, at least on my system:
```
;; assume that the package archive is already populated
(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
(add-to-list 'package-archives '("marmalade" . "http://marmalade-repo.org/packages/"))
(add-to-list 'package-archives '("melpa-stable" . "http://stable.melpa.org/packages/") t)
(package-initialize)
(require 'use-package)
(use-package nyan-mode) ;; <-- this fails with "Could not load package nyan-mode" in *Messages*
```

If I run `(package-install 'nyan-mode)` and restart emacs, the problem goes away and nyan-mode works (i.e. productivity is restored!) FWIW, nyan-mode is one of a handful of packages with which I've seen this problem, and it's only a small minority of packages that seem to have any problems.

Am I doing something wrong? If so, it would be great if the error message told me what was going on.

**Comment by npostavs** [comment]
You need to add `:ensure t` to tell `use-package` to run `package-install`.

https://github.com/jwiegley/use-package/blob/master/README.md#for-packageel-users

**Comment by abingham** [comment]
Ugh, right you are. I managed to do it correctly for 95% of my packages, and then I turned stupid...

**Comment by npostavs** [comment]
You should try implementing #27 then :)

**Comment by abingham** [comment]
Maybe if nobody else gets to it, though it looks like it's well in hand :) I've got enough of my own fires to deal with right now!
