### ISSUE TITLE
bind-key* macro binds in both global map and override-global-map

### ISSUE THREAD

**Issue by scfrazer** [jwiegley/use-package#148]
The `bind-key*` macro (and by extension `:bind*` in `use-package`) binds key mappings to both the global map and `override-global-map`.  This prevents me from disabling the custom keymap easily, specifically in the minibuffer.  Furthermore, it is inconsistent with `bind-keys*` which only puts keys into `override-global-map`.  An easy solution would be change it to:

    (defmacro bind-key* (key-name command)
      `(progn
         (bind-key ,key-name ,command override-global-map)))

**Comment by jwiegley** [comment]
This sounds reasonable; would there be any loss of functionality from what we have now?

**Comment by YoungFrog** [comment]
Two minor remarks :

- The current behaviour records the binding as a global one for
describe-personal-keybindings.
- The progn is useless if there is only one form.
