### ISSUE TITLE
Edebugging functions defined in the use-package wrapper

### ISSUE THREAD

**Issue by kaushalmodi** [jwiegley/use-package#152]
Hi,

I had posted [this question](http://emacs.stackexchange.com/questions/7643/how-do-i-edebug-a-function-defined-in-a-use-package-block) on the Emacs SE. I am having problem doing `edebug-defun` on the functions I have defined in the `use-package` wrapper.

Here's a dummy example:

<pre>
(use-package ido
  :config
  (progn
    (defun dummy/function ()
      (interactive)
      (message "I am in the dummy function."))))
</pre>

The popular suggestion is to use `debug-on-entry` instead of `edebug-defun` for such cases. But I am spoiled by edebug.

Do you have a suggestion on how `edebug-defun` can be made to work with such functions defined inside `use-package` wrappers?

Thanks!

**Comment by npostavs** [comment]
It seems [Bruce-Connor/names deals with the same issue][1], so perhaps the solution can be similar too.

[1]: https://github.com/Bruce-Connor/names#edebug-and-eval-defun-support

**Comment by jwiegley** [comment]
Even `C-M-x` does not work right for functions defined within the `use-package` macro.  I've taken to just inserting a `(debug)` form directly, and not using edebug for these functions.  If anyone else knows a better way, please let me know.

**Comment by YoungFrog** [comment]
My own approach would be : move these defuns out of use-package (or even to a separate file). Defining a function isn't all that expensive anyway. Is there a reason for keeping the defun inside the macro ?

**Comment by jwiegley** [comment]
The only reason to keep it in the macro is that it makes it easy to mark the package `:disabled` later, which has the efficiency gain of causing even those few functions to be omitted from the byte-compiled output entirely.

**Comment by kaushalmodi** [comment]
I use this as a solution to edebug any defun or defmacro, be it defined in a use-package wrapper or not; simply call `modi/toggle-edebug-defun` while the point is inside defun/defmacro.

```el
;; Edebug a defun or defmacro
(defvar modi/fns-in-edebug nil
  "List of functions for which `edebug' is instrumented.")

(defconst modi/fns-regexp (concat "(\\s-*"
                                  "\\(defun\\|defmacro\\)\\s-+"
                                  "\\(?1:\\(\\w\\|\\s_\\)+\\)\\_>") ; word or symbol char
  "Regexp to find defun or defmacro definition.")

(defun modi/toggle-edebug-defun ()
  (interactive)
  (let (fn)
    (save-excursion
      (search-backward-regexp modi/fns-regexp)
      (setq fn (match-string 1))
      (mark-sexp)
      (narrow-to-region (point) (mark))
      (if (member fn modi/fns-in-edebug)
          ;; If the function is already being edebugged, uninstrument it
          (progn
            (setq modi/fns-in-edebug (delete fn modi/fns-in-edebug))
            (eval-region (point) (mark))
            (setq-default eval-expression-print-length 12)
            (setq-default eval-expression-print-level  4)
            (message "Edebug disabled: %s" fn))
        ;; If the function is not being edebugged, instrument it
        (progn
          (add-to-list 'modi/fns-in-edebug fn)
          (setq-default eval-expression-print-length nil)
          (setq-default eval-expression-print-level  nil)
          (edebug-defun)
          (message "Edebug: %s" fn)))
      (widen))))
```

**Comment by jwiegley** [comment]
@kaushalmodi Neat, I'll try it!
