### ISSUE TITLE
Package pinning is not working for upgrading packages?

### ISSUE THREAD

**Issue by thomasf** [jwiegley/use-package#153]
Pinning as implemented #136 does not seem to work properly for upgrading packages.
`package-pinned-packages` is nil.

I guess that the reason is that :pin does survive after init.el is compiled (?).

**Comment by thomasf** [comment]
ping @peterhoeg

**Comment by glucas** [comment]
Just came to file the same issue.. If I byte-compile my init file then nothing is pinned. Is this expected behavior?

**Comment by thomasf** [comment]
Yes, with the current implementation it is but it should probably be fixed.

**Comment by jwiegley** [comment]
When would people like for the pin/ensure logic to happen, at byte-compilation time -- so that the .emacs you compile against only compiles if the entire environment is available -- or at load time, which means possible a lot of expensive checks that may be redundant after the first time?

**Comment by thomasf** [comment]
After byte compilation time the only thing important is that package-pinned-packages is added to, no other things needed to be done.

**Comment by jwiegley** [comment]
@thomasf Should be fixed in 233130f, can you confirm?

**Comment by thomasf** [comment]
It seems to work now.
