### ISSUE TITLE
How do you use :bind to bind Function keys

### ISSUE THREAD

**Issue by xmaillard** [jwiegley/use-package#155]
I am trying to bind F6 to the function ace-window, this is how I would do it:

(use-package ace-window
  :bind ("[F6]" . ace-window)
  ...
)

C-x C-e returns (error "Key sequence f 6 starts with non-prefix key f") no matter the combination I am trying to use to define f6 (<f6>, kbd, ...)

The sole way to workaround that is to use a :config blocK

  ;; :config
  ;; (progn
  ;;   (bind-key '[f6]' ace-window))

What am I doing wrong here ?

Thanks

**Comment by ThibautVerron** [comment]
You can use `"<f6>"`. The `:bind` keyword doesn't expect a key sequence, but a string to pass to `kbd`.

**Comment by xmaillard** [comment]
ThibautVerron <notifications@github.com> writes:

> You can use `"<f6>"`. The `:bind` keyword doesn't expect a key sequence, but a string to pass to `kbd`.

Holly sh... That works ! Thanks a lot !
--
Sent with my mu4e
