### ISSUE TITLE
Specifying :load-path without using a string literal

### ISSUE THREAD

**Issue by abingham** [jwiegley/use-package#156]
I think this is more about my ignorance of emacs macro expansion than anything else, but I can't seem to use a variable for specifying `:load-path` when I call `use-package`. I want to do something like this:
```
(setq foo-root-directory "/location/of/foo")
. . .
(use-package foo
  :load-path 'foo-root-directory
  . . .)
```
However, no amount of quoting, not quoting, backticking, eval-ing, etc. seems to let me do this. If I use anything other than a string literal after `:load-path`, I get errors like:
```
Debugger entered--Lisp error: (wrong-type-argument stringp quote)
  file-name-absolute-p(quote)
  #[(path) "\302\303\304!\203\f\202\305	\"E\207" [path user-emacs-directory add-to-list (quote load-path) file-name-absolute-p expand-file-name] 5](quote)
  mapcar(#[(path) "\302\303\304!\203\f\202\305	\"E\207" [path user-emacs-directory add-to-list (quote load-path) file-name-absolute-p expand-file-name] 5] (quote ycmd-root))
  #[(name &rest args)
. . . etc . . .
```

Is there a way to use a symbol there instead of a literal? I need to use my emacs configuration across multiple machines, each with different directory structures, so I'd like to be able to configure a few "root directories" which then get used in my `use-package` calls.

**Comment by YoungFrog** [comment]
The following should work :

(use-package foo
  :load-path ,foo-root-directory
  ...)

**Comment by abingham** [comment]
Thanks, works like a charm!
