### ISSUE TITLE
confusion between :commands and :defer in README

### ISSUE THREAD

**Issue by malcook** [jwiegley/use-package#157]
In the README 

> If you aren't using :commands, :bind, :mode, or :interpreter (all of which imply :commands)

should read instead

> If you aren't using :commands, :bind, :mode, or :interpreter (all of which imply :defer)

Agreed?

**Comment by YoungFrog** [comment]
I think what was meant here is that all of :bind, :mode and :interpreter imply :commands (i.e. will set up autoloads) and thus imply :defer.

**Comment by malcook** [comment]
Thanks for explaining this, but, still, I don't get it.  

For example, why should binding a key to a command also need to setup an auto-load for that command?

**Comment by YoungFrog** [comment]
Because otherwise there is a risk that you press the keys and the command is not defined, which means an error will be thrown.

**Comment by jwiegley** [comment]
I think the edit is correct.

**Comment by malcook** [comment]
thanks!  glad I understood your intention.
