### ISSUE TITLE
Support lazy :load-path when the path value is a function

### ISSUE THREAD

**Issue by pf** [jwiegley/use-package#158]
I have the following piece of configuration

```elisp
(use-package ledger-mode
  :commands ledger-mode
  :load-path (lambda ()
	       (list (expand-file-name "share/emacs/site-lisp/ledger"
				       (string-right-trim '(?\n) (shell-command-to-string "brew --prefix ledger"))))))
```

where `brew --prefix ledger` takes a bit to execute, but technically load-path update is not required until ledger-mode has been requested to load.

does it make sense to make load-path lazy for cases where provided value is a function?

**Comment by YoungFrog** [comment]
I think it is possible but:
- I'm not sure the impact on bytecompilation of the init file
- other people will want to execute the function right away
  (e.g. if they use-package in a let-binding).

It seems to me it will be easier to add to the load-path "manually"
with the :pre-init argument.

**Comment by jwiegley** [comment]
Yes, I don't think something this corner-case should be a feature of use-package, since you can always define your own autoload in init.el that adds to the load-path and then loads the file that provides the function.
