### ISSUE TITLE
Document the "hidden backquoting" mechanism.

### ISSUE THREAD

**Issue by YoungFrog** [jwiegley/use-package#160]
There is a "hidden backquoting" mechanism which was first introduced in c46d1f5c94d82fa6c820b88005e2ac9d87dd9e4d for some arguments of the macro use-package. It means that the argument is first evaluated as if it were backquoted ; thus making it possible to use a comma for evaluating things.

I kept the behaviour when I introduced ```use-package-plist-get``` and I like the principle : it combines usefulness of the macro (not having to quote all the things all the time), while making it possible to request evaluation. Caveat : I'm not sure how it behaves wrt lexbinding though (but I'm pretty sure the answer is : poorly).

Anyway, it's been noted in #159 that the feature is left undocumented. Could we document it ?

Note that, at the moment, only some arguments of use-package are "backquote-evalled" (.e.g. :disabled is not, right now). Should we treat all arguments the same way and just document that as a general feature ?

**Comment by npostavs** [comment]
> Caveat : I'm not sure how it behaves wrt lexbinding though (but I'm pretty sure the answer is : poorly).

The anti-quoted forms are evaluated at macro expansion time, while `let` operates at run time so let-bindings won't be seen regardless of whether you're using dynamic or lexical binding. I think `cl-symbol-macrolet` might work.

**Comment by jwiegley** [comment]
@YoungFrog I do not really like the back-quoting magic.  I would rather that if you wish for an argument to be evaluated that ordinarily isn't, make it a lambda and have that particular feature respond to lambdas by evaluating them.  I do this myself for setting things like `:load-path` dynamically.

**Comment by jwiegley** [comment]
This support has been removed.  Dynamism can now be expressed by passing a lambda, in the rare cases where it should be needed.

If people find that this is needed frequently enough that lambdas are an annoyance, we can revisit this idea.
