### ISSUE TITLE
:ensure no longer works for me

### ISSUE THREAD

**Issue by egh** [jwiegley/use-package#164]
This code:

```
(use-package ag :ensure t)
```

No longer works for me. Neither does:

```
(use-package ag :ensure ag)
```

Am I using ensure wrong?

This is using the most recent version from MELPA (20150314.322)

**Comment by egh** [comment]
Forgot the error:
```
package-compute-transaction: Package `(symbol-value (quote t))-' is unavailable
```

**Comment by nbren12** [comment]
I am having the same issue.

**Comment by mayersj1** [comment]
Same for me.  After cleaning up my :pre- entries and modifying some :init to :config entries, I was still having an issue with my emacs.el loading caused by the use of the :ensure keyword.

**Comment by npostavs** [comment]
fixed by #163, I guess

**Comment by freebroccolo** [comment]
I just ran across this one too. The linked PR does seem to fix it.

**Comment by choma** [comment]
I'm having the same issue, but #163 isn't working for me. I replaced use-package.el, and then recompiled it. I'm losing something? (Sorry, I'm not used to install packages manually :-/)

**Comment by nivaca** [comment]
Same problem for me. This is my debug log: 
Debugger entered--Lisp error: (error "Package `(symbol-value (quote t))-' is unavailable")
  signal(error ("Package `(symbol-value (quote t))-' is unavailable"))
  error("Package `%s-%s' is unavailable" (symbol-value (quote t)) "")
  package-compute-transaction(nil (((symbol-value (quote t)))))
  package-install((symbol-value (quote t)))
  (progn (package-install package))
  (if (not (package-installed-p package)) (progn (package-install package)))
  use-package-ensure-elpa((symbol-value (quote t)))
  (progn (require (quote package)) (use-package-ensure-elpa package-name))
  (if package-name (progn (require (quote package)) (use-package-ensure-elpa package-name)))
  (let* ((ensure (plist-get args* :ensure)) (package-name (or (and (eq ensure t) name) ensure))) (if package-name (progn (require (quote package)) (use-package-ensure-elpa package-name))))
  (let* ((name-string (if (stringp name) name (symbol-name name))) (name-symbol (if (stringp name) (intern name) name)) (args* (condition-case err (use-package-normalize-plist name-symbol args) ((debug error) (message (error-message-string err)))))) (let ((archive-name (plist-get args* :pin))) (if archive-name (progn (use-package-pin-package name archive-name)))) (let* ((ensure (plist-get args* :ensure)) (package-name (or (and (eq ensure t) name) ensure))) (if package-name (progn (require (quote package)) (use-package-ensure-elpa package-name)))) (let* ((body (use--package name-symbol name-string args*)) (pred (plist-get args* :if)) (expansion (if pred (cons (quote when) (cons pred body)) (if (= (length body) 1) (car body) (cons (quote progn) body)))) (requires (plist-get args* :requires)) (pre-compile-load (if (and (boundp (quote byte-compile-current-file)) byte-compile-current-file) (progn (list (cons ... ...))))) (body* (use-package-cat-maybes pre-compile-load (list (if (null requires) expansion (list ... ... expansion)))))) (if (= (length body*) 1) (car body*) (cons (quote progn) body*))))
  (if (member :disabled args) nil (let* ((name-string (if (stringp name) name (symbol-name name))) (name-symbol (if (stringp name) (intern name) name)) (args* (condition-case err (use-package-normalize-plist name-symbol args) ((debug error) (message (error-message-string err)))))) (let ((archive-name (plist-get args* :pin))) (if archive-name (progn (use-package-pin-package name archive-name)))) (let* ((ensure (plist-get args* :ensure)) (package-name (or (and (eq ensure t) name) ensure))) (if package-name (progn (require (quote package)) (use-package-ensure-elpa package-name)))) (let* ((body (use--package name-symbol name-string args*)) (pred (plist-get args* :if)) (expansion (if pred (cons (quote when) (cons pred body)) (if (= ... 1) (car body) (cons ... body)))) (requires (plist-get args* :requires)) (pre-compile-load (if (and (boundp ...) byte-compile-current-file) (progn (list ...)))) (body* (use-package-cat-maybes pre-compile-load (list (if ... expansion ...))))) (if (= (length body*) 1) (car body*) (cons (quote progn) body*)))))
  (lambda (name &rest args) "Declare an Emacs package by specifying a group of configuration options.\n\nFor full documentation, please see the README file that came with\nthis file.  Usage:\n\n  (use-package package-name\n     [:keyword [option]]...)\n\n:init          Code to run before PACKAGE-NAME has been loaded.\n:config        Code to run after PACKAGE-NAME has been loaded.  Note that if\n               loading is deferred for any reason, this code does not execute\n               until the lazy load has occurred.\n\n:mode          Form to be added to `auto-mode-alist'.\n:interpreter   Form to be added to `interpreter-mode-alist'.\n\n:commands      Define autoloads for commands that will be defined by the\n               package.  This is useful if the package is being lazily loaded,\n               and you wish to conditionally call functions in your `:init'\n               block that are defined in the package.\n\n:bind          Bind keys, and define autoloads for the bound commands.\n:bind*         Bind keys, and define autoloads for the bound commands,\n               *overriding all minor mode bindings*.\n:bind-keymap   Bind a key prefix to an auto-loaded keymap defined in the\n               package.  This is like `:bind', but for keymaps.\n:bind-keymap*  Like `:bind-keymap', but overrides all minor mode bindings\n\n:defer         Defer loading of a package -- this is implied when using\n               `:commands', `:bind', `:bind*', `:mode' or `:interpreter'.\n:demand        Prevent deferred loading in all cases.\n\n:if EXPR       Initialize and load only if EXPR evaluates to a non-nil value.\n:disabled      The package is ignored completely, the same as `:if nil'.\n:defines       Declare certain variables to silence the byte-compiler.\n:functions     Declare certain functions to silence the byte-compiler.\n:load-path     Add to the `load-path' before attempting to load the package.\n:diminish      Support for diminish.el (if installed).\n:idle          Adds a form to be run on an idle timer after initialization.\n:idle-priority Schedules the :idle form to run with the given priority (lower\n               priorities run first).  Default priority is 5; forms with the\n               same priority are run in the order in which they are evaluated.\n:ensure        Loads the package using package.el if necessary.\n:pin           Pin the package to an archive." (if (member :disabled args) nil (let* ((name-string (if (stringp name) name (symbol-name name))) (name-symbol (if (stringp name) (intern name) name)) (args* (condition-case err (use-package-normalize-plist name-symbol args) ((debug error) (message ...))))) (let ((archive-name (plist-get args* :pin))) (if archive-name (progn (use-package-pin-package name archive-name)))) (let* ((ensure (plist-get args* :ensure)) (package-name (or (and ... name) ensure))) (if package-name (progn (require (quote package)) (use-package-ensure-elpa package-name)))) (let* ((body (use--package name-symbol name-string args*)) (pred (plist-get args* :if)) (expansion (if pred (cons ... ...) (if ... ... ...))) (requires (plist-get args* :requires)) (pre-compile-load (if (and ... byte-compile-current-file) (progn ...))) (body* (use-package-cat-maybes pre-compile-load (list ...)))) (if (= (length body*) 1) (car body*) (cons (quote progn) body*))))))(paradox :ensure t :config (setq paradox-execute-asynchronously t) (setq paradox-github-token (quote paradox)) (setq paradox-github-token t) :commands (paradox-upgrade-packages paradox-list-packages))
  (use-package paradox :ensure t :config (setq paradox-execute-asynchronously t) (setq paradox-github-token (quote paradox)) (setq paradox-github-token t) :commands (paradox-upgrade-packages paradox-list-packages))
  eval-buffer(#<buffer  *load*-373838> nil "/Users/nivaca/Dropbox/emacs/mypackages.el" nil t)  ; Reading at buffer position 2661
  load-with-code-conversion("/Users/nivaca/Dropbox/emacs/mypackages.el" "/Users/nivaca/Dropbox/emacs/mypackages.el" nil nil)
  load("/Users/nivaca/Dropbox/emacs/mypackages.el" nil nil t)
  load-file("~/Dropbox/emacs/mypackages.el")
  eval-buffer(#<buffer  *load*-468308> nil "/Users/nivaca/Dropbox/emacs/myinit.el" nil t)  ; Reading at buffer position 2656
  load-with-code-conversion("/Users/nivaca/Dropbox/emacs/myinit.el" "/Users/nivaca/Dropbox/emacs/myinit.el" nil nil)
  load("~/Dropbox/emacs/myinit.el")
  eval-buffer(#<buffer  *load*> nil "/Users/nivaca/.emacs" nil t)  ; Reading at buffer position 35
  load-with-code-conversion("/Users/nivaca/.emacs" "/Users/nivaca/.emacs" t t)
  load("~/.emacs" t t)
  #[0 "\205\262	\306=\203\307\310Q\202;	\311=\204\307\312Q\202;\313\307\314\315#\203*\316\202;\313\307\314\317#\203:\320\nB\321\202;\316\322\323\322\211#\210\322=\203a\324\325\326\307\327Q!\"\323\322\211#\210\322=\203`\210\203\243\330!\331\232\203\243\332!\211\333P\334!\203}\211\202\210\334!\203\207\202\210\314\262\203\241\335\"\203\237\336\337#\210\340\341!\210\266\f?\205\260\314\323\342\322\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" (initialization "`_emacs' init file is deprecated, please use `.emacs'") "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7 "\n\n(fn)"]()
  command-line()
  normal-top-level()

**Comment by nivaca** [comment]
#163 Fixed the issue for me.

**Comment by jwiegley** [comment]
My apologies to everyone for the churn, a change of this magnitude is hard to pull off flawlessly.  I had thought the size and diversity of my own configuration would be representative enough, but I don't use the `:ensure` keyword.  I'll take a look at #163 and also compare to see what the older code did.

**Comment by jwiegley** [comment]
@choma Does the latest version fix your issue?

**Comment by choma** [comment]
I just updated to the latest version, it's working perfect now!
Thanks for the quick fix! :)

**Comment by nivaca** [comment]
Latest version works fine. Thanks.

**Comment by egh** [comment]
Thank you!
