### ISSUE TITLE
`:bind` with vector broken

### ISSUE THREAD

**Issue by lunaryorn** [jwiegley/use-package#166]
`:bind` doesn't accept key vectors anymore in latest `master`.  For instance, `:bind ([remap execute-extended-command] . smex)` yields the following error:

```
use-package: :bind wants a string, (string . symbol) or list of these
```

**Comment by manuel-uberti** [comment]
Happens here too, can't use vectors in ```:bind``` anymore.

**Comment by npostavs** [comment]
By the way: `:bind ("<remap> <execute-extended-command>" . smex)` should have the same effect.

**Comment by lunaryorn** [comment]
@npostavs Thanks a lot.  I've changed my `init.el` to this syntax to work around this issue.  I still prefer the vector syntax for this purpose, though, so I'd be happy to see it re-introduced if possible.

**Comment by jwiegley** [comment]
Thanks for the report, @lunaryorn, this is just the validation code being too strict.

**Comment by rangilin** [comment]
It seems like the latest commit a255b28 resloved this issue

If anyone using Cask, you can setup your dependency like this before Melpa updated.
(depends-on "use-package" :git "https://github.com/jwiegley/use-package.git" :ref "a255b28")


I still getting some error reports about void variable/function in `:init`, I move those setting to `:config` and everything works again.

**Comment by jwiegley** [comment]
@rangilin That change does not yet resolve @lunaryorn's issue.

**Comment by lunaryorn** [comment]
@jwiegley I'd go so far as to say it's entirely unrelated.

**Comment by manuel-uberti** [comment]
Thanks for the workaround.
