### ISSUE TITLE
`:config` seems to be called too early

### ISSUE THREAD

**Issue by Silex** [jwiegley/use-package#167]
Hello,

I have the following config:

``` elisp
(use-package fic-mode
  :defer t
  :config
  (setq fic-background-color "Orange")
  (setq fic-foreground-color "Black")
  (modify-face 'font-lock-fic-face fic-foreground-color
               fic-background-color nil t nil nil nil nil))
```

But this seems to execute the `:config` block all the time, like if it was `:init` (the error is `Error (use-package): Failure in :config of fic-mode: (error "Invalid face" font-lock-fic-face)`).

At this point fic-mode is not loaded so the `:config` block should not execute (e.g `(featurep 'fic-mode)` returns nil).

When I `load-library` fic-mode or `M-x fic-mode` the error goes away when evaling the `modify-face` form.

**Comment by npostavs** [comment]
I think this is #52 again.

**Comment by Silex** [comment]
Haha, good catch let's try renaming the files.

**Comment by Silex** [comment]
Yes, I confirm it's because of the file names being the same as the mode's name.

**Comment by Silex** [comment]
Thanks @npostavs & @jwiegley!
