### ISSUE TITLE
Default idle priority broken

### ISSUE THREAD

**Issue by lunaryorn** [jwiegley/use-package#169]
The README claims that `:idle` *without* `:idle-priority` defaults to a priority of 5.  Effectively, however, use-package inserts `:idle` forms without an explicit `:idle-priority` as `nil` priority, and subsequently fails to sort forms by priority when trying to compare `nil` with numbers.

To re-produce, add a package with an `:idle` form *without* priority, and another with `:idle` and `:idle-priority`, e.g:

```cl
(use-package ignoramus
  :ensure t
  :defer t
  :idle (ignoramus-setup)
  
(use-package projectile
  :ensure t
  :defer t
  :init (projectile-global-mode)
  :idle (projectile-cleanup-known-projects)
  :idle-priority 10)
```

This causes the following backtrace on the first idle initialisation step:

```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  <(nil 5)
  sort((5) <)
  use-package-idle-priorities()
  use-package-idle-pop()
  use-package-idle-eval()
  apply(use-package-idle-eval nil)
  timer-event-handler([t 0 3 0 t use-package-idle-eval nil idle 0])
```

Inspecting `use-package-idle-forms` shows that the `ignoramus` form is stored under the key `nil` instead of 5.

**Comment by jwiegley** [comment]
The `:idle` feature has been removed, until a better design can be found.

**Comment by dakrone** [comment]
@jwiegley should the `:idle` docs be removed from the readme, or maybe a section added to the "Users upgrading to 2.0" section?

**Comment by jwiegley** [comment]
@dakrone Yes, thank you, I'll do that right now.
