### ISSUE TITLE
use-package-20150315.1840 broke my Emacs

### ISSUE THREAD

**Issue by nivaca** [jwiegley/use-package#171]
My Emacs was fine with use-package-20150315.149. But an hour ago I upgraded to use-package-20150315.1840, and it broke my Emacs. I get an error with Paradox:

     Symbol's value as variable is void: paradox

I then proceded to comment the init lines which load Paradox, and then I started to get warnings saying that e.g.:

    Variable pretty-mode is void.

Don't know what's going on, but I decided to move back to 149.

**Comment by lurdan** [comment]
Same here.

It seems that if it's configuration has :commands or :mode, use-package cannot expand specified package name (as simbol?)

**Comment by jwiegley** [comment]
This was fixed very recently, please pull and try again.
