### ISSUE TITLE
Looking for ways to make startup faster

### ISSUE THREAD

**Issue by jwiegley** [jwiegley/use-package#173]
At the present time, I'm hitting a wall at getting `use-package` to be much faster than it is.  Byte-compiling my own `init.el` file only results in a 10% speed improvement (on Mac, on Linux I see no improvement at all).  Turning on `use-package-verbose` degrades speed by 20%, but turning on `use-package-expand-minimally` has no effect (although this is not terribly surprising).

Do others have any ideas for making things load even faster?  As much as possible I would like to see near-instant startup times, with everything that can be initialized lazily.  Are there ways to make this happen more easily for complex packages like helm, which I've found difficult to properly lazy-load?

**Comment by thomasf** [comment]
How fast does your emacs start now?

I'm quite satisfied with having ~1-3s startup time depending on os/env.

The insanity route would be trying to use `dump-emacs` in some way, I've only looked at that long enough to put it in th

**Comment by jwiegley** [comment]
On Linux my config loads in 1.7s, on Mac 2.2s.  I'd like <0.5s.

**Comment by jwiegley** [comment]
I've gone the `dump-emacs` route before.  It is much more trouble than it's worth.

**Comment by manuel-uberti** [comment]
Just saying. On Linux my config loads in 20.0 seconds the first time, then 5.6 seconds. I don't know if it is use-package fault. I got over 100 packages set up, so it could be just me not configuring them properly. I use ```:defer``` as much as possible.

**Comment by krzysztof-magosa** [comment]
Add
(setq package-enable-at-startup nil)
Before package-initialize.

Then you have to define :mode and :interpreter for each defered package but emacs will start in 0,5 so it's worth to do ;)

**Comment by manuel-uberti** [comment]
I am already using ```(setq package-enable-at-startup nil)``` before package-initialize. I will try ```:mode``` and ```:interpreter```.

**Comment by manuel-uberti** [comment]
I am already using ```(setq package-enable-at-startup nil)``` before package-initialize. I will try ```:mode``` and ```:interpreter```.

**Comment by Silex** [comment]
Having a SSD changes emacs boot time drastically. A good way to test the maximum speed attainable is running `emacs -Q`... without a SSD that still takes almost one second.

My config takes around 3 seconds on non SSD and 0.7 with SSD.

**Comment by krzysztof-magosa** [comment]
Could you paste somewhere your whole config? Some pastebin or so?

**Comment by manuel-uberti** [comment]
It's all [here](https://github.com/manuel-uberti/emacs).

**Comment by Silex** [comment]
It seems that you use `el-get`. As far as I know el-get is very slow.

**Comment by manuel-uberti** [comment]
I use ```el-get``` only to install ```po-mode``` which is not on MELPA. Aside from that, all my packages come from MELPA.
Did you mean ```el-get``` slows startup? I tried commenting all that is ```el-get``` related, gaining little in startup time.

**Comment by krzysztof-magosa** [comment]
Emacs starts in 0.3s on my machine.
I didn't cover all my plugins with :mode yet, but I think it won't add too much time to startup.
GNU Emacs 24.4.1, OS X 10.10.2, i7 CPU, 16 GB RAM, SSD

Maybe try with my config to see how much time it will need to load.
https://github.com/krzysztof-magosa/dotfiles/blob/master/.emacs

**Comment by manuel-uberti** [comment]
Well, my seven years old Inspiron 1525 cannot be compared to your hardware: 4 GB RAM, no SSD, Core Duo.
If it is an issue related to my old hardware, I'll stop writing. :)

**Comment by krzysztof-magosa** [comment]
I use also Ubuntu on VirtualBox, it has assigned 1 core + 1 GB ram and emacs starts in less than 1 second.

**Comment by krzysztof-magosa** [comment]
I see that you uses :defer with number very often.
You can specify :defer t, and then package won't be loaded until needed by file with extension specified in :mode "\\.ext$"

**Comment by manuel-uberti** [comment]
Ok, doing that to some modes worked reducing startup from 5.6 to 5.1 seconds. A little bit better. Thank you.

**Comment by thomasf** [comment]
My numbers right now seems to be: 
* 1.2s after disk cache warm up running the emacs-24 branch on a some years old Intel(R) Core(TM) i7 CPU 860  @ 2.80GHz with an 10krpm hard drive. 
* 2.1s on an about one year old 13" macbook pro with fast flash system bus storage. 

The init does things a little bit different between the operating systems which might account for some of the difference.

Both osx and xmonad gets the frame in place at about the same time.

**Comment by jwiegley** [comment]
With some more work adding deferral and idle loads, I was able to get my Linux setup to load in 0.5s, and that's for 218 packages.  I doubt I can ask for much more speed than that, so I'll just close this.

**Comment by syl20bnr** [comment]
@jwiegley this is with a byte-compiled init ?

**Comment by jwiegley** [comment]
Yes.

**Comment by syl20bnr** [comment]
Impressive, everything is lazy-loaded in spacemacs and the load time is 1.7s not byte compiled. I'll have to profile to see where the bottleneck is.
I started to `:defer [n]` some packages instead of `:defer t` but I don't expect improvements with such moves.

**Comment by npostavs** [comment]
> I started to :defer [n] some packages instead of :defer t

There is no way that `:defer [n]` can improve loading time over `:defer t`. You should consider adding `:defer [n]` to some package that *isn't* currently deferred.
