### ISSUE TITLE
use-package returns nil instead of t

### ISSUE THREAD

**Issue by syl20bnr** [jwiegley/use-package#174]
Seems that `use-package` now returns `nil` instead of `t` when successful. Is it intentional ?
Reference: https://github.com/syl20bnr/spacemacs/pull/850

**Comment by jwiegley** [comment]
@syl20bnr I did that as a cleanup thing today, I'll revert it.

**Comment by syl20bnr** [comment]
@jwiegley thanks you :+1:

**Comment by jcpetkovich** [comment]
Seems like this is happening again with the newest version of use-package, only it always returns nil, successful or not. For example:

    (use-package simple) ;; => nil
    (use-package doesnotexist) ;; => nil, plus warning

This isn't necessarily a problem if we're not supposed to depend on `use-package` output to determine if a package has been succesfully required or not. But it certainly is convenient.

**Comment by jwiegley** [comment]
I realized as I went to bed last night that I had broken this.  It will be fixed soon.

**Comment by jcpetkovich** [comment]
Do you know what specifically broke this? Maybe I can fix it if you're too busy to?

**Comment by jwiegley** [comment]
I know exactly what broke it and how to fix it, I've simply lacked time.  Also, what should the exact semantics be?  Right now I'm thinking:

  - If the package is defer-loaded, then return `nil` only if there were errors during processing of `:init`.
  - Otherwise, return `t` if the package successfully loaded, and there were no errors during `:config`.

**Comment by jcpetkovich** [comment]
I think those semantics make sense. I can't think of an example where those results would be unexpected.

**Comment by jwiegley** [comment]
I'm not sure whether the fix for this issue will work properly with every possible combination of keywords that `use-package` accepts, so please add more notes here if you notice something broken.

**Comment by jwiegley** [comment]
It turns out there are too many macro forms where the answer ends up being nil for different reasons, so rather than try to support this, I'm just going to say: The return value from the `use-package` form has no meaning.

**Comment by syl20bnr** [comment]
Makes sense. I looked again at the ESS layer in Spacemacs and we don't rely anymore on the return value of the code generated by use-package. I'm pretty sure this was the only place where we were doing this.
