### ISSUE TITLE
`:bind` overrides existing autoloads

### ISSUE THREAD

**Issue by lunaryorn** [jwiegley/use-package#177]
`:bind` adds new autoloads regardless of whether the function is already autoloaded or not.   The corresponding code in `use--package` is commented.  Why is that the case?  It didn't happen in older use-package versions.

Imho, `use-package` should never create autoloads for anything that is already `fboundp`.  That's just plain wrong.

**Comment by YoungFrog** [comment]
Related are #135 (initial problem), #138 (PR for a tentative fix) and comments on commit 40965ab.

TL;DR: the --now commented out-- code was only added recently then commented out because of breakage. John said he was going to look into it.

**Comment by jwiegley** [comment]
@lunaryorn What is the actual problem?  The docstring for `autoload` says that it will be a no-op if there is already a function defined with that name.

**Comment by jwiegley** [comment]
When I uncomment the "fix" for this that's in the case, several of my packages no longer work.  I still don't have a fix for this.

**Comment by npostavs** [comment]
The docstring says
> If FUNCTION is already defined other than as an autoload,
> this does nothing and returns nil.

i.e. it's a no-op if there is a function definition, but it does have effect if the existing definition is only an autoload.

**Comment by lunaryorn** [comment]
@jwiegley It's a no-op if there's a real function with that name.  But it does override a previously existing autoload, i.e. from package.el.

IOW, if there's already an autoload for `foo`, `:bind` always replaces it with its own autoload.  The consequence of this change is that you can't add `:bind`s for functions from other features, because in that case `:bind` would replace the previously existing autoload with one that points to the wrong library.

For instance, I used to add sx.el like this:

```cl
(use-package sx
  :ensure t
  :bind (("C-c w s" . sx-tab-frontpage)))
```

This used to work, even though `sx-tab-frontpage` actually comes from `sx-tab.el` instead of `sx.el`, because use-package would not replace the autoload defined by the sx package.

Now it does replace the autoload, and subsequently Emacs tries to load `sx-tab-frontpage` from `sx`.el, which fails for obvious reasons.

Hence I now have to structured my `:bind`s like the internal structure of the SX package, even though all the autoloads are already there.

**Comment by jwiegley** [comment]
@lunaryorn Ok, I'll dig into this today and find a way to not clobber existing autoloads.

**Comment by lunaryorn** [comment]
@jwiegley That would be great!

**Comment by jwiegley** [comment]
One part of the problem I was having appears to be this:

``` elisp
(autoloadp (symbol-function 'foo))
```

The above fails if the `autoload` declaration for `foo` has been byte-compiled, even though the Help docstring for `foo` will say that it's an autoload.

**Comment by lunaryorn** [comment]
Why don't you just test for `fboundp`?

**Comment by jwiegley** [comment]
I just tried `fboundp`, and it also breaks my configuration.

**Comment by jwiegley** [comment]
It could be that I'm doing something odd here on my side, so first I'll track down why exactly it breaks it for me.

**Comment by thomasf** [comment]
If autoloads were not added the following would not override the emacs built in org mode?

```
(use-package org
  :ensure org-plus-contrib
  :commands (org-mode)
...
```

**Comment by jwiegley** [comment]
@lunaryorn @thomasf Please try now.  The reason this wasn't working for me was just some oddness on my side.  I was able to fix my configuration, and now guarding with `fboundp` works just fine.

**Comment by lunaryorn** [comment]
@jwiegley Thank you, it's working now.  And many thanks for this package.

**Comment by jwiegley** [comment]
@lunaryorn You're most welcome!  Thank you for flycheck. :)

I've discovered a problem with this solution: By placing the autoload under a conditional, the byte-compiler no longer sees the definition, and so complains about autoloaded functions not being defined.  I think I should be able to work around this by using `declare-function` in each case after doing the check.

**Comment by jwiegley** [comment]
Well, I can be made to work with a hack: in `use-package`, we manually remove the `redefined` element from `byte-compile-warnings`, so that it simply isn't reported (since redefinition here is harmless).  Sadly, that removes the check for real redefinitions.  Do you have any suggestions?

**Comment by lunaryorn** [comment]
@jwiegley I'm not sure.  Generally, I don't think that you should rely on these "implicit" autoloads for byte compiler warnings.  It feels too magic.

If I had to rely on functions being defined, I'd put them into `:commands`, which could then do unconditional autoloading—it's probably safe to assume that the user wants autoloading if they put a function here.

I'm really just talking about the “implicit” autoloads created by `:bind`, `:modes`, etc.  These should be as “safe” as possible.

Specifically, did you try to move the entire block, including the conditional, into an `eval-and-compile`?

**Comment by jwiegley** [comment]
Ah, that's a good point about `:bind` vs. `:commands`.  That may be just the ticket.

**Comment by jwiegley** [comment]
No, I didn't try moving it all into an eval-and-compile, although that's certainly worth trying out.

**Comment by lunaryorn** [comment]
@jwiegley Generally, I think that `use-package` could do with a little less magic.  I understand that it's convenient to have `:bind` add autoloads for you, but it's also hard to understand and hard to debug, if it breaks.

Would be a lot of effort to add a separate `:autoloads` keyword that just adds autoloads, and remove all other autoloads functionality?  But then again, it's probably not acceptable to you, for if you don't use package.el, you'll have to manage a lot of autoloads this way.

**Comment by jwiegley** [comment]
Yep, exactly.  Part of the reason I wrote use-package was to automate the generation of autoloads. :)

**Comment by jwiegley** [comment]
And more specifically: exactly that set of autoloads which I actually need.  I have a `Makefile` that can generate autoloads for everything I have installed; and it takes more seconds to load that generated file -- it is so large -- than to load my whole configuration based on `use-package`.

So, since I'm not a `package.el` user, or a generated autoloads user, the magic nature of `:bind` is what I would call one of my principal use cases.

I'm keeping this issue open until I find a copacetic way to make the byte-compiler happy.  At the moment I've succeeded, but at the cost of locally suppressing warnings about function definitions.  I think the use of `:commands` to establish unconditional autoloads sounds like the best solution, albeit it a less elegant one.

One thing I want to avoid with `use-package` is having elaborate definitions to get the features that I want.  Because in that case, I just wouldn't use use-package at all.  I have always wanted it to infer what I mean as much as it is safe to do so, so that my config can focus on what I want to configure, rather than the peripheral machinery which I feel Emacs should be able to figure out for me.

**Comment by thomasf** [comment]
Maybe an customisation option for implicit autoloads generation outside of :commands ?

**Comment by jwiegley** [comment]
Sure, I'd be open to that.  `use-package` needs a few more configuration options.

**Comment by thomasf** [comment]
I still want the implicit behaviour but'

**Comment by jwiegley** [comment]
And I still think the implicit behavior should be the default.  It allows for very tidy configurations like:

``` elisp
(use-package foo-mode
  :mode "\\.foo\\'"
  :bind ("C-c f" . foo-load-file))
```

With only a minimal amount of configuration, Emacs knows to only loads the package when I actually use its functionality in some way, without my having to think about, or setup, autoloads explicitly.

**Comment by jwiegley** [comment]
Something else that I fixed removed the need for my hack, so I'm happy with the way things are now.
