### ISSUE TITLE
:pin fails if package.el is not required at load time

### ISSUE THREAD

**Issue by thomasf** [jwiegley/use-package#180]
Because of undefined variable  `package-pinned-packages`.

**Comment by thomasf** [comment]
Some things does not work as expected when I dont package-initalize, closing this issue for now.

**Comment by jwiegley** [comment]
Also, I think that if you want to use the packaging logic, you really do need to require `package` at load time.

**Comment by thomasf** [comment]
It seems as if it's doable without it. I have my own load-path-setup function which just iterates the packages directory and adds everything because it's much faster. I think I got it working now.
