### ISSUE TITLE
Surprising behavior with `:commands`

### ISSUE THREAD

**Issue by syl20bnr** [jwiegley/use-package#181]
I wrote `surprising` but it is likely because I don't understand autoload correctly, help ! :-)

Repro step:
- Paste this in scratch and eval
```elisp
(use-package rcirc
  :commands spacemacs/rcirc
  :init
  (defun spacemacs/rcirc (arg)
    (interactive "P")
    (message "%s" (rcric-process-list))))
```
-  `M-x spacemacs/rcirc`

Behavior: `rcirc-process-list` is not defined
Expected behavior: `spacemacs/rcirc` autoloads `rcirc` and `rcirc-process-list` is defined.

**Comment by jwiegley** [comment]
I think you want:

``` elisp
(use-package rcirc
  :commands rcirc-process-list
  :preface
  (defun spacemacs/rcirc (arg)
    (interactive "P")
    (message "%s" (rcric-process-list))))
```

**Comment by jwiegley** [comment]
Btw, `:init` would have been just fine too.  The main reason to use `:preface` for functions defined locally to `use-package` declaration is that they won't be defined inside the guard blocks that I use to detect errors during initialization, which masks the definition from the byte-compiler.

**Comment by syl20bnr** [comment]
It does not work. Same behavior. :-(

**Comment by jwiegley** [comment]
Really?  Even with `:commands` set to `rcirc-process-list`?  Also, in what you pasted above there is a typo of `rcric`.

**Comment by syl20bnr** [comment]
Yes, this is really weird.

**Comment by syl20bnr** [comment]
ahah.... hum....

**Comment by syl20bnr** [comment]
It works with `rcirc-process-list` and the typo fixed. Now I don't understand why it does not work with my function.

**Comment by syl20bnr** [comment]
Thank you for the help, I'll dig the use-package macro + elisp doc.

**Comment by jwiegley** [comment]
@syl20bnr It certainly *should* work with your function.  I have a similar pattern in many places through my init file.
