### ISSUE TITLE
dolist expansion no longer working

### ISSUE THREAD

**Issue by gberenfield** [jwiegley/use-package#182]
My simple `(dolist)` block is no longer working since a few days ago.

```
(defvar my-packages '(auto-compile
                       better-defaults
                       smex
                       fiplr
                       discover
                       yafolding
                       helm
                       org))

(dolist (p my-packages)
  (use-package p))

=> Error (use-package): Could not load package p
```

**Comment by jwiegley** [comment]
`use-package` is a macro that takes a symbol name as its argument; it doesn't accept a variable name like that.  I'm not sure how that worked before, but even if it had, if you'd tried using `:bind` or the other keywords, bad things would have happened.

To pull in packages programmatically like this, you should just be using `require`:

``` elisp
(dolist (p my-packages)
  (require p nil t))
```

`use-package` is for placing declarative sections in your `.emacs`, and cannot be called programmatically as you have above.

**Comment by chuchana** [comment]
I have a similar list that I use with `package-install` like this:
> ~~~
> (dolist (p my-packages)
>   (when (not (package-installed-p p))
>     (package-install p)))
> ~~~

Does it make sense to convert it to `use-package` even when the packages need no configuration?
