### ISSUE TITLE
Need a maintainer for the `:pin` and `:ensure` logic

### ISSUE THREAD

**Issue by jwiegley** [jwiegley/use-package#183]
Since I do not use `package.el`, I need someone who is willing to constantly test the `:pin` and `:ensure` logic for capability with ongoing changes to use-package, including functionality when loading both byte-compiled and non-byte-compiled flavors of one's `.emacs` file.  Is there anyone who would be willing to do this, and to address all of the GitHub issues that have been marked with the "ensure" label?

**Comment by thomasf** [comment]
I'll report/discuss issues I stumble upon, I usually update my packages once a day at least so the feedback loop will probably be good enough there.
Currently available time is not very good for me but I'll help out where I can.
I try to will answer peoples questions about these areas and provide patches.

**Comment by jwiegley** [comment]
Thanks @thomasf!
