### ISSUE TITLE
use-package-with-elapsed-timer has to be a macro

### ISSUE THREAD

**Issue by tarsius** [jwiegley/use-package#185]
If it is a function, then it's BODY argument is first evaluated and stored in the dynamically scoped variable named `body`. It then goes on using `use-package-progn` which is an attempt at avoiding to needlessly wrap a single form with `progn`. I think that's a mistake in itself, but let's just assume for a moment that `progn` was used instead.

The `progn` **does not** wrap one or more yet-to-be-evaluated forms, i.e. BODY; instead it wraps the variable `body` whose value is the result of having evaluated BODY earlier.

`body` is not only wrapped by a progn-like form, in one code path it is also wrapped by code which is intended to determine how long it takes to evaluate BODY (that's the whole point of this macro/function). But when that happens BODY has already been evaluated and we effectively time how long it takes to retrieve the value of the variable `body` and for `use-package-progn` to play with that value a bit, which is always a very short - and almost constant - period of time.

(But because it is not `progn` but `use-package-progn` which is actually used that may cause an error. The value of `body` better be a list, because otherwise `use-package-progn` is going to try to cons the symbol `progn` onto an atom).

**Comment by jwiegley** [comment]
Why is `use-package-progn` a mistake in itself?

Do you have an example of a scenario that manifests this error?  At the moment, the job of all the functions in `use-package` is to produce a list of forms, as data.  The final macro, `use-package`, causes these forms to be seen as code by the evaluator/compiler.  So I shouldn't need anything else in the program to be a macro except for the top-level `use-package` macro.

**Comment by jwiegley** [comment]
For example, when I look at the expansion of the macro for a given form, the timing is performed on the code that was in BODY, not on the retrieval of the variable `body`:

``` elisp
(progn
  (eval-and-compile
    (defun my-dired-toggle-mode-hook nil
      (interactive)
      (visual-line-mode 1)
      (setq-local visual-line-fringe-indicators
                  '(nil right-curly-arrow))
      (setq-local word-wrap nil)))
  (unless
      (fboundp 'dired-toggle)
    (autoload
      (function dired-toggle)
      "dired-toggle" nil t))
  (declare-function dired-toggle "dired-toggle")
  (bind-key "C-. d"
            (function dired-toggle))
  (eval-after-load 'dired-toggle
    '(let
         ((now
           (current-time)))
       (message "%s..." "Configuring package dired-toggle")
       (prog1
           (condition-case-unless-debug err
               (add-hook 'dired-toggle-mode-hook
                         (function my-dired-toggle-mode-hook))
             (error
              (ignore
               (display-warning 'use-package
                                (format "use-package: Error in %s: %s" "dired-toggle"
                                        (error-message-string err))
                                :error))))
         (let
             ((elapsed
               (float-time
                (time-subtract
                 (current-time)
                 now))))
           (if
               (> elapsed 0.1)
               (message "%s...done (%.3fs)" "Configuring package dired-toggle" elapsed)
             (message "%s...done" "Configuring package dired-toggle"))))))
  t)
```

**Comment by tarsius** [comment]
I couldn't quite figure out if it does what it is supposed to do. But that's probably because I looked at a case where it blows up, as described above. It's probably useful in macros. In anycase it fixes a very minor issue, the issue of code not being evaluated at the right time is a bigger deal - let's concentrate on that.

**Comment by npostavs** [comment]
> the issue of code not being evaluated at the right time is a bigger deal - let's concentrate on that.

@tarsius: do you mean to say there is currently a problem with `use-package-with-elapsed-timer`? I don't think there is, unless you have a use case outside of the `use-package` macro in mind. Maybe it should be renamed to `use-package--with-elapsed-timer`.

**Comment by jwiegley** [comment]
Agreed.  Please provide examples of bad behavior and I'm quite eager to fix them.

**Comment by tarsius** [comment]
Yes, I use `use-package-with-elapsed-timer` "outside of `use-package`", e.g. to report how long it takes to load `init.el` in total, which I believe is fairly closely related to the purpose of `use-package`.

```lisp
(use-package-with-elapsed-timer "Loading init file"
  (use-package foo ...)
  (use-package bar ...)
  ...)
```

But doing so is an uphill battle because it keeps getting broken: at least #96 and #151. I think I am going to give up on it.

The behavior changed in that previously BODY was a &rest argument while it now has to be a quoted list of forms. I don't see what you gain by doing that.

> Please provide examples of bad behavior.

Whenever BODY isn't quoted it fails in two ways: (a) it times how long it takes to get the value of a variable instead of how long it takes to evaluate BODY, and (b) if BODY is so bold as to return an atom then it tries consing onto an atom.

**Comment by jwiegley** [comment]
Ah, I see.  `use-package-with-elapsed-timer` is no longer intended to be a general utility macro to be used by others.  I would recommend abstracting such functionality out to a standalone macro that has nothing to do with `use-package`.

**Comment by npostavs** [comment]
> I would have to use
> 
> ```
> (use-package-with-elapsed-timer "Loading init file"
>   '(progn (use-package foo ...)
>           (use-package bar ...)
>           ...))
> ```

That just returns a list, nothing is timed. You would actually need something like 

```elisp
(defmacro with-elapsed-timer (text body)
  (car (use-package-with-elapsed-timer text body)))

(with-elapsed-timer "Loading init file"
  (progn (use-package foo ...)
         (use-package bar ...)
         ...))
```

**Comment by jwiegley** [comment]
Or maybe:

``` elisp
(defmacro with-elapsed-timer (text &rest body)
  (car (use-package--with-elapsed-timer text body)))

(with-elapsed-timer "Loading init file"
  (use-package foo ...)
  (use-package bar ...)
  ...)
```

**Comment by tarsius** [comment]
@npostavs You got it backward.

@jwiegley Fine. The nice thing about having this in `use-package` was that this was the only package I had to load before I could start timing how long it took to load "everything in the init file". I am going to just define a similar macro at the very top of my init file.

**Comment by jwiegley** [comment]
@tarsius I can appreciate that, and I'm sorry I killed the functionality for you.  I just want to pare `use-package` down to solving exactly one problem as well as it can.  And since there were several usage patterns I wasn't testing (like, using parts of `use-package` outside of `use-package`), I just had to give up on those for the sake of the primary goal.
