### ISSUE TITLE
Cannot defer loading for info+

### ISSUE THREAD

**Issue by tuhdo** [jwiegley/use-package#188]
I tried loading it with `commands`, but no success:

```elisp
(use-package info+
    :commands (info Info-mode)
    :config
    (require 'info+))
```

**Comment by jwiegley** [comment]
Can you define what "success" would look like?

The `:config` form here is entirely redundant, you should just have:

``` elisp
(use-package info+
    :commands (info Info-mode))
```

This will cause `info+` to be loaded whenever you invoke `info` or `Info-mode`.

**Comment by jwiegley** [comment]
Also, please check what other things in your config (especially in your customizations) may be forcing the load.  Here's what the above use-package macro expands into:

``` elisp
(progn
  (unless
      (fboundp 'info)
    (autoload #'info "info+" nil t))
  (unless
      (fboundp 'Info-mode)
    (autoload #'Info-mode "info+" nil t)))
```

So I cannot believe it is `use-package` causing `info+` to not defer load.

**Comment by tuhdo** [comment]
If `info+` is successfully loaded, it will have extra highlighting when a manual is opened. To test it out:

- Load it with `(require 'info+)`
- `M-x info` and you will see extra highlighting.

The only thing that works is to load with `require`. However, I want to defer until I run `info` or when I open a buffer with `Info-mode`. But `use-package` currently cannot load even when I put them in `:commands`.

**Comment by tuhdo** [comment]
`info+` is not a mode but rather a set of functions that enhances the internal of stock `Info-mode`. Probably that's why `use-package` cannot load? Is there a way to load such packages properly?

**Comment by YoungFrog** [comment]
The autoloading feature should be used for loading a library that
defines the command. M-x info is not defined by 'info+, so autoloading
info+ via info doesn't make sense.

You could add a :before advice to info which would load info+ :

(advice-add 'info :before (lambda (&rest _) "Load `info+'" (load "info+" t)))

(If you're using emacs before 24.4, you need a defadvice instead -- the
syntax is a bit different though)

**Comment by npostavs** [comment]
> (advice-add 'info :before (lambda (&rest _) "Load `info+'" (load "info+" t)))

I would suggest `require` instead of `load` there, else you will reload `info+` every time you run `info`.

Another possibility is 
```elisp
(use-package info
  :defer t
  :config (require 'info+))
```

**Comment by tuhdo** [comment]
@npostavs that works. Thanks.

**Comment by YoungFrog** [comment]
> I would suggest require instead of load there, else you will reload
> info+ every time you run info.

Agreed. My initial idea was to have an advice that removes itself, but
then I was too lazy to actually write it.

**Comment by jwiegley** [comment]
Btw, this is what I would have done:

``` elisp
(use-package info
  :commands (info Info-mode)
  :config (require 'info+))
```

I have something very similar to this for `dired+` in my own config.

**Comment by tuhdo** [comment]
@jwiegley that's even better. Thanks.
