### ISSUE TITLE
Delight addon inclusion

### ISSUE THREAD

**Issue by darkfeline** [jwiegley/use-package#189]
Delight addon for use-package, request for inclusion (in place of diminish?)

https://gist.github.com/darkfeline/f615f8ccb4cc104ca6a6

This is working for me so far.

Old issue:
https://github.com/jwiegley/use-package/issues/187

**Comment by jwiegley** [comment]
This is great, thank you!  I'm happy have it in addition to diminish, but I don't want to remove that support, since it works just fine for me -- and others have their configurations already based on it.

**Comment by jwiegley** [comment]
@darkfeline Isn't it impossible for the first test in your `cond` form to ever return `t`?

**Comment by darkfeline** [comment]
@jwiegley Yeah, sorry for the bug, should be `(symbolp (car args))`

https://gist.github.com/darkfeline/f615f8ccb4cc104ca6a6
