### ISSUE TITLE
use-package runs when it's not supposed to.

### ISSUE THREAD

**Issue by marwy** [jwiegley/use-package#192]
I'm not sure if it's a bug or if I'm just missing something, for I'm not well versed in Elisp ;-).
I have the following code:
```elisp
(unless (string= system-name "here-elfeed-shall-not-run")
  (use-package elfeed
    :ensure t
    :config
     (setq elfeed-feeds '(blabla doesnt matter))))  
```
given that ```(string= system-name "here-elfeed-shall-not-run")``` returns true, the following ```use-package``` bit shouldn't run, right? Unfortunately it does run.
If I comment out the bit about ```use-package``` then elfeed is not installed, so I'm fairly sure this is the only place where it does get installed.

**Comment by Silex** [comment]
given use-package is a macro it runs no matter what. You should use the `:if` keyword, tho I'm not sure if it's implemented yet.

The usage would look something like : 

``` elisp
(use-package elfeed
  :if (not (string= system-name "here-elfeed-shall-not-run"))
  :ensure t
  :config
  (setq elfeed-feeds '(blabla doesnt matter)))
```

**Comment by jwiegley** [comment]
You should use:

    :unless (string= system-name "here-elfeed-shall-not-run")

Some aspects of use-package are run no matter what, and some aren't.

John

**Comment by marwy** [comment]
I haven't tried Silex's solution, but ```unless``` did the trick, thanks! 
Maybe it'd be a good idea to document this feature in the README file.

**Comment by jwiegley** [comment]
This is documented under "Conditional loading".
