### ISSUE TITLE
Diminish keyword issue

### ISSUE THREAD

**Issue by ddoherty03** [jwiegley/use-package#193]
John,

After a recent upgrade, I now get an error "key-chord mode not a registered minor mode" with this:

    (use-package key-chord
       :ensure t
       :init (key-chord-mode 1)
       :diminish "K")

Any ideas?

**Comment by jwiegley** [comment]
You'll need to move the call to `:config`.  `:init` happens before the package is loaded, so the minor mode has not been defined yet.

**Comment by ddoherty03** [comment]
Ah, thanks for the quick response.
