### ISSUE TITLE
Need semver compatible tags for MELPA stable

### ISSUE THREAD

**Issue by mkleehammer** [jwiegley/use-package#194]
MELPA stable requires [semver](http://semver.org/) compatible tags, such as 1.2.3, to build.  Can you switch to using versioned tags.  Not only would this help your users detect non-backwards compatible changes, I would expect a long-term migration from MELPA to MELPA stable.

I've had a lot of breakage using MELPA since it builds everything from the last commit on the master branch.

Thanks.

**Comment by jwiegley** [comment]
Thanks for bringing it to my attention, it will be fixed with the next
release.

**Comment by mkleehammer** [comment]
Awesome, thanks!  Any chance you could tag your last release, though, so it can be used now?  It should be safe to have two tags on the same commit.

**Comment by jwiegley** [comment]
I've tagged the code prior to my rewrite as `1.9`.

**Comment by mkleehammer** [comment]
Worked like a champ!  Thanks.  By the way, I think use-package is one of the best things to happen to emacs in a long time.  Great work.  With use-package and MELPA stable, it will be a lot easier for new users to configure emacs to their workflow.
