### ISSUE TITLE
While setting up a new machine, getting: "Symbol's value as variable is void: ,"

### ISSUE THREAD

**Issue by hartzell** [jwiegley/use-package#196]
Hi All,

I doubt that this is actually a use-package problem, but my emacs-lisp-fu is failing me.

I'm setting up a new machine (OS X 10.10.1, emacs etc... from homebrew last Thursday) and using a copy of my .emacs.d that's running happily on my older mac.

When I run `emacs --debug-init`, I see the following message:

```
Debugger entered--Lisp error: (void-variable \,)
  symbol-value(\,)
  eval((symbol-value (quote \,)))
  use-package-normalize-paths(":load-path" \, t)
  #[(x) "\302^H \303#@\207" [label x use-package-normalize-paths t] 4](\,)
  mapcar(#[(x) "\302^H  \303#@\207" [label x use-package-normalize-paths t] 4] (\, (f-join personal-dir "bbdb")))
  use-package-normalize-paths(":load-path" (\, (f-join personal-dir "bbdb")))
  use-package-as-one(":load-path" ((\, (f-join personal-dir "bbdb"))) use-package-normalize-paths)
  use-package-normalize/:load-path(bbdb-autoloads :load-path ((\, (f-join personal-dir "bbdb"))))
  use-package-normalize-plist(bbdb-autoloads (:load-path (\, (f-join personal-dir "bbdb")) :init (progn (add-hook (quote bbdb-load-hook) (quote (lambda nil$
  #[(name &rest args) "\306^H\235?\205\321^@  ;\203^R^@\307 !\202^S^@ ^Z\310\n^H\"\311\312^[^\^]\313^M\f\"\203(^@^M\202-^@\314^M\f^K#+^^'\315^N(\203R^@^N'\$
  (use-package bbdb-autoloads :load-path (\, (f-join personal-dir "bbdb")) :init (progn (add-hook (quote bbdb-load-hook) (quote (lambda nil (setq bbdb/mail$
  eval-buffer(#<buffer  *load*-604739> nil "/Users/bioinfo/.emacs.d/personal/init.el" nil t)  ; Reading at buffer position 9160
  load-with-code-conversion("/Users/bioinfo/.emacs.d/personal/init.el" "/Users/bioinfo/.emacs.d/personal/init.el" nil nil)
  load("/Users/bioinfo/.emacs.d/personal/init.el")
  (progn (load personal-init))
  (if (file-exists-p personal-init) (progn (load personal-init)))
  (let ((personal-init (f-expand "init.el" personal-dir))) (if (file-exists-p personal-init) (progn (load personal-init))))
  eval-buffer(#<buffer  *load*> nil "/Users/bioinfo/.emacs.d/init.el" nil t)  ; Reading at buffer position 2126
  load-with-code-conversion("/Users/bioinfo/.emacs.d/init.el" "/Users/bioinfo/.emacs.d/init.el" t t)
  load("/Users/bioinfo/.emacs.d/init" t t)
  #[0 "^H\205\262^@ \306=\203^Q^@\307^H\310Q\202;^@ \311=\204^^^@\307^H\312Q\202;^@\313\307\314\315#\203*^@\316\202;^@\313\307\314\317#\203:^@\320\nB^R\321$
  command-line()
  normal-top-level()
```

The problematic code seems to be here:

```
;; the big brother database, address book, contacts and more.
(use-package bbdb-autoloads
  :load-path ,(f-join personal-dir "bbdb")
  :init
  (progn
    (add-hook 'bbdb-load-hook
    ...
```

I'm sure that somewhere in my slightly newer copy of emacs and my slightly newer copies of all of the various packages there has been a change and my configuration (which was in large parts cargo-culted) is no longer sensible.  I'm at a loss as to where to look though.

Suggestions?

Thanks!

g.

**Comment by thomasf** [comment]
You should probably drop that comma prefix.

**Comment by thomasf** [comment]
Also see https://github.com/jwiegley/use-package#note-to-users-upgrading-to-20

**Comment by hartzell** [comment]
That leads to different unpleasantness, which I *think* makes sense....

```
Debugger entered--Lisp error: (void-variable f-join)
  symbol-value(f-join)
  eval((symbol-value (quote f-join)))
  use-package-normalize-paths(":load-path" f-join t)
  #[(x) "\302^H \303#@\207" [label x use-package-normalize-paths t] 4](f-join)
  mapcar(#[(x) "\302^H  \303#@\207" [label x use-package-normalize-paths t] 4] (f-join personal-dir "bbdb"))
  use-package-normalize-paths(":load-path" (f-join personal-dir "bbdb"))
  use-package-as-one(":load-path" ((f-join personal-dir "bbdb")) use-package-normalize-paths)
  use-package-normalize/:load-path(bbdb-autoloads :load-path ((f-join personal-dir "bbdb")))
  use-package-normalize-plist(bbdb-autoloads (:load-path (f-join personal-dir "bbdb") :init (progn (add-hook (quote bbdb-load-hook) (quote (lambda nil (set$
  #[(name &rest args) "\306^H\235?\205\321^@  ;\203^R^@\307 !\202^S^@ ^Z\310\n^H\"\311\312^[^\^]\313^M\f\"\203(^@^M\202-^@\314^M\f^K#+^^'\315^N(\203R^@^N'\$
  (use-package bbdb-autoloads :load-path (f-join personal-dir "bbdb") :init (progn (add-hook (quote bbdb-load-hook) (quote (lambda nil (setq bbdb/mail-auto$
  eval-buffer(#<buffer  *load*-921474> nil "/Users/bioinfo/.emacs.d/personal/init.el" nil t)  ; Reading at buffer position 9159
  load-with-code-conversion("/Users/bioinfo/.emacs.d/personal/init.el" "/Users/bioinfo/.emacs.d/personal/init.el" nil nil)
  load("/Users/bioinfo/.emacs.d/personal/init.el")
  (progn (load personal-init))
  (if (file-exists-p personal-init) (progn (load personal-init)))
  (let ((personal-init (f-expand "init.el" personal-dir))) (if (file-exists-p personal-init) (progn (load personal-init))))
  eval-buffer(#<buffer  *load*> nil "/Users/bioinfo/.emacs.d/init.el" nil t)  ; Reading at buffer position 2126
  load-with-code-conversion("/Users/bioinfo/.emacs.d/init.el" "/Users/bioinfo/.emacs.d/init.el" t t)
  load("/Users/bioinfo/.emacs.d/init" t t)
  #[0 "^H\205\262^@ \306=\203^Q^@\307^H\310Q\202;^@ \311=\204^^^@\307^H\312Q\202;^@\313\307\314\315#\203*^@\316\202;^@\313\307\314\317#\203:^@\320\nB^R\321$
  command-line()
  normal-top-level()
```

I "need" to evaluate the s-exp, calling the f-join, to get the path that I want added to the load path.

I'll check out the link you just posted.

Thx!

**Comment by jwiegley** [comment]
You'll now need:

``` elisp
  :load-path (lambda () (f-join personal-dir "bbdb"))
```

Also, ensure that `f-join` is defined both at compile-time and at load time.

**Comment by hartzell** [comment]
Hmmm.  Only thing that I see in the 2.0 doc that rings a bell is the bit about :load-path and eval-and-compile.

On a whim, I tried:

```
(eval-and-compile
 (defun bbdb-path ()
    (f-join personal-dir "bbdb"))
)

;; the big brother database, address book, contacts and more.
(use-package bbdb-autoloads
;  :load-path ,(f-join personal-dir "bbdb")
  :load-path (lambda () (list (bbdb-path)))
  :init
  (progn
  ...
```

Which seems to work.

Since I'm not byte-compiling my init stuff, this confused me, so I tried this:

```
;(eval-and-compile
 (defun bbdb-path ()
    (f-join personal-dir "bbdb"))
;)
```

Which also works.  So, it seems that `eval-and-compile` isn't fixing anything.

Which leaves me with my original question: what's wrong with using the comma to evaluate the `f-join` sexp in the use-package statement?

Thanks!

**Comment by thomasf** [comment]
@hartzell , needs to be implemented in the use-package macro to be recognized as anything. By itself it does not mean anything.

**Comment by hartzell** [comment]
@jwiegley, made the changes you suggest, things work.  Thanks.  Can you briefly describe what changed in use-package to require my code to change so I understand a bit better?

@thomasf, I thought that the comma was the "special marker" refered to in the second paragraph of the [Backquote docs](http://www.gnu.org/software/emacs/manual/html_node/elisp/Backquote.html).  Am I way off base?

**Comment by thomasf** [comment]
So two things, first an `(eval-and-compile...` around the definition of `personal-dir` and then make sure that both the setting and  `(use-package f)` are located above the bbdb part

**Comment by jwiegley** [comment]
`eval-and-compile` is only technically needed if you actually compile your init.el.  If you never do, you won't need it.

**Comment by hartzell** [comment]
@jwiegley That makes sense.  To push my luck asking for explanations, what changed so that the comma version no longer works?

**Comment by thomasf** [comment]
@hartzell It was removed and replaced because lambdas is the canonical way to do it.

**Comment by npostavs** [comment]
> I thought that the comma was the "special marker" refered to in the second paragraph of the Backquote docs. Am I way off base?

Before 2.0, use-package was putting an implicit backquote before some arguments. It no longer does that, so using `,` doesn't work anymore. Now, use-package will check for a lambda and funcall it instead,  see #160.

The compile vs eval time stuff hasn't changed (if you needed it before, you still need it now; if you didn't, you still don't). It's just a different syntax.

**Comment by hartzell** [comment]
@npostavs, @jwiegley, *et al.*.  That made the light-bulb go on.

Thanks!

**Comment by jwiegley** [comment]
I wanted the value passed to any given keyword to be one or more *values*, not special forms handled by the macro nature of `use-package` (which may change in future, you never know).  Lamdas are, as @thomasf points out, the canonical way to pass "functionality" (i.e., something whose value is determined by evaluating code) as a value.
