### ISSUE TITLE
:init runs when :if is false

### ISSUE THREAD

**Issue by ckruse** [jwiegley/use-package#197]
Hi,

I just noticed that `:init` gets called when `:if` evaluates to false. Is this a bug?

Regards,

**Comment by fbergroth** [comment]
Can you provide an example? The following code does not signal an error for me:
```el
(use-package test
  :if nil
  :init (error ":init"))
```

**Comment by ckruse** [comment]
I tried to use this to execute circe on non-osx-plattforms:

    (use-package circe
      :commands (circe circe-set-display-handler)
      :unless (eq system-type 'darwin)
      :init (progn
              (defun my-irc-login ()
                "Login into my usual IRCs."
                (interactive)
                (circe "EPD-ME")
                (circe "CCC")
                (circe "Freenode"))
    
              (load "~/dev/mail/znc.el")
              (run-with-idle-timer 5 nil 'my-irc-login))
      :config (progn
        ;; a lot of config code
      ))

But circe started none-the-less. It doesn’t matter if I use `:if (not
…)` or `:unless`.  When I change it to this:

    (use-package circe
      :commands (circe circe-set-display-handler)
      :disabled (eq system-type 'darwin)
      :init (progn
              (defun my-irc-login ()
                "Login into my usual IRCs."
                (interactive)
                (circe "EPD-ME")
                (circe "CCC")
                (circe "Freenode"))
    
              (load "~/dev/mail/znc.el")
              (run-with-idle-timer 5 nil 'my-irc-login))
      :config (progn
        ;; a lot of config code
      ))

It works, circe doesn’t get started.

**Comment by thomasf** [comment]
I think :init is supposed to always run. Put the activating stuff in :config instead or any other strategy that solves it.

**Comment by ckruse** [comment]
Wouldn't that make the `:if`/`:unless` pointless? I thought `use-package` is about being able to disable everything regarding a specific package very fast? And also would then `:disabled` be inconsistent: when it isn't true the `:init` isn't executed

**Comment by thomasf** [comment]
It's not pointless.

example:
```elisp
(use-package savehist
  :if (and (not noninteractive) (not degrade-p-minimalism))
  :init
  (progn
    (setq
     savehist-file (expand-file-name
                    "savehist" user-data-directory)
     savehist-additional-variables '(search ring regexp-search-ring)
     savehist-autosave-interval 60))
  :config
  (progn
    (savehist-mode 1)))
```

**Comment by thomasf** [comment]
And  `:disabled` is supposed to be the early deactivation point which allowes for the whole macro to  evaluate to `nil`

**Comment by thomasf** [comment]
When using `:if` i can still trigger the package to load when emacs is already running and and still have the variables set in `:init` available.

**Comment by ckruse** [comment]
Good point, especially the last one. So it is intended behaviour? Would be nice to document that more clearly.

**Comment by thomasf** [comment]
It's kind of documented here https://github.com/jwiegley/use-package#semantics-of-init-is-now-consistent

**Comment by ckruse** [comment]
That's why I wrote *more clearly* ;) The later section about conditional loading made me think that this is not intended.

**Comment by thomasf** [comment]
yeah :)

I guess that concept of *loading* in the readme specifically refers to calling the Emacs require/load functions. That is probably not obvious.

**Comment by npostavs** [comment]
> :disabled (eq system-type 'darwin)

By the way, I'm pretty sure this is equivalent to `:disabled t`.

**Comment by ckruse** [comment]
On OS X: yes, confirmed and intended. On linux: why should it be?

**Comment by thomasf** [comment]
Ah, yes. Took a quick look. `:disabled` is only checked for existence, not value.

**Comment by YoungFrog** [comment]
> On OS X: yes, confirmed and intended. On linux: why should it be?

Because the form isn't evaluated.

**Comment by thomasf** [comment]
maybe it should be, some packages only works for certain os'es.

**Comment by ckruse** [comment]
Hm, any suggestion but to put everything in one big `(when (progn ...))`?

**Comment by thomasf** [comment]
maybe https://github.com/jwiegley/use-package#prevent-a-package-from-loading-at-compile-time , I havent used that..

**Comment by thomasf** [comment]
Experiment :)  I suggest using the handy macrostep to macrostep-expand your use-package forms to test things out.

**Comment by jwiegley** [comment]
If think `:unless` may be broken.  What happen if you use `:if` combined with `not`?

**Comment by bricewge** [comment]
Yes `:unless` is broken but `:if` work. For example `:if (not (daemonp))` has the expected behaviour.
