### ISSUE TITLE
Compile warning about undefined functions with :functions

### ISSUE THREAD

**Issue by darkfeline** [jwiegley/use-package#198]
```
 (use-package moe-theme
   :ensure t
   :functions moe-dark
   :config
   (moe-dark))
```

Using `:functions`, I still get a warning about `moe-dark` not being defined when I try to compile.  Am I misinterpreting the usage of `:functions`?

**Comment by jwiegley** [comment]
You shouldn't need `:functions` here at all, since the `:config` section only occurs after the module has been required.  Are you sure that function is being defined by moe-theme?

**Comment by darkfeline** [comment]
`moe-theme` does define `moe-dark`.  I'm also seeing the same problem for `term-send-raw-string`, `evil-set-initial-state`, and others in the same situation.

I have two files:

    ;;;; init.el
    (package-initialize)
    (compile-and-load "other.el")



    ;;;; other.el
    (eval-when-compile (require 'use-package))
    (require 'bind-key)
    (use-package moe-theme
     :ensure t
     :functions moe-dark
     :config
     (moe-dark))

I get the warning whether or not `:functions` is used.  The warnings don't go away even if I require `use-package` in `init.el`.

**Comment by jwiegley** [comment]
Here is what your initial form compiles to:

``` lisp
(progn
  (use-package-ensure-elpa 'moe-theme)
  (eval-when-compile
    (declare-function moe-dark "moe-theme"))
  (require 'moe-theme nil 'nil)
  (moe-dark)
  t)
```

**Comment by jwiegley** [comment]
I wonder if this is happening because the `declare-function` is nested under a `progn` and an `eval-when-compile` form.

**Comment by darkfeline** [comment]
(This is a very old bug and I no longer use moe-theme or use-package, it's too complicated for my taste and I like writing my own Emacs Lisp now =))

Nesting the `declare-function` in `eval-when-compile` is almost certainly the issue.  The `eval-when-compile` is kind of pointless anyway, since `declare-function` is a macro that expands to nil and serves as a magic value for the byte compiler.

Also, from maintaining my own set of light use-package replacements, I think the problem here is that the byte compiler does not automatically evaluate non-top-level `require` forms.  If the `require` is in a `progn`, I have found that I needed to wrap them in a `eval-and-compile` form to get the byte compiler to quit complaining.  `eval-when-compile` doesn't work either since the byte compiler will then complain that the functions may not be defined at run time.

The byte compiler clearly has room for improvement here, but that's a separate issue.

**Comment by jwiegley** [comment]
I'm unable to reproduce this with a small example, btw.  I have this:

``` lisp
(eval-when-compile
  (add-to-list 'load-path "~/emacs/lisp/use-package")
  (require 'use-package))

(use-package ascii
  :bind ("C-c e A" . ascii-toggle)
  :commands ascii-on
  :functions ascii-off
  :preface
  (defun ascii-toggle ()
    (interactive)
    (if ascii-display
        (ascii-off)
      (ascii-on)))
  :config
  (ascii-off))
```

Commenting out `:functions` causes the warning to appear, but having it present makes the warning go away.  Maybe there is another layer of indirection involved with themes?

**Comment by jmcarthur** [comment]
I am having this problem as well.

    (eval-and-compile
      (add-to-list 'load-path
                   (expand-file-name "packages/use-package" user-emacs-directory))
      (require 'use-package))
    (require 'bind-key)
    
    (use-package evil
      :load-path "packages/evil"
      :functions evil-mode ;; the presence of this line makes no difference
      :config (evil-mode 1))

I get:

    init.el:40:1:Warning: the function ‘evil-mode’ might not be defined at
        runtime.

When I expand the macro, I don't even see `declare-function` in the result:

    (progn
      (eval-and-compile
        (add-to-list 'load-path "/home/jake/.emacs.d/packages/evil"))
      (if
          (not
           (require 'evil nil 't))
          (ignore
           (message
            (format "Cannot load %s" 'evil)))
        (condition-case-unless-debug err
            (evil-mode 1)
          (error
           (ignore
            (display-warning 'use-package
                             (format "%s %s: %s" "evil" ":config"
                                     (error-message-string err))
                             :error))))
        t))
