### ISSUE TITLE
use-package-always-defer

### ISSUE THREAD

**Issue by pkkm** [jwiegley/use-package#202]
Most of the `use-package` declarations in my config are for packages whose autoloading is managed by `package.el`, so they don't need `:commands` or `:mode`. However, I need to specify `:defer t` so that they're not loaded at startup.

I think it would be useful to have a variable that made `use-package` default to `:defer t`, unless overridden by `:demand t`, similar to how `use-package-always-ensure` works. It would also help with writing fast Emacs inits: when the user forgets `:defer`, default to doing the performant thing.

**Comment by jwiegley** [comment]
Sounds reasonable to me.
