### ISSUE TITLE
Problem with (use-package "foo" ...)

### ISSUE THREAD

**Issue by alezost** [jwiegley/use-package#203]
Hello, I suppose this issue may be counted as a feature request.

With the old use-package (pre 2.0) I could use a string as a package
name and it eventually expanded into `(eval-after-load "foo" ...)`.  But
with the current use-package, the string is interned and the use-package
clause is expanded into `(eval-after-load 'foo ...)`.

I find it inconvenient, as not every emacs file provides a feature.
For example, I used:

```elisp
(use-package "isearch"
  :diminish " 🔎"
  :config
  (setq isearch-allow-scroll t))
```

And it used to work with the old use-package, but not with the
current one, since "isearch.el" does not contain `(provide
'isearch)`.

Do you plan to add a support for string package names?

**Comment by thomasf** [comment]
use-package should probably only concern itself with things that are features.
Isnt isearch always loaded anyway?

**Comment by npostavs** [comment]
Support for string packages was removed in 4476482dfbc3dd570b754f15b906eb98ad6e4cb6:
```diff
-               ,(if (stringp name)
-                    `(load ,name t)
-                  `(require ',name nil t)))))
+               (require ',name-symbol nil t))))
```

Support for `eval-after-load`ing string packages was removed later by 526d308ddef1685cdd0643be84308a906365aadc

See also https://github.com/jwiegley/use-package/pull/168#issuecomment-81320624 (I didn't realize string package support had already been removed).

**Comment by alezost** [comment]
@thomasf, I know that isearch is already loaded, I just like to use use-package for everything.

**Comment by thomasf** [comment]
Ive been thinking about that too. In that case I also want to use it for grouping my 5kloc lines of functions as well. That would mean using it for things that arent packages by any definition at all.

**Comment by Silex** [comment]
As a workaround, maybe you could use a feature that you know is always loaded?

**Comment by alezost** [comment]
@Silex: Ah, thanks, that's an interesting idea; but I think I will not
use use-package for those files that do not provide features.

**Comment by thomasf** [comment]
You can also add an empty proper package called my-isearch.el or something

**Comment by npostavs** [comment]
It might be enough to just say `(provide 'isearch) (use-package isearch ...)`

**Comment by jwiegley** [comment]
@npostavs Can you submit a PR to revert that change which broke it?

**Comment by npostavs** [comment]
@jwiegley: it's not so trivial because the support was removed before the keyword modularising. So to reenable this all the handlers would have to take name instead of name-symbol.

A draft (untested!) is at https://github.com/jwiegley/use-package/compare/master...npostavs:string-packages?expand=0

**Comment by jwiegley** [comment]
Perhaps you'd be willing to turn that into a tested PR? :)  I'll accept.
