### ISSUE TITLE
Allow rx in :mode

### ISSUE THREAD

**Issue by berhoel** [jwiegley/use-package#204]
``` elisp
(use-package f90
  :mode ((rx "." (or "f90" "F90" "f95" "F95") eos) . f90-mode))
```

gives `Error: use-package: :mode wants a string, (string . symbol) or list of these`.

Could the code be modified, so that rx is allowed in mode definitions?

**Comment by jwiegley** [comment]
Hmm... Perhaps there should be a global config to just disable argument checking, because there might be other corner cases we're not thinking of.

**Comment by npostavs** [comment]
Just disabling argument checking wouldn't help because the `rx` call still has to be evaluated by somebody.

**Comment by jwiegley** [comment]
Ah, great point.  And then we'd want to allow `rx` in every place that a string is currently allowed, and evaluate it if and when we find it.

I support adding such a feature, but I'm going to let it sit on the back-burner for now.

**Comment by yangyingchao** [comment]
hi, Jeiegley,

 How is this feature going? I'm really looking forward to it, since it is really convenient to generate regex strings with `rx'.

 This is what I'm using currently:

(defmacro yc/set-mode (mode expr)
  "Set MODE EXPR into `auto-mode-alist."
  `(add-to-list 'auto-mode-alist
                (cons ,expr ,mode)))

(use-package cmake-mode
  :commands (cmake-mode)
  :init
  (progn
    (yc/set-mode 'cmake-mode (rx (or "CMakeList.txt" "CMakeLists.txt" ".cmake")))))


As you can see, it is not elegant ...

 Thanks.

**Comment by berhoel** [comment]
My definition for your cmake-mode entry would look like:

(use-package cmake-mode
  ;; (rx (or "CMakeList.txt" "CMakeLists.txt" ".cmake"))
  :mode ("\\(?:\\.cmake\\|CMakeList\\(?:s?\\.txt\\)\\)" . cmake-mode))

I move the cursor behind the last closing brace in the comment, use "C-x
C-e" to evaluate the expression and copy the result from the "*Messages*"
buffer into the ":mode" command.

Kind regards
Berthold

-- 
A: Weil es die Lesbarkeit des Textes verschlechtert.
F: Warum ist TOFU so schlimm?
A: TOFU
F: Was ist das größte Ärgernis im Usenet?

2016-06-16 10:16 GMT+02:00 Yang, Ying-chao <notifications@github.com>:

**Comment by yangyingchao** [comment]
Well, I'm doing the same for some other modes:

 ;; (rx "." (or "bat" "cmd"))
(use-package batch-mode :mode "\\.\\(?:bat\\|cmd\\)")

Anyway, thanks for your work!

**Comment by npostavs** [comment]
> `(use-package batch-mode :mode "\.\(?:bat\|cmd\)")`

You need to double up those backslashes.

You might also look at https://github.com/joddie/pcre2el which can convert elisp regexps back and forth from elisp string regexps to rx form.

**Comment by yangyingchao** [comment]
yes, you are right. I am using double backslashes, but it turns out to be one slash after pasting them here...

**Comment by npostavs** [comment]
Oh, it's 'cause backslashes are used as markdown escaping outside of backquotes.

**Comment by yangyingchao** [comment]
Oh right, github uses markdown...
> 在 2016年6月16日，下午7:24，Noam Postavsky <notifications@github.com> 写道：
> 
> Oh, it's 'cause backslashes are used as markdown escaping outside of backquotes.
> 
>

**Comment by jwiegley** [comment]
>>>>> Berthold Höllmann <notifications@github.com> writes:

> (use-package cmake-mode
>   ;; (rx (or "CMakeList.txt" "CMakeLists.txt" ".cmake"))
>   :mode ("\\(?:\\.cmake\\|CMakeList\\(?:s?\\.txt\\)\\)" . cmake-mode))

Note that I don't think this feature has to be internal to use-package.  Just
write:

``` elisp
`(use-package cmake-mode
  :mode (,(rx (or "CMakeList.txt" "CMakeLists.txt" ".cmake")) . cmake-mode))
```

**Comment by npostavs** [comment]
> Just write: 
```elisp
`(use-package cmake-mode 
  :mode (,(rx (or "CMakeList.txt" "CMakeLists.txt" ".cmake")) . cmake-mode))
```

You would need to wrap that in `eval` which is kind of icky.

**Comment by jwiegley** [comment]
>>>>> Noam Postavsky <notifications@github.com> writes:

> You would need to wrap that in `eval` which is kind of icky.

It might need to be `eval-when` in order to match semantics exactly.

**Comment by yangyingchao** [comment]
Hey man, thanks!

I tried to add “,” before rx expression earlier, but I forgot to add a back quote before “use-package”, and that is why it did not work.

Thanks for pointing out this!

Cheers
> 在 2016年6月17日，上午1:40，John Wiegley <notifications@github.com> 写道：
>

**Comment by yangyingchao** [comment]
Just realized that backquote returns a S-exp instead of expanding use-package macro. 

To make it work, i need to evaluate the S-exp returned by backquote.

Here is what I did: wraps `use-package’ with a simple marco, and call `eval` in the wrapper:

```
(defmacro yc/use-package (&rest args)
  "Macro to wrap use-package to take use of rx expression."
  (list 'eval (list 'backquote `(use-package ,@args))))

(yc/use-package cmake-mode
  :mode ,(rx (or "CMakeList.txt" "CMakeLists.txt" ".cmake")))
```

> 在 2016年6月17日，上午8:36，Tubo Yang 杨英超 <yangyingchao@gmail.com> 写道：
> 
> Hey man, thanks!
> 
> I tried to add “,” before rx expression earlier, but I forgot to add a back quote before “use-package”, and that is why it did not work.
> 
> Thanks for pointing out this!
> 
> Cheers
>> 在 2016年6月17日，上午1:40，John Wiegley <notifications@github.com <mailto:notifications@github.com>> 写道：
>>
