### ISSUE TITLE
use-package with empty clauses seems to break helm

### ISSUE THREAD

**Issue by hrehfeld** [jwiegley/use-package#205]
If I have something like:
    (use-package foo :ensure foo :init (progn) :config (progn) :commands nil :bind nil),
my helm fails with something like:
    (no-method-definition constructor (helm-absolute-time-timers-class "absolute time timers"))

Not sure how to debug or provide better report info..?

**Comment by MaikuMori** [comment]
Check for typos, I've ran into this before as well, I think it was because
of typo on my end.

**Comment by hrehfeld** [comment]
@MaikuMori What kind of typos do you mean?

**Comment by hrehfeld** [comment]
this triggers it as well:

(use-package yasnippet
  :ensure t
  :defer t
  :config
  (progn
;	(add-to-list 'yas-snippet-dirs `(,(concat (file-name-as-directory user-emacs-directory) "yasnippet/snippets")))
;	(setq yas-prompt-functions '(yas-ido-prompt  yas-completing-prompt))
	(setq yas-indent-line 'auto)
	(yas-global-mode 1)
	)
  :bind-keymap
  (
;   yas-minor-mode-map
;   ("\t" . nil)
   ("C-c e" .  yas-expand)
  )
)

**Comment by hrehfeld** [comment]
I think it only happens when helm is autoloaded after this call.

**Comment by thomasf** [comment]
dou you use package.el autoloads?

**Comment by thomasf** [comment]
I install my packages from package.el but not at load time.

I just load the helm-autoloads file manually because helm is too much to keep
track of for me.

```
(use-package helm
  :ensure t
  :commands (helm-M-x helm-bookmarks
            ...
            helm-browse-code helm-recentf helm-find)
  :bind (("M-o M-x" . helm-M-x)
         ("C-x f r" . helm-recentf)
         ("C-h r" . helm-recentf)
         ("C-x f L" . helm-locate))
  :preface
  (progn
    (load "helm-autoloads" t t))
  :init
  (progn
    ...
```

**Comment by jwiegley** [comment]
@hrehfeld Unless you think there is an actual bug in `use-package`, I am closing.

**Comment by hrehfeld** [comment]
Sry, I seem to have solved or worked-around somehow, but I can't remember right now. Will try to go through my vcs log asap.

**Comment by anuragpeshne** [comment]
@hrehfeld I'm facing similar issue, Can you please share what solved this problem?

**Comment by anuragpeshne** [comment]
Yes, it was due to a syntax error. I was passing list of list to `:mode`. If anyone else faces this issue, look for syntax/typo errors.
