### ISSUE TITLE
Can't diminish hideshowvis / hs-minor-mode

### ISSUE THREAD

**Issue by mcandre** [jwiegley/use-package#207]
I want to hide the `hs` from the modeline like I hide other minor modes, but `:diminish hs-minor-mode` doesn't seem to work for some reason.

Configuration:

https://github.com/mcandre/dotfiles/blob/a0de1159c4a5674527cb0504461f2d204dd41eb6/.emacs#L880-L915

**Comment by thomasf** [comment]
Because the minor mode name is hideshowvis-minor-mode (if google led me to the correct source)

**Comment by mcandre** [comment]
Odd.

In any case, when I simplify my Emacs configuration to:

```
(use-package hideshowvis
  :diminish hs-minor-mode
  :bind ("M-[" . hs-toggle-hiding)
  :config
  (progn
    (hideshowvis-enable)

    ;; graphical +/- fold buttons
    (hideshowvis-symbols)))
```

then the mode is correctly diminished.

**Comment by thomasf** [comment]
It's still wrong though,... should probably be  `:diminish hideshowvis-minor-mode`

**Comment by mcandre** [comment]
On my machine, `C-h v minor-mode-alist` says it's `hs-minor-mode`.

**Comment by thomasf** [comment]
I checked this quickly just now..

`hs-minor-mode` is s built in in emacs

http://emacswiki.org/emacs/hideshowvis.el otoh has `hideshowvis-minor-mode`, when you removed the loading stuff from the earlier commit it probably stopped activating.
