### ISSUE TITLE
:defer [N] example needed

### ISSUE THREAD

**Issue by mcandre** [jwiegley/use-package#208]
I can't get the syntax of :defer [N] right, Emacs keeps complaining that :defer only takes one argument. Could you please add an example to the README?

... has use-package released a new version since `:defer [N]` was introduced? I updated my version of use-package, and now :idle is gone but :defer [N] doesn't seem to be available yet (at least in MELPA).

**Comment by thomasf** [comment]
this is an example

```elisp
(use-package back-button
  :ensure t
  :commands (back-button-mode)
  :diminish ""
  :defer 2
  :init
  (progn
    (setq back-button-show-toolbar-buttons nil))
  :config
  (progn
    (back-button-mode 1)))
    
```
