### ISSUE TITLE
:ensure t doesn't manage to load package from remote archive

### ISSUE THREAD

**Issue by mn200** [jwiegley/use-package#211]
I have the following in my `.emacs.d/init.el`

    (when (>= emacs-major-version 24)
      (require 'package)
      (add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
      (package-initialize))

    (if (not (package-installed-p 'use-package))
        (progn
          (package-refresh-contents)
          (package-install 'use-package)))

    (require 'use-package)
    (use-package swiper :ensure t)

The `swiper` package is not locally installed.  (If I do `M-x package-list-packages`, then I see that there are `swiper` entries at `gnu` and `melpa`.  Neither has the `20150422.858` version number (see below) attached (the first is `0.4.0`; the melpa one is `20150513...`).   When I try to execute the `use-package` line, I get an error.  If enabled, the backtrace is 

    Debugger entered--Lisp error: (file-error "http://melpa.org/packages/swiper-20150422.858.tar" "Not found")
      signal(file-error ("http://melpa.org/packages/swiper-20150422.858.tar" "Not found"))
      url-insert-file-contents("http://melpa.org/packages/swiper-20150422.858.tar")
      package-install-from-archive([cl-struct-package-desc swiper (20150422 858) "Isearch with an overview. Oh, man!" ((emacs (24 1))) tar "melpa" nil ((:url . "https://github.com/abo-abo/swiper") (:keywords "matching")) nil])
      mapc(package-install-from-archive ([cl-struct-package-desc swiper (20150422 858) "Isearch with an overview. Oh, man!" ((emacs (24 1))) tar "melpa" nil ((:url . "https://github.com/abo-abo/swiper") (:keywords "matching")) nil]))
      package-download-transaction(([cl-struct-package-desc swiper (20150422 858) "Isearch with an overview. Oh, man!" ((emacs (24 1))) tar "melpa" nil ((:url . "https://github.com/abo-abo/swiper") (:keywords "matching")) nil]))
      package-install(swiper)
      use-package-ensure-elpa(swiper)
      #[(name &rest args) "\306!\210\307\310\311\211$\307\312\"\307\313\"\307\314\"\307\315\"\307\316\311#@\307\317\311\211$A\307\320\"B\307\321\"C\307\322\311\211$D\307\323\311\211$E\307\324\311\211$F\307\325\311\211$G\307\326\311\211$\211H;\203oHIB\202qHJ\307\327\311\211$\211K;\203\210KIB\202\212KL\307\330\"M\307\331\311\211$N\307\332\"OA\205\270A<\203\263\333\334A\"\202\270\335ADCP\307\336\311#\211Q\204\311\311\202\344Q<\203\336\337\340\341\333\342\343QDEED\202\344\344\343QDDRI;\203\361I\202\365\345I!SI;\203\346I!\202IT\307\347\"?\2050O\203\350IO\"\210\307\351\"\211U\311=\203-I\206/U\211V\203>\352\353!\210\354V!\210*@\203\220\355
    \356@;\203]\357\343\346S\360P!D@EC\202\215@9\203m\357\343@DDC\202\215@:\203\210@A;\203\210\357\343@@D@AEC\202\215\333\361@\"BE	\203\234	9\203\234	CB\203\267C\204\251\362C\355\363\364\365\341BECE\fF\366\211W\367F\311#\210W\370G\311#\210W\371D\"\210W\372E\"\210W\373J\"\210W\374L\"\210)\355\375\333\376N;\203\367NC\202\377N!\203N \202N\"\201Y\201Z\201[\375P\201\\\201]I;\203,\201^I\201_BB\2026\352\343ID\201`BB\201a\201b\201c\343ID\201dBBB\201eBBFC\"BBD	\204o\307\201f\"\204o\307\324\"\204o\307\325\"\203\330\307\201g\"\204\330\341X\201h\201i	\"\210\201ZM\206\215\311\n\375X\f
    \205\313\201jI;\203\244I\202\250\343ID\201k\201l\365\341\201mR\201n\201o\201pS\"
    EEECBCCBE\201qBB\")BBB\202,\201m\201rM\206\344\311RE\201n\201o\201sS\"\201m\337I;\203\n\201^I\201tBB\202\352\343ID\201uBBD\201b\201vSE\n\f
    \201wBBBBBBEED\"BB.\207" [args commands pre-init-body pre-load-body init-body config-body use-package-validate-keywords use-package-plist-get :commands t :pre-init :pre-load :init :config :diminish :defines :idle :idle-priority :bind :bind* :bind-keymap :bind-keymap* :mode :interpreter :if :load-path :pin mapcar #[(var) "\301D\207" [var defvar] 2] defvar :requires not member nil (function featurep) quote featurep symbol-name intern :disabled use-package-pin-package :ensure require package use-package-ensure-elpa progn ignore-errors diminish "-mode" #[(var) "<\203\301\302@DAE\207\301\302DD\207" [var diminish quote] 3] ...] 24 ("/Users/michaeln/.emacs.d/elpa/use-package-20150118.722/use-package.elc" . 7295)](swiper :ensure t)
      macroexpand((use-package swiper :ensure t) nil)
      macroexp--expand-all((use-package swiper :ensure t))
      macroexpand-all((use-package swiper :ensure t))
      eval-sexp-add-defvars((use-package swiper :ensure t))
      eval-last-sexp-1(nil)
      eval-last-sexp(nil)
      call-interactively(eval-last-sexp nil nil)
      command-execute(eval-last-sexp)

Am I misunderstanding what `:ensure t` is supposed to doing?  (I thought it would download the package from the remote sources as needed, but that doesn't seem to be happening.)

**Comment by thomasf** [comment]
that should work,, maybe a problem with melpa?

**Comment by midraal** [comment]
try doing (package-refresh-contents) and try to install it again, might be it's trying to install an outdated version

**Comment by mn200** [comment]
Hah!  Thanks @midraal, that seems to have done the trick.

I'll add `(package-refresh-contents)` to the startup code I quoted before so that it runs every time.
