### ISSUE TITLE
:ensure list of packages

### ISSUE THREAD

**Issue by vanzef** [jwiegley/use-package#212]
I am trying to feed a list of packages to `:ensure` like this:
```
(use-package company
  :ensure '(company
	    company-ghc
	    company-cabal
	    company-auctex
	    company-math
	    )
 ```

but it says that `use-package-error: use-package: :ensure wants an optional package name (an unquoted symbol name)`

Can you fix/add this feature?

Thanks.

P.S. Also, I am not very good in Emacs Lisp at all. Correct me, please, if I am wrong.

**Comment by thomasf** [comment]
it's probably better to have multiple `(use-package...` 

Something like this:

```
(use-package company
  :ensure t
  :config
  (progn
    (use-package company-ghc :ensure t)
    (use-package company-cabal :ensure t)))
```

**Comment by linktohack** [comment]
You can have multiple `:ensure` params. I have something like this

```emacs-lisp
(use-package evil
  :ensure t :ensure evil-commentary :ensure evil-rsi
  :diminish evil-commentary-mode evil-rsi-mode undo-tree-mode
  :demand t
  :init
```

and it works pretty well :)

**Comment by superbobry** [comment]
See #111 for previous discussion.
