### ISSUE TITLE
Symbol's function definition is void: async-bytecomp-package-mode while seting up helm 1.7.1

### ISSUE THREAD

**Issue by azynheira** [jwiegley/use-package#214]
Hi,
I get the following error while trying to setup helm 1.7.1:
'Error (use-package): helm :init: Symbol's function definition is void: async-bytecomp-package-mode Warning (initialization): An error occurred while loading `/home/pedrog/.emacs.d/init.el':'

The use-package statement used is:
(use-package helm
  :ensure helm
  :diminish helm-mode
  :pin melpa-stable
  :init (progn
          (require 'helm-config)
          (require 'helm-grep)
          (setq helm-M-x-fuzzy-match t
                helm-M-x-requires-pattern nil
                helm-apropos-fuzzy-match  t
                helm-buffers-fuzzy-matching t ; fuzzy matching buffer names when non-nil - useful in helm-mini that lists buffers
                helm-buffers-list t
                helm-candidate-number-limit 500 ; limit the number of displayed canidates
                helm-ff-file-name-history-use-recentf t
                helm-ff-search-library-in-sexp t ; search for library in `require' and `declare-function' sexp.
                helm-ff-skip-boring-files t
                helm-idle-delay 0.0 ; update fast sources immediately (doesn't).
                helm-imenu-fuzzy-match nil
                helm-input-idle-delay 0.01 ; this actually updates things reeeelatively quickly.
                helm-lisp-fuzzy-completion t
                helm-locate-fuzzy-match  t
                helm-move-to-line-cycle-in-source t ; move to end or beginning of source when reaching top or bottom of source.
                helm-quick-update t                 ; do not display invisible candidates
                helm-recentf-fuzzy-match t
                helm-scroll-amount 4 ; scroll 4 lines other window using M-<next>/M-<prior>
                helm-semantic-fuzzy-match  t
                helm-split-window-in-side-p t ;; open helm buffer inside current window, not occupy whole other window
                )
          (add-to-list 'helm-sources-using-default-as-input 'helm-source-man-pages)
          ;; The default "C-x c" is quite close to "C-x C-c", which quits Emacs.
          ;; Changed to "C-c h". Note: We must set "C-c h" globally, because we
          ;; cannot change `helm-command-prefix-key' once `helm-config' is loaded.
          (global-set-key (kbd "C-c h") 'helm-command-prefix)
          (global-unset-key (kbd "C-x c"))

          (when (executable-find "curl")
            (setq helm-google-suggest-use-curl-p t)))
  :bind (("C-x b" . helm-mini)
         ("C-h f"  . helm-apropos)
         ("C-x C-b" . helm-buffers-list)
         ("M-x" . helm-M-x)
         ("M-y"  . helm-show-kill-ring)
         ("C-c h C-c w" . helm-wikipedia-suggest)
         ("C-c h o" . helm-occur)
         ("C-c h x" . helm-register)
         ("C-h C-l" . helm-locate-library)
         ("C-h SPC" . helm-all-mark-rings)
         ("C-h r" . helm-info-emacs)
         ("C-x C-f" . helm-find-files)
         ("C-x r j" . jump-to-register)
         ("C-x C-r" . helm-recentf))

  :config (progn
            (define-key helm-map (kbd "<tab>") 'helm-execute-persistent-action) ; rebihnd tab to do persistent action
            (define-key helm-map (kbd "C-i") 'helm-execute-persistent-action) ; make TAB works in terminal
            (define-key helm-map (kbd "C-z")  'helm-select-action) ; list actions using C-z

            (define-key helm-grep-mode-map (kbd "<return>")  'helm-grep-mode-jump-other-window)
            (define-key helm-grep-mode-map (kbd "n")  'helm-grep-mode-jump-other-window-forward)
            (define-key helm-grep-mode-map (kbd "p")  'helm-grep-mode-jump-other-window-backward)

            (define-key 'help-command (kbd "C-f") 'helm-apropos)
            (define-key 'help-command (kbd "r") 'helm-info-emacs)
            (define-key 'help-command (kbd "C-l") 'helm-locate-library)

            (custom-set-faces
             '(helm-selection ((t (:background "ForestGreen" :foreground "black")))))

            ;; Disable IDO-MODE
            (ido-mode -1)
            ;; Enable HELM-MODE
            (helm-mode 1)
            (helm-autoresize-mode 1)))

**Comment by midraal** [comment]
could you try installing the async package and trying again, that package provides async-bytecomp-package-mode

**Comment by azynheira** [comment]
Update async to version 1.3 of melpa-stable for example. I had a similar issue.

**Comment by midraal** [comment]
see also https://github.com/emacs-helm/helm/issues/1025

**Comment by azynheira** [comment]
That did the trick. I also reported in helm as well. Can be closed!
Thanks
