### ISSUE TITLE
Since upgrading to use-package 2.0, :config can run more than once

### ISSUE THREAD

**Issue by spwhitton** [jwiegley/use-package#215]
I have my org-mode config in a separate file, `init-org.el`, which I used to load like this:

    (use-package org
      :mode (("\\.org" . org-mode)
             ("\\.org_archive" . org-mode))
      :commands (org-capture
                 org-store-link
                 org-agenda)
      :config (load "~/.emacs.d/init-org.el"))

However, after upgrading to use-package 2.0, I found that the `:config (load ...)` got executed over and over again on opening each Org file.  As you can imagine this is pretty bad when I start my Emacs session by opening my Org agenda.

I have worked around the problem by removing the `:config` entry from my `(use-package org)` declaration, and using a separate `(eval-after-load 'org (load "~/.emacs.d/init-org.el"))` above it.

Is this intentional behaviour of use-package 2.0?  If so, what's the recommended way to load my init-org.el just once, within the use-package framework?  Thanks.

**Comment by thomasf** [comment]
Hmm,. your example exapnds to more or less the same things as you did manually in a slightly different order:

```elisp
(progn
  (unless
      (fboundp 'org-capture)
    (autoload
      (function org-capture)
      "org" nil t))
  (unless
      (fboundp 'org-store-link)
    (autoload
      (function org-store-link)
      "org" nil t))
  (unless
      (fboundp 'org-agenda)
    (autoload
      (function org-agenda)
      "org" nil t))
  (unless
      (fboundp 'org-mode)
    (autoload
      (function org-mode)
      "org" nil t))
  (eval-after-load 'org
    '(progn
       (condition-case-unless-debug err
           (load "~/.emacs.d/init-org.el")
         (error
          (ignore
           (display-warning 'use-package
                            (format "%s %s: %s" "org" ":config"
                                    (error-message-string err))
                            :error))))
       t))
  (ignore
   (push
    '("\\.org" . org-mode)
    auto-mode-alist)
   (push
    '("\\.org_archive" . org-mode)
    auto-mode-alist)))
```

**Comment by npostavs** [comment]
> using a separate `(eval-after-load 'org (load "~/.emacs.d/init-org.el"))`

You're missing a quote beore the `(load...)`, this is the same as just `(load "~/.emacs.d/init-org.el")` by itself.

**Comment by spwhitton** [comment]
@npostavs thanks, nice catch.

Fixing that mistake of mine is an effective workaround, despite the expansion to nearly the same thing.

**Comment by thomasf** [comment]
The effective eval-after-load is so similar I'm guessing that your problem might reoccur  when you fixed the problem with your workaround mentioned by npovstars.

**Comment by spwhitton** [comment]
@thomasf it didn't!

**Comment by spwhitton** [comment]
@thomasf Thanks for your reply.  The problem doesn't reoccur when I fix the problem with my workaround mentioned by npovstars.

Using `:config (require 'init-org)` and add `(provides 'init-org)` to init-org.el means that init-org.el doesn't seem to get loaded at all.

**Comment by thomasf** [comment]
thats really strange, or its just me readinf too fast again :( init-org.el needs to be added to load-path to be found,  ~/.emacs.d should not be on the load path... I have files like that in ~/.emacs.d/lisp/

**Comment by npostavs** [comment]
Yeah, I was half expecting the reloading thing to pop up again when you added the missing quote too. Maybe try adding `(debug)` to the `:config` block so you can see where it's getting called from?
