### ISSUE TITLE
Where should helm face configuration live?

### ISSUE THREAD

**Issue by angrybakon** [jwiegley/use-package#216]
Hi, I came across this package when looking for help as I was trying to wrap my package-related configuration with `with-eval-after-load`s... And I must say, I'm very pleased someone took the time to put this up :).

However, I'm having a hard time figuring out how [`helm`](https://github.com/emacs-helm/helm) should be initialized:

```elisp
;; https://github.com/emacs-helm/helm
(use-package helm
  ...
  :config
  (when (member "Monaco" (font-family-list))
    (set-face-attribute 'helm-header nil :font "Monaco-12")
    (set-face-attribute 'helm-source-header nil :font "Monaco-14"))
  (set-face-attribute 'helm-header nil :italic t)
  (set-face-attribute 'helm-source-header nil :foreground zenburn/blue :background zenburn/bg :box nil)
  (set-face-attribute 'helm-match nil :foreground "gold1")

  (use-package helm-command
    ...))
```

```elisp
;; https://github.com/bbatsov/projectile
(use-package projectile
  ...
  :config

  (use-package helm-projectile
    :config
    (helm-projectile-on))
  ...)
```

The `set-face-attribute`s don't seem to be active, I still have default styles. Work as expected when I eval those lines though. Any idea what I am doing wrong ?

---

**Edit:**

There seem to be an issue with [`expand-region`](https://github.com/magnars/expand-region.el) as well:

```elisp
;; https://github.com/magnars/expand-region.el
(use-package expand-region
  ...
  :config
  (pending-delete-mode t))
```

`(pending-delete-mode t)` has no effect within `:config`, but works fine when `eval`'d.

**Comment by angrybakon** [comment]
In regard of my first issue, it appears that code is well evaluated but `(load-theme 'zenburn t)` overrides it all. How can I tell each of configuration partials to be loaded after the theme has been activated?

**Comment by jwiegley** [comment]
It's possible you may need to put your face configuration on a mode-related hook (i.e., not using just `:config` in use-package).  I find helm to be a very tricky package to configure correctly; you may want to see how I do it in my own configuration: https://github.com/jwiegley/dot-emacs.
