### ISSUE TITLE
There is no good way to install and upgrade `use-package`

### ISSUE THREAD

**Issue by marcinant** [jwiegley/use-package#219]
Problem is that `use-package` is available as ELPA package and this is probably easiest way to install and upgrade.
Unfortunately `use-package` should be initialized before Emacs initializes ELPA packages.

So, when this macro is installed as ELPA package there is no way to `(require 'use-package)` because Emacs doesn't know where `use-package` is.

The only way I see is to add full path to `bind-key` and `use-package` as second argument to `require`.
It works however manual update is required every time ELPA package is upgraded.

Any other ideas to solve this problem?

**Comment by thomasf** [comment]
I'm not sure that I follow.. When use-package is installed, package.el will find it and upgrade it after invoking `list-packages`

I have additionaly set up so that I don't need to initalize packages by saving the load path

This is 
```

```

**Comment by xuchunyang** [comment]
> Unfortunately use-package should be initialized before Emacs initializes ELPA packages.

Why? I think there is no need to initialize use-package, of course you have to install use-package before using it, you can install use-package from ELPA like this way:

```elisp
;; Setup package.el
(require 'package)
(setq package-enable-at-startup nil)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
(package-initialize)

;; Bootstrap `use-package'
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

;; Use use-package now
```

**Comment by marcinant** [comment]
Running `package-initialize` on top of emacs is plain stupid.

You are right. If I add `package-initialize` before I try to require `use-package` then it's going to run properly.

However and idea behind `package-initialize` is to run this command AFTER `.emacs` or `init.el` and run all configuration on `after-init-hook`.

**Comment by thomasf** [comment]
@marcinant My solution only requires/uses `packages.el` inside `eval-when-compile` in init.el or when `load-path.el` is recompiled

**Comment by thomasf** [comment]
My emacs starts in about 1-1.1seconds on my 2009 i7 desktop computer (provided files are loaded into disk cache)..  
Thats with 778 packages in elpa/ and a ~10kloc `init.el`

**Comment by thomasf** [comment]
I just also remembered my `load-path.el`only recompiles itself if it already is byte compiled,

**Comment by npostavs** [comment]
> Running package-initialize on top of emacs is plain stupid.

?

[Artur Malabarba wrote](https://lists.gnu.org/archive/html/emacs-devel/2015-03/msg01016.html):
> On the "Customizable modes..." thread I suggested we run
> (package-initialize) sooner than the way it's currently done. Right
> now, it's called after loading the init file. Which means any user who
> tries to customize an installed package by pasting some code into his
> init file will be confronted with errors.
> This happens A LOT.
> 
> Stefan kindly explains why it can't just be done before loading the init file:
> > [...] the user may need/want to run some Elisp
> > code of his own choosing *before* package-initialize is called.
> > E.g. [...] set package-load-list and package-directory-list
> 
> But I'm asking that we try a little harder to find a better solution.
> This package.el-induced "cannot find load file" error is the most
> predominant issue I see people run into in the wild. Some people file
> issues for this stuff on github (and waste developer time), [...]

> Option 2) Instead of us manually telling users to add
> `(package-initialize)' to their init-files, we have Emacs do that
> automatically. [...]

**Comment by marcinant** [comment]
> Running package-initialize on top of emacs is plain stupid.
> 
> ?

Just because `startup.el` contains this code:
```
       (package-initialize))

  (setq after-init-time (current-time))
  (run-hooks 'after-init-hook)
```

So, `package-initialize` is part of normal startup procedure and there is no reason to disturb this order and run `package-initialize` **twice**.

> 
> Artur Malabarba wrote:
> 
>     On the "Customizable modes..." thread I suggested we run
>     (package-initialize) sooner than the way it's currently done. Right
>     now, it's called after loading the init file. Which means any user who
>     tries to customize an installed package by pasting some code into his
>     init file will be confronted with errors.
>     This happens A LOT.

It's their problem. They should use `after-init-hook` and that's it.

>     Some people file
>     issues for this stuff on github (and waste developer time), [...]

Developer should just provide documentation how to configure package on `after-init-hook`.

**Comment by thomasf** [comment]
@marcinant  it runs twice unless you set `(setq package-enable-at-startup nil)`

**Comment by thomasf** [comment]
I used strace to guide my decision of removing `package-initialize`  on normal emacs startup.. The combination of emacs synchronized io and lot's of file descriptor calls just makes it slow.

Since use-pakcage `:commands` generates autoloads there is little `package.el` does at start up except set the load path.

**Comment by marcinant** [comment]
Hmm... is your .emacs available somewhere?

Anyway I decided to use this dirty piece of code:
```
(when package-enable-at-startup
  (eval-when-compile
    (let ((default-directory package-user-dir))
      (require 'bind-key (car (file-expand-wildcards "bind-key*/bind-key.elc" t)))
      (require 'use-package (car (file-expand-wildcards "use-package*/use-package.elc" t))))))
```
Now I need to switch my .emacs to use package and test it.
I don't care about load time that much as I use emacsclient and run emacs on startup just once.

**Comment by thomasf** [comment]
yeah https://github.com/thomasf/dotfiles-thomasf-emacs

**Comment by marcinant** [comment]
After further code analysis I have to admit that I don't understand the idea behind `use-package`.

Package.el is intended to load **after** user init file.
Unfortunately `use-package` doesn't want to work while packages are not initialized.

IMHO this is just plain wrong. Could someone (an author) enlighten me and tell why is it designed in this way?

**Comment by thomasf** [comment]
It's not really designed for package.el.. John (the author) doesnt even use package.el.

**Comment by marcinant** [comment]
Ok. Now I can see what the problem was. All my packages are not in load-path until `package.el` is initialized. Sigh....

**Comment by marcinant** [comment]
Well, you may close this bug. However problem is still alive.

Although `use-package` is available on ELPA it should not be installed as package.

**Comment by thomasf** [comment]
I disagree that this is an use-package issue, after all it's elisp were talking about and it's as easy as invoking `(package-initialize)` when it's needed.. Also the emacs-devel discussion link posted by npostavs in this issue suggests that the default behavior might actually change into doing it before user init by default.

**Comment by marcinant** [comment]
It's undocumented. It should be mentioned in readme that one has to invoke `(package-initialize)` or provide load-path manually.

When someone will install this macro as ELPA package and initialize in the way described in readme then it's not going to work.

**Comment by thomasf** [comment]
btw. emacs-25, ie. the master branch now does this to the top of the user  init.el

;; Added by Package.el.  This must come before configurations of
;; installed packages.  Don't delete this line.  If you don't want it,
;; just comment it out by adding a semicolon to the start of the line.
;; You may delete these explanatory comments.
 (package-initialize)

**Comment by marcinant** [comment]
Well it's just wierd. Default policy is: use init.el to set up config with after-init-hooks, then 'package-initialize' is issued automatically by 'startup.el' right after 'init.el' is loaded.

There is no good reason to run 'package-initialize' from 'init.el'.

**Comment by thomasf** [comment]
Weird or not, the default policy seems to be changing. 

I find it a bit less weird with `(package-initialize)` at the top than having to wrap most of init.el inside  hook functions when the only reason is to wait for package.el. The new policy will  probably be a lot less confusing for many Emacs newbies as well.

**Comment by errge** [comment]
I made a pull request to implement something similar to thomasf's setup, but a simpler way: https://github.com/jwiegley/use-package/pull/487

**Comment by raxod502** [comment]
> Default policy is: use init.el to set up config with after-init-hooks, then 'package-initialize' is issued automatically by 'startup.el' right after 'init.el' is loaded.

Sorry, but I disagree. There is simply no practical disadvantage to running `package-initialize` in the init-file, and it makes things so much simpler. Putting your entire configuration in `after-init-hook`? That's a needless layer of indirection.

In any case, Emacs now initializes the package system before loading the init file, thus rendering this entire debate superfluous. The feature will be released in Emacs 27.

**Comment by jwiegley** [comment]
> In any case, Emacs now initializes the package system before loading the init file, thus rendering this entire debate superfluous. The feature will be released in Emacs 27.

As long as this can be disabled, right?

**Comment by raxod502** [comment]
> this can be disabled, right?

In `~/.emacs.d/early-init.el`, place:

```elisp
(setq package-enable-at-startup nil)
```
