### ISSUE TITLE
Method of handling package dependencies

### ISSUE THREAD

**Issue by belak** [jwiegley/use-package#220]
For instance, if I need to load `company-go` after `company` is loaded. Currently, I believe the only way to do this is to nest calls to `use-package` but that makes it so if I want to group all my Go (as an example) packages together, I'd need to do it all inside an unrelated declaration.

Is there a better way of doing this? And if not, would something like a `:requires` keyword make sense?

**Comment by belak** [comment]
It looks like you use :requires in your own config, so it might already exist?

**Comment by Silex** [comment]
There's a `req-package` somewhere that is implemented using `use-package`.

**Comment by belak** [comment]
There's this: https://github.com/jwiegley/use-package/blob/master/use-package.el#L519

However, there's no documentation, so I'm not 100% positive it does what I think it does. Seems to work though.

**Comment by jwiegley** [comment]
I think `:requires foo` is the same thing as `:if (feature foo)`.  I didn't even remember this was in there, but it's apparently been a part of `use-package` since the beginning.
