### ISSUE TITLE
Installation??

### ISSUE THREAD

**Issue by rusimody** [jwiegley/use-package#222]
Hi John
Must have surely missed it but how to install use-package?
I didn't really try but running locate library on the list of requires I see gave me some blanks

**Comment by jwiegley** [comment]
just `(require 'use-package)`, assuming it is found on your `load-path`.  Then use the macro as per the documentation.

**Comment by rusimody** [comment]
Tnx John :+1: 
Seems to work
Having a line in readme would of course help dimwits (like urs truly)
