### ISSUE TITLE
binding local keymaps to keys

### ISSUE THREAD

**Issue by vapniks** [jwiegley/use-package#226]
This works: `(define-key dired-mode-map "/" dired-filter-map)`
This doesn't: `(bind-key "/" dired-filter-map dired-mode-map)`
`dired-filter-map` is a keymap from the dired-hacks / dired-filter package: https://github.com/Fuco1/dired-hacks

**Comment by npostavs** [comment]
How does it go wrong?

**Comment by jwiegley** [comment]
You will need to use `bind-keymap`.

**Comment by vapniks** [comment]
Sorry, my mistake: `(bind-key "/" dired-filter-map dired-mode-map)` does actually work, 
but ```(bind-keys :map dired-mode-map ("/" . dired-filter-map) ("#" . dired-filter-mark-map))``` doesn't. 
It says `Symbol's function definition is void: dired-filter-mark-map`
 
The problem with `bind-keymap` is that it binds the key to the keymap globally, so then I can't use `"/"` normally in other modes. I need to bind a key within a keymap to another keymap.

**Comment by jwiegley** [comment]
`bind-keymap` should support local definitions just as `bind-key` does.

**Comment by vapniks** [comment]
What is the syntax for that? 
If I do this:
```(use-package dired-filter
         :bind-keymap ("/" . dired-filter-map)
         :commands dired-filter-map)```
the `"/"` key is bound globally, but if I do this:
```(use-package dired-filter
         :bind-keymap ("/" dired-filter-map dired-mode-map)
         :commands dired-filter-map)```
I get an error: "bind-keymap wants a string, (string . symbol) or a list of these"

**Comment by jwiegley** [comment]
I believe the syntax would be `:bind-keymap (:mode dired-mode-map ("/" . dried-filter-map))`, but it may not work just yet due to another pending bug fix.

**Comment by jasonm23** [comment]
@jwiegley Could you update the docs section of the code to show the proper syntax for `:bind-keymap` and `:bind-keymap*`?

It looks like it would be very useful! After doing a quick survey of all usage of `use-package` in github emacs.d repos, I can't find a single instance of `:bind-keymap` in the wild.

**Comment by waymondo** [comment]
@jasonm23 the basic syntax is the same as `:bind`, but using keymaps instead of functions. here's an example in the wild if that helps:

https://github.com/waymondo/hemacs/blob/master/init.el#L498-L516

**Comment by jasonm23** [comment]
@waymondo so it isn't for binding commands? In your example

```
:bind-keymap ("s-p" . projectile-command-map)
```

<kbd>Super</kbd> - <kbd>p</kbd> would switch on the `projectile-command-map` ?

Could you help me understand the usefulness of this?

**Comment by jasonm23** [comment]
@waymondo my assumption was that I could use `:bind-keymap` to add key bindings to the keymaps in a package, is that completely off base?

**Comment by jasonm23** [comment]
Should I just be using:

```
:bind (:map some-mode-map (("C-c j" . command) 
         ("C-c k" . command)))
```

Instead?

**Comment by waymondo** [comment]
yes, i believe the later is the right approach to binding additional functions to a specific keymap. note though that if `some-mode-map` isn't autoloaded though, the `:bind` keyword doesn't provide that for the map like it does for the functions: https://github.com/jwiegley/use-package/issues/269

**Comment by jasonm23** [comment]
@jwiegley please clarify, your other comments relating to `:bind-keymap` seem to suggest that it's _going to be_ the preferred way.

Hopefully it's working already, and the syntax is just unclear. (the lazy evaluation is obviously a key  requirement!)

**Comment by jwiegley** [comment]
Sure, I'll document it. I'd like `bind-keymap` to become the default behavior of `:map` if the map you're binding to isn't presently in scope.

**Comment by jwiegley** [comment]
Hmm... I see where the confusion might be coming from.  I'll take another look at `bind-keymap`, and find a way to unify it with `bind` in a manner that is intuitive.

**Comment by kaushalmodi** [comment]
Here's a discussion about this on reddit: https://www.reddit.com/r/emacs/comments/3rftqi/bindkeymap_in_usepackage/

**Comment by jasonm23** [comment]
@jwiegley much appreciated

**Comment by vapniks** [comment]
@jwiegley Congratulations on your new role :)

**Comment by jwiegley** [comment]
@vapniks Thanks!

**Comment by Silex** [comment]
@jwiegley: any progress on this? I'm moving away from `define-key` and the current lack of documentation/working examples is very confusing.

**Comment by jwiegley** [comment]
@Silex Rather than document `:bind-keymaps`, I'm going to merge its functionality into `:bind` and document the use of the `:map` keyword. It will happen soon, but my schedule has been terrible recently. For reasons you can probably imagine. :)

**Comment by Silex** [comment]
Alright, will wait then.

**Comment by jwiegley** [comment]
Fixed.  The following:

``` elisp
(use-package term
  :bind (("M-a" . term-send-a)
         :map term-mode-map
         ("M-p" . term-send-up)
         ("M-n" . term-send-down)
         :map term-raw-map
         ("M-o" . other-window)
         ("M-p" . term-send-up)
         ("M-n" . term-send-down)))
```

Expands to this (minimally):

``` elisp
(progn
  (unless
      (fboundp 'term-send-a)
    (autoload
      (function term-send-a)
      "term" nil t))
  (unless
      (fboundp 'term-send-up)
    (autoload
      (function term-send-up)
      "term" nil t))
  (unless
      (fboundp 'term-send-down)
    (autoload
      (function term-send-down)
      "term" nil t))
  (unless
      (fboundp 'other-window)
    (autoload
      (function other-window)
      "term" nil t))
  (ignore
   (progn
     (bind-key "M-a" 'term-send-a nil nil)
     (eval-after-load 'term
       '(progn
          (bind-key "M-p" 'term-send-up term-mode-map nil)
          (bind-key "M-n" 'term-send-down term-mode-map nil)))
     (eval-after-load 'term
       '(progn
          (bind-key "M-o" 'other-window term-raw-map nil)
          (bind-key "M-p" 'term-send-up term-raw-map nil)
          (bind-key "M-n" 'term-send-down term-raw-map nil))))))
```

**Comment by jwiegley** [comment]
`:bind-keymaps' has been removed entirely.

**Comment by jasonm23** [comment]
Excellent, thank you John, much appreciated.



jasonm23@gmail.com
skype: jasonm23
mobile phone: +65 8717 4344 (Singapore)

**Comment by jasonm23** [comment]
Excellent, thank you John  @jwiegley

**Comment by jwiegley** [comment]
Oops, had to bring back `:bind-keymaps'.  It still does something special that can't be inferred, since I don't know that what you're binding to won't become a keymap after the package is autoloaded.
