### ISSUE TITLE
Question about using other shortcuts to call a function inside certain package

### ISSUE THREAD

**Issue by maniux** [jwiegley/use-package#227]
Hi, not an issue but just a question.
A little confuse here:

I find that even if I comment the lines below:
> (use-package expand-region  
>     :ensure t
>     :defer t)

I can still call the expand-region function using key-chord keybindings:
>    (key-chord-define-global "xx"     'er/expand-region)

Since I have many packages, and trying to speed up the start process, will the
> use-package expand-region
do anything if I do not make any config to the package? And will it cost time to do this?
Because otherwise I can uncomment all similar packages.

Thanks.

**Comment by jwiegley** [comment]
The form `(use-package foo :defer t)` will macro expand to just nil.

**Comment by maniux** [comment]
Got it.
Thanks.
