### ISSUE TITLE
unbind-keys?

### ISSUE THREAD

**Issue by c02y** [jwiegley/use-package#232]

**Comment by IvanMalison** [comment]
@jwiegley Why was this closed? Should unbind-keys just take place in :config?

**Comment by jwiegley** [comment]
I think so; I prefer not adding new keywords for rare things that can happen in `:config`.  Something has to be a very common pattern to justify a keyword, or be something where having the keyword prevents you from making a mistake, or it makes the expanded result much more efficient than the typical way of doing things.
