### ISSUE TITLE
Support multiple :maps in bind-key

### ISSUE THREAD

**Issue by nickalcock** [jwiegley/use-package#237]
This does, in fact, not work. The latest use-package (with my commit to support :bind :map) expands to this (courtesy of pp-macroexpand-expression):

    `(use-package wide-n
      :bind (:map narrow-map ("x" . wide-n-repeat)
             :map ctl-x-map ("nx" . wide-n)))`
     -> 
    `(progn
      (unless
          (fboundp 'wide-n-repeat)
        (autoload #'wide-n-repeat #1="wide-n" . #2=(nil t)))
      (unless
          (fboundp 'wide-n)
        (autoload #'wide-n #1# . #2#))
      (ignore
       (bind-keys :map narrow-map
                  ("x" . wide-n-repeat)
                  :map ctl-x-map
                  ("nx" . wide-n))))`

Unfortunately we then get a backtrace from the expansion of bind-keys, which makes it look very much like bind-keys isn't ready to see anything but a list after the lists start, most particularly not a keyword argument:

    `Debugger entered--Lisp error: (wrong-type-argument listp :map)
      car(:map)
      (list (quote bind-key) (car form) (list (quote quote) (cdr form)) m)
      (lambda (m) (list (quote bind-key) (car form) (list (quote quote) (cdr form)) m))(narrow-map)
      mapcar((lambda (m) (list (quote bind-key) (car form) (list (quote quote) (cdr form)) m)) (narrow-map))
      (if maps (mapcar (function (lambda (m) (list (quote bind-key) (car form) (list (quote quote) (cdr form)) m))) maps) (list (list (quote bind-key) (car form) (list (quote quote) (cdr form)))))
      (if prefix-map (list (list (quote bind-key) (car form) (list (quote quote) (cdr form)) prefix-map)) (if maps (mapcar (function (lambda (m) (list (quote bind-key) (car form) (list (quote quote) (cdr form)) m))) maps) (list (list (quote bind-key) (car form) (list (quote quote) (cdr form))))))
      (lambda (form) (if prefix-map (list (list (quote bind-key) (car form) (list (quote quote) (cdr form)) prefix-map)) (if maps (mapcar (function (lambda (m) (list (quote bind-key) (car form) (list ... ...) m))) maps) (list (list (quote bind-key) (car form) (list (quote quote) (cdr form)))))))(:map)
      mapcar((lambda (form) (if prefix-map (list (list (quote bind-key) (car form) (list (quote quote) (cdr form)) prefix-map)) (if maps (mapcar (function (lambda (m) (list (quote bind-key) (car form) (list ... ...) m))) maps) (list (list (quote bind-key) (car form) (list (quote quote) (cdr form))))))) (("x" . wide-n-repeat) :map ctl-x-map ("nx" . wide-n)))
      (apply (function nconc) (mapcar (function (lambda (form) (if prefix-map (list (list (quote bind-key) (car form) (list ... ...) prefix-map)) (if maps (mapcar (function ...) maps) (list (list ... ... ...)))))) key-bindings))
      (append (if prefix-map (progn (cons (list (quote defvar) prefix-map) (append (if doc (progn (list ...))) (if menu-name (list (list ... ... nil menu-name)) (list (list ... ...))) (if maps (mapcar (function ...) maps) (list (list ... prefix ...))))))) (apply (function nconc) (mapcar (function (lambda (form) (if prefix-map (list (list ... ... ... prefix-map)) (if maps (mapcar ... maps) (list ...))))) key-bindings)))
      (macroexp-progn (append (if prefix-map (progn (cons (list (quote defvar) prefix-map) (append (if doc (progn ...)) (if menu-name (list ...) (list ...)) (if maps (mapcar ... maps) (list ...)))))) (apply (function nconc) (mapcar (function (lambda (form) (if prefix-map (list ...) (if maps ... ...)))) key-bindings))))
      (let* ((map (plist-get args :map)) (maps (if (listp map) map (list map))) (doc (plist-get args :prefix-docstring)) (prefix-map (plist-get args :prefix-map)) (prefix (plist-get args :prefix)) (menu-name (plist-get args :menu-name)) (key-bindings (progn (while (keywordp (car args)) (car-safe (prog1 args (setq args ...))) (car-safe (prog1 args (setq args ...)))) args))) (if (or (and prefix-map (not prefix)) (and prefix (not prefix-map))) (progn (error "Both :prefix-map and :prefix must be supplied"))) (if (and menu-name (not prefix)) (progn (error "If :menu-name is supplied, :prefix must be too"))) (macroexp-progn (append (if prefix-map (progn (cons (list (quote defvar) prefix-map) (append (if doc ...) (if menu-name ... ...) (if maps ... ...))))) (apply (function nconc) (mapcar (function (lambda (form) (if prefix-map ... ...))) key-bindings)))))
      (lambda (&rest args) "Bind multiple keys at once.\n\nAccepts keyword arguments:\n:map - a keymap into which the keybindings should be added\n:prefix-map - name of the prefix map that should be created for\n              these bindings\n:prefix - prefix key for these bindings\n:prefix-docstring - docstring for the prefix-map variable\n:menu-name - optional menu string for prefix map\n\nThe rest of the arguments are conses of keybinding string and a\nfunction symbol (unquoted)." (let* ((map (plist-get args :map)) (maps (if (listp map) map (list map))) (doc (plist-get args :prefix-docstring)) (prefix-map (plist-get args :prefix-map)) (prefix (plist-get args :prefix)) (menu-name (plist-get args :menu-name)) (key-bindings (progn (while (keywordp (car args)) (car-safe (prog1 args ...)) (car-safe (prog1 args ...))) args))) (if (or (and prefix-map (not prefix)) (and prefix (not prefix-map))) (progn (error "Both :prefix-map and :prefix must be supplied"))) (if (and menu-name (not prefix)) (progn (error "If :menu-name is supplied, :prefix must be too"))) (macroexp-progn (append (if prefix-map (progn (cons (list ... prefix-map) (append ... ... ...)))) (apply (function nconc) (mapcar (function (lambda ... ...)) key-bindings))))))(:map narrow-map ("x" . wide-n-repeat) :map ctl-x-map ("nx" . wide-n))
      macroexpand((bind-keys :map narrow-map ("x" . wide-n-repeat) :map ctl-x-map ("nx" . wide-n)) nil)`

I'll have a look at this, but it might be next week before I can get to it.

**Comment by nickalcock** [comment]
Oh good grief that's unreadable. Sorry! Markdown's backtick code-quoting is running lines together, most unhelpfully...

**Comment by andersjohansson** [comment]
@nickalcock, make it a code block by indenting four spaces. :smile:

**Comment by zakkak** [comment]
Or use three backticks in a row instead

    ```
    Code here
    ```

**Comment by nickalcock** [comment]
Thanks, it looks better now!

**Comment by IvanMalison** [comment]
What is the status of this?

Has anyone tried to implement the unbind funtionality that @jwiegley seems to use in https://youtu.be/2TSKxxYEbII?t=26m1s?

**Comment by jwiegley** [comment]
This is quite easy to fix in and of itself, it's just a question of retaining accurate error messages when people use the feature wrongly, and this is what has held this ticket up.

**Comment by IvanMalison** [comment]
@jwiegley What is the standard for error messages that you have in mind?

Also, is the syntax proposed by @nickalcock definitely the one that should be used for multiple maps. It seems strange to use the same keyword symbol multiple times in the same list. though it will obviously be possible to parse this and do the right thing in the use-package macro, I think it might be better to put each mode-map in its own list

**Comment by jwiegley** [comment]
That if someone has a `:bind` value of an incorrect form, they are alerted to this fact, and told why it is incorrect, making it easier to correct their `use-package` declaration.

**Comment by jwiegley** [comment]
The worst is when starting up your Emacs gives you a backtrace like "Value not stringp". I want incorrect uses of `use-package` to tell the user as clearly as possible what went wrong, where, and why.

**Comment by kaushalmodi** [comment]
Sorry, I couldn't understand the discussion. Is the format to specify bindings for multiple maps incorrect? Or is it not supported?

**Comment by jwiegley** [comment]
The feature is present, just the input validation is not sophisticated enough yet to support it.

**Comment by jwiegley** [comment]
Multiple `:map` invocations within a single `:bind` now works.
