### ISSUE TITLE
Use-package is not visible in Messages buffer

### ISSUE THREAD

**Issue by ReneFroger** [jwiegley/use-package#240]
## Setup:
GNU Emacs GUI version 24.4.51.1 (x86_64-w64-mingw32) 
[Compiled from Harroogan Emacs.](https://bitbucket.org/Haroogan/emacs-for-windows/)
Use-package, using the latest version of use-package from MELPA
Windows 7 x64 bit.

## Situation:
The documentation says the following: 

      Here is the simplest use-package declaration:

       (use-package foo)

           This loads in the package foo, but only if foo is available on your system. If not, a warning is  logged to the *Messages* buffer. If it succeeds, a message about "Loading foo" is logged, along with the time it took to load, if it took over 0.1s.

## Action:
You could try a minimal setup in your `dot-emacs`:

     (require 'package)
     (package-initialize)
     
     (add-to-list 'package-archives
                  '("melpa" . "http://melpa.org/packages/") t)
     
     (setq user-emacs-directory "C:/Dropbox/Emacs/")
      (setq custom-file (concat user-emacs-directory "custom.el"))
     (add-to-list 'load-path "C:/Dropbox/Emacs/.emacs.d/")
     
    
     ;; Basic requires
     (require 'cl)
     (require 'cl-lib)
     (require 'use-package)
     (setq use-package-verbose t)

       (eval-when-compile (require 'cl-lib))
     
       (eval-and-compile
         (add-to-list 'load-path
           (concat user-emacs-directory "modules/")))
    
     (load "C:/Dropbox/Emacs/init.el")

Then in the init.el:

     (require 'config-evil)

And in the `modules/config-evil.el`: 

     (use-package evil
         :ensure t
          :config
          (evil-mode 1)
        )

I notice with this minmal setup, Evil gets loaded. But I see no any log in the *Messages* buffer.

**Comment by thomasf** [comment]
What is this `dot-emacs` you are referring to? Is it the same as `init.el`?

The following line should cause an error unless you have also created an variable named `set`:

```elisp
 (setq use-package-verbose set t)
```

**Comment by ReneFroger** [comment]
It was a typo. Thanks for your attention.

**Comment by thomasf** [comment]
so it was never your actual config here?

**Comment by ReneFroger** [comment]
It's my actual config. After reading the option of `use-package-verbose`, I added it to my configuration, tried it with <kbd>C-x C-e</kbd> and edited the post above manually, hence the typo.

**Comment by thomasf** [comment]
So it still doesn't work even after you fixed the error? That is strange.. Do you maybe have an left over `.elc` somewhere causing the `.el` not to be loaded?

**Comment by ReneFroger** [comment]
It still doesn't work, and there is no error. It was just a typo on this Github reply screen. I thought it was clear enough.
I compile the modules whcih are `.el` files to `.elc`. Only the Helm package is a big load, then I see this: 

     Loading package helm...done (1.911s)

But for the other packages, I don't see any load times. But I use a specific Emacs organization. For example, package foobar is specificed in `modules/config-foobar.el`


    (provide 'config-foobar)
    (use-package foobar

    :config
    [..]

    )

Then in my `init.el`

    (require config-foobar)


The init.el is being loaded from my dot-emacs in my home directory. It is constructed as following:

    (require 'package)
    (package-initialize)

    ;; Basic requires
    (eval-when-compile (require 'cl))
    (eval-when-compile (require 'cl-lib))

    (require 'use-package)
    (setq use-package-always-ensure t
        use-package-verbose t)

    (eval-and-compile
        (add-to-list 'load-path
        (concat user-emacs-directory "modules/")))

    (load "C:/Dropbox/Emacs/init.el")

**Comment by npostavs** [comment]
Does it help if you wrap the `use-package-verbose` setting in `eval-and-compile`?

**Comment by ReneFroger** [comment]
Refering to your tip, I modified my dot-emacs as following: 

    (require 'package)
    (package-initialize)

    ;; Basic requires
    (eval-when-compile (require 'cl))
    (eval-when-compile (require 'cl-lib))

    (require 'use-package)
    (eval-and-compile (setq-default use-package-verbose t))
    (eval-and-compile (setq use-package-verbose t))

    (eval-and-compile
        (add-to-list 'load-path
        (concat user-emacs-directory "modules/")))

    (load "C:/Dropbox/Emacs/init.el")

Then I restarted Emacs. However, it didt't help a much. My `messages` buffer still looks like this: 

![screenshot](https://cloud.githubusercontent.com/assets/5211845/9145165/a8d91286-3d52-11e5-8ccb-4fee0284f3dd.png)

Note that after the `For information about GNU Emacs and the GNU system, type C-h C-a.` the rest of packages are loaded with the `:defer` option in use-package.

But I'm still missing the load times with the setting `use-package-verbose`.

**Comment by npostavs** [comment]
Oh, you just want to set `use-package-minimum-reported-time` to 0.

**Comment by ReneFroger** [comment]
Ah yes! That's it. Now I get the load times of the packages, even the little ones. But for the packages with the `defer` option, I see only the configuration time, and no loading time, which I find somewhat strange. But I'm already happy. 

Thank you, Noam!

**Comment by npostavs** [comment]
> But for the packages with the defer option, I see only the configuration time, and no loading time, which I find somewhat strange.

For deferred packages use-package doesn't trigger the loading, so it can't be timed. And `autoload-do-load` is in C, so probably even using advice wouldn't work.

**Comment by ReneFroger** [comment]
Ah, that explains a lot. Thanks.
