### ISSUE TITLE
Could the "Note to users upgrading to 2.0" placed at bottom in README?

### ISSUE THREAD

**Issue by ReneFroger** [jwiegley/use-package#241]
I found the large "Note to users upgrading to 2.0" block very confusing, when trying to figure out what use-package means. Could it be placed on the bottom, so that the "Use-package" documentation is again on the top?

**Comment by alamaison** [comment]
+1 I found that very confusing two. I gave use-package a miss several times because I thought the documentation was chaotic. It took me a while to realise I just had to scroll really far down.
