### ISSUE TITLE
Don't convert package names specified as strings to symbols

### ISSUE THREAD

**Issue by Alexander-Shukaev** [jwiegley/use-package#244]
There exist packages which don't do `provide` and, hence, cannot be referred to with symbols, but should rather be referred to with strings.  Here is a simple example.  Consider the standard `window.el`.

```
(use-package "window"
  :defer
  :init
  (message "init")
  :config
  (message "config"))
```

The `:config` body will never be executed, and the reason is the sloppy handling of symbols vs. strings for the `name` parameter in the `use-package` macro.  The problematic code snippets are

```
(let* ((name-symbol (if (stringp name) (intern name) name)) ...
```

and

```
`((eval-after-load ',name-symbol
              ',(macroexp-progn config-body)))
```

In case of the current example (`window.el`) this will expand into

```
(eval-after-load 'window ...
```

which does nothing because there is no package loaded which would `(provide 'window)`.

To conclude, the solution is to make it expand into

```
(eval-after-load "window" ...
```

which would deliver the expected results.  Please, fix handling of the `name` parameter appropriately.

**Comment by npostavs** [comment]
I think this should be covered by #225, looks like we all forgot about it.

**Comment by Alexander-Shukaev** [comment]
Good job! :+1:
