### ISSUE TITLE
No way to handle errors from somehow defered packages

### ISSUE THREAD

**Issue by edvorg** [jwiegley/use-package#246]
Maybe provide on? For example throw en error to some handler.

**Comment by jwiegley** [comment]
@edvorg What is this issue requesting?  I don't understand at all.

**Comment by edvorg** [comment]
What happens if :config block generates error when package is deferred (by
keybinding, autoloader, delay, etc)? The issue is that last time I checked
there are were not way to handle this error - provide a handler to be
invoked when error happens.

**Comment by jwiegley** [comment]
The error is reported to the `*Messages*` before.

**Comment by edvorg** [comment]
But it's not handling, it's logging :)
