### ISSUE TITLE
Fail on install

### ISSUE THREAD

**Issue by jtgd** [jwiegley/use-package#248]
I get the error 
> "Compiling file /home/jay/.emacs.d/elpa/use-package-20150817.2257/use-package.el at Sun Aug 30 13:31:57 2015
> use-package.el:690:1:Error: Wrong type argument: integer-or-marker-p, key"

upon installing from melpa. Is there some prerequisite state I need to be in to simply install use-package?

**Comment by jwiegley** [comment]
None that I know of.  Without further info, I have no idea what is going wrong.
