### ISSUE TITLE
Perhaps tag a release?

### ISSUE THREAD

**Issue by mdorman** [jwiegley/use-package#249]
I realize there's a backlog of issues, which might be a disincentive to doing this, but the fact is, it's been a long time since a release was marked at all stable---it would be nice if people could take advantage of the new facilities without having to track melpa...

**Comment by lvillani** [comment]
:+1: 

I second this, tagging a new release would help those of us who prefer to use melpa-stable and would like to take advantage of new features.

**Comment by jwiegley** [comment]
I've tagged 2.1.

**Comment by lvillani** [comment]
I am not sure why but Melpa Stable still seems to pick the `20140601` tag. It could be because it is a version number with a single component that is higher than any other version (i.e.: I believe that it is trying to compare 20140601 with the first component of version "2.1" and "1.9" that is, 2 and 1 respectively).

**Comment by lvillani** [comment]
May I suggest to delete/rename the 20140601 tag? Otherwise I can escalate the issue with Melpa developers.

**Comment by vyp** [comment]
``` elisp
(version<= "20140601" "2.1") ;; => nil
```

@lvillani So I think you are correct.

**Comment by jwiegley** [comment]
I think this is not an assumption that should be made in MELPA.

**Comment by thomasf** [comment]
In that case I would argue that it shouldt fetch a tag that's not prefixed with a "v" either..  I mean, 20140601 is a numerically higher version than 2.1.

**Comment by lvillani** [comment]
As I understand it, Melpa Stable considers tags with and without the "v" prefix equally.

**Comment by purcell** [comment]
Yes, we use the latest numeric version tag, with or without a v prefix. It's hard to argue that's unreasonable in the general case, and adding special handling for versions which look like a date would probably just break other recipes, so I'm hesitant to introduce a workaround for this isolated case. Deleting the tag would be my preferred resolution here, unless there's an alternative I'm overlooking.

**Comment by jwiegley** [comment]
@purcell The date tag should now be deleted.

**Comment by thomasf** [comment]
@purcell I guess that if anything would happen in melpa, recipes could be extended have a version tag  regexp. I'm guessing that this isn't a common problem so it's maybe not that important after all.

**Comment by mdorman** [comment]
@purcell The tag is now gone, but melpa-stable is still showing the 2014-ish thing as the current version---does it perhaps need a kick in the pants?

**Comment by mdorman** [comment]
@purcell I'm *guessing* you did something, because `use-package` is now showing version 2.1 on `melpa-stable`.  Unfortunately, `bind-key` is not.

**Comment by purcell** [comment]
Yep, I gave it a kick, and now I've done the same for `bind-key`, but it might take an hour or two to rebuild, sorry.
