### ISSUE TITLE
(pre|post)-(init|config) hooks aren't run if the relevant block isn't present

### ISSUE THREAD

**Issue by TheBB** [jwiegley/use-package#250]
E.g.

``` lisp
(add-hook 'use-package--derp--pre-init-hook
          (lambda () (message "hi")))
(use-package derp)
```

The message is never printed. (Let us assume the presence of a `derp` package.)

This might be the indended behaviour but I found it quite unexpected. Intuitively, an empty `:init` or `:config` block is more like a no-op.

**Comment by jwiegley** [comment]
Do you have `use-package-inject-hooks` set to `t`?

**Comment by TheBB** [comment]
I do. [Here's](https://gist.github.com/TheBB/93a68137ff240cd4e23a) a gist showing the output of `macroexpand` with and without an `:init` block.

**Comment by darkfeline** [comment]
I'm interested in fixing this, and I'd like some advice.

I'm thinking of adding more clauses here https://github.com/jwiegley/use-package/blob/master/use-package.el#L1102

in the vein:

~~~ emacs-lisp
(args* (use-package-sort-keywords
        (use-package-plist-maybe-put
         args* :init)))
~~~

I'm fairly certain this would work, but I'm not sure if this is the best way to
fix it or not.
