### ISSUE TITLE
Is it possible store package names which are not available with a variable?

### ISSUE THREAD

**Issue by tumashu** [jwiegley/use-package#251]
When a package is not available, use-package will show a message, I want to store them to a variable, is it possible?

**Comment by jwiegley** [comment]
Good question; at the moment, probably not, I'd have to put in some kind of hook for you to use to collect that data.

**Comment by jwiegley** [comment]
This would only apply in certain circumstances, and so would be rather tricky to handle in a truly reliable way.  Thus, I am closing as "will not implement".
