### ISSUE TITLE
Question about `:commands`

### ISSUE THREAD

**Issue by noctuid** [jwiegley/use-package#254]
If the package I'm setting up with `use-package` has autoload cookies for all the commands I need and is installed with package.el (autoloads generated), is there any difference between using `:commands (command command2 ....)` and just `:defer t`? Is the primary use case for `:commands` for packages that don't have any autoload cookies (or are not installed with package.el)?

**Comment by jwiegley** [comment]
Correct, `:commands` creates autoloads, which is pretty much all that it does.

**Comment by noctuid** [comment]
Okay, thank you.
