### ISSUE TITLE
How to ensure a package without requiring it

### ISSUE THREAD

**Issue by whatyouhide** [jwiegley/use-package#257]
I use `use-package` with `:ensure t` a lot so that I can keep my installed packages up to date between computers and new installations. In my `init.el`, I have a bunch of themes installed:

```elisp
(use-package aurora-theme :ensure t)
(use-package color-theme-sanityinc-tomorrow :ensure t)
(use-package gruvbox-theme :ensure t)
(use-package material-theme :ensure t)
(use-package molokai-theme :ensure t)
(use-package monokai-theme :ensure t)
(use-package zenburn-theme :ensure t)
```

This loads each theme (resulting in a terrible color-flashing when Emacs is starting up, because it loads all the themes one after the other). I can't seem to say to `use-package` "don't load this theme, just ensure it's installed, I'll use `load-them` later manually).

Is there an easy way to do this? I tried `:no-require t` but it has no effects. Sorry, I'm no Emacs/elisp expert so this question might turn out to be ridicolous :\

**Comment by thomasf** [comment]
```
(use-package aurora-theme :ensure t :defer t)
```

**Comment by whatyouhide** [comment]
I knew this had to be trivial :) Thanks a lot for the help, @thomasf!
