### ISSUE TITLE
Entering "(use-package kill" causes Emacs frozen

### ISSUE THREAD

**Issue by goofansu** [jwiegley/use-package#260]
Emacs version: `GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2015-04-11 on builder10-9.porkrind.org`

Problem:

I entered `(use-package kill` by accident, but I found every time I enter this sentence, Emacs calls melpa first and then frozen.

My config to reproduce this problem:

```
(require 'package)
(setq package-enable-at-startup nil)
(add-to-list 'package-archives
             '("melpa" . "http://melpa.org/packages/"))

(package-initialize)

;; Bootstrap `use-package'
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(eval-when-compile
  (require 'use-package))
(require 'diminish)                ;; if you use :diminish
(require 'bind-key)                ;; if you use any :bind variant

(setq use-package-always-ensure t)

(use-package swiper
  :bind (("C-s" . swiper)
	 ("C-r" . swiper)
	 ("s-z" . ivy-resume))
  :init
  (setq ivy-use-virtual-buffers t)
  (setq ivy-re-builders-alist
	'((t . ivy--regex-fuzzy)))
  :config (ivy-mode 1))

(use-package counsel
  :bind (("s-g" . counsel-git-grep)
	 ("s-x" . counsel-M-x)
	 ("s-y" . counsel-yank-pop)))

(use-package projectile
  :diminish projectile-mode
  :bind (("s-p" . projectile-switch-project)
	 ("s-f" . projectile-find-file)
	 ("s-d" . projectile-find-dir)
	 ("s-c" . projectile-compile-project)
	 ("s-t" . projectile-test-project))
  :init (setq projectile-completion-system 'ivy)
  :config (projectile-global-mode))

(use-package company
  :diminish company-mode
  :init
  (setq company-idle-delay 0.5)
  (setq company-tooltip-limit 10)
  (setq company-minimum-prefix-length 2)
  (setq company-tooltip-flip-when-above t)
  :config (global-company-mode))

''' just enter "(use-package kill" here
```

**Comment by thomasf** [comment]
I don't think this is an issue with use-package.

**Comment by goofansu** [comment]
@thomasf Only when entering `use-package` with words like `kill` or `recentf` will cause this problem.

**Comment by npostavs** [comment]
@goofansu: are you saying you put `(use-package kill` without a close paren, and you didn't get a parse error?

**Comment by goofansu** [comment]
@npostavs I mean the process of entering `(use-package kill`. After finish entering `ki`, Emacs is frozen.

Before frozen, there is `Contacting host: melpa.org:80` in the mini buffer.

I think there should not be the "Contacting" when I'm entering in my `init.el`.

**Comment by goofansu** [comment]
I got it. It's a feature. Sorry

**Comment by dgutov** [comment]
@jwiegley This seems to be about code completion, more context here: https://github.com/company-mode/company-mode/issues/387#issuecomment-151463134

**Comment by kovrik** [comment]
This happens if you are using `company-mode` + `use-package` + `(setq use-package-always-ensure t)`.

**Comment by jwiegley** [comment]
@dgutov Hi, I don't use `ensure` at all, so I'm not  sure how I would debug this.

**Comment by dgutov** [comment]
@jwiegley Can't you just `(setq use-package-always-ensure t)`?

Then type `(use-package ` and press `C-M-i`. IIUC the issue right (I don't have `use-package` installed), that will trigger the downloading.

If you use company-mode, you can type one more letter and simply wait, instead of pressing `C-M-i`.

**Comment by kovrik** [comment]
@dgutov  @jwiegley 
Yes, just tested with **disabled** `company-mode`.

`C-M-i` on `(use-package 123|` triggers contacting repos and fetching data.

**Comment by jwiegley** [comment]
I don't use `package.el`, and I don't use `company` in elisp, so I'm not the best person to track this down.  I'd actually rather than all the package-related details move out of core `use-package.el`, so they can be maintained by someone who uses those features.

**Comment by kovrik** [comment]
@jwiegley 
You don't need `company-mode` to reproduce this issue.

Emacs with `use-package` installed is enough.
Just type `(use-package 123` and press `C-M-i`.

**Comment by thomasf** [comment]
I guess that the target would be to prohibit `lisp-completion-at-point` to expand the use-package macro which it seems like it does.

**Comment by dgutov** [comment]
> I guess that the target would be to prohibit lisp-completion-at-point to expand the use-package macro which it seems like it does.

I suppose implementing blacklisting is doable, if fixing this problem properly turns out to be too hard.

**Comment by kovrik** [comment]
Created a pull request to fix this issue (see above).
