### ISSUE TITLE
Request for :bind like keyword to also specify the keymap

### ISSUE THREAD

**Issue by kaushalmodi** [jwiegley/use-package#263]
I like to bind keys in my minor mode map.

So I have constructs like below for almost all the packages:

```el
(use-package foo
  :commands (foo1 foo2)
  :init
  (progn
    (bind-key "C-c f" #'foo1 my-mode-map)
    (bind-key "C-c g" #'foo2 my-mode-map)))
```

I'd like to use the `:bind` key but it does not accept the keymap argument. *Correct?* 

It would be cool to have something like below:

```el
(use-package foo
  :bind2 (my-mode-map . (("C-c f" . foo1)
                         ("C-c g" . foo2))))
```

- It makes the custom keymap bindings more concise 
- Also autoloads `foo1` and `foo2` (in the example above)

**Comment by thomasf** [comment]
search the issues before opening new ones, there are probably a bunch of bind + keymap related ones open right now.,

**Comment by kaushalmodi** [comment]
My apologies.

**Comment by kaushalmodi** [comment]
Related: https://github.com/jwiegley/use-package/issues/237
