### ISSUE TITLE
(use-package epa-file) fails.

### ISSUE THREAD

**Issue by introom** [jwiegley/use-package#264]
I am on the latest emacs, so epa-file is bundled. It is accessible by (require 'epa-file) directly.

However, when using (use-package epa-file), use-package will try to fetch it on melpa, which will finally fail.

**Comment by vyp** [comment]
Cannot reproduce. Are you sure you're not using `:ensure`? Because `(use-package epa-file)` should just work without needing `:ensure` if you always use an emacs that comes with `epa-file.el`. Or perhaps you have `use-package-always-ensure` set to `t`?

**Comment by introom** [comment]
Yes. I globally set the use-package-always-ensure.
