### ISSUE TITLE
How to evalute some code right before the package is loaded?

### ISSUE THREAD

**Issue by introom** [jwiegley/use-package#265]
:init evalutes the code when emacs starts.

:config evalutes the code when the package **has been** loaded.

Is there any way to evalute some code that right **before** a packge is loaded?

**Comment by Silex** [comment]
Just curious, do you have an example where that behavior is desired (right before the package is loaded)? I can't think of an example.

**Comment by introom** [comment]
For example,

Here https://github.com/cofi/evil-leader#usage <https://github.com/cofi/evil-leader#usage>  , 

Note: You should enable global-evil-leader-mode before you enable evil-mode, otherwise evil-leader won’t be enabled in initial buffers (*scratch*, *Messages*, …).


When I want to load “evil”, I’d like to load “evil-leader” before it.

(However, I don’t want to load “evil-leader” if “evil” is not loaded at all.)

As of writing now,  I am thinking of one work around maybe like:


(use-package evil
  :config
  (progn
     (use-package evil-leader)
     (global-evil-leader-mode)
     (evil-mode 1))

But it crammed two packages into one big clause, which is a little bit ugly.


Regards.

**Comment by xuchunyang** [comment]
> Note: You should enable global-evil-leader-mode before you enable evil-mode, otherwise evil-leader won’t be enabled in initial buffers (*scratch*, *Messages*, …).

then you should just use (assuming you have installed these two packages correctly):

```elisp
(global-evil-leader-mode)
(evil-mode)
```

or with use-package:

```elisp
(use-package evil
  :config
  (use-package evil-leader
    :config (global-evil-leader-mode))
  (evil-mode))
```

or better ask the evil-leader maintainer to make `global-evil-leader-mode` works correctly even when `evil-mode` is already enabled if possible (I'm not sure since I don't use evil or evil-leader)

---

BTW, if you still want do that, as far as I know, there is no Emacs built-in solution, maybe you can try to advice `require`.

**Comment by justmytwospence** [comment]
Another way using the `:after` key that doesn't require nesting:

```
(use-package evil
  :after evil-leader
  :config
  (evil-mode)

(use-package evil-leader
  :config
  (global-evil-leader-mode)
```

**Comment by jwiegley** [comment]
@justmytwospence Don't you mean to specify that `:after` keyword in `evil-leader`?
