### ISSUE TITLE
Defer load until specific mode is enabled

### ISSUE THREAD

**Issue by zakkak** [jwiegley/use-package#268]
Hello,

Is there any way I can defer loading of a package until a specific mode is enabled?

When combining hooks with :commands emacs ends up always loading the package

e.g.

```
(use-package flycheck
  :commands flycheck-mode
  :config
  (setq flycheck-check-syntax-automatically '(save))
  )
(add-hook 'prog-mode-hook 'flycheck-mode)
```

Thanks

**Comment by jwiegley** [comment]
What you've show me should do just what you've asked for.  I find it odd that flycheck is being loaded immediately?

**Comment by YoungFrog** [comment]
I guess emacs will fire prog-mode-hook when setting *scratch* to lisp-interaction-mode.

**Comment by thomasf** [comment]
Yeah, lisp-interaction-mode causes a lot of early loading, even more so if your not gonna edit elisp..
I have added a small initial mode which switches into lisp-interaction-mode using C-c C-c or C-C c.

```
(defvar initial-mode-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "C-c c") 'lisp-interaction-mode)
    (define-key map (kbd "C-c C-c") 'lisp-interaction-mode)
    map)
  "Keymap for `initial-mode'.")

(define-derived-mode initial-mode nil "Initial"
  "Major mode for start up buffer.
\\{initial-mode-map}"

  (setq-local text-mode-variant t)
  (setq-local indent-line-function 'indent-relative))

(setq  initial-major-mode 'initial-mode )
```

**Comment by zakkak** [comment]
@YoungFrog is right. It did not cross my mind, thanks. 

Nice hack @thomasf thanks for sharing.
