### ISSUE TITLE
:bind on mode maps ought to be lazy

### ISSUE THREAD

**Issue by IvanMalison** [jwiegley/use-package#269]
Normal bind depends on autoload definitions to allow lazy loading of commands that are bound to specific keys. This doesnt work for binding keys in maps that don't exist until the required package is actually loaded. This is because the mode map may not even exist when the form generated by use-package is evaluated.

Perhaps support for binding keys to mode-maps for modes that are lazily loaded is beyond the scope of the :bind keyword, but it seems pretty reasonable to me to want to do something like this:

```
(use-package smartparens
  :bind (:map smartparens-mode-map
              ("C-{" . sp-backward-barf-sexp)
              ("C-)" . sp-forward-slurp-sexp)
              ("C-}" . sp-forward-barf-sexp)
              ("C-(" . sp-backward-slurp-sexp)
               (:unbind  "C-<backspace>"  "M-<backspace>")))
```
and
This does not work because, as mentioned above, smart-parens-mode-map is not defined when the bind-key is attempted. This does bring up the issue of "how should the evaluation of the binding be triggered?". In this case we want this code to execute once smartparens-mode is activated, and there happens to be a hook for exactly this purpose. Perhaps there could be an additional keyword that could be used to specify the hook list that should be used to trigger these definitions?

```
(use-package smartparens
  :bind (:map smartparens-mode-map :hook smartparens-mode-hook
              ("C-{" . sp-backward-barf-sexp)
              ("C-)" . sp-forward-slurp-sexp)
              ("C-}" . sp-forward-barf-sexp)
              ("C-(" . sp-backward-slurp-sexp)
               (:unbind  "C-<backspace>"  "M-<backspace>")))

```

This issue is closely related to #237 and #232 and #121 but not quite the same.

**Comment by jwiegley** [comment]
Note that this sort of binding is what `:bind-keymap` was made for.  At the moment, this is not the same thing as `:bind` using a `:map`, although it should be.

**Comment by jasonm23** [comment]
@waymondo this is actually why I ended up trying to make `:bind-keymap` work.  I think maybe your usage is not correct?

**Comment by IvanMalison** [comment]
@jwiegley didn't know about bind-keymap. I'll take a look. Is bind-keymap documented anywhere?

The only mention that I can find in the README is 
```
If you aren't using :commands, :bind, :bind*, :bind-keymap, :bind-keymap*, :mode, or
```

I guess I can read the code, but it might be good to add something to the readme.

**Comment by waymondo** [comment]
@jasonm23 hmm, yes, maybe i was under the wrong assumption after reading this again.

**Comment by jwiegley** [comment]
`:bind` on `:map` keywords is now lazy.
