### ISSUE TITLE
Add a default setting for :ensure

### ISSUE THREAD

**Issue by alanpearce** [jwiegley/use-package#27]
I think that it would be nice to allow the possibility to `:ensure` all packages by default.

I started to look at adding this via a customize variable, with a way to stop a particular package from being “ensured” when the customize variable is set to `t`.

The first thought I had would be to use `:ensure nil` for the override. However, I found that `plist-get` returns `nil` when the argument is unspecified, so all packages would override a default of `t`.

So I thought I'd come back here and ask about it. Is it a good idea? What kind of argument should override the default when it's `t` to say ‘no, don't ensure this is installed’?

**Comment by jwiegley** [comment]
I will add a default setting for this.
