### ISSUE TITLE
eval-after-load

### ISSUE THREAD

**Issue by phillord** [jwiegley/use-package#274]
I can't see any good way of doing the equivalent of "eval-after-load". I am thinking, for instance, of adding a org-mode exporter, which can't be autoload but needs to be installed as soon as org-mode has loaded.

**Comment by YoungFrog** [comment]
That's what :config is for, isn't it ?

**Comment by jwiegley** [comment]
`:config` paired with one of the directives that delays loading, such as `:bind`, `:commands`, `:mode`, or just `:defer`.

**Comment by phillord** [comment]
How would that work. I mean, I can see:

    (use-package org
      :config (use-package ox-blah))

But this seems pretty ugly. I was thinking more along the lines
of:

    (use-package ox-blah
      :after org)

which would be the equivalent of

    (eval-after-load
        "org.el"
      (use-package ox-blah))

**Comment by jwiegley** [comment]
Your first example is what I use.

**Comment by phillord** [comment]
Okay, no worries, I will stick with that, although I worry that it's rather overloading the org use-package statement, especially if I have four or five backends to install.

Currently, though, I don't have four or five backs to install, so I'll worry about that when I do. Thanks for the feedback.

**Comment by jwiegley** [comment]
I just checked my `init.el` file, and it's actually a pretty common idiom there.  I even found this:

``` elisp
(use-package eclimd
  :load-path "site-lisp/emacs-eclim"
  :commands start-eclimd
  :config
  (use-package eclim
    :defer t
    :config
    (global-eclim-mode)
    (use-package company-emacs-eclim
      :requires company
      :config
      (company-emacs-eclim-setup))))
```

**Comment by YoungFrog** [comment]
I guess you know about the variable `org-export-backends', but I
mention it here for the record.

**Comment by phillord** [comment]
@YoungFrog I didn't as it happens, but in this case, it doesn't work in my use case. I need to set the load-path, hence the use of use-package.

**Comment by phillord** [comment]
@jwiegley To be honest, this makes me feel that you are providing me the evidence that there is a problem:-) Having lots of nested use-packages just seems scary to me. I guess this is what "req-package" is designed to cope with.

Would you be interested in a patch for :after? It would work like ":defer 10" but instead of expanding to a timer call, you'd get an eval-after-load/require form. (Not that I will get around to it any time soon!)

**Comment by zakkak** [comment]
@phillord It sounds like a nice extension/feature. 

It would allow for cleaner and better organized configuration files.

**Comment by jwiegley** [comment]
@phillord `:after` does sound useful, for the simple use cases.  It should even be able to take a list, since nested `eval-after-load` forms should "do the right thing".  I even remember the author `req-package` author and I discussing exactly this... So yes, I'd like it!

**Comment by phillord** [comment]
Ok. In which case, I will reopen the issue, until I have a PR for it!

**Comment by jwiegley** [comment]
@phillord Thank you!

**Comment by tumashu** [comment]
```
(use-package xxx4
  :after (xxx3 xxx2 xxx1))
```

Is this feature works?

**Comment by phillord** [comment]
It does when I use it. Does it not for you?

**Comment by vyp** [comment]
@phillord also see the new issue @tumashu created: #283

**Comment by phillord** [comment]
@vyp @tumashu 

So, this:

    (use-package xxx4
      :after (xxx3 xxx2 xxx1))

expands to this:

    (progn
      (eval-after-load 'xxx3
        '(require 'xxx4))
      (eval-after-load 'xxx2
        '(require 'xxx4))
      (eval-after-load 'xxx1
        '(require 'xxx4)))


Which is an "or" or "any" semantics indeed. And "and" or "all" semantics
would need something like (untested):

    (eval-after-load 'xxx3
      '(eval-after-load 'xxx2
         '(eval-after-load 'xxx1
            '(require 'xxx4))))


I did not have a strong use case in mind when I wrote this (I only cared about the single :after use case).
I picked the former because it made more sense to me -- "load company mode after java, or
lisp or lua mode". If you have a strong use case where "and" semantics is
needed, then it's changable.

**Comment by tumashu** [comment]
@phillord 

```
(eval-after-load 'xxx3
  '(eval-after-load 'xxx2
     '(eval-after-load 'xxx1
        '(require 'xxx4))))
```
I think this is very useful too,  maybe :require is more meanful name than :after,
it can make config flatten:

```
(use-package xxx1
  :config
  (setq xxx1 nil)
  (use-package xxx2
    :config
    (setq xxx2 nil)
    (use-package xxx3
      :config
      (setq xxx3 nil)
      (use-package xxx4
        :config
        (setq xxx4 nil)))))
```
with :after
```
(use-package xxx1
  :config
  (setq xxx1 nil))

(use-package xxx2
  :after (xxx1)
  :config
  (setq xxx2 nil))

(use-package xxx3
  :after (xxx2 xxx1)
  :config
  (setq xxx3 nil))

(use-package xxx4
  :after (xxx3 xxx2 xxx1)
  :config
  (setq xxx4 nil))
```
I think the latter is more beautiful and portable.

**Comment by phillord** [comment]
Yes, well, that was my use case! ":after" comes from "eval-after-load".  I didn't like require because it justs the other way around -- loading xxx2 will force loading of xxx1.
