### ISSUE TITLE
User must call package-initialize before (require 'use-package)

### ISSUE THREAD

**Issue by ahyatt** [jwiegley/use-package#275]
This isn't clear from the docs.

If the user fails to do this, they will not, for example, be able to use the latest version of seq on emacs 25.  use-package will just grab the seq found in the emacs 25 lisp dir, and the load-path is only changed afterwards - so you won't be able to get new version of seq loaded.  What needs to happen is that (package-initialize) must be called first to alter the load-path, then (require 'use-package) can get the correct version of the libraries it needs.

**Comment by thomasf** [comment]
This is of course only relevant for people using `package.el` which use-package isn't limited to.

**Comment by unhammer** [comment]
I've seen this given as a solution:

    (require 'package)
    (setq package-enable-at-startup nil)
    (package-initialize)
    (require 'use-package)

**Comment by npostavs** [comment]
Note that Emacs 25 will automagically insert `(package-initialize)` at the top your init.el, if it's not already present.

**Comment by yisraeldov** [comment]
Is this still required? I feel like package-initialize slows down emacs and I don't get the benefit of "deferred"  loading.

**Comment by jwiegley** [comment]
I personally don't use `package-initialize`.

**Comment by yisraeldov** [comment]
I see, but you also don't use ensure.

How are you installing packages then ? By hand ?
