### ISSUE TITLE
completion-at-point for use-package

### ISSUE THREAD

**Issue by zakkak** [jwiegley/use-package#277]
Hello,

I am trying to develop a completion-at-point function for `use-package`.

My question is not related to `use-package` but I thought someone will know.

Following the example from http://ergoemacs.org/emacs/elisp_keyword_completion.html I got the following function which works fine, but I would like to make it suggest the completions only when the previous symbol is `use-package`.  Any help would be much appreciated.

``` elisp
(defun xyz-complete-package ()
  "Perform keyword completion on word before cursor."
  (interactive)
  (let ((posEnd (point))
        (meat (thing-at-point 'symbol))
        (complition-list (mapcar #'car package-archive-contents))
        maxMatchResult)

    ;; when nil, set it to empty string, so user can see all lang's keywords.
    ;; if not done, try-completion on nil result lisp error.
    (when (not meat) (setq meat ""))
    (setq maxMatchResult (try-completion meat complition-list))

    (cond ((eq maxMatchResult t))
          ((null maxMatchResult)
           (message "Can't find completion for “%s”" meat)
           (ding))
          ((not (string= meat maxMatchResult))
           (delete-region (- posEnd (length meat)) posEnd)
           (insert maxMatchResult))
          (t (message "Making completion list…")
             (with-output-to-temp-buffer "*Completions*"
               (display-completion-list
                (all-completions meat complition-list)
                meat))
             (message "Making completion list…%s" "done")))))
```

**Comment by jwiegley** [comment]
@zakkak Oh, `pcomplete` will make this a thousand times easier for you to do, not to mention giving you a bunch of cool features besides (cycling completion, structured sub-completion, etc).  I would recommend checking there before going much further down the road of using `try-completion' directly.

**Comment by zakkak** [comment]
Thanks @jwiegley, indeed it looks much better than `try-completion`, but the only simple examples I find are about completing commands in eshell.

I find `org-pcomplete.el` from `org-mode` very educative, but a bit advanced to start from.  Is there any simpler examples you are aware of that you could point me to?

**Comment by manuel-uberti** [comment]
[pcomplete-extension](https://github.com/thierryvolpiatto/pcomplete-extension) has some nice features you might have a look at.

**Comment by jwiegley** [comment]
@manuel-uberti Nice!
