### ISSUE TITLE
Symbol's value as variable is void: auctex

### ISSUE THREAD

**Issue by hyunkyu87** [jwiegley/use-package#279]
I'm a newbie in emacs and auctex.
I'm using Emacs 23.4 (9.0) in Mac OS X 10.7.5

I was trying to follow the answer in 
http://tex.stackexchange.com/questions/239544/adding-keybord-shortcut-for-auctex-in-emacs

I don't know how to do things in a right way or in an efficient way, so in my .emacs file I added

(load-file "~/.emacs.d/site-lisp/macroexp.el")
(load-file "~/.emacs.d/site-lisp/cl-lib.el")
(load-file "~/.emacs.d/site-lisp/bind-key.el")
(load-file "~/.emacs.d/site-lisp/use-package.el")

after downloading those files and copying to my directory site-lisp
then as a test, I added

(use-package latex
  :ensure auctex
  :config
  (add-to-list 'LaTeX-font-list
               '(?\C-p "\\pname{" "}")))

Then when I run emacs, it says

Symbol's value as variable is void: auctex

Note that the above lines that I added to my .emacs are added after

(load "auctex.el" nil t t)

Can anyone tell me what the problem is?

**Comment by vyp** [comment]
I think you may need to enable melpa first: https://github.com/milkypostman/melpa#usage

Or you could just download the auctex elisp files and load them too. The :ensure keyword causes the package(s) to be installed automatically if not already present on your system: https://github.com/jwiegley/use-package#for-packageel-users

**Comment by vyp** [comment]
Although auctex is already in elpa, so I'm not sure what's going on. (Unless you haven't set `package-archives` completely.)

**Comment by npostavs** [comment]
I *think* it might be a bug introduced in #273; `ensure` should be quoted, as in:

```diff
diff --git i/use-package.el w/use-package.el
index afb306f..6027c9f 100644
--- i/use-package.el
+++ w/use-package.el
@@ -464,7 +464,7 @@ (defun use-package-ensure-elpa (package &optional no-refresh)
 
 (defun use-package-handler/:ensure (name keyword ensure rest state)
   (let ((body (use-package-process-keywords name rest state)))
-    `((let ((package-name (or (and (eq ,ensure t) (use-package-as-symbol ',name)) ,ensure)))
+    `((let ((package-name (or (and (eq ',ensure t) (use-package-as-symbol ',name)) ',ensure)))
           (when package-name
             (require 'package)
             (use-package-ensure-elpa package-name)))
```

/cc @kovrik

**Comment by kovrik** [comment]
@npostavs 
That's correct.

Sorry, my fault.

**Comment by kovrik** [comment]
@jwiegley 
Could you please merge @npostavs changes?

**Comment by npostavs** [comment]
> Sorry, my fault.

Or we can blame it on `$NUMBER` of people using `:ensure` who didn't test *before* it was merged ;)

**Comment by hyunkyu87** [comment]
Thanks everyone. I managed to solve the issue by following your instructions.
