### ISSUE TITLE
Getting assignment forms before submission into Emacs

### ISSUE THREAD

**Issue by jwiegley** [jwiegley/use-package#282]
- [x] ~@BernardHurley~
- [x] @DamienCassou (Damien Cassou)
- [x] @Fuco1 (Matus Goljer)
- [x] ~@MaikuMori (Miks Kalnins)~
- [x] @PhilHudson (Phil Hudson)
- [x] @Silex (Philippe Vaucher)
- [x] @YoungFrog (Nicolas Richard)
- [x] @aethanyc (Ting-Yu Lin)
- [x] @alezost (Alex Kost)
- [ ] @andschwa (Andy Schwartzmeyer)
- [x] @aspiers (Adam Spiers)
- [x] @basil-conto (Basil L. Contovounesios)
- [x] ~@bdd (Berk D. Demir)~
- [x] @canatella (Damien Merenne)
- [x] ~@carldotac (Carl Lieberman)~
- [x] ~@cmpitg (Ha-Duong Nguyen)~
- [x] @dabrahams (Dave Abrahams)
- [x] @dudebout (Nicolas Dudebout)
- [x] ~@edvorg (Eduard Knyshov)~
- [x] @ffevotte (François Févotte)
- [x] ~@hartzell (George Hartzell)~
- [x] @jabranham (Alex Branham)
- [x] @joewreschnig (Joe Wreschnig)
- [x] @justbur (Justin Burkett)
- [x] @kaushalmodi (Kaushal Modi)
- [x] @killdash9 (Russell Black)
- [x] @kovrik
- [x] ~@marcwebbie (Marc Webbie)~
- [x] ~@matklad (Aleksey Kladov)~
- [x] ~@mcandre (Andrew Pennebaker)~
- [x] ~@milkypostman (Donald Curtis)~
- [x] @nickmccurdy (Nick McCurdy)
- [x] @npostavs (Noam Postavsky)
- [x] @peterhoeg (Peter Hoeg)
- [x] @phillord (Phil Lord)
- [x] @phst (Philipp Stephani)
- [x] @purcell (Steve Purcell)
- [x] @raxod502 (Radon Rosborough)
- [x] ~@rememberYou (Terencio Agozzino)~
- [x] ~@syl20bnr (Sylvain Benner)~
- [x] @tarsius (Jonas Bernoulli)
- [x] ~@thiagowfx (Thiago Perrotta)~
- [x] @thomasf (Thomas Frössman)
- [x] @vermiculus (Sean Allred)
- [x] ~@vyp~
- [x] @waymondo (Justin Talbott)

To everyone who has contributed code to use-package: I would like to include use package in the next version of Emacs, but to do so, I need copyright assignment forms to be signed by anyone who has added code to use-package. If you do not wish to sign such a copyright assignment form, let me know so that I can find a way to back out any changes you may have made.

It's quite possible that due to recent code rewrites, your change may not appear anymore. If that is the case, I only ask that you verify this, so I can take you off of the list of people I need assignment forms from.

Thank you!

John

**Comment by MaikuMori** [comment]
I have only contributed to the `README.md` so far, but I have no objection to signing the copyright form especially if it works for any kind of contributions to Emacs, not just this package.

**Comment by npostavs** [comment]
I have already signed papers for Emacs contributions.

**Comment by thomasf** [comment]
I've been meaning to do this for a while so this is a good push! Last time I got lost trying to figure out exactly how I should start the process.. 
Just to make it clear here, should we as, as future contributors start this process by sending e-mail to assign@gnu.org ?

**Comment by ffevotte** [comment]
Hi, I've already signed the FSF copyright assignment form. Should I send you something so that you can verify? (I should be able to retrieve the scanned form from my mail archive...)

**Comment by waymondo** [comment]
I have not signed anything but would be very happy to.

**Comment by Silex** [comment]
I'm okay too, what do we need to do?

**Comment by tarsius** [comment]
I have already signed papers for Emacs contributions, and have no objections to `use-package` becoming part of Emacs (and my copyright assignment therefore covering that library too).

**Comment by phillord** [comment]
@thomasf You need to send some information to assign@gnu.org. I will email you (and anyone else) the form. The FSF then send you the real forms (the process and forms, unfortunately, depend on your country of residence).

@jwiegley The FSF have my forms!

**Comment by jwiegley** [comment]
@MaikuMori Yes, you can sign a more general form with the FSF that covers anything you might contribute to Emacs. You'll have to get it approved by your place of work, so that the FSF is certain it is valid for you to sign the form. Send any questions you might have to assign@gnu.org.

Sorry if it should have been obvious to me that some of you already have formed signed, I just sent this to all past contributors in order to be sure to not miss anyone!

**Comment by thiagowfx** [comment]
Could you please list the steps needed to be done? I am happy to sign the form, but I don't have time to search for stuff and run after it myself, at least not for now, so i detailed and self-contained instructions are provided, you can count on me.

**Comment by jwiegley** [comment]
@thiagowfx Just send an e-mail to assign@gnu.org.  Tell them either that you'd like to sign a copyright assignment for contributions to `use-package.el` to be included in future versions of Emacs; or say that you'd like to sign a general assignment form for any future contributions to Emacs. They will send you the PDF that you need to sign and return to them.

**Comment by thomasf** [comment]
@phillord  Thanks.  I understand why the process is somewhat manual,  I don't think the way that  copyright assignment  generally is described on the FSF site (from a US point of view?)  is compatible with Swedish law where you either are required to have an actual contract to establish ownership of code with the exception of public domain which is allowed.

**Comment by thiagowfx** [comment]
@jwiegley Okay, I just e-mailed them. I will unsubscribe from notifications from this issue now.

**Comment by phillord** [comment]
@thomasf The process on the FSF is just to make sure that you get the right forms! I am sure that they will have got Swedish law figured out.

**Comment by jwiegley** [comment]
@thiagowfx Ok, thanks, please let me know when your process is completed. I'm going to be maintaining a checklist, and will reach out again to people if I've not heard back in a few weeks.

**Comment by mcandre** [comment]
+1 applied for copyright consent form. Thanks for pushing for use-package as an Emacs built-in, it's a great addition!

**Comment by vermiculus** [comment]
I do hope that unquoting lambda forms is insignificant enough for the FSF to just be 'anonymous' or something like that. I've had great difficulty in getting the forms signed by my employer in the past, thought maybe they would react differently to something that I spent time on before this job :smile: 

I'll ask.

**Comment by MaikuMori** [comment]
Email sent. I will let you know when the process is done.

**Comment by DamienCassou** [comment]
Already sent mine years ago.

**Comment by syl20bnr** [comment]
> Email sent. I will let you know when the process is done.

Same here.

**Comment by dabrahams** [comment]
Long since done.

**Comment by vyp** [comment]
Sent email.

**Comment by bdd** [comment]
You can remove me from the list.  My pull request was only whitespace fixes.

**Comment by peterhoeg** [comment]
Email sent.

**Comment by matklad** [comment]
My contribution is very minor (a quote added, it is not even shown in blame now), do I still need to sign a form? The signing would require more effort then the contribution did :)

**Comment by YoungFrog** [comment]
I already have an assignment for emacs.

**Comment by edvorg** [comment]
I'be sent an email.

**Comment by purcell** [comment]
> I already have an assignment for emacs.

Me too.

**Comment by Silex** [comment]
@jwiegley: I only have documentation/typo fixes... can I just "give" those change to you? I don't feel like going throught the whole assignment process just for silly changes like this.

**Comment by aspiers** [comment]
I also already have FSF copyright assignment for emacs as per http://orgmode.org/worg/org-contribute.html#contributors_with_fsf_papers.  Congratulations on the appointment BTW!  Looking forward to seeing some great improvements :)

**Comment by PhilHudson** [comment]
On 11 November 2015 at 20:43, John Wiegley <notifications@github.com> wrote:

> I would like to include
> use package in the next version of Emacs, but to do so, I need copyright
> assignment forms to be signed by anyone who has added code to use-package.
>

​I've signed the FSF papers (prompted by BBDB, several years back).

I asked the Emacs.el podcast guy just a couple of days ago to ask you
whether you planned to do this when he interviews you. Guess I know now.
:-)​



-- 
Phil Hudson                   http://hudson-it.ddns.net
@UWascalWabbit                 PGP/GnuPG ID: 0x887DCA63

**Comment by jwiegley** [comment]
@Silex @matklad If the changes are minor enough, such as correcting a typo, no assignment is needed.

**Comment by Silex** [comment]
:+1:

**Comment by vyp** [comment]
@jwiegley I just checked, and it also looks like my changes are minor, just typo fixes: <https://github.com/jwiegley/use-package/commits?author=vyp>. So I think it's okay for no assignment. Otherwise just let me know.

**Comment by waymondo** [comment]
@jwiegley assignment email sent

**Comment by alezost** [comment]
I signed papers for Emacs contributions last year.

**Comment by jwiegley** [comment]
Thank you everyone for being so responsive to this. It will help us get `use-package.el` into the tarball for 25.1.

**Comment by cmpitg** [comment]
@jwiegley Sorry for the late reply. Mine was just a simple one-word typo fix as well[1].

[1] https://github.com/jwiegley/use-package/commits/master/README.md?author=cmpitg

**Comment by aethanyc** [comment]
@jwiegley: I've already signed the assignment for Emacs two years ago. It's great to see use-package to be included in Emacs.

**Comment by thomasf** [comment]
I'll let you know when my assignment form process has finished

**Comment by thiagowfx** [comment]
Hey @jwiegley, I began the assignment but I then realized it was more complicated than it should, at least for me. Anyways, I reviewed my commits and then suddenly realized that the only one was actually a typo: https://github.com/jwiegley/use-package/commit/90644b578f82def2a6053b0233839500307b7007

In this case, I believe the assignment is not really necessary -- if my contributions were more significative, then it would probably be worth the effort of filling the form, but I think not in this case. Agreed?

**Comment by jwiegley** [comment]
@thiagowfx Agreed.

**Comment by mcandre** [comment]
My contribution so far is a minor README tweak. Consider me to have agreed
to all applicable licensing for all GNU projects. Forms suck.

On Thu, Nov 19, 2015 at 10:11 AM, John Wiegley <notifications@github.com>
wrote:

> @thiagowfx <https://github.com/thiagowfx> Agreed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jwiegley/use-package/issues/282#issuecomment-158103280>
> .
>



-- 
Cheers,
Andrew

**Comment by milkypostman** [comment]
I changed a header line. Do I need to do anything further. Sorry for spam to everyone else.

**Comment by jwiegley** [comment]
Documentation changes, typos, and other truly minor edits, do not need a copyright assignment.

**Comment by hartzell** [comment]
[My changes](https://github.com/jwiegley/use-package/commits?author=hartzell) are just minor doc fixes.

**Comment by dudebout** [comment]
I just completed the copyright assignment process.

**Comment by thomasf** [comment]
I havent had time to get somewhere i have pribter access yet so I have not been able to send the form yet..

**Comment by syl20bnr** [comment]
@jwiegley Sorry for the late reply, I still don't have received anything and my contribution to `use-package` is a small fix which can be considered a minor edit.
See commit https://github.com/jwiegley/use-package/commit/d5efa6fcbd0acaf1196cd2f47748b818d3ac7674

**Comment by peterhoeg** [comment]
@jwiegley - fairly slow turnaround from here, but I have (finally) submitted the signed form.

**Comment by jwiegley** [comment]
@peterhoeg Thank you!  I think soon I'll do a review to see if we have everything we need to move to GNU ELPA, and if not, it may mean rewriting some sections.

**Comment by MaikuMori** [comment]
@jwiegley Still haven't received any response, but my contribution was minor (readme) so don't have to wait for me.

**Comment by marcwebbie** [comment]
I don't see any form to sign.

2016-01-25 16:07 GMT-02:00 Miks Kalnins <notifications@github.com>:

**Comment by jwiegley** [comment]
@marcwebbie Send a message to `assign@gnu.org`.

**Comment by edvorg** [comment]
Hi @jwiegley, I found that my change was reverted due to some bugs in
compile time mode, so no need to wait for my submission as well.

**Comment by rski** [comment]
Hi @jwiegley, are you still looking into bringing use-package into Emacs?

**Comment by jwiegley** [comment]
Indeed, my summer just became catastrophically busy. It's in no way less important to me, though.

**Comment by rski** [comment]
@jwiegley is there any way I can help? I could try rounding up the contributors again for copyright assignment.

**Comment by jwiegley** [comment]
@rski Your help is most welcome! Really we just need to make a checklist.  I have the list of assignments here, so even just building the checklist to start would help me, as then my task is limited to merely checking off names.

**Comment by rski** [comment]
great, I had a checklist in mind as well. I'll do it sometime later today.

**Comment by phillord** [comment]
@rski @jwiegley I've been working with assign@gnu.org to make this process a bit easier to manage. This might be a good opportunity to see if it works. Want to email for details?

**Comment by jwiegley** [comment]
Mail sent, but I don't know @rski 's address.

**Comment by jwiegley** [comment]
Ok, this is next on the TODO list. :)

**Comment by thomasf** [comment]
I'm not sure that any of my code still is traceable in use-package but I have finally bought a printer so that I can print and send the assigment form back..

**Comment by hartzell** [comment]
@jwiegley -- my only contribution appears to be [this documentation related buglet fix](https://github.com/jwiegley/use-package/commit/d43af5e0769a92f77e01dea229e376d9006722ef).

Do you need an assignment for that?

**Comment by jwiegley** [comment]
@hartzell No, it won't be needed for that fix, thanks for asking!

**Comment by BernardHurley** [comment]
Sorry for leaving this so long but I have had a numbers of medical problems.  I can’t remember off hand what I contributed but  I will willingly sign a assignment, if needed.  How do I go about it?

**Comment by jwiegley** [comment]
@BernardHurley I'm sorry to hear about your health, Bernard. I hope things have turned to the better in the meantime!

If you send an e-mail to assign@gnu.org and ask them for forms for contributing to GNU Emacs, they will help you through the process.

**Comment by rchar01** [comment]
Hi, what's the current status?
Do you have a current list of authors/commits without signed assignment forms?

**Comment by basil-conto** [comment]
I have already signed papers for Emacs contributions.

**Comment by kaushalmodi** [comment]
My assignment is on file too.

**Comment by killdash9** [comment]
I have also signed papers for Emacs contributions.

**Comment by carldotac** [comment]
My only contributions were fixing typos in documentation.
https://github.com/jwiegley/use-package/commits?author=carldotac
My understanding is you don't need assignment from me, but if it's helpful, I'll fill out the forms.

**Comment by justbur** [comment]
My copyright assignment is on file

**Comment by Silex** [comment]
Is this still active? I said my copyright assignment was done ages ago and I'm still not ticked. I suspect this issue should be closed.

**Comment by rememberYou** [comment]
Sorry for the delay in responding,

I didn't have any notification about this issue. I sent an e-mail to [assign@gnu.org](assign@gnu.org.) according to sign the copyright assignment for `use-package`.

**Comment by canatella** [comment]
I've signed at merge time, so I guess I'm still ok.

**Comment by raxod502** [comment]
I have a copyright assignment on file, although I would like to point out that I am unwilling to assign copyright for any of my work except as I explicitly specify. I am fine assigning copyright for my contributions to `use-package`.

**Comment by joewreschnig** [comment]
My papers are on file.

**Comment by raxod502** [comment]
@jwiegley I went through the thread and updated the checklist in the OP. There are 10 people left who have >15 lines of contributions, but who haven't said here that they signed paperwork. (Does the FSF not maintain a public listing of people on file, or is it not possible to send them a list of people for verification?)

**Comment by jabranham** [comment]
I've signed the FSF copyright forms.

**Comment by nickmccurdy** [comment]
I seem to have more minor changes, mostly documentation/configuration, and the only one directly involving code just adds 3 lines. Would I still need to submit paperwork, and if so, is emailing assign@gnu.org still the easiest way?

**Comment by phst** [comment]
My contributions should be covered by an existing agreement between Google and the FSF.

**Comment by Fuco1** [comment]
Hi, I have signed the emacs contributor agreement on 11 Feb 2015, you can check me completed :)

**Comment by dudebout** [comment]
@raxod502, I went through the list in the summary, and noted a few missing entries:

+ [X] Fuco1 (done on February 11 2015)
+ [ ] andschwa
+ [X] dudebout (done on December 10 2015)
+ [ ] kovrik
+ [X] nickmccurdy (minor changes only)
+ [X] phst (should be covered by Google/FSF agreement)
+ [ ] thomasf (engaged in the thread but no confirmation)
+ [X] vermiculus (minor changes only: unquoting lambda forms)
+ [X] waymondo (done on November 11 2015)

**Comment by andschwa** [comment]
Hi, I have signed copyright assignment forms for my contributions to GNU Emacs already. However, last I heard (~December) they were still reviewing the disclaimer from my company. Just sent an email off to the copyright clerk to see where that landed.

**Comment by jwiegley** [comment]
Looks like we are very close to being able to make a patch submission to Emacs! Just three more contributors to confirm?

**Comment by andschwa** [comment]
Hi all,

The last I heard from the FSF copyright clerk was in July, his response was:

> Thanks for checking in. There is nothing new to report at this time, but you reminder has been sent up the chain. Feel free to ping me as often as you would like, and I will pass those along as well. I do apologize for the time this is taking.

I will ping again, but my copyright assignment paperwork is signed and turned in, this is all in the hands of the clerk (and I guess FSF legal too) right now.

**Comment by progfolio** [comment]
> @phillord Thanks. I understand why the process is somewhat manual, I don't think the way that copyright assignment like it is described on the FSF site (from a US point of view?) is compatible with Swedish law where you either are required to have an actual contract to establish ownership of code with the exception of public domain which is allowed.

@thomasf:

I reached out to the FSF regarding the above comment to see if they could offer some clarification.
Here's the response I got:

> I'm not sure the scenario that was described is accurate for Sweden. However, I am not a lawyer and this is not legal advice, but if it is necessary the FSF can seek out legal counsel to verify (although this will take additional time).
> 
> A couple of factors lead me to believe we can accept copyright assignment from Swedish citizens.
> 
> 1. We have accepted dozens and dozens (if not hundreds) of copyright assignments and disclaimers from Swedish citizens starting as early as 1987.
> 
> 2. Sweden has signed on to the Berne Convention which would make it operate like almost all countries when it comes to copyright. <https://www.wipo.int/treaties/en/notifications/berne/treaty_berne_45.html>
> 
> As I mentioned, I am not a lawyer, but I have access to one if necessary.

**Comment by progfolio** [comment]
I've also reached out to @kovrik on github and reddit to see if they could comment on their intent on whether or not to follow through with the paperwork. Have not heard back.

**Comment by kovrik** [comment]
@progfolio
Hi,

Sorry for such a late response.
Yes sure, I have no issues with that.
Will flick an email to assign@gnu.org (is that the easiest way?).

Cheers,
kovrik

**Comment by progfolio** [comment]
Not a problem! Appreciate the response. Yes, you've got the idea. 
As John described above: https://github.com/jwiegley/use-package/issues/282#issuecomment-155909393

Just let them know your intention and they'll send you an email with further instructions.
Thank you.

**Comment by mplscorwin** [comment]
Hello.  I notice some conversation on emacs-devel today suggesting, I think incorrectly, that progress has stalled on this.  Can I ask for an updated status on assignment and merge to Emacs core?

Thank you so much for use-package and especially for all of the administivia around this task especially; can't wait to see this capability in core!

**Comment by andschwa** [comment]
Update on my case: I’ve been informed my papers are next in line for review. Maybe we’ll be done with this soon!

**Comment by jwiegley** [comment]
OK, I've talked with the other maintainers and we're a go for integration. I'll get the commit ready this week, and as soon as we have either papers signed or replacements for work unsigned, it can go in!

**Comment by thomasf** [comment]
So I have packed up the printer I bought a few years ago just to print out the copyright assignment form.. Will try to install it today and mail it during the coming weeks when I have an errand to go outside the house where I can send a letter.

**Comment by jwiegley** [comment]
Thank you @thomasf, whatever it is that the FSF requirements to include your work with Emacs. I have no personal preferences as to the extent of the liberties you allow.

**Comment by progfolio** [comment]
> So I have just packed up the printer I bought a few years ago just to print out the copyright assignment form.. Will try to install it today and mail it during the coming weeks when I have an errand to go outside the house where I can send a letter.

The form can be signed digitally, too. May be more convenient than digging out the printer if you're familiar with gpg.

**Comment by MatthewZMD** [comment]
> mail it during the coming weeks when I have an errand to go outside the house where I can send a letter.

The letter doesn't have to be mailed, you can simply send them through email.

**Comment by thomasf** [comment]
> > So I have just packed up the printer I bought a few years ago just to print out the copyright assignment form.. Will try to install it today and mail it during the coming weeks when I have an errand to go outside the house where I can send a letter.
> 
> The form can be signed digitally, too. May be more convenient than digging out the printer if you're familiar with gpg.

Oh, I don't think this was available when I started the process in 2015 or it was very secret. 

I only have the PDF version that I got emailed in 2015, should I contact assign@gnu.org again to get new info on how to digitally sign using gnupg?

**Comment by kidd** [comment]
I'm following this thread like reaching the end of an epic novel that you want to finish, but you really don't want to end, because you're so engaged with the characters you'll miss them afterwards.

/r/oddlysatisfying and wholesome.  

Big thanks everyone involved on this mission. You rock!

**Comment by thomasf** [comment]
I just tried to find some information about digitally signing.. It seems like it maybe was introduced in 2016 but it's only available for USA or Italy.

> After receiving the necessary form, the contributor needs to sign it. Contributors residing in the USA or Italy may use GPG in order to sign their assignment. Contributors located anywhere else can print, sign, and then email (or fax) a scanned copy back to the FSF.

https://www.gnu.org/prep/maintain/html_node/Copyright-Papers.html

I have already had COVID19 once and haven't fully recovered yet after 5 months so I'm not leaving home unless I have a very important reason so I'll post it when I can.

**Comment by MatthewZMD** [comment]
> I just tried to find some information about digitally signing.. It seems like it maybe was introduced in 2016 but it's only available for USA or Italy.
> 
> > After receiving the necessary form, the contributor needs to sign it. Contributors residing in the USA or Italy may use GPG in order to sign their assignment. Contributors located anywhere else can print, sign, and then email (or fax) a scanned copy back to the FSF.
> 
> https://www.gnu.org/prep/maintain/html_node/Copyright-Papers.html
> 
> I have already had COVID19 once and haven't fully recovered yet after 5 months so I'm not leaving home unless I have a very important reason so I'll post it when I can.

That's terrible to hear, hope you're feeling better now! :-(

You can print the paper, sign, scan at home and email to assign@gnu.org. You can also fax +1-617-542-2652.

This is part of the email I received from the copyright-clerk@fsf.org when I was filling out the document couple months ago:

```
Thank you so much for contributing. Please find the attached PDF(s) of your 
assignment(s) in the email after this one. Please print out the form, sign it, 
and then email a scanned copy in PDF format to <assign@gnu.org> or fax it to us 
at +1-617-542-2652. You can also send it to us via the postal mail if you prefer:

Copyright & Licensing Associate
Free Software Foundation
51 Franklin Street, Fifth Floor
Boston, MA 02110

Once the FSF has signed it, we will send you a digital copy in PDF format for 
your records.
```

You should email them for the latest info, although I doubt there will be any additional changes.

Hope use-package makes into emacs core soon!

**Comment by ane** [comment]
Why is digital signing only available for residents of the USA and Italy, I wonder?

**Comment by thomasf** [comment]
> Why is digital signing only available for residents of the USA and Italy, I wonder?

Probably because no one on the FSF side has looked into whats legally required from an digital cryptographic signature of any other country. 

...

In any case, I printed, signed, scanned, converted back to PDF and e-mailed my back a week or so ago. No reply yet but it should be on in someones inbox at least now.

**Comment by thomasf** [comment]
My assignment form is also signed by FSF and complete now.

**Comment by jwiegley** [comment]
@kovrik @andschwa any status you can report?

**Comment by andschwa** [comment]
Last update from the FSF copyright clerk in December was that my paperwork was next to be reviewed, I’ve just sent another email asking for an update. Frankly I really don’t know what happened: I got the original copyright assignment paperwork from the FSF sometime in 2018, got it reviewed and approved by my employer’s legal team (and they didn’t tell me to they’d made any changes, they just said to have my manager sign it), so in 2019 it got signed by my then-manager and I mailed it in. FSF said it wasn’t quite the same language and that it needed to be reviewed by their legal team, which is the queue it’s been sitting in since then. I offered to just get fresh paperwork signed but if I recall correctly they said that was unnecessary and just wanted to have it reviewed. So anyway, I guess eventually it will happen.

**Comment by kovrik** [comment]
Yeah I am still waiting for the reply from FSF.
Is there an alternative way to avoid the whole hassle?
I don't even remember what changes I've done (probably something really minor), maybe it's not even there anymore.

**Comment by andschwa** [comment]
Unfortunately the whole hassle is unavoidable. It’s a particularly paperworked process that the [FSF requires](https://www.gnu.org/licenses/why-assign.html) (and that many other projects use simpler means for, like automatic CLA-bots, but still wouldn’t have been possible here since the code is getting incorporated from another project).

I think I have four different Emacs projects (including Emacs itself) that I have been unable to continue to contribute to because of this legalese, despite wanting to make more contributions. It’s changed my opinions of copyright assignment, that’s for sure.

There’s a lot of [history](http://www.h-online.com/open/features/Copyright-assignment-Once-bitten-twice-shy-1049631.html) to this if you’re interested.

**Comment by jwiegley** [comment]
Thanks to you both for keeping up with this. I know it can be tiresome, but it helps to keep Emacs entirely free from any possible copyright encumbrances.

**Comment by MatthewZMD** [comment]
I don't know what's taking so long but I suggest following up with the FSF folks on the IRC might help.

**Comment by kovrik** [comment]
Guys, guys, we are almost there. 
I have finally received the assignment form pdf from FSF. Planning to sign and send it to FSF today. Will report back shortly.

**Comment by kovrik** [comment]
OK, signed and sent the assignment form back to FSF.

**Comment by jwiegley** [comment]
@andschwa Unless I'm misreading, your commits have all been additions of documentation, which shouldn't need you to submit forms to the FSF.

**Comment by andschwa** [comment]
For `use-package`, yes, I [agree with that assessment](https://github.com/jwiegley/use-package/issues/282#issuecomment-621310930) (sorry, I guess that was missed).

**Comment by mplscorwin** [comment]
Hi again.

May I trouble you all again for an update on the potential migration of use-package into Emacs' core?  I think it would be really amazing if this could land for Emacs 28 along with native-comp.  (The native-comp branch is likely to be merged to master in a few days pending a few issues with atypical installation/invocation IIUC).

Thanks for this wonderful package.

**Comment by jwiegley** [comment]
Work has obliterated my time this year and last. We have our first public release coming up very soon now, and I'm intending after that happens of getting back to a lot of languishing issue across several projects. Thank you for your patience!

**Comment by mplscorwin** [comment]
I [understand](https://www.reddit.com/r/emacs/comments/t5cmap/comment/hz56r56/?utm_source=share&utm_medium=web2x&context=3) you may be able to use assistance getting this "the last mile".  I'll certainly follow conversations on devel and via debbugs.gnu.org; please don't hesitate to "assign" anything out.

I can have a look at the "moving files about" bit, and see if I'm up to the task of generating a patch set from there.  I won't at all be upset if others also attempt this and are more successful or simply quicker about it.  I'll reply back here to share any success  I may have if that sounds OK.

**Comment by progfolio** [comment]
Will 2023 be "The Year of Desktop use-package"?

**Comment by skangas** [comment]
@jwiegley Could this issue be closed?

**Comment by jwiegley** [comment]
I think the purpose of this issue has been concluded.

**Comment by skangas** [comment]
I briefly reopened this as we were still lacking assignments for three PRs. The relevant changes have been reverted for now, while we're waiting for a copyright assignment, so this is no longer blocking the merge to Emacs.

I'm therefore closing this issue again now.
