### ISSUE TITLE
:after multi packages?

### ISSUE THREAD

**Issue by tumashu** [jwiegley/use-package#283]
```
(use-package xxx4
  :after (xxx3 xxx2 xxx1))
```

Is this feature works?

**Comment by vyp** [comment]
I think it works as in, if *any* of `xxx3`, `xxx2`, or `xxx1` are loaded, then it will load `xxx4`, but I may be incorrect. But see https://github.com/jwiegley/use-package/pull/276#issuecomment-155697809.

**Comment by jwiegley** [comment]
If we implemented `:after` with nested calls to `eval-after-load`, then it would work as I'd have expected: xx4 loads after the other three have loaded.

**Comment by tumashu** [comment]
"all" mode is more useful than "any", i think , may be we can do like this:

:after  (all xxx1 xxx2 (any xxx3 xxx4))

**Comment by jwiegley** [comment]
They should be keywords, though, `:all` and `:any`.

**Comment by tumashu** [comment]
maybe add another keywords: :not , I think  :all :any with :not can deal with most dependence between features

**Comment by tumashu** [comment]
I prefer:

```
:after (all xxx1 xxx2 (any xxx3 xxx4) (not xxx5))
```

I think it it more flexible than three keywords

**Comment by ennokde** [comment]
I recently looked for some kind of dependency handling and found something that probably does what :all would stand for:
https://github.com/edvorg/req-package

`:require package1 package2 ...`

**Comment by justmytwospence** [comment]
There could also just be two keywords in the macro: `after-all` and `after-any`.

**Comment by jwiegley** [comment]
I'd much rather have a DSL with `:all` and `:any`, with synonyms `:and` and `:or`, for those of us who think in those terms.
