### ISSUE TITLE
some keywords not fully documented

### ISSUE THREAD

**Issue by aspiers** [jwiegley/use-package#287]
The following keywords are documented in the `use-package` docstring, but not in README.md:
- [x] `:after`
- [x] `:bind-keymap`
- [x] `:bind-keymap*`

but even the docstring is missing a full description of the options which should be given to those keywords.

Additionally, there are 5 other keywords that aren't documented either in the README.md nor in the `use-package` docstring, but are still valid (thanks to @bricewge for spotting these):
- [x] `:when`
- [x] `:unless`
- [x] `:requires`
- [x] `:no-require`
- [x] `:delight`

**Comment by aspiers** [comment]
Furthermore, I see that `bind-keys` can use `:map`, but it's undocumented how this could be used within `use-package`.  Based on #88 and #129 it looks like this is still WIP but I'm not really sure.  Would be great if you could clarify for those of us currently lacking time to hack on this ;-)

**Comment by aspiers** [comment]
Ahh, now I found #119 and #121.  But if someone has to submit an issue or trawl through the database of issues in order to find out how to use a feature, that is a documentation bug, so IMHO it's not a good idea to provide the answer in the issue and then close it without fixing the documentation, as happened in #119 and #121 ;-)  So please document it, otherwise people will keep filing issues like this one :-)  Thanks!

**Comment by bricewge** [comment]
There are 5 other keywords that aren't documented either in the README.md nor in the `use-package` docstring, but are still valid:
- `:when`
- `:unless`
- `:requires`
- `:no-require`
- `:delight`

**Comment by aspiers** [comment]
Thanks @bricewge - I have added these to the issue description above.  @jwiegley It would be great if in future you insist that PR submitters include corresponding doc updates with their new features before merging :-)  Even better if tests are added too ;-)

**Comment by kostya-sh** [comment]
I suggest to add examples for all use-package macros to README. Sometimes it is difficult to understand how to use them.

Suggested example for `bind-keymap`:

    (use-package projectile
      :bind-keymap
      ("C-c p" . projectile-command-map)

**Comment by jwiegley** [comment]
@kostya-sh Yes, there should be a "reference" section that lists every possible keyword, and gives one or more examples for each.  At some point this will be written, though I welcome pull requests in the meantime. :)

**Comment by jwiegley** [comment]
This also connects with #365
