### ISSUE TITLE
diminish imply commands

### ISSUE THREAD

**Issue by fommil** [jwiegley/use-package#288]
it would be really great if `:diminish` implied `:commands` as I find myself repeating the minor mode in both these sections when I want to lazily load.

**Comment by npostavs** [comment]
But then it would be impossible to `:diminish` without loading lazily, right?

**Comment by fommil** [comment]
ah

**Comment by jwiegley** [comment]
You can always use `:demand t` to avoid lazy loading.

Looking at my own `init.el`, I too repeat the major mode twice nearly everywhere that I use `:diminish`.  The only problem with making this change is that it might surprise many of its current users...

**Comment by npostavs** [comment]
> You can always use :demand t to avoid lazy loading.

Ah, good point.

> Looking at my own init.el, I too repeat the major mode twice nearly everywhere that I use :diminish.

Hah, I've looked at mine, and I found a few places where I used `:diminish` without `:defer`, but in each of those cases I see that I *should* be using `:defer` anyway!

> The only problem with making this change is that it might surprise many of its current users...

Yes, in a few of the cases mentioned above, I'd also need to move some code from `:config` to `:init` (though again, I should probably do this anyway).

But still, on the whole, +1 from me on this change.

**Comment by jwiegley** [comment]
Given the different ways that `:commands` and `:diminish` are handled in the code, I'm going to avoid making this any more magical.  It will simply require duplication if lazy loading is desired.

**Comment by jwiegley** [comment]
Something we might want someday is the ability to have "plugin optimizers", or code passes that are free to rewrite `use-package` declarations according to rules specified by the user.  Then request like this would be trivial, as they would happen before we start expanding the macro.
