### ISSUE TITLE
use-package doesn't work with lisp-mode

### ISSUE THREAD

**Issue by fommil** [jwiegley/use-package#289]
I am using use-package even for built-in emacs packages so that my init.el is consistent, but this tries to download `lisp-mode` from ELPA

```elisp
(use-package lisp-mode
  :commands emacs-lisp-mode
  :config
  (bind-key "RET" 'comment-indent-new-line emacs-lisp-mode-map)
  (bind-key "C-c c" 'compile emacs-lisp-mode-map))
```

is this a bug or am I doing it wrong?

**Comment by fommil** [comment]
workaround seems to be to use `:ensure nil` but this isn't needed on other packages such as `subword` and `eldoc`

**Comment by vyp** [comment]
#243
