### ISSUE TITLE
Cannot use use-package on a list

### ISSUE THREAD

**Issue by emacsuser123** [jwiegley/use-package#290]
Hi.

I'm trying to use use-package iterating over a list.
Something  like:

`(setq package-list '(magit`
`		               smex`
`		               helm))`
`(dolist (p package-list)`
`  (use-package p))`

But emacs throws an error saying that package 'p-' is not available.

If I use use-package with each package individually, then there is no problem at all: every
package is installed successfully, if needed (use-package-always-ensure is set to t).
 
Here below is the debugging output:

-----------------------------------------
Debugger entered--Lisp error: (error "Package `p-' is unavailable")
  signal(error ("Package `p-' is unavailable"))
  error("Package `%s-%s' is unavailable" p "")
  package-compute-transaction(nil ((p)))
  package-install(p)
  use-package-ensure-elpa(p t)
  use-package-ensure-elpa(p)
  (progn (require (quote package)) (use-package-ensure-elpa (quote p)))
  (progn (progn (require (quote package)) (use-package-ensure-elpa (quote p))) (let ((now (current-time))) (message "%s..." "Loading package p") (prog1 (if (not (require (quote p) nil (quote noerror))) (ignore (message (format "Could not load %s" (quote p))))) (let ((elapsed (float-time (time-subtract ... now)))) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Loading package p" elapsed) (message "%s...done" "Loading package p"))))))
  (while --dolist-tail-- (setq p (car --dolist-tail--)) (progn (progn (require (quote package)) (use-package-ensure-elpa (quote p))) (let ((now (current-time))) (message "%s..." "Loading package p") (prog1 (if (not (require (quote p) nil (quote noerror))) (ignore (message (format "Could not load %s" ...)))) (let ((elapsed (float-time ...))) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Loading package p" elapsed) (message "%s...done" "Loading package p")))))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- package-list) p) (while --dolist-tail-- (setq p (car --dolist-tail--)) (progn (progn (require (quote package)) (use-package-ensure-elpa (quote p))) (let ((now (current-time))) (message "%s..." "Loading package p") (prog1 (if (not (require ... nil ...)) (ignore (message ...))) (let ((elapsed ...)) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Loading package p" elapsed) (message "%s...done" "Loading package p")))))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  eval-buffer(#<buffer  *load*> nil "/home/roberto/.emacs.d/init.el" nil t)  ; Reading at buffer position 3091
  load-with-code-conversion("/home/bobv/.emacs.d/init.el" "/home/bobv/.emacs.d/init.el" t t)
  load("/home/bobv/.emacs.d/init" t t)
-----------------------------------------

Any idea?

Thanks a lot.
-BobV

**Comment by thomasf** [comment]
It's because use-package is a macro.. It's probably possible to do this by converting your code into a macro which ensurs that that the `p` argument gets expanded before the `use-package` macro   you probably shouldn't really be using `use-package` for this because you could just call `package-install` in such a loop instead using something like this function instead:

```el
 (defun require-package (package &optional min-version no-refresh)
    "Install given PACKAGE, optionally requiring MIN-VERSION.
If NO-REFRESH is non-nil, the available package lists will not be
re-downloaded in order to locate PACKAGE."
    (if (package-installed-p package min-version)
        t
      (if (or (assoc package package-archive-contents) no-refresh)
          (package-install package)
        (progn
          (package-refresh-contents)
          (require-package package min-version t))))))
```

**Comment by emacsuser123** [comment]
Understood ...

I was trying to use use-package since it wraps up a number of features that help reducing clutter.

Thanks a lot.
-BobV

**Comment by thomasf** [comment]
Yes it does but it doesnt make much sense in using it in a loop since th
