### ISSUE TITLE
duplicate indentation specification

### ISSUE THREAD

**Issue by introom** [jwiegley/use-package#291]
For example, 
here: https://github.com/jwiegley/use-package/blob/master/use-package.el#L1069

and here: https://github.com/jwiegley/use-package/blob/master/use-package.el#L1112

Is this sorta duplication(contradiction) on purpose?

**Comment by jwiegley** [comment]
Not on purpose, they were just written by different people. The latter one should be removed I think.

**Comment by jwiegley** [comment]
I think the duplication is harmless, and I'm not sure if older Emacsen might need it.
