### ISSUE TITLE
error when using use-package with package.el in .emacs

### ISSUE THREAD

**Issue by DanLipsitt** [jwiegley/use-package#292]
If use-package is installed with package.el, then it can't be used in `.emacs` without some extra work. I think this is a documentation problem rather than a bug in use-package.

The problem is that emacs runs  `package-initialize` *after* `.emacs` is loaded. Therefore, if `use-package` itself has been installed with `package.el`, it won't be available yet.

**Comment by npostavs** [comment]
This is not a really a problem of use-package at all, it's a general problem of package.el installed packages, and the solution is to call `package-initialize` at the top of your .emacs. Newer Emacs will insert this call automatically.
