### ISSUE TITLE
Use add-to-list instead of push when handling :mode lists

### ISSUE THREAD

**Issue by lixinchin** [jwiegley/use-package#293]
Currently the modes listed under the `:mode` binding are added to `auto-mode-alist` using `push`. However this doesn't check if the mode binding already exists, possibly leading to duplicate bindings in `auto-mode-alist`. This doesn't seem harmful, but it does look a bit messy.

The attached patch seems to fix this issue.
[use-package-patch.txt](https://github.com/jwiegley/use-package/files/54875/use-package-patch.txt)

**Comment by npostavs** [comment]
> The attached

Dude, it's one line, just inline it.
```diff
--- use-package.el	2015-12-08 11:02:59.362470300 +0800
+++ use-package-patch.el	2015-12-08 11:02:47.803002400 +0800
@@ -777,7 +777,7 @@
   (let* (commands
          (form (mapcar #'(lambda (mode)
                            (push (cdr mode) commands)
-                           `(push ',mode auto-mode-alist)) arg)))
+                           `(add-to-list 'auto-mode-alist ',mode)) arg)))
     (use-package-concat
      (use-package-process-keywords name
        (use-package-sort-keywords
```

**Comment by vyp** [comment]
@npostavs otoh having a file means it's more convenient to `patch`. ;)
