### ISSUE TITLE
binding keys in a mode rather then globaly

### ISSUE THREAD

**Issue by gozes** [jwiegley/use-package#294]
I want to rebind helm-execute-persistent-action and helm-select-action to <tab> and <M-<tab> but only in the helm buffer/mode. If I use the :bind it will remap <tab> globally. How can I bind a key so that it will only be use in that mode?

**Comment by WorldsEndless** [comment]
The main readme makes reference to `:bind-keymap` and `:bind-keymap*` but I can't find a definition for these. However, I did find the following in the preface of the bind-key package (which ships with use-package):

    ;; If you want the keybinding to override all minor modes that may also bind
    ;; the same key, use the `bind-key*' form:
    ;;
    ;;   (bind-key* "<c-return>" 'other-window)
    ;;
    ;; If you want to rebind a key only in a particular keymap, use:
    ;;
    ;;   (bind-key "c-c x" 'my-ctrl-c-x-command some-other-mode-map)
    ;;
    ;; To unbind a key within a keymap (for example, to stop your favorite major
    ;; mode from changing a binding that you don't want to override everywhere),
    ;; use `unbind-key':
    ;;
    ;;   (unbind-key "c-c x" some-other-mode-map)
    ;;
    ;; To bind multiple keys at once, or set up a prefix map, a `bind-keys' macro
    ;; is provided.  It accepts keyword arguments, please see its documentation
    ;; for a detailed description.
    ;;
    ;; To add keys into a specific map, use :map argument
    ;;
    ;;    (bind-keys :map dired-mode-map
    ;;               ("o" . dired-omit-mode)
    ;;               ("a" . some-custom-dired-function))
    ;;
    ;; To set up a prefix map, use `:prefix-map' and `:prefix' arguments (both are
    ;; required)
    ;;
    ;;    (bind-keys :prefix-map my-customize-prefix-map
    ;;               :prefix "C-c c"
    ;;               ("f" . customize-face)
    ;;               ("v" . customize-variable))

So I'm going to start using (bind-keys :map my-map... in my stuff. Note that you can put these bind commands in the :config section of your use-package and it should do what you want. There's probably a shortcut with the afore-mentioned `:bind-keymap` too.

**Comment by gozes** [comment]
I will need to try that. Now I am wandering dose the <mode-name>-mode-map variable is generated by Emacs when you define mode so using the :map with let say helm-mode-map should work right? I am not sure if the <mode-name>-mode-map is a convention or something that Emacs enforces when you declare a major/minor mode

**Comment by npostavs** [comment]
> I am not sure if the -mode-map is a convention or something that Emacs enforces when you declare a major/minor mode

It's a convention, not enforced, but using `define-minor-mode` follows it unless you specifically pass another variable name.
```
define-minor-mode is an autoloaded Lisp macro in `easy-mmode.el'.

(define-minor-mode MODE DOC &optional INIT-VALUE LIGHTER KEYMAP &rest
BODY)

Define a new minor mode MODE.
...
Optional KEYMAP is the default keymap bound to the mode keymap.
...If you supply a KEYMAP
  argument that is not a symbol, this macro defines the variable
  MODE-map and gives it the value that KEYMAP specifies.
...
```

**Comment by WorldsEndless** [comment]
yeah, it's only a convention; bit if you are a helm user (as you mentioned), using `C-h v` (describe-variable) and letting the helm auto-complete work for you is a great way to search for the right mode map. Example:

`C-h v` `mo map` and I can see all variables named mode map; just add "tex" or whatever mode and you'll find the right map.

**Comment by jwiegley** [comment]
Here is how you would do this now:

``` elisp
(use-package helm
  :bind (:map helm-mode-map
         ("C-c h" . helm-execute-persistent-action)))
```
