### ISSUE TITLE
Use package is not working with desktop mode

### ISSUE THREAD

**Issue by jaseemabid** [jwiegley/use-package#296]
This didn't work

```emacs-lisp
(use-package desktop
  :config
  (desktop-save-mode t))
```

and I had to add an extra 

```emacs-lisp
  :init
  (add-hook 'after-init-hook 'desktop-read)
```

for desktop mode to read previous session.

**Comment by thomasf** [comment]
thdesktop

**Comment by thomasf** [comment]
try moving (desktop-save-mode t) to the `:init` block as well.. this might be about some value initialization order thing. I don't think this has anything todo with use package itself.

**Comment by jaseemabid** [comment]
I noticed the same with recentf as well.

This wont work, 

    (use-package recentf-mode
      :bind ("C-x C-r" . recentf-open-files)
      :config 
      (recentf-mode 1))

but this will.

    (use-package recentf-mode
      :bind ("C-x C-r" . recentf-open-files)
      :init
      (recentf-mode 1))

**Comment by npostavs** [comment]
> I noticed the same with recentf as well.

That's a different problem, you have the package name wrong, try

```elisp
(use-package recentf
  :bind ("C-x C-r" . recentf-open-files)
  :config 
  (recentf-mode 1))
```
