### ISSUE TITLE
request: describe-personal-keybindings for one or some keymaps only

### ISSUE THREAD

**Issue by Antoine-Patel** [jwiegley/use-package#297]
I began to rely a lot on `describe-personal-keybindings`, at least I would like to. I have too many personal keybindings as I remapped almost everything (and I'm not done yet) because of wrists/fingers pain; the output is getting too big to be useful (loosing time scrolling up and down to find what I need...).

It would be really nice if `describe-personal-keybindings` could optionally filter bindings belonging only to one keymap or a given list of keymaps in the output. I'd like to do something like `(describe-personal-keybindings (current-local-map))` in a custom command and then bind it; it would filter a lot of the output, and give the info I want most of the time. Another example: `(describe-personal-keybindings helm-map helm-swoop-map)`.

(Warning: my elisp is weak. I hope I got it right). Maybe changing its defun to something like `(defun describe-personal-keybindings (&optional &rest filter-keymaps) ...` would do ? It wouldn't break any existing code, but I don't know if it's a good idea. I see in the output that bindings are already nicely grouped into their respective keymaps, so I thought I could just ask for it.

**Comment by jwiegley** [comment]
I'd be interested in a Pull Request to implement this, but I think the request is uncommon enough that I'm going to close as "will not implement".
