### ISSUE TITLE
:bind prevents evaluation of :config?

### ISSUE THREAD

**Issue by WorldsEndless** [jwiegley/use-package#298]
In the following use-package invocation, I find that un-commenting the :bind line (which I know IS functional if uncommented) prevents the :config section from working. 

    (use-package smartparens-config
      :ensure smartparens
      ;:bind (("C-<f5>" . smartparens-mode)) ; prevents evaluation of the :config stuff
      :config
      (smartparens-global-mode)
      (show-smartparens-global-mode)
      (sp-use-paredit-bindings)
      (add-hook 'emacs-lisp-mode-hook 'turn-on-smartparens-strict-mode)
      (add-hook 'clojure-mode-hook 'turn-on-smartparens-strict-mode)
      (add-hook 'cider-repl-mode-hook #'turn-on-smartparens-strict-mode)
      (bind-keys
       :map smartparens-strict-mode-map
       (";" . sp-comment)
       ("M-f" . sp-forward-symbol)
       ("M-b" . sp-backward-symbol)
       ("M-a" . sp-beginning-of-sexp)
       ("M-e" . sp-end-of-sexp)))

GNU Emacs 24.5.1 (x86_64-unknown-linux-gnu, X toolkit, Xaw3d scroll bars) of 2015-11-26

**Comment by jwiegley** [comment]
Right, the `:bind` there is causing the package load to be deferred.

You have two options: Use `:init` instead of `:config`, so it happens before load. Or add `:demand t` to force it to be loaded.
