### ISSUE TITLE
flycheck reported fail for `:pin` also the archive was in package-list

### ISSUE THREAD

**Issue by Gnouc** [jwiegley/use-package#299]
Here is part of my configuration:
```
(require 'package)
(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
                         ("marmalade" . "https://marmalade-repo.org/packages/")
                         ("melpa" . "https://melpa.org/packages/")
                         ("melpa-stable" . "http://melpa.milkbox.net/packages/")
                         ("elpy" . "https://jorgenschaefer.github.io/packages/")))

;; markdown-mode
(use-package markdown-mode
  :ensure t
  :pin marmalade
  :mode "\\.md\\'"
  :config
  (add-hook 'markdown-mode-hook
            (lambda ()
              (when buffer-file-name
                (add-hook 'after-save-hook
                          'check-parens
                          nil t)))))
```

Although I could installed `markdown-mode` successfully, every time I save the buffer, `flycheck` with `emacs-lisp` as default checker always reported:
```
Archive 'marmalade` requested for package 'markdown-mode' is not available
```

I also replaced `marmalade` with `gnu` or `melpa-stable` with no luck.

What cause this issue and how to fix?

**Comment by Gnouc** [comment]
@jwiegley Could you please take a look at this issue?

**Comment by npostavs** [comment]
Does it work if you wrap the `setq` in `eval-when-compile`? I think it might be checking the the archives at macro-expansion time, before your `setq` has taken effect.

**Comment by Gnouc** [comment]
@npostavs Yes, wrapping `setq` in `eval-when-compile` made the error from `:pin` disappear, but made a bunch of other warning messages, example my [sh hook](https://github.com/Gnouc/emacs.d/blob/master/init.el#L443) was warned with message
```
assignment to free variable `sh-basic-offset'
assignment to free variable `sh-indentation'
```

**Comment by Gnouc** [comment]
@npostavs Yes, wrapping `setq` in `eval-when-compile` made the error message disappear.

**Comment by npostavs** [comment]
So currently we have
```elisp
(defun use-package-handler/:pin (name keyword archive-name rest state)
...
    ;; This happens at macro expansion time, not when the expanded code is
    ;; compiled or evaluated.
...
```

But actually, I think the `:pin` should take effect the same time as `:ensure`: runtime and during byte-compilation. @kovrik, @thomasf  does that seem right to you?

**Comment by jwiegley** [comment]
I don't use `:pin` at all, so I have nothing to add to this discussion.

**Comment by kovrik** [comment]
I agree with @npostavs.
It's better to move `:pin` (honestly, I'd move all non-trivial functionality) out of macro expansion time to runtime/byte-compilation time the same way we did that for `:ensure`.

I will take a look at the code today or tomorrow (`:pin` looks easier for me than `:ensure`, but I'm not sure).
As far as I understand, the only thing `:pin` does is adding an entry into `package-pinned-packages` var.

**Comment by kovrik** [comment]
@Gnouc 
By the way, I can't reproduce that issue.

1) I paste your config, 
2) enable `emacs-lisp-mode`, 
3) enable `flycheck-mode`, 
4) use `flycheck-select-checker` to select `emacs-lisp` default checker, 
5) save buffer. 

And that's all, I don't get that warning.
Am I missing something?

Can you please provide more details on how to reproduce it?

**Comment by npostavs** [comment]
> As far as I understand, the only thing :pin does is adding an entry into package-pinned-packages var.

Yes, the only difficulty I forsee is making sure that this effect precedes the effect of `:ensure`.

> Am I missing something?

Maybe a `(require 'use-package)`?

**Comment by kovrik** [comment]
> Maybe a (require 'use-package)?

Already tried that. Same result, no error.

**Comment by Gnouc** [comment]
@kovrik  Here's my [complete config](https://github.com/Gnouc/emacs.d/blob/master/init.el).

Maybe you should try [these lines](https://github.com/Gnouc/emacs.d/blob/master/init.el#L26).

**Comment by kovrik** [comment]
`use-package` docs say:

>use-package throws an error if you try to pin a package to an archive that has not been configured using package-archives (apart from the magic manual archive mentioned above):
**Archive 'foo' requested for package 'bar' is not available.**

So, I can reproduce that error when I do NOT set `package-archives` 
(**or** `:pin` package to some malformed archive):
``` lisp
(require 'package)
(use-package test :ensure t :pin doesnotexist)
```

When I evaluate such form I get:
>if: Archive 'doesnotexist' requested for package 'test' is not available.

And I can reproduce the issue with `flycheck` like this:
``` lisp
;;; test--- Summary
;;; Commentary:
;;; Code:
(require 'package)
(package-initialize)
(require 'use-package)

(use-package test :pin doesnotexist)

(provide 'test)
;;; test.el ends here
```
Flycheck-errors:
>  8   1 error           Archive 'doesnotexist' requested for package 'test' is not available.... (emacs-lisp)

**BUT** I don't get the error if I `:pin` using any archive from `package-archives` list.

**Comment by kovrik** [comment]
@Gnouc 
Correct, Get the error using those lines.

**Comment by kovrik** [comment]
@Gnouc 
Nope, still **can't** reproduce it (even with those lines) if I use **correct** archive name and set it in `package-archives` var.

This error states that you are trying to install a package pinned to the `marmalade` archive, but the time you are evaluating that `use-package` form, you don't have `marmalade` in your `package-archives` list.

So, yes, moving `:pin` out of macroexpansion is a good thing to do,
but I can't reproduce the error you got.

**Comment by kovrik** [comment]
Also, it looks like it macro-expands in the wrong order.
For me both 
`(macroexpand '(use-package markdown-mode :pin melpa :ensure t)))` and
`(macroexpand '(use-package markdown-mode :ensure t :pin melpa))` expand into:

``` lisp
(progn                                                               
  (progn                                                             
    (require (quote package))                                        
    (use-package-ensure-elpa (quote markdown-mode)))                 
  (if (not (require ... nil ...))                                    
      (ignore (message ...)))                                        
  (push (quote (markdown-mode . "melpa")) package-pinned-packages) t)
```
So it first tries to install the package and then pins it to the specified archive.

**Comment by kovrik** [comment]
@Gnouc 
Could you please check if you still have the same error if you grab changes from the pull request above?

**Comment by Gnouc** [comment]
@kovrik: It fixed the error :+1:

**Comment by kovrik** [comment]
@Gnouc
Cool! Thank you for testing!
