### ISSUE TITLE
Did bind-key change from being lazy-loaded? Bind-key to Python map not working anymore.

### ISSUE THREAD

**Issue by nayefc** [jwiegley/use-package#300]
I have a bunch of functions minded in the `python-mode-map` to keys, for example:
```
(bind-key "C-x a i f" 'copy-function-name python-mode-map)
```

In the past few days (I may have updated, although I was always pretty much up to date with `use-package`), this started to throw the following error: 

```
Symbol's value as variable is void: python-mode-map
```

Any idea why this is happening? Is it because its not lazy loading anymore? Did anything change recently?

**Comment by npostavs** [comment]
I don't think it was ever lazy loaded. Maybe you stopped loading python early?

`git blame` tells me the last change to `bind-key` was in March (bfceecd9629702ce9f34c0b1c0534b75940702fb).

**Comment by nayefc** [comment]
Yeah I saw the logs. But yeah that does make sense. Turns out I had `use-package` load python early for me. Thanks.
