### ISSUE TITLE
Fix the bind-keymaps mess (binding local keymaps)

### ISSUE THREAD

**Issue by Silex** [jwiegley/use-package#304]
Hello,

The issues #88, #226, #294 and https://github.com/waymondo/use-package-chords/issues/5 are basically about people being confused by bind-keymap because the documentation is not consistent and no clear communication is done about it. This ticket hopes to address that.

From what I understood, here are the steps that still needs to be done:

* [ ] merge `:bind-keymaps` into `:bind`
* [ ] remove `:bind-keymap` from the documentation
* [ ] document the use of the `:map` keyword, with examples

Once these steps will be done, most of the issues should be able to be closed.

@jwiegley: please update the list above, and if it was already implemented but only lacks the documentation, point me at the relevant part and I'll try to make a PR.

**Comment by jwiegley** [comment]
They are not done already, but you are right, this is the next thing that needs to happen in `use-package`.

**Comment by Silex** [comment]
Alright, waiting all excited then :smile:

**Comment by jwiegley** [comment]
Ok `:bind-keymap` is still unique, so I'm going to document it now.

`:map` will be documented too, and now works properly with regard to laziness.

**Comment by Silex** [comment]
:+1:
