### ISSUE TITLE
package dependency issue when using `:after`

### ISSUE THREAD

**Issue by isolet** [jwiegley/use-package#305]
I have some problems when trying to use `use-package` to speed up my emacs and solving package dependency. To simply the problem, I've the following code in my .emacs

```
(use-package helm
  :ensure t

  :bind
  (("C-x C-m" . helm-M-x))

  :init
  (setq helm-command-prefix-key "C-c h")

  (use-package helm-swoop
    :ensure t
    :after helm
    :bind
    (("C-c h w" . helm-swoop)))

  :config
  (use-package helm-config)
  (helm-mode 1))
```

I supposed this would be work since I guess the `helm-swoop` will be `fully loaded` only  after `helm` is loaded.

The problem is that after emacs started up, *immediately* I press `C-c h w` and `helm-swoop` run as expected. But I press the key stroke again, `C-c h w` become undefined.

Firstly, I have a question. Under this situation, which package will be loaded first ? (`B` is set to `after` `A` but is excuted firstly while its keybinding has the same prefix with `A`)

You may ask why I place the `use-package helm-swoop` inside `use-package helm` and even the `:init` part, I do this for the following reason(goals).

1. To disable a `package family` like the `helm-*** family` by putting a `:disabled t` into the parent the dependency tree, instead of putting into every package.
2. The config should install all the packages automatically from elpa if I'm working at a empty `elpa` directory.
3. Defer loading the parent and children packages.
4. When `helm` is loaded, the children packages are unnecessarily loaded until I use them.
5. I don't want to maintain another `list` containing all the packages should be installed from elpa.

Here are some actions

If I excute `helm-M-x` first, `C-c h w` will run the default binding(`helm-surfraw`) of `helm`, instead of the desiring command `helm-swoop`.

If I remove the `:after helm`, the undefined warning(error) is still there.

Changing `helm` into `helm-mode` makes nothing change.

If I seperate the two `use-package`, to disable the `helm` (big) family, I have to add `:disabled t` into all packags like `helm-ag`, `helm-dash` etc. thus beaks 1.

If I put the `use-package helm-swoop` into the `:config` part of `helm`, `helm-swoop` may not be installed until I press any `helm` command thus breaks 2.

I'm not good at English but I hope someone can understand me.

What's best practics of using `use-package` to solve this? Can these goals be achived ? I know there's a `req-package` may help, but I would prefer to try `use-package` first.

Any help will be greatly appriciated.

**Comment by jwiegley** [comment]
Put the `helm-swoop` configuration into `:config`, and don't use `:after`.

**Comment by isolet** [comment]
Hi, thanks for your answer. Is that mean I can't achieve `2` in this situation ?

>  If I put the use-package helm-swoop into the :config part of helm, helm-swoop may not be installed until I press any helm command thus breaks 2.

**Comment by jwiegley** [comment]
I'm not sure; I have never used the `:after` keyword, so perhaps someone more knowledge about that feature can comment here. I had thought `:after` meant that you could move both `use-package` declarations to the top-level and it would work.
