### ISSUE TITLE
Straightforward way to run code iff the package is available

### ISSUE THREAD

**Issue by dabrahams** [jwiegley/use-package#306]
Hi John!

I found myself today writing:

```lisp
  :demand t
  :config …code...
```

to get some stuff to run immediately, but *only if the package is available*.  The use case was wanting to add yas/expand to org-mode hooks right away, but only if yas is available; seems like a pretty common thing to want todo.  Actually this forces yas to load, which is possibly suboptimal.  It would be nice if there was a more straightforward way of expressing exactly what I want.

Thanks!
-Dave

**Comment by kovrik** [comment]
Didn't get it.
If package is not available, then `:config` won't execute.

**Comment by npostavs** [comment]
I think OP wants `:init-only-if-package-available <code>` (i.e. execute `<code>` before package loads, but only if it will load) instead of `:demand t :config <code>`

**Comment by kovrik** [comment]
If I evaluate
``` lisp
(use-package doesnotexist
  :init (message "INIT")
  :config (message "CONFIG"))
```
I don't get any message at all (even "INIT").

**Comment by npostavs** [comment]
> I don't get any message at all (even "INIT").

I do. Perhaps you didn't notice because it's covered quickly by other messages (`Could not load doesnotexist`, and `nil`).

**Comment by kovrik** [comment]
No, I don't see it even in `*Messages*` buffer.
Weird.

Are you using the latest version?

**Comment by npostavs** [comment]
> Are you using the latest version?

I was a few revisions behind, but just retried with latest `master` (2a50241538b8ead3d620be33bd8e0087f98f42c5), `emacs -Q -L . -l use-package.el`, after pasting your `doesnotexist` example into `*scratch*` and evaluating with `C-x C-e`, `*Messages*` contains
```
For information about GNU Emacs and the GNU system, type C-h C-a.
Mark set
INIT
Could not load doesnotexist
nil
```

**Comment by kovrik** [comment]
Yes, able to reproduce it with `emacs -q`.
Sorry for confusion.

For me it makes sense to skip evaluation of `:init` (and `:config` obviously) if package is not available.

@jwiegley @npostavs
What do you think?

**Comment by jwiegley** [comment]
@dabrahams Hiya, Dave!  Is `:after` what you're after?  It will cause a declaration to load only if/when its antecedent loads. Or so I understand from what @phillord has told me.

**Comment by kovrik** [comment]
From what I can see in the sources, I doubt that `:after` will help here.

**Comment by jwiegley** [comment]
What makes you say that?

**Comment by kovrik** [comment]
Code:
``` lisp
(defun use-package-require-after-load (features name)
  "Return form for after any of FEATURES require NAME."
  `(progn
     ,@(mapcar
        (lambda (feat)
          `(eval-after-load
               (quote ,feat)
             (quote (require (quote ,name)))))
        features)))
```

As far as I understand, given a list of `features` (say `'(f1 f2 f3)`) and a `name` it produces:
``` lisp
(eval-after-load f1
  (require 'name)) 
(eval-after-load f2
  (require 'name)) 
(eval-after-load f3
  (require 'name)) 
```
And that's all.

What OP wants (if I understand him correctly) is to pass a `form`, which should be evaluated if package is available.
So, it's the same what `:init` does, but with one exception - currently `:init` evaluates even if package is not available.

**Comment by dabrahams** [comment]
Yes, I want the form evaluated immediately, but only if the package is available.

**Comment by dabrahams** [comment]
In fact, one could argue that there’s no point at all in `:init` having its current semantics, since you can always write what goes in an `:init` block just before invoking `use-package`.  This seems like a much more generally-useful thing.

**Comment by thomasf** [comment]
@dabrahams for me, the point of having :init is mostly to get a better layout and grouping of package related code.. Also `:disabled` actually removes the `:init` as well so it has some functionality as well..

**Comment by npostavs** [comment]
> For me it makes sense to skip evaluation of :init if package is not available.

I think adding this behaviour to every `:init` could be costly in startup time, as it could be adding extra disk IO to search the filesystem for the package (although I say this without having measured anything).

**Comment by kovrik** [comment]
If you add `:ensure t` (or use **global** `(setq use-package-always-ensure t)` flag), then it will try to install package first **before** evaluating `:init` form.
If ensuring fails (package is not available or something), then it returns immediately and `:init` (and `:config`, obviously) form is not evaluated.

**Example:**
``` lisp
(use-package doesnotexist
  :ensure t
  :init (message "INIT")
  :config (message "CONFIG"))
```
Just throws an error (without printing any message).

You can see that:
``` lisp
(pp-macroexpand-expression
 '(use-package doesnotexist
    :ensure t
    :init (message "INIT")
    :config (message "CONFIG")))
```
Expands to:
``` lisp
(progn
  (progn
    (require 'package)
    (use-package-ensure-elpa 'doesnotexist)) ;; check if package is available FIRST
  (condition-case-unless-debug err           ;; eval init form AFTER ensuring
      (message "INIT")
    (error
     (ignore ...)))
  (let
      ((now ...))
    (message "%s..." "Loading package doesnotexist")
    (prog1
        (if ... ... ...)
      (let ... ...))))
```
I agree, that it's not obvious, but it works (at least for me) and requires no changes.

@dabrahams
Can you use this solution? :)

**Comment by jwiegley** [comment]
@kovrik `:after X` means that the use-package declaration only takes effect once `X` has been loaded. What is confusing about that?

**Comment by vyp** [comment]
FWIW, I agree with @thomasf about the point of `:init`'s current semantics. I also agree with @npostavs here.

`:ensure` is the obvious solution, but I guess that only works for someone who is using package repositories? (or am I wrong?) What about a *configuration* option for this behaviour then (with the default set to what the current behaviour is now)?

**Comment by dabrahams** [comment]
@thomasf you have a point about the current `:init` semantics.  They’re not completely useless.

@kovrik no, I don’t think this works, because I don’t want to incur network traffic during startup when the package isn’t installed.  The point of this is to be able to have configuration that runs immediately, but only when the package is installed, and without eagerly loading that package.

**Comment by dabrahams** [comment]
what I want is the equivalent of
```lisp
:init (when (ignore-errors (find-library <packagename>)) <code here>)
```

I run into the problem of having written `:init` code that can’t run without the package actually installed so often that it’s almost guaranteed I actually need this construct if I want my .emacs to be resilient and usable on new machines where I don’t have, or don’t want to install, everything I know how to configure.

**Comment by phillord** [comment]
Does this not work?

    :if (require 'my-feature nil t)

**Comment by npostavs** [comment]
@phillord should be
```elisp
:if (locate-library "my-feature")
```
to avoid eager loading. But I guess the whole idea is that `use-package` should save you from having to write this everywhere.

**Comment by jwiegley** [comment]
Another thing that `:init` does is ensure that the byte-compilation environment is setup for code inside it.

**Comment by phillord** [comment]
@npostavs Yes, that works, although there is a nasty interaction with :load-path, which needs to be evaluated BEFORE the :if statement.

**Comment by kovrik** [comment]
So, this can't be achieved using current keywords, right?
Should we introduce one new keyword ("eval only if package is installed") or change semantics of existing one?

**Comment by phillord** [comment]
Without looking at the code, I would think not. You could do:

    :if (progn (add-to-list 'load-path "~/emacs") (locate-library "my feature"))

which would be slightly perverse, and also makes the "if" change the path by side effect. This might be 
acceptable, though. If you know where the file is going to be, mostly I guess, you know whether it is there or not?

Either way I am not completely convinced that another keyword, and increasing the complexity of interpretation of load-path would be worth the effort though. Especially if you want to avoid the somewhat nasty semantics of changing the load-path by side-effect.

**Comment by npostavs** [comment]
You can avoid the side effect with
```elisp
:if (locate-library "my feature" nil (cons "~/emacs" load-path))
```

**Comment by jwiegley** [comment]
Wait a minute, `use-package` is designed so that it only runs the `:init` block if the package succeeds at loading. So why is this `:if` needed?

**Comment by vyp** [comment]
@jwiegley 

``` elisp
(use-package doesnotexist
  :init (message "INIT")
  :config (message "CONFIG"))
```

prints `INIT` as @kovrik and @npostavs says?

**Comment by npostavs** [comment]
> Wait a minute, use-package is designed so that it only runs the `:init` block if the package succeeds at loading.

Did you confuse `:init` with `:config`?

**Comment by kovrik** [comment]
@jwiegley 

Right now this code:
``` lisp
(pp-macroexpand-expression 
 '(use-package doesnotexist
	       :init (message "INIT")
	       :config (message "CONFIG")))
```
expands into:
``` lisp
(progn
  (condition-case-unless-debug err
      (message "INIT")      ;; <---------- it evaluates init body first (!!!)
    (error
     (ignore ...)))
  (if (not (require 'doesnotexist nil 'noerror))   ;; <---- THEN try to load the package
      (ignore
       (message (format "Could not load %s" ...)))
    (condition-case-unless-debug err             ;; <---- then eval config
	(message "CONFIG")
      (error ...))
    t))
```

**Comment by kovrik** [comment]
As far as I can see, this happens because this code which tries to load package:
``` lisp
...
(if (not (require 'doesnotexist nil 'noerror))   ;; <---- THEN try to load the package
      (ignore
       (message (format "Could not load %s" ...)))
...
```
is a part of `:config` keyword **(!)**, hence it will always be executed **after** `:init` (unless `:ensure` fails)

Even if actual `:config` is not specified (`(use-package doesnotexist :init ...)`), then it adds it automatically:
``` lisp
...
(args0 (use-package-plist-maybe-put
        (use-package-normalize-plist name args)
           :config '(t)))
...
```
Maybe we can move that `(if (not (require 'doesnotexist nil 'noerror)) ...` part out of `:config` keyword and always add it just after the `:ensure` keyword?

So the order will be like:
`:disabled` -> `:pin`->`:ensure` -> ...(other keywords)... -> that `(if (not (require 'doesnotexist nil 'noerror)) ...` part -> `:init` (will be called only if previous step hasn't failed) -> `:config` without (if (not (require 'doesnotexist nil 'noerror)) ... part -> .. (rest keywords)...

**Comment by npostavs** [comment]
> (5) that `(if (not (require 'doesnotexist nil 'noerror))` ... part
> (6) `:init` (will be called only if previous step not failed)

That won't help because then `:init` executes after package is loaded, i.e. it's no different from `:config`.

**Comment by kovrik** [comment]
@npostavs 
Didn't get it.
It will fail if package is not available and won't go next.

I think we can move that `require` part from `:config` to `:init` and do `use-package-plist-maybe-put` on `:config '(t)` (the same we do it with `:config` now).

**Comment by npostavs** [comment]
@kovrik: The distinction between `:init` and `:config` is that `:init` code runs before the package has loaded, `:config` runs after. If you `require` before running `:init` then you lose the distinction; you may as well just remove support for `:init` completely, much simpler.

**Comment by jwiegley** [comment]
I think we need to add a new check outside the entire use-package declaration, to check whether the library is loadable. This was always an intention, I'm not sure why we lost this ability.

**Comment by kovrik** [comment]
@npostavs 
Yes, now I get your point, you are right.

@jwiegley 
Sounds good.

**Comment by phillord** [comment]
@jwiegley I didn't know that use-package converted a "not found" error to a message. I can see the logic for loading in the idle cycle, but during start up, to me it should fail.

**Comment by jwiegley** [comment]
@phillord Part of the use-package "philosophy" is that failure to configure a package should not cause all of Emacs to fail to load. Rather, it loads and configures everything that it can, in order to provide you with as functional an Emacs as possible.

**Comment by kovrik** [comment]
@jwiegley 
hm, didn't know that.
For me it was always fail-fast, not fail-safe (which makes sense to me).

**Comment by phillord** [comment]
@jwiegley I can see that, although it also means load failures become a line in the startup spam.

Anyway, it's a design decision, and probably wondering off-topic, so I will leave it there.

**Comment by thomasf** [comment]
Personally I also like a fail fast behavior. My Emacs init is complicated enough that without me  spending an unjustifieable amount of time on it will not function well under those circumstances..   
I guess that converting package locating errors to non failing messages also would be enough for me since I can act on the problem and maybe can fix it without `emacs -q`.

**Comment by vyp** [comment]
I like fail safe because it means I still (hopefully) have a functional enough emacs to edit the config and solve the issue (use-package tells you if something failed, I think in Messages buffer or somewhere.)

**Comment by jwiegley** [comment]
I will make fail fast a configuration option. That's easy enough.

**Comment by dabrahams** [comment]
Re: startup spam, it seems don’t we also want to suppress load warnings when the package isn’t available?

Here’s the latest instance that hit me, incidentally.  I don’t even remember what gnus-harvest is offhand.

```lisp
(use-package gnus-harvest
  :init (gnus-harvest-install 'message-x))
```

**Comment by unhammer** [comment]
> I think we need to add a new check outside the entire use-package declaration, to check whether the library is loadable. This was always an intention, I'm not sure why we lost this ability.

So the user would have to wrap the calls to `use-package` with a check? Or were you talking about wrapping the actual code for `use-package` with a check?

I also just got bit by this myself; couldn't do magit-status because I had installed magit-gh-pulls on one machine and added ```

(use-package magit-gh-pulls
  :commands turn-on-magit-gh-pulls
  :init
  (add-hook 'magit-mode-hook #'turn-on-magit-gh-pulls))
``` to my synced .emacs, imagining that `:init` would only run if magit-gh-pulls was lazy-loadable.

I wouldn't mind slightly slower startup-speed myself if all `:init`'s only run `(when (locate-library lib))`. I very much prefer having graceful degradation over completely failing while I have a moment of focus on actual work :)

**Comment by jwiegley** [comment]
> I wouldn't mind slightly slower startup-speed myself if all :init's only run (when (locate-library lib)). I very much prefer having graceful degradation over completely failing while I have a moment of focus on actual work :)

I want this behavior too (optional, of course, since the `load-path` can change dynamically while Emacs is running), so know that it's coming soon to a use-package near you.

**Comment by jwiegley** [comment]
@dabrahams Hi Dave, I think the answer to your original question is the following:

``` elisp
(use-package foo
  :demand t
  :if (locate-library "yasnippet")
  :init
  (message ":init")
  :config
  (message ":config"))
```

This will cause the `:init` block to only run if `yasnippet` can be found on the `load-path`.  If it can be, it is run immediately; otherwise, the whole `use-package` block is ignored (no warnings in `*Messages*`).

Is this what you're looking for?  I hestitate to bake this into `use-package` itself because it could result in a major speed impact calling `locate-library` so many times. Also, I imagine it's use could be somewhat rare.  However, if you do find yourself using such a construction often, I could add an `:if-available` keyword as a shortcut or something.

**Comment by dabrahams** [comment]
on Thu Feb 25 2016, John Wiegley <notifications-AT-github.com> wrote:

> @dabrahams Hi Dave, I think the answer to your original question is the following:
>
> ``` elisp
> (use-package foo
>   :demand t
>   :if (locate-library "yasnippet")
>   :init
>   (message ":init")
>   :config
>   (message ":config"))
> ```
>
> This will cause the `:init` block to only run if `yasnippet` can be
> found on the `load-path`.  If it can be, it is run immediately;
> otherwise, the whole `use-package` block is ignored (no warnings in
> `*Messages*`).
>
> Is this what you're looking for?  

It means having to—in the normal case—name the package twice.  It also
presumably doesn't take advantage of cacheing that would otherwise occur
when the library is in fact found. use-package could be locating the
library and then using the absolute path it found to do the load.
Lastly, it's only a small improvement on 

``` elisp
(if (locate-library "yasnippet")
  (use-package foo
    :demand t
    :init
    (message ":init")
    :config
    (message ":config")))
```

> I hestitate to bake this into `use-package` itself because it could
> result in a major speed impact calling `locate-library` so many
> times. 

Maybe you should test it.  If it doesn't cause a slowdown, wouldn't this
be better semantics?

> Also, I imagine it's use could be somewhat rare.  
> However, if you do find yourself using such a construction often, I
> could add an `:if-available` keyword as a shortcut or something.

For me, it's what I always thought use-package was doing, and was a
major reason that I used use-package.  So I, at least, would want it all
the time.

P.S. I'd love it if init would be renamed “immediately” and “config”
would be renamed “before-load” or “after-load” as appropriate to its
semantics, whatever they may be.  I find it really hard to remember
these things and have to go back to the docs every time I want to add or
maintain a new invocation.

-- 
-Dave

**Comment by jwiegley** [comment]
@dabrahams Please try the attached patch, and tell me what affect is has on your loading speed.

What I don't like about this, performance-wise, is that the speed of N calls to `locate-library` will depend very much on how large the user's load-path is, and how large the directories it references are.

Given that this is such a simple change, it can surely be offered as an off-default customization option, however, which I think satisfies us both, yes?

``` diff
diff --git a/use-package.el b/use-package.el
index 619c6c3..d521826 100644
--- a/use-package.el
+++ b/use-package.el
@@ -938,7 +938,10 @@ deferred until the prefix key sequence is pressed."
   (let ((body (use-package-process-keywords name rest state)))
     (use-package-concat
      ;; The user's initializations
-     (use-package-hook-injector (use-package-as-string name) :init arg)
+     `((if (locate-library ,(use-package-as-string name))
+           ,(macroexp-progn
+             (use-package-hook-injector (use-package-as-string name)
+                                        :init arg))))
      body)))
 
 ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
```

**Comment by jwiegley** [comment]
As for the renaming: I can't stomach `:immediately'.  I'm not opposed to aliases, if a good pair of names can be found.

`:init` executes the given code immediately, if `:if` satisfied, and `:disabled` was not used.  This is code for initializing Emacs to use the package, although it's always possible that the package was loaded before the `use-package` form was encountered.

`:config` configures the package after it loads, provided it could be loaded (which is `use-package`'s job if it wasn't loaded already and nothing is being deferred; it's Emacs' job if it happens lazily).

Given that there are some subtleties, there's no obvious pair of names that comes to mind, since they could both potentially happen after the package is loaded, and they could both potentially never happen at all, if `:if` or `:disabled` are blocking them.

Maybe `:earlier` and `:later`?

**Comment by jwiegley** [comment]
> Maybe you should test it. If it doesn't cause a slowdown, wouldn't this be better semantics?

It's unnecessary, though. Better or not, `use-package` has operated without this check for several years now and no one has brought this up, so it's clearly not necessary.

The role of `:init` is that it should work when the package is unloaded; therefore, it should also work if the package doesn't exist.  Wanting the code to not execute at all if the package doesn't exist is a new feature that was never part of the semantics before.

**Comment by jwiegley** [comment]
@dabrahams You might also like this:

``` elisp
(setq use-package-keywords
      (mapcar
       #'(lambda (kw)
           (cl-case kw
             (:init :immediately)
             (:config :config-after)
             (otherwise kw)))
       use-package-keywords))

(defalias use-package-normalize/:immediately 'use-package-normalize/:init)
(defalias use-package-handler/:immediately 'use-package-handler/:init)

(defalias use-package-normalize/:config-after 'use-package-normalize/:config)
(defalias use-package-handler/:config-after 'use-package-handler/:config)
```

The joys of the extensible keyword support in 2.x. :)

**Comment by AlexanderS** [comment]
Is there something similar available for `:bind`? This would also properly fix #65.

**Comment by unhammer** [comment]
PROTIP: A much faster alternative to `locate-library` for packages installed with package.el is `package-installed-p` (for 1000 executions on the same library, the difference is 20.40368s vs 0.00108s).

**Comment by jwiegley** [comment]
When do we know for sure that every package being configured by use-package was installed by package.el?

**Comment by unhammer** [comment]
> When do we know for sure that every package being configured by
> use-package was installed by package.el?

I wasn't suggesting to use it everywhere! Just as a replacement for `:if (locate-library "")` for users.

Maybe Someone™ could even make a keyword/extension `:init-if-package body` that basically does `:init (when (package-installed-p ,name-symbol) ,@body)`.

Note that (package-installed-p 'cl-lib) returns t, so it does check "built-in" packages as well, but (package-installed-p 'message) does not, even though (require 'message) works. I'd only use it with package.el stuff.
