### ISSUE TITLE
Commit 7f9f685b4481b135a1b4fc778f92e4be1694bfa9 broke using :ensure to install package as a selected package

### ISSUE THREAD

**Issue by lixinchin** [jwiegley/use-package#317]
As per the title. The commit was meant to ensure that any package installed using the :ensure directive was listed as a selected package in the package.el system, however it has the exact opposite effect.

Original changed lines patch:
(defun use-package-ensure-elpa (package &optional no-refresh)
   (if (package-installed-p package)
       t
     (if (or (assoc package package-archive-contents) no-refresh)
-        (package-install package)
+        (package-install package t)
       (progn
         (package-refresh-contents)
         (use-package-ensure-elpa package t)))))

However the documentation of `package-install' from the latest emacs snapshot (as of 2016-02-10) is:

(package-install PKG &optional DONT-SELECT)
...
If called interactively or if _DONT-SELECT_ **nil**, add _PKG_ to `package-selected-packages'.

I.e., (package-install package t) should be **(package-install package nil)** instead.

**Comment by npostavs** [comment]
> I.e., `(package-install package t)` should be `(package-install package nil)` instead.

Which would be the same as  `(package-install package)`, so I guess the commit should just be reverted then.
