### ISSUE TITLE
bind-key.el - Lint warnings

### ISSUE THREAD

**Issue by jaalto** [jwiegley/use-package#32]
FYI, The following warnings are displayed for the *.el file

    *** Lint Emacs 24.3.1 2013-06-25 13:16:00 file: bind-key.el

    ** Lint M-x lm-verify (list-mnt.el)
    Missing: ;; Maintainer:
    Missing: ;; URL:
    Missing: ;;; History:
    Missing: ;;; Code:

    ** Lint M-x checkdoc-current-buffer (checkdoc.el)
    bind-key.el:119: All variables and subroutines might as well have a documentation string
    bind-key.el:122: All variables and subroutines might as well have a documentation string
    bind-key.el:127: All variables and subroutines might as well have a documentation string
    bind-key.el:146: All variables and subroutines might as well have a documentation string
    bind-key.el:173: All interactive functions should have documentation
    bind-key.el:71: First line is not a complete sentence
    bind-key.el:79: First line should be capitalized
    bind-key.el:79: First sentence should end with punctuation
    bind-key.el:98: All variables and subroutines might as well have a documentation string

**Comment by jwiegley** [comment]
Mostly fixed.  I don't care enough about checkdoc, but I'll accept PRs.
