### ISSUE TITLE
Package uniquify- is unavailable

### ISSUE THREAD

**Issue by jojojames** [jwiegley/use-package#320]
Getting that error message upon starting emacs. "Package uniquify- is unavailable"

(use-package uniquify
  :config
  (setq uniquify-buffer-name-style 'reverse)
  (setq uniquify-separator "|")
  (setq uniquify-after-kill-buffer-p t)
  (setq uniquify-ignore-buffers-re "^\\*"))

I assume it might be related to setting

(setq use-package-always-ensure t) but uniquify should be one of the default packages.

http://hastebin.com/cayilaqibu.lisp - link to init.el

**Comment by thomasf** [comment]
It's probably because it's not a `package.el` package (it's not visible in `package-list-packages`).

**Comment by thomasf** [comment]
so you should probably add a `:ensure nil` or whatever the correct way to specify that situation is.

**Comment by jojojames** [comment]
Thanks, that was what I suspected.
