### ISSUE TITLE
bind-keys overwrites existing prefix-maps

### ISSUE THREAD

**Issue by jgeerds** [jwiegley/use-package#321]
I'm not sure if this is a bug or the intended behavior. Calling `bind-keys` multiple times with the same prefix-map will overwrite previously defined keybindings. Here is a very quick example:
```
(bind-keys 
 :prefix-map my-fancy-map
 :prefix "C-M-c"
 ("f" . forward-char))

(bind-keys 
 :prefix-map my-fancy-map
 :prefix "C-M-c"
 ("b" . backward-char))
```
I would expect that both keybindings (e.g. `C-M-c f` and `C-M-c b`) exist in the keymap but that's not the case.

Is there a different way to achieve this?

By the way, I [fixed](https://github.com/jgeerds/use-package/commit/2ba93da5dcb73d4a69b7d5cb242ee7cfba177aa7) this already on my fork but I don't think this should be the final solution. I'm not very familar with elisp :smile:

**Comment by jwiegley** [comment]
This is intended behavior, since `bind-key` defines the prefix map, it doesn't just add to whatever already exists.  You should use this:

``` elisp
(bind-keys 
 :prefix-map my-fancy-map
 :prefix "C-M-c"
 ("f" . forward-char)
 ("b" . backward-char))
```
