### ISSUE TITLE
package in "use-package" is not really a elisp package.

### ISSUE THREAD

**Issue by declanqian** [jwiegley/use-package#322]
I found it confusing with the "use-package" name. Recently I was trying to figure out Emacs/elisp package system. There is a [package](https://www.gnu.org/software/emacs/manual/html_node/elisp/Packaging.html#Packaging) section in elisp manual. Says something about Simple packages and Multi-file Packages. Due to some elisp convention, the simple package name is same as the elisp file name and the provided feature name I think. And the multi-file package with a name "pkg-name" may not has a file with name: pkg-name.el in it, like the `org-plus-contrib`.
And I do find that `use-package` can specify a package name for `:ensure` different from the name for `use-package`, which can handle this scenario.
What I am trying to say here that the word "package" in the "use-package" name is not the same the "package" in the elisp manual, I guess. More like a "feature" or single lisp file name, since you use 
<pre>
(defun use-package-load-name (name &optional noerror)
      "Return a form which will load or require NAME depending on whether it's a string or symbol."
      (if (stringp name) `(load ,name 'noerror) `(require ',name nil 'noerror)))
</pre>
to load it. Right?
Address this in the README may help elisp new comer?  Hope not to bother you.

**Comment by jwiegley** [comment]
@declanqian Do you have a sketch of candidate text that would help newcomers?  Or is this is a theoretical concern based on your own understanding of what packages are?  To date, I'm not aware of it having confused anyone, so I'd rather not add documentation that might actually create the very confusion we'd be seeking to avoid.

**Comment by declanqian** [comment]
You are right. Recently I am trying to learn some elisp. Sorry for bothering you.
Oh, you are the new maintainer of Emacs!!  I watch some videos with Sacha Chua. Awesome!

**Comment by jwiegley** [comment]
Thanks, @declanqian. I'm sorry if my response to this issue sounded harsh, that's not how it was meant.  I just want to make sure we're addressing a real need before adding more words or code. Many thanks for your support!
