### ISSUE TITLE
Multiple bindings combined with :map does not work

### ISSUE THREAD

**Issue by martinp** [jwiegley/use-package#324]
When using `:bind` to add multiple bindings and map-specific bindings with `:map`, none of the global bindings are added.

Example:

```elisp
:bind (("C-x m" . magit-status)
       ("C-c b" . git-blame)
       ("C-c w" . git-branch-with-prefix)
       ("C-c g" . git-grep-root)
       :map magit-status-mode-map
       ;; make C-o and o behave as in dired
       ("o" . magit-diff-visit-file)
       ("C-o" . magit-diff-visit-file-noselect))
```
In this case, none of the global bindings are added. Only `o` and `C-o` are bound (in `magit-status-mode`).

```elisp
:bind ((("C-x m" . magit-status)
        ("C-c b" . git-blame)
        ("C-c w" . git-branch-with-prefix)
        ("C-c g" . git-grep-root))
       :map magit-status-mode-map
       ;; make C-o and o behave as in dired
       ("o" . magit-diff-visit-file)
       ("C-o" . magit-diff-visit-file-noselect))
```

In this case, only `C-x m` is bound globally and `o` and `C-o` are bound in `magit-status-mode`. `C-c b`, `C-c w` and `C-c g` are not bound.

```elisp
:bind (("C-x m" . magit-status)
       ("C-c b" . git-blame)
       ("C-c w" . git-branch-with-prefix)
       ("C-c g" . git-grep-root))
```
When excluding `:map` all bindings are added and work as expected.

**Comment by martinp** [comment]
Use two `:bind` keywords seems to work:

```elisp
:bind (("C-x m" . magit-status)
       ("C-c b" . git-blame)
       ("C-c w" . git-branch-with-prefix)
       ("C-c g" . git-grep-root))

:bind (:map magit-status-mode-map
        ;; make C-o and o behave as in dired
        ("o" . magit-diff-visit-file)
        ("C-o" . magit-diff-visit-file-noselect))
```

**Comment by manuel-uberti** [comment]
I can confirm this one: two separate `:bind` works as expected.

**Comment by xuchunyang** [comment]
BTW, it works if there are an odd number of global bindings.

**Comment by joostkremers** [comment]
Just ran into the same issue:

``` emacs-lisp
(use-package jump-char
  :ensure t
  :bind (("C-M-z" . jump-char-forward)
         ("M-z" . jump-char-backward)
         :map jump-char-isearch-map
         ("<return>" . jump-char-exit)))
```

This only creates the local binding in `jump-char-isearch-map`. The global bindings aren't created.

On the other hand, the following snippet works:

``` emacs-lisp
(use-package org
  :ensure t
  :pin org
  :bind (("C-c l" . org-store-link)
         ("C-c a" . org-agenda)
         ("C-c c" . org-capture)
         :map org-mode-map
         ("C-c t" . org-todo)
         ("C-c C-t" . outline-previous-visible-heading)
         ("C-c b" . ebib-insert-bibtex-key)))
```

**Comment by kaushalmodi** [comment]
Looks like the commands get autoloaded but the bindings are not set until the feature is loaded.

**Comment by kaushalmodi** [comment]
Here's an example:

```el
(use-package multiple-cursors
  :bind (:map modi-mode-map
         ("C-S-c C-S-c"   . mc/edit-lines))
  :bind (:map region-bindings-mode-map
         ("a" . mc/mark-all-like-this)))
```

---

Macro expansion before the recent change:

```el
(progn
  (unless
      (fboundp 'mc/mark-all-like-this)
    (autoload #'mc/mark-all-like-this "multiple-cursors" nil t))
  (unless
      (fboundp 'mc/edit-lines)
    (autoload #'mc/edit-lines "multiple-cursors" nil t))
  (ignore
   (bind-keys :map region-bindings-mode-map
              ("a" . mc/mark-all-like-this)))
  (ignore
   (bind-keys :map modi-mode-map
              ("C-S-c C-S-c" . mc/edit-lines))))
```

---

Macro expansion AFTER the recent change:
Note that now the bindings are not getting set until multiple-cursors is loaded. I expected multiple-cursors to get autoloaded as soon as I used those bindings (earlier behavior).

```el
(progn
  (unless
      (fboundp 'mc/mark-all-like-this)
    (autoload #'mc/mark-all-like-this "multiple-cursors" nil t))
  (unless
      (fboundp 'mc/edit-lines)
    (autoload #'mc/edit-lines "multiple-cursors" nil t))
  (ignore
   (eval-after-load 'multiple-cursors
     '(progn
        (bind-key "a" 'mc/mark-all-like-this region-bindings-mode-map nil))))
  (ignore
   (eval-after-load 'multiple-cursors
     '(progn
        (bind-key "C-S-c C-S-c" 'mc/edit-lines modi-mode-map nil)))))
```

**Comment by manuel-uberti** [comment]
This is working for me, though:
```
(use-package swiper                     ; Isearch with an overview
  :ensure t
  :bind (("C-c s s" . swiper)
         ("C-c s S" . swiper-all))
  :bind (:map isearch-mode-map
              ("M-i" . swiper-from-isearch)))
```

**Comment by kaushalmodi** [comment]
@manuel-uberti As soon as you start emacs, ensure that `M-: (featurep 'swiper)` returns `nil`. Then can you do `M-i` from an `isearch` to switch to `swiper`? I believe that will not work because that `M-i` binding will not get set until `swiper` gets loaded.

**Comment by manuel-uberti** [comment]
@kaushalmodi yes, you're right.

**Comment by kaushalmodi** [comment]
Hmm, looks like this behavior is by design ( https://github.com/jwiegley/use-package/commit/468c4643138eafc65b5bd8734494be2e0325877e#diff-04c6e90faac2675aa89e2176d2eec7d8R136 ). But that would mean that I would need to redo my emacs configuration and move all `:bind` based bindings as `bind-keys` forms in `:init`.. Doesn't seem right.

**Comment by manuel-uberti** [comment]
Let's wait for @jwiegley. I'm sure he can help us on this one.

**Comment by kaushalmodi** [comment]
Hi John, the snippet I posted above ( https://github.com/jwiegley/use-package/issues/324#issuecomment-189321805 ) still does not work as before after the https://github.com/jwiegley/use-package/commit/428982c5bfda0649797725d4b9aae1df0422dc65 fix.

**Comment by jwiegley** [comment]
@kaushalmodi It looks correct here; what do you expect it to do?

**Comment by manuel-uberti** [comment]
I'm still having the same issue: [this snippet](https://github.com/jwiegley/use-package/issues/324#issuecomment-189326116) doesn't work, meaning `M-i` from `isearch` doesn't activate `swiper`.

**Comment by jwiegley** [comment]
Ah, I see the problem.  We need to establish the map bindings if the map is actually in scope.  Otherwise, it assumes that the map will be loaded from the package and waits until then.

**Comment by jwiegley** [comment]
Ugh, allowing `:map` to take a list is really complicating things.  I'm going to remove that ability.

**Comment by kaushalmodi** [comment]
Thank you! I am glad to have the old behavior back.
