### ISSUE TITLE
use patterns

### ISSUE THREAD

**Issue by arademaker** [jwiegley/use-package#326]
It would be nice having a general suggestion about how to use use-package as a replacement for the traditional config pattern of packages. 

For example, a lot of packages follow a template like 

https://github.com/kurtjx/n3-mode-for-emacs

What would be the better way to use use-package for archiving the same goal? My naive approach was to up all commands inside the :config parameter, am I right?

```
(use-package n3-mode
  :config
  (autoload 'n3-mode "n3-mode" "Major mode for OWL or N3 files" t)
  (add-hook 'n3-mode-hook 'turn-on-font-lock)
  (setq auto-mode-alist
	(append (list '("\\.n3" . n3-mode)
		      '("\\.ttl" . n3-mode))
		auto-mode-alist)))
```

**Comment by jwiegley** [comment]
``` elisp
(use-package n3-mode
  :load-path "{path}/n3-mode.el"
  :mode (("\\.n3"  . n3-mode)
         ("\\.owl" . n3-mode))
  :config
  (add-hook 'n3-mode-hook 'turn-on-font-lock))
```

**Comment by arademaker** [comment]
nice! Thank you. I am assuming the ```load-path``` can be ignored if the packaged is installed from melpa, right?

**Comment by jwiegley** [comment]
I don't know, actually.
