### ISSUE TITLE
use-package should add to package-selected-packages

### ISSUE THREAD

**Issue by phillord** [jwiegley/use-package#327]
I add all of my packages with use-package. In Emacs-25, this means that if I use M-x package to update my packages, I get offered:

    Package menu: Operation finished.  31 packages are no longer needed, type ‘M-x package-autoremove’ to remove them

That is, none of my packages are needed. I think that `(use-package blah :ensure t)` should add `blah` to the `package-selected-packages` var if it exists.

**Comment by npostavs** [comment]
I think we just need to revert #314 (the second argument to `package-install` actually does the opposite of what is described in the commit message).

**Comment by phillord** [comment]
Yes, I think you are right, no second arg should DTRT.
