### ISSUE TITLE
`:mode` documentation may benefit from a change in wording

### ISSUE THREAD

**Issue by Trevoke** [jwiegley/use-package#328]
The explanation for `:mode` says it can accept a string, a cons cell, or a list. I figured a list meant, well, a lispy list, so I wrote `("\\.html$" "\\.mustache$")` which it turns out causes `abbrev` to break. After doing some research, I found out that someone had the same problem, which was how I was able to fix it.

I'm not really sure how to improve the wording, but I wanted to let you know it was ambiguous.

**Comment by jwiegley** [comment]
Will add these notes to #365.
