### ISSUE TITLE
Feature Request: Function to find use-package declaration

### ISSUE THREAD

**Issue by justbur** [jwiegley/use-package#329]
I think it would be really nice if there were a way to jump to the location of a use-package declaration for a given package. Not sure how difficult this is. Perhaps a list could record a marker position for each feature that is loaded with use-package? Thanks

**Comment by justbur** [comment]
Or if there were just a way to generate an alist of packages with markers that could be fed into a completing read function that would be great.

**Comment by jwiegley** [comment]
I could easily tag the package's symbol name with metadata identifying the file the use-package form came from.  I'm not so sure about identifying its file and line number.  I like this idea, though.

**Comment by justbur** [comment]
With the file, a simple regexp search should be enough. Having the marker
would be cool though.

**Comment by waymondo** [comment]
FWIW I have a personal solution for this in my `.emacs`. I have an `imenu` expression setup so I can quickly jump to any specific `use-package` declaration:

``` elisp
(defun use-package-imenu-elisp-expression ()
    (add-to-list 'imenu-generic-expression
                 '("packages" "^\\s-*(\\(use-package\\)\\s-+\\(\\(\\sw\\|\\s_\\)+\\)" 2)))
  (add-hook 'emacs-lisp-mode-hook #'use-package-imenu-elisp-expression)
```

I also have `ido-ubiquitous` and `imenu-anywhere` installed so I get a nice completing read from any `emacs-lisp-mode` file, but built-in `imenu` support might be cool since it is a native package.

**Comment by justbur** [comment]
imenu would be nice, but this feature would be much more useful to me if it
could open the file the declaration is in. I don't have them all in one
file.
