### ISSUE TITLE
bind-key.el - Add ###autoloads stanzas

### ISSUE THREAD

**Issue by jaalto** [jwiegley/use-package#33]
The bind-key seems not to have any  `;;;###autoload` [*]. Perhaps they could be added?

[*] 15.5 Autoload (GNU Emacs Lisp Reference Manual) http://www.gnu.org/software/emacs/manual/html_node/elisp/Autoload.html

**Comment by jwiegley** [comment]
Sure, this should be done for `use-package` also.

**Comment by npostavs** [comment]
Is there really any point to that? `use-package` and `bind-key` are meant to be used in the init file, so they will always be loaded on startup. `autoload`ing them first doesn't save anything.

**Comment by jwiegley** [comment]
It would mean the user doesn't need to explicitly load them to use them.
