### ISSUE TITLE
Should there be a :hook part to the macro?

### ISSUE THREAD

**Issue by Trevoke** [jwiegley/use-package#331]
Adding hooks is common enough; given that there is a `:mode` already, should there also be a `:hook` ?

**Comment by jwiegley** [comment]
I appreciate the suggestion, but the aim of `use-package` is not to replace Emacs Lisp as a language for configuring packages, but simply to abstract common patterns, and to make regularity and correct semantics easy to achieve.

A `:hook` keyword would require guessing which hook to add to, or it would need two arguments: the hook variable, and the function to add. Once we get to that level of verbosity, we're only a few characters less than calling `add-hook` within `:config`.  Further, what about multiple hooks, or adding lambdas to hooks, or adding to a local hook, etc.

I'd prefer to have that done in the `:config` block, where using `add-hook` is clear and has a well-known meaning.  The time to add a new `use-package` keyword is if there's some tricky bit of Lisp that's needed to do something well, and we want to save users from error prone repetition of such tricky bits throughout their configuration.
