### ISSUE TITLE
:bind doesn't see local keymaps before package has been loaded

### ISSUE THREAD

**Issue by vanzef** [jwiegley/use-package#332]
I'm trying to set up `god-mode` with :bind and :map keywords, here is a snippet:

```
(use-package god
  :bind (:map god-local-mode-map
              ("." . repeat)
              )
  :config (god-mode)
  )
```

So, at start emacs fails to load `init.el`, 'cause of `Symbol's value as variable is void: god-local-mode-map`, but if I load `god-mode` manually and them run `eval-buffer`, emacs reloads `init.el` correctly.

It is written in README.md that `slightly different from binding a key to a keymap, is binding a key within a local keymap that only exists after the package is loaded`, so I've decided that package loads first and only after that `:bind :map` "runs". Is it true and there is a bug in `use-package` (or `god-mode`) or I just use it in a wrong way?

**Comment by vanzef** [comment]
Also, `:bind` makes `flycheck` works strange: if following snippet is not commented, emacs loads `flycheck`, but it doesn't work, I even can not see it in mode line; if I load `flycheck` manually, emacs says that `flychek-mode` has been disabled, so I have to type `M-x flycheck-mode` twice to get `flycheck` works. Without `:bind` it works well.

```
  :bind (([f6] . flycheck-previous-error)
         ([f8] . flycheck-next-error))
```

**Comment by sooheon** [comment]
I am seeing the same behaviour, but only when my init.el is byte-compiled to init.elc. When I delete the elc file, use-package works properly. Declaring the map with `:defines` does not help for the byte-compiling case.

**Comment by jwiegley** [comment]
Try this: copy your `use-package` declaration, comment out the original, expand the macro into your init.el, then see whether the same bug occurs with the expanded version.  If it does, that removes `use-package` from the loop, and then we just have to see what's strange about the byte-compiled version of that lisp form.

**Comment by sooheon** [comment]
Without the .elc file, with original commented out and macroexanded, the problem persists.

Error I get: `Symbol's value as variable is void: evil-insert-state-map`

Original:

```
;; (use-package evil
;;   :bind (:map evil-insert-state-map
;;               ("C-w" . evil-delete-backward-word))
;;   :init (setq-default evil-want-C-u-scroll t
;;                 evil-want-fine-undo nil
;;                 evil-cross-lines t
;;                 evil-symbol-word-search t
;;                 evil-move-cursor-back nil
;;                 evil-want-C-i-jump t
;;                 evil-disable-insert-state-bindings t)
;;   :config (evil-mode 1))
```

Expanded:

```
(progn
  (unless
      (fboundp 'evil-delete-backward-word)
    (autoload #'evil-delete-backward-word "evil" nil t))
  (condition-case-unless-debug err
      (setq-default evil-want-C-u-scroll t evil-want-fine-undo nil evil-cross-lines t evil-symbol-word-search t evil-move-cursor-back nil evil-want-C-i-jump t evil-disable-insert-state-bindings t)
    (error
     (ignore
      (display-warning 'use-package
                       (format "%s %s: %s" "evil" ":init"
                               (error-message-string err))
                       :error))))
  (eval-after-load 'evil
    '(let
         ((now
           (current-time)))
       (message "%s..." "Configuring package evil")
       (prog1
           (progn
             (condition-case-unless-debug err
                 (evil-mode 1)
               (error
                (ignore
                 (display-warning 'use-package
                                  (format "%s %s: %s" "evil" ":config"
                                          (error-message-string err))
                                  :error))))
             t)
         (let
             ((elapsed
               (float-time
                (time-subtract
                 (current-time)
                 now))))
           (if
               (> elapsed 0.1)
               (message "%s...done (%.3fs)" "Configuring package evil" elapsed)
             (message "%s...done" "Configuring package evil"))))))
  (ignore
   (let*
       ((name "C-w")
        (key
         (if
             (vectorp name)
             name
           (read-kbd-macro name)))
        (kdesc
         (cons
          (if
              (stringp name)
              name
            (key-description name))
          'evil-insert-state-map))
        (binding
         (lookup-key
          (or evil-insert-state-map global-map)
          key)))
     (add-to-list 'personal-keybindings
                  (list kdesc 'evil-delete-backward-word
                        (unless
                            (numberp binding)
                          binding)))
     (define-key
       (or evil-insert-state-map global-map)
       key 'evil-delete-backward-word))))
```

**Comment by sooheon** [comment]
Ah! Worth mentioning, I'm on `GNU Emacs 25.0.94.1 (x86_64-apple-darwin15.5.0, NS appkit-1404.47 Version 10.11.5 (Build 15F31a)) of 2016-05-26`

**Comment by aslpavel** [comment]
It seems that I've found the source of issue here. My files are precompiled and have `:ensure t`, if package is not available during compilation it will produce this error. Once you recompile it with package installed ,this issue is gone.

**Comment by sooheon** [comment]
Whether a package is installed at time of compilation makes no difference for me.

**Comment by igorepst** [comment]
I have the same issue with `elisp-slime-nav-mode-map`, only when the code is byte-compiled, not using `:ensure` at all. However, I found a workaround: instead of `:defines`, use `:preface (defvar elisp-slime-nav-mode-map nil)`

**Comment by sooheon** [comment]
I have tried @igorepst's method, `:preface (defvar company-active-map nil)` and `:bind (:map company-active-map ...)`, and it doesn't work for me. company-active-map remains bound to nil, and the bindings i put in the :bind form appear to be bound to global map.

**Comment by igorepst** [comment]
Yep, this is something I didn't see until now - the bindings indeed are in global map. I actually tried to byte compile today only. Now whenever I press "tab", the company completion shows. Not good :)

**Comment by jwiegley** [comment]
This works now.
