### ISSUE TITLE
bind-keys with map, non-prefix keys, and :prefix binds prefix key globally

### ISSUE THREAD

**Issue by alphapapa** [jwiegley/use-package#334]
I'm not sure if this is a bug or intended behavior.  If it's the latter, I guess the docstring could use an adjustment, because it's not clear to me.  :)

When I run this code, the `y` key is bound globally, not just in `w3m-lnum-mode-map`.  As a result, I can't even type a `y` anywhere until I run `(bind-key "y" 'self-insert-command)`:

``` el
(bind-keys :map w3m-lnum-mode-map
           ("Y" . whole-line-or-region-kill-ring-save)
           :prefix "y"
           :prefix-map w3m-y-prefix-map
           ("y" . w3m-print-current-url)
           ("f" . w3m-lnum-print-this-url)
           ("t" . w3m-print-this-url))
```

But when I run this code, it works properly, binding `y` only in `w3m-lnum-mode-map`:

``` el
(bind-keys :map w3m-lnum-mode-map
           ;;("Y" . whole-line-or-region-kill-ring-save)
           :prefix "y"
           :prefix-map w3m-y-prefix-map
           ("y" . w3m-print-current-url)
           ("f" . w3m-lnum-print-this-url)
           ("t" . w3m-print-this-url))
```

The first example expands to:

``` el
(progn
  (bind-key "Y" 'whole-line-or-region-kill-ring-save w3m-lnum-mode-map nil)
  (defvar w3m-y-prefix-map)
  (define-prefix-command 'w3m-y-prefix-map)
  (bind-key "y" 'w3m-y-prefix-map nil nil)
  (bind-key "y" 'w3m-print-current-url w3m-y-prefix-map nil)
  (bind-key "f" 'w3m-lnum-print-this-url w3m-y-prefix-map nil)
  (bind-key "t" 'w3m-print-this-url w3m-y-prefix-map nil))
```

While the second example expands to:

``` el
(progn
  (defvar w3m-y-prefix-map)
  (define-prefix-command 'w3m-y-prefix-map)
  (bind-key "y" 'w3m-y-prefix-map w3m-lnum-mode-map nil)
  (bind-key "y" 'w3m-print-current-url w3m-y-prefix-map nil)
  (bind-key "f" 'w3m-lnum-print-this-url w3m-y-prefix-map nil)
  (bind-key "t" 'w3m-print-this-url w3m-y-prefix-map nil))
```

It seems like the first example follows the `(use-package ... :bind ((key . fn) :map (key . fn)))` pattern, and the help for `bind-keys` doesn't seem to prohibit it, but it doesn't work as expected.

Thanks for your help.

**Comment by jwiegley** [comment]
I can certainly believe this.  The argument handling code for `bind-keys` needs to be rewritten to properly normalize its input values, rather than relying on the hueristics that it does now.

**Comment by raxod502** [comment]
Just to clarify things, the current behavior is that each *group of keyword arguments* applies to every cons *until the next group of keyword arguments*. I'm not sure whether this makes sense or not. It's certainly different behavior than `use-package` keywords, but on the other hand the `use-package` semantics would not provide for any way to bind keys in different maps in the same `bind-keys` form (because only one `:map` could be specified). At the very least, the behavior should be documented—I might make a pull request for this depending on whether I have time and whether it's going to be changed soon.

**Comment by raxod502** [comment]
@jwiegley It looks like this change makes `:map` "sticky", i.e. its value persists until the next setting of `:map`. (Correct me if I'm wrong.) Can one reset the value to the global keymap by specifying `:map nil`?

**Comment by jwiegley** [comment]
Yes, `:map nil` or `:map global-map`.  Consider `:map` now as being scoped until the end of the arguments list, or until the next `:map`.

**Comment by raxod502** [comment]
Is `:map` the only "sticky" argument? And when you specify a `:map`, does that reset `:filter`, etc. to their default values?

And can this be documented?
