### ISSUE TITLE
:if with :ensure ensures unconditionally

### ISSUE THREAD

**Issue by fice-t** [jwiegley/use-package#335]
When using `:if` and `:ensure` together, I believe it shouldn't try to ensure that the package is loaded if the conditional is false. An example:

``` elisp
(use-package test
  :ensure t
  :if nil)
```

The above expands into the following, which tries to ensure the package is installed regardless of the `:if` statement:

``` elisp
(progn (progn (require (quote package)) (use-package-ensure-elpa (quote test))) (when (symbol-value (quote nil)) (if (not (require (quote test) nil (quote noerror))) (ignore (message (format "Cannot load %s" (quote test)))))))
```

**Comment by jwiegley** [comment]
Ensure is handled before `:if` is considered.  This can be changed by customizing `use-package-keywords`.
