### ISSUE TITLE
bind-key.el - Unsafe package (not using unique prefix for symbols)

### ISSUE THREAD

**Issue by jaalto** [jwiegley/use-package#34]
It appears that this package is not safe to install as it does not use customary `PREFIX-*` for all symbols. The names may clash existing or future definitions in Emacs; or user's own definitions.

Would it be possible to prefix all with `bind-key-*` to make it clear that these symbols are defined in `bind-key.el` package?

    $ grep def bind-key.el

    (defgroup bind-key nil
    (defcustom bind-key-segregation-regexp
    (defvar override-global-map (make-keymap)
    (define-minor-mode override-global-mode
    (defvar personal-keybindings nil)
    (defmacro bind-key (key-name command &optional keymap)
	   (define-key (or ,keymap global-map) ,keyvar ,command))))
    (defmacro unbind-key (key-name &optional keymap)
    (defmacro bind-key* (key-name command)
	 (define-key override-global-map ,(read-kbd-macro key-name) ,command)))
    (defun get-binding-description (elem)
    (defun compare-keybindings (l r)
    (defun describe-personal-keybindings ()

**Comment by jwiegley** [comment]
I prefer for `unbind-key` to remain global, unless someone can come up with a better and equally memorable name.
