### ISSUE TITLE
:ensure implies :defer ?

### ISSUE THREAD

**Issue by xuchunyang** [jwiegley/use-package#346]
Since `package.el` already does the setup (autload commands, adjust auto-mode-alist, etc) for me.  I have the following in my init.el

``` el
(use-package ipretty             :ensure t :defer t)
(use-package pcache              :ensure t :defer t)
(use-package persistent-soft     :ensure t :defer t)
(use-package log4e               :ensure t :defer t)
(use-package alert               :ensure t :defer t)
(use-package bug-hunter          :ensure t :defer t)
(use-package nginx-mode          :ensure t :defer t)
```

**Comment by thomasf** [comment]
No, `:ensure` does not imply `:defer`..  It's probably not a good idea to modify that behavior now since it will break some peoples emacs init's

**Comment by xuchunyang** [comment]
> It's probably not a good idea to modify that behavior now since it will break some peoples Emacs init's.

Don't have to change the current behavior, adding a new user option for this is sufficient, or maybe someone knows some workaround without modifying use-package's codebase at all ?

**Comment by raxod502** [comment]
Why not just set `use-package-always-ensure` and `use-package-always-defer`?
