### ISSUE TITLE
Putting parens around a single string in :mode breaks forward-word globally

### ISSUE THREAD

**Issue by bilts** [jwiegley/use-package#348]
This works as expected:

``` elisp
(use-package scss-mode
  :mode ("\\.scss\\'" "\\.css\\'"))
```

This works as expected:

``` elisp
(use-package scss-mode
  :mode "\\.scss\\'")
```

This causes global errors when doing any operation that relies on word boundaries (`forward-word`, `kill-word`, etc):

``` elisp
(use-package scss-mode
  :mode ("\\.scss\\'"))
```

After evaluating that form, every time I do a kill-word, I get this:

`kill-word: Symbol's function definition is void: nil`

I'm not extremely familiar with elisp, but I don't see why the last one is invalid, and it took forever to track this down.

**Comment by npostavs** [comment]
> I don't see why the last one is invalid, and it took forever to track this down.

The `:mode` parameter also accepts parameters like `:mode ("\\.py\\'" . python-mode)` and `("\\.scss\\'")` is an alternate syntax for `("\\.scss\\'" . nil)`. But since `nil` can never be a mode function, it would make sense to treat this specially.

**Comment by npostavs** [comment]
> But since nil can never be a mode function, it would make sense to treat this specially.

See #348.
