### ISSUE TITLE
Defer load symbols when requested

### ISSUE THREAD

**Issue by magicdirac** [jwiegley/use-package#351]
Currently we have :commands to defer load commands, 
is it possible defer load symbols so that when I need them load the file.

The reason I come up with this is sometimes I want to change themes but I do not want load the theme file until I use load-theme to load them. However, load-theme itself mostly can not find the themes unless you initialize them. I was wondering can we define a autoload of symbols in use-package, so that load-theme knows where to load them.

**Comment by Trevoke** [comment]
I am in a similar situation. Currently the best solution is to not use `use-package` for themes. It's not a *huge* deal but it's a little annoying.

**Comment by npostavs** [comment]
Can't you do something like 
```elisp
(use-package the-theme 
  :init (add-to-list 'custom-theme-load-path "path/to/the-theme") 
  :defer t)
```

**Comment by jwiegley** [comment]
How would it ever know to load `the-theme` though?  There is no autoload here, nor any trigger.  Or is that a feature of theme support?

**Comment by npostavs** [comment]
OP said:

> I do not want load the theme file until I use load-theme to load them.

**Comment by jwiegley** [comment]
@npostavs Thanks for reminding me. :)

**Comment by jwiegley** [comment]
@magicdirac How would you write such deferral without `use-package`?

**Comment by jwiegley** [comment]
I need more information to address this bug.  Please reopen with an example of the form that doesn't work now, what you expected to do, and how you solved it without `use-package`.  Perhaps special theme support is necessary, but I don't know yet.
