### ISSUE TITLE
:ensure is installing package but not adding it in package-selected-packages

### ISSUE THREAD

**Issue by thierryvolpiatto** [jwiegley/use-package#353]
Hi,

Using `:ensure` should assume user wants to install this package directly and not as dependency.

So when using `(use-package foo :ensure t)`, package foo should be added to
`package-selected-package` when emacs version is emacs-25+.

I didn't look at the code in use-package, but I guess you are using directly `package-install`, so after checking if `package-selected-packages` is bound you can use the MARK-SELECTED argument of `package-install`: `(package-install PKG &optional MARK-SELECTED)`.

**Comment by npostavs** [comment]
We've gone over this before: #314, #327, #336.

You seem to be using a non-standard version of `package.el`, here is describe-function of `package-install` in Emacs 25.0.94 (as you can see, the 2nd arg has the opposite sense from yours)

```
package-install is an interactive autoloaded compiled Lisp function in
‘package.el’.

(package-install PKG &optional DONT-SELECT)

Install the package PKG.
PKG can be a package-desc or a symbol naming one of the available packages
in an archive in ‘package-archives’.  Interactively, prompt for its name.

If called interactively or if DONT-SELECT nil, add PKG to
‘package-selected-packages’.

If PKG is a package-desc and it is already installed, don’t try
to install it but still mark it as selected.
```

**Comment by thierryvolpiatto** [comment]
Noam Postavsky <notifications@github.com> writes:

> We've gone over this before: #314, #327, #336.
>
> You seem to be using a non-standard version of package.el, here is
> describe-function of package-install in Emacs 25.0.94 (as you can see,
> the 2nd arg has the opposite sense from yours)

Ah! Ok I see, I will upgrade my version.

Thanks and sorry for the noise.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Ok, works fine now after having changed meaning of package-install 2nd arg.

Thanks.
