### ISSUE TITLE
Should :demand and :after play nice with each other?

### ISSUE THREAD

**Issue by angrybacon** [jwiegley/use-package#357]
``` elisp
(setq-default use-package-always-defer t)
(use-package anzu :demand t)
(use-package spaceline :demand t :after anzu)
```

I still get `spaceline` loaded first. Is there a way to have `spaceline` loaded after `anzu`?

I would prefer not having to do nested `use-package`s and/or use `req-package`.

**Comment by angrybacon** [comment]
I originally tried to load `spaceline` after `anzu` as advised here https://github.com/TheBB/spaceline#anzu. There seem to be a way to inhibit default behavior and have `anzu` stop injecting itself in the mode-line (resulting in having duplicates): `(setaq-default anzu-cons-mode-line-p nil)`.

I'm still interested in how both :after and :demand should work together though.

**Comment by npostavs** [comment]
> I still get spaceline loaded first.

I don't see how that's possible, since the forms you wrote expand into
```elisp
(if
    (not
     (require 'anzu nil 't))
    (ignore
     (message
      (format "Cannot load %s" 'anzu))))
(progn
  (progn
    (eval-after-load 'anzu
      '(require 'spaceline)))
  (if
      (not
       (require 'spaceline nil 't))
      (ignore
       (message
	(format "Cannot load %s" 'spaceline)))))
```

clearly `anzu` is `require`d first.

**Comment by angrybacon** [comment]
Oops, the order is swapped. I indeed have `anzu` defined after `spaceline`.

**Comment by npostavs** [comment]
So would dropping the `:demand t` from `spaceline` do what you want?

```elisp
(setq-default use-package-always-defer t)
(use-package spaceline :after anzu)
(use-package anzu :demand t)
```

**Comment by angrybacon** [comment]
Not exactly, I need `spaceline` loaded as soon as possible (so it doesn't
look weird when starting up Emacs). In other words, I was looking for some
kind of hierarchy amongst :demand`ed packages. I feel this is exactly what
`req-package` is for though.
