### ISSUE TITLE
use-package.el - Lint warnings

### ISSUE THREAD

**Issue by jaalto** [jwiegley/use-package#36]
FYI, The following warnings are displayed for the *.el file:

    *** Lint Emacs 24.3.1 2013-06-25 13:37:25 file: use-package.el

    ** Lint M-x lm-verify (list-mnt.el)
    Missing: ;; Maintainer:
    Missing: ;; URL:
    Missing: ;;; History:

    ** Lint M-x checkdoc-current-buffer (checkdoc.el)
    use-package.el:305: First sentence should end with punctuation
    use-package.el:310: All variables and subroutines might as well have a documentation string
    use-package.el:326: All variables and subroutines might as well have a documentation string
    use-package.el:359: Argument `form' should appear (as FORM) in the doc string
    use-package.el:388: All variables and subroutines might as well have a documentation string
    use-package.el:392: Argument `name' should appear (as NAME) in the doc string

**Comment by jwiegley** [comment]
Mostly fixed.  I don't care enough about checkdoc, but I'll accept PRs.
