### ISSUE TITLE
:ensure t doesn't appear to actually ensure packages are installed

### ISSUE THREAD

**Issue by mcandre** [jwiegley/use-package#362]
.emacs:

```
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/")
             '("marmalade" . "http://marmalade-repo.org/packages/"))
(when (< emacs-major-version 24)
  ;; For important compatibility libraries like cl-lib
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
(package-initialize)

(eval-when-compile
  (require 'use-package))

(use-package apache-mode
  :ensure t)
```

However, when I `emacs ~/.htaccess`, the file opens in Fundamental mode, and the apache-mode function is undefined.

System:

* GNU Emacs 24.5.1 via Homebrew
* Homebrew 0.9.9 (git revision 11d47; last commit 2016-06-08)
* Mac OS 10.11.5 El Capitan

**Comment by mcandre** [comment]
Update: The problem seems to have been related to saving+compiling this change to my live .emacs file while using my older .emacs settings. When I launch a new Emacs instance and save+compile, then everything works.

**Comment by npostavs** [comment]
> ```
> (add-to-list 'package-archives
>              '("melpa" . "https://melpa.org/packages/")
>              '("marmalade" . "http://marmalade-repo.org/packages/"))
> ```

FYI, `add-to-list` doesn't work like that, you have to make 1 call per item to add.

**Comment by mcandre** [comment]
👍 yeah, my package repo syntax was way off
