### ISSUE TITLE
use-package evaluates :init before package is installed

### ISSUE THREAD

**Issue by mcandre** [jwiegley/use-package#363]
I want use-package to ensure yafolding is installed, but in practice, Emacs complains of an undefined term, `yafolding-mode`, if yafolding hasn't been installed yet.

.emacs:

```
(require 'package)
(setq package-archives
      '(("melpa" . "https://melpa.org/packages/")
        ("marmalade" . "https://marmalade-repo.org/packages/")
        ("gnu" . "https://elpa.gnu.org/packages/")))
(package-initialize)

(eval-when-compile
  (require 'use-package))
(require 'diminish)
(require 'bind-key)
(setq use-package-always-ensure t)

(use-package yafolding
  :bind ("M-]" . yafolding-toggle-element)
  :init
  (dolist (hook '(prog-mode-hook
                  conf-mode-hook
                  groovy-mode-hook
                  text-mode-hook
                  html-erb-mode-hook
                  nxml-mode-hook))
    (add-hook hook 'yafolding-mode)))
```

Workaround:

We can work around this by protecting the hook additions with a check that the yafolding-mode is defined:

```
(use-package yafolding
  :bind ("M-]" . yafolding-toggle-element)
  :init
  (if (fboundp 'yafolding-mode)
      (dolist (hook '(prog-mode-hook
                      conf-mode-hook
                      groovy-mode-hook
                      text-mode-hook
                      html-erb-mode-hook
                      nxml-mode-hook))
        (add-hook hook 'yafolding-mode))))
```

But ideally, `:init` would not be evaluated unless the package is, in fact, installed.

**Comment by npostavs** [comment]
There was some discussion about this in #306, but it was inconclusive.

@jwiegley wrote these 2 comments that seem contradictory to me:

https://github.com/jwiegley/use-package/issues/306#issuecomment-171535916
> I think we need to add a new check outside the entire use-package declaration, to check whether the library is loadable. This was always an intention, I'm not sure why we lost this ability.

https://github.com/jwiegley/use-package/issues/306#issuecomment-189074717
> The role of :init is that it should work when the package is unloaded; therefore, it should also work if the package doesn't exist. Wanting the code to not execute at all if the package doesn't exist is a new feature that was never part of the semantics before.

**Comment by stevenspasbo** [comment]
From what I understand, `:init` is run when emacs is started before any packages are loaded, so you shouldn't be referencing any symbols that requires the package to be loaded unless you declare it first. For example, in my `flycheck` configuration I have:

    (use-package flycheck
      :ensure
      :commands (global-flycheck-mode)
      :init
      (add-hook 'after-init-hook #'global-flycheck-mode)
      :config
      ; everything else

**Comment by DamienCassou** [comment]
I have the same kind of problem. I want Emacs to install packages from `package-selected-packages` using `package-install-selected-packages`. However, I have plenty of `:init` sections just like @stevenspasbo shows which will break my configuration until the package is installed. I see myself adding `:if (package-installed-p '<package-name>)` to many `use-package` declarations.

**Comment by stevenspasbo** [comment]
I've just about completely rewritten my emacs config since that last comment. For flycheck now I just have:

    (use-package flycheck
      :ensure
      :config
      (global-flycheck-mode
      ;; other config stuff`

However, it shouldn't be throwing errors in the init as long as variables and functions are declared beforehand. I took a look at your init.el and have a few suggestions for refactoring.

Before:

    (use-package ace-link
      :ensure t
      :init
      (progn
        (ace-link-setup-default)))

After:

    (use-package ace-link
      :ensure t
      :config
      (ace-link-setup-default))

Before:

    (use-package flycheck
      :ensure t
      :diminish flycheck-mode
      :init
      (progn
        (add-hook 'emacs-lisp-mode-hook #'flycheck-mode)
        (use-package flycheck-cask
          :ensure t
          :init
          (progn
            (add-hook 'flycheck-mode-hook #'flycheck-cask-setup)))))

After:

    (use-package flycheck
      :ensure t
      :diminish flycheck-mode
      :commands flycheck-mode
      :init
      (add-hook 'emacs-lisp-mode-hook #'flycheck-mode))

    (use-package flycheck-cask
      :ensure t
      :after flycheck
      :config
      (flycheck-cask-setup))

Before:

    (use-package discover
      :ensure t
      :init
      (progn
        (global-discover-mode 1)))

After:

    (use-package discover
      :ensure t
      :config
      (global-discover-mode 1))

Those should allow use-package to download the package before attempting to load them. `:init` should be used to configure variables that the package will rely on, not variables that the package defines. Here's an example from my config where I make use of `:init`:

    (use-package spaceline-config
      :ensure spaceline
      :commands (spaceline-spacemacs-theme spaceline-emacs-theme spaceline-helm-mode)
      :init
      ;; Displays arrows incorrectly if not set
      (setq ns-use-srgb-colorspace nil) ;; defined in C source code.
      :config
      (setq powerline-default-separator 'wave))

**Comment by DamienCassou** [comment]
@stevenspasbo Thank you very much for your help. I understand better how things work now. I started refactoring my init file (and [commited the results](https://github.com/DamienCassou/emacs.d/blob/master/init.el)), but I don't understand why `dired` is loaded very early:

```
Loading /nix/store/d8xd54zhqx059s25qg5fxwcz8mjbf5hy-emacs-25.1/share/emacs/site-lisp/site-start.el (source)...done
Loading elec-pair...done
Loading subword...done
Loading recentf...done
Loading paren...done
Loading winner...done
Loading /home/cassou/.emacs.d/recentf...done
Loading package undo-tree...
Configuring package undo-tree...done (0.001s)
Loading package undo-tree...done (0.015s)
Configuring package dired...done (0.000s)
Configuring package recentf...done (0.000s)
```

Is there a way to understand why a package is loaded?

**Comment by thomasf** [comment]
IIRC you can see the log of what's loading what in the `load-history` variable
