### ISSUE TITLE
use-package doesnot load the builded packages 

### ISSUE THREAD

**Issue by ReichKV** [jwiegley/use-package#364]
Hey,

Very often i see that people use the use-package to load the builded local packages. For example:
Instead of (require 'dired-aux) they write (use-package dired-aux). When i use such command use-package tries to download it from melpa, doesnot find it and fail to load the package.  Could you help me to fix it?

**Comment by thomasf** [comment]
It should not happen if you don't use `use-package-always-ensure`

**Comment by ReichKV** [comment]
Thank you , i forgot i put this in my init file
