### ISSUE TITLE
Create a Texinfo doc page for use-package

### ISSUE THREAD

**Issue by jtecca** [jwiegley/use-package#365]
I usually have to refer back to the README page for the documentation on a keyword feature that I haven't used in a long time, but I think it would be useful to have a texinfo document for a quick lookup.  

If you're willing to accept a PR, I could attempt to convert the README markdown into a texinfo doc (probably via pandoc and some manual cleanup).  I'm not sure of how to best handle setting the Info-default-directory-list variable in order to pick up the new info doc, but I could look into this.

**Comment by priyadarshan** [comment]
That would be such a good addition. I rely mainly on Emacs' Info system, and having `use-package` docs listed there would be really excellent.

**Comment by jwiegley** [comment]
This now becomes very important, if `use-package` is to be included as part of Emacs.

**Comment by jtecca** [comment]
I know this has been a long time, but I started working on this a while ago.  I converted the README into a texdoc format via pandoc, but the default conversion leaves a lot to be desired.

I looked at some of the info pages bundled with emacs, but it looks like there is a lot of extra metadata in those files than what pandoc would include in the conversion.

Does anyone know of any documentation for writing Info docs for emacs?  Maybe there's already a package out there for converting existing files?

**Comment by jwiegley** [comment]
The documentation has begun, see `use-package.org`.

**Comment by Nek** [comment]
http://use-package.org is down. Is it intentional?

**Comment by jwiegley** [comment]
I meant the file of that name within the project.

**Comment by Nek** [comment]
@jwiegley it was stupid of me :/
@nickmccurdy thanks!

**Comment by nickmccurdy** [comment]
No worries, I was confused by it too
