### ISSUE TITLE
:map and a fresh new keymap

### ISSUE THREAD

**Issue by habamax** [jwiegley/use-package#366]
Is it possible to bind a key to a yet nonexistent keymap?

Smth like this:

```
(use-package multiple-cursors
  :bind (("M-n" . mc/mark-next-like-this)
         ("M-p" . mc/mark-previous-like-this)
         ("M-N" . mc/unmark-next-like-this)
         ("M-P" . mc/unmark-previous-like-this)
         :map haba/mc-map
         ("m" . mc/mark-all-like-this-dwim)
         ("i" . mc/insert-numbers))
         ;; ("C-x m d" . mc/mark-all-like-this-dwim)
         ;; ("C-x m i" . mc/insert-numbers))
  :init
  (define-prefix-command 'haba/mc-map)
  (define-key ctl-x-map "m" 'haba/mc-map))
```

**Comment by habamax** [comment]
I have found bind-keymap (there are no example usage but)

It look like I can get what I want by using:


    (use-package multiple-cursors
      :bind-keymap (("C-x m" . haba/mc-map))
      :bind (("M-n" . mc/mark-next-like-this)
             ("M-p" . mc/mark-previous-like-this)
             ("M-N" . mc/unmark-next-like-this)
             ("M-P" . mc/unmark-previous-like-this)
             :map haba/mc-map
             ("m" . mc/mark-all-like-this-dwim)
             ("i" . mc/insert-numbers))
      :init
      (define-prefix-command 'haba/mc-map)
      (define-key ctl-x-map "m" 'haba/mc-map))

Is this correct usage of bind-keymap?

**Comment by jwiegley** [comment]
Yes, bind-keymap is for establishing a binding to a keymap that won't exist
until the package is loaded, which lets you load on demand when you use that
keymap.

**Comment by iNode** [comment]
Can we have it in the examples in the README.md file?

**Comment by jwiegley** [comment]
This should be documented as part of #365
