### ISSUE TITLE
Suppress interactivity?

### ISSUE THREAD

**Issue by treyharris** [jwiegley/use-package#373]
I run Emacs in `--daemon` mode, which works great except when for some reason, a package starts up and asks a question (usually having to do with prior crashing state or some such). Then the daemon just sits there forever, never progressing since it has no user to talk to.

When I find cases like this, I'm left doing something like

``` elisp
  (use-package desktop
  :init
  (progn
    (defadvice desktop-restore-file-buffer
        (around my-desktop-restore-file-buffer-advice)
      "Be non-interactive while starting a daemon."
      (if (and (daemonp)
               (not server-process))
          (let ((noninteractive t))
            ad-do-it)
        ad-do-it))
    (ad-activate 'desktop-restore-file-buffer))
```

I've been trying to figure out a way to generalize this; and it feels like a `:nointeract` keyword taking a function that may go interactive should be possible, given what use-package does for some of the other keywords, but I'm not a good enough Elisp metaprogrammer to make this work myself.

But I'd imagine an interface like this:

``` elisp
(defcustom use-package-nointeract-behavior t
  "What the `:nointeract DEFUN' feature should do.

If `t', suppress interaction if Emacs is run noninteractively. If
`always', suppress interaction, even when Emacs is run
interactively. If `nil', do not change interactive behavior (that
is, ignore the keyword). Note that this feature is always ignored
when running under `--debug-init'."
  ;; ....
  )

;; and then:
(use-package noisy
  :nointeract (noisy-interactive-function noisy-other-function))
```

**Comment by npostavs** [comment]
See also: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=13697

**Comment by treyharris** [comment]
Hey @npostavs, seeing [that link](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=13697):
> This bug report was last modified 3 years and 183 days ago.

There was never a reply, and looking at the `yes-or-no-p` source, doesn't look like any action was ever taken to address this. So I'm not sure what you're saying by posting that link?

**Comment by npostavs** [comment]
> There was never a reply, and looking at the yes-or-no-p source, doesn't look like any action was ever taken to address this. So I'm not sure what you're saying by posting that link?

That bug seems very related to this issue, and I think that if there is ever any action taken to address this issue, then the solution could very well be relevant to that bug as also (and vice versa).

**Comment by jwiegley** [comment]
Since this sort of feature can be implemented externally to core use-package (and it's not something I would be able to maintain, since this is not my use case), I'm going to close this issue here, and recommend you look at `use-package-keywords`.
