### ISSUE TITLE
How to add exceptions to bind-key*?

### ISSUE THREAD

**Issue by QiangF** [jwiegley/use-package#374]
The `bind-key*' form override all minor modes that may also bind the same key,
What should I do if I don't want to override all minor modes? I mean how to
unbind that key for a particular minor mode or in the minibuffer.
Thank you!

**Comment by djl** [comment]
I'd like this feature (or something like it), too.

My use case is that I want a set of generic "default" keybindings that get overridden by more specific keys for certain minor modes.

Example:

    ;; my default keys
    (bind-key* "C-c C-c" #'djl/clipboard-copy)
    (bind-key* "C-c C-v" #'djl/clipboard-paste)

    ;; calc-mode specific copy/pasting
    (use-package calc-mode
      :bind (:map calc-mode-map
                  ("C-c C-c" . djl/calc-copy-to-clipboard)
                  ("C-c C-v" . djl/calc-yank-clipboard)))

**Comment by QiangF** [comment]
What do you mean by "Currently functions need to be mode-aware"? Does your function djl/clipboard-copy have an exception for calc-mode?

**Comment by djl** [comment]
Yep, exactly. `djl/clipboard-copy` will do different things depending on the current mode(s). The same thing happens with the equivalent cut/paste functions (and a few other functions).

**Comment by npostavs** [comment]
Try the `PREDICATE` argument:

```elisp
(bind-key* "C-c C-c" #'djl/clipboard-copy (not (eq major-mode 'calc-mode)))
```

**Comment by djl** [comment]
That's what I meant by "every `bind-key*` needs to have every exception accounted for". This is really just moving the exceptions from inside the function to the `bind-key*` call :(

**Comment by npostavs** [comment]
Oh, then I don't understand what kind of interface you want? If you have some exceptions, it seems like they would have to be written down somewhere...

**Comment by djl** [comment]
Sorry. I suck at explaining myself.

Using my example code:

    ;; my default keys
    (bind-key* "C-c C-c" #'djl/clipboard-copy)
    (bind-key* "C-c C-v" #'djl/clipboard-paste)
    
    ;; calc-mode specific copy/pasting
    (use-package calc-mode
      :bind (:map calc-mode-map
                  ("C-c C-c" . djl/calc-copy-to-clipboard)
                  ("C-c C-v" . djl/calc-yank-clipboard)))


Intuitively I'd expect the calc-mode bindings, having been created *after* `bind-key*`, would take precedence.

Right now to accomplish this I have to add a new predicate to the original `bind-key*` call before calling `bind-key*` again for the specific mode I want to change.

Having to update two different places in my code when I want to override a single binding seems...odd?

If that's the only way to do it, though, it's not a big deal :)

**Comment by npostavs** [comment]
The point of `bind-key*` is to override all mode bindings. `bind-key` is for stuff you want to get overridden by modes. Perhaps you want something in the middle?

Although depending on the order of binding calls seems kind of icky to me.

**Comment by djl** [comment]
Something in the middle would be ideal.

`bind-key*` is great for overriding keys on all modes, giving the user a personal keymap to build on. Being able to override it again seems natural to me. Maybe I just want something outside of the scope of `bind-key`?

> Although depending on the order of binding calls seems kind of icky to me.

I think I'm misunderstanding something. How would relying on the order of the binding calls be different from how `bind-key` currently works? With multiple calls calls to `bind-key`, the last one wins:

    (bind-key "C-c a" #'(lambda () (interactive) (message "first")))
    (bind-key "C-c a" #'(lambda () (interactive) (message "second")))
    # pressing C-c a results in "second"

**Comment by npostavs** [comment]
So if there was a `bind-key*M` that would only override major mode maps, and not minor modes, would that fit your use case?

> How would relying on the order of the binding calls be different from how `bind-key` currently works? With multiple calls calls to `bind-key`, the last one wins:

Right, so I would avoid making multiple calls to `bind-key` binding the same key, i.e., I would avoid relying on this property.

**Comment by djl** [comment]
> So if there was a `bind-key*M` that would only override major mode maps, and not minor modes, would that fit your use case?

Ah, yeah! That would cover 90% of my `bind-key` usage.

**Comment by npostavs** [comment]
So I think that could be implemented by

```elisp
(defvar override-global-minor-map (make-keymap)
  "`override-global-mode' keymap for `minor-mode-map-alist'.
Should override only major modes.")
(add-to-list 'minor-mode-map-alist
             `(override-global-mode . ,override-global-minor-map)
             'append)
```

and then you could use `(bind-key "C-c C-c" #'djl/clipboard-copy override-global-minor-map)`.

**Comment by djl** [comment]
That doesn't appear to work but I'm probably using it incorrectly. I have this in my `init.el`:

    (bind-key "C-c C-c" #'djl/clipboard-copy override-global-minor-map)
    (bind-key "C-c C-v" #'djl/clipboard-paste override-global-minor-map)

    # C-c C-c is still bound to djl/clipboard-copy
    (use-package calc-mode
      :bind (:map override-global-minor-map
                  ("C-c C-c" . calc-copy-to-clipboard)
                  ("C-c C-v" . calc-yank-clipboard)))

    # doesn't work either
    (use-package calc-mode
      :bind (:map calc-mode
                  ("C-c C-c" . calc-copy-to-clipboard)
                  ("C-c C-v" . calc-yank-clipboard)))

Is this wrong?

**Comment by npostavs** [comment]
Oh, `calc-mode` is a major mode, so my suggestion can't work. Try this instead:

```elisp
(defvar override+-global-map (make-keymap)
  "Takes precedence over `override-global-map'.")
(add-to-list 'emulation-mode-map-alists
             `(override+-global-mode . ,override-global-minor-map))
```

and then

```elisp
(bind-key* "C-c C-c" #'djl/clipboard-copy)
;;...
(bind-key "C-c C-c" #'djl/calc-copy-to-clipboard override+-global-mode
          (eq major-mode 'calc-mode))
```

**Comment by djl** [comment]
That doesn't work either. The original `bind-key*` still takes precedence over the later `bind-key` :(

**Comment by npostavs** [comment]
I'm sorry, I had a bunch of mistakes in that. That's what I get for posting code without testing. This should work (I verified that it binds `C-c C-c` to `djl/clipboard-copy` in `*scratch*`, and to `djl/calc-copy-to-clipboard` in `*Calculator*`).

```elisp
(defvar override+-global-map (make-sparse-keymap)
  "Takes precedence over `override-global-map'.")
(add-to-list 'emulation-mode-map-alists
             `((override-global-mode . ,override+-global-map)))
```

```elisp
(bind-key* "C-c C-c" #'djl/clipboard-copy)
;;...
(bind-key "C-c C-c" #'djl/calc-copy-to-clipboard override+-global-map
          (eq major-mode 'calc-mode))
```

**Comment by djl** [comment]
That's almost perfect now but there's an issue with binding the same keys multiple times in different modes - the last called `(bind-key)` wins. nnExample:

    ;; This key is ignored
    (bind-key "C-c C-c" #'djl/calc-copy-to-clipboard override+-global-map
              (eq major-mode 'calc-mode))

    ;; Only this key is still bound
    (bind-key "C-c C-c" #'djl/calculator-copy-to-clipboard override+-global-map
              (eq major-mode 'calculator-mode))


I suppose this makes given that their both bound to the same keymap. I'll need to figure out a way around this.

Thanks for the help so far!

**Comment by npostavs** [comment]
> That's almost perfect now but there's an issue with binding the same keys multiple times in different modes - the last called (bind-key) wins. An example

Hmm, right. That's no good. How about this:

```elisp
(defvar bind-key-override-mode-alist nil)
(add-to-list 'emulation-mode-map-alists 'bind-key-override-mode-alist)

(defmacro bind-key-in-mode (key-name command mode)
  (let ((override-map (intern (concat "bind-key-override-" (symbol-name mode) "-map"))))
    `(progn (defvar ,override-map)
            (unless (boundp ',override-map)
              (setq ,override-map (make-sparse-keymap))
              (push `(override-global-mode . ,,override-map)
                    bind-key-override-mode-alist))
            (bind-key ,key-name ,command ,override-map (eq major-mode ',mode)))))

(bind-key* "C-c C-c" #'djl/clipboard-copy)
;;...
(bind-key-in-mode "C-c C-c" #'djl/calc-copy-to-clipboard calc-mode)
(bind-key-in-mode "C-c C-c" #'djl/calculator-copy-to-clipboard calculator-mode)
```

**Comment by djl** [comment]
Perfect! That's exactly what I needed. Thanks again!
