### ISSUE TITLE
How to use package's keymaps in its default configuration

### ISSUE THREAD

**Issue by liuxueyang** [jwiegley/use-package#377]
For eg. ace-jump-mode. I install it like this:

```
(use-package ace-jump-mode
  :bind ("C-." . ace-jump-mode))
```

Obviously, I can use `C-.' to run `ace-jump-mode'. But I can not use its keymaps in its default configuration such as: 

* “C-c SPC” ⇒ ace-jump-word-mode
* “C-u C-u C-c SPC” ⇒ ace-jump-line-mode

in its wiki [ace-jump-mode](https://www.emacswiki.org/emacs/AceJump)

**Comment by npostavs** [comment]
AFAICT, "default configuration" would mean
```elisp
(use-package ace-jump-mode
  :bind ("C-c SPC" . ace-jump-mode))
```

**Comment by liuxueyang** [comment]
@npostavs I was stupid... Thanks you so much. 👍
