### ISSUE TITLE
Use eval-after-load for :bind (:map ...)

### ISSUE THREAD

**Issue by tarsius** [jwiegley/use-package#378]
I tried adding this to my init file:

``` lisp
(use-package magit-mode
  :defer t
  :bind (:map magit-mode-map
              ("f" . magit-pull-and-fetch-popup)
              ("F" . nil)))
```

which expands to:

``` lisp
(progn
  (unless
      (fboundp 'magit-pull-and-fetch-popup)
    (autoload
      (function magit-pull-and-fetch-popup)
      "magit-mode" nil t))
  (ignore
   (progn
     (bind-key "f" 'magit-pull-and-fetch-popup magit-mode-map nil)
     (bind-key "F" 'nil magit-mode-map nil))))
```

and results in this warning:

```
Symbol's value as variable is void: magit-mode-map
```

Have a nice day!

**Comment by jwiegley** [comment]
Hi @tarsius, this is a known deficiency of `:bind` at the moment.  For this to work, you'd need to avoid deferring the load of `magit`.  I do want to see this fixed, however.

**Comment by tarsius** [comment]
Okay, thanks for the info.

**Comment by jyp** [comment]
Personally I'm using `:bind` ... `:map` and I'm *relying* on the bindings not being in `eval-after-load`. If `eval-after-load` is the intended behaviour, what am I supposed to do to bind into an arbitrary, pre-existing keymap?

**Comment by tarsius** [comment]
@jyp It probably doesn't matter for you usecase. From `eval-after-load`s doc-string:

> Arrange that if FILE is loaded, FORM will be run immediately afterwards. **If FILE is already loaded, evaluate FORM right now.**

**Comment by npostavs** [comment]
> It probably doesn't matter for you usecase. From `eval-after-loads doc-string`:
>> If FILE is already loaded, evaluate FORM right now.

I don't think that helps, consider 
```elisp
(use-package foo
  :defer t
  :bind (:map ctl-x-map
              ("f" . foo-command)))
```

**Comment by tarsius** [comment]
Hm, you are right. Simply removing `(if (boundp map) bindings` isn't right, it should be replaced with something smarter. If the keymap is bound, then we should additionally check whether it is defined by the package in question I suppose. But things might get hairy because it might be defined in any library belonging to the package or even another third-party package ...

**Comment by tarsius** [comment]
Well, since it's hard to know until run-time, why not just wait until run-time before deciding? If added a squash commit to do that to my pr.
