### ISSUE TITLE
Either :ensure or set :load-path depending on existence of package checkout

### ISSUE THREAD

**Issue by tsdh** [jwiegley/use-package#380]
I just started to restructure my `~/.emacs` using `use-package`, and it's really nice especially that you can automatically bootstrap your fully configured emacs just from your init file on new machines.  But there's one question which I can't answer myself.

I'm maintainer of several emacs packages, e.g., `highlight-parentheses`.  That means that on my DEV machine, I want to run it straight from the git checkout whereas on every other machine, I want to use the MELPA package instead.

I can obviously do it like that:

``` elisp
(if (file-exists-p "~/Repos/el/highlight-parentheses.el/")
    ;; Use my checkout on my dev machine
    (use-package highlight-parentheses
      :load-path "~/Repos/el/highlight-parentheses.el/"
      ...)
  ;; Get the ELPA package anywhere else
  (use-package highlight-parentheses
    :ensure t
    ...))
```

But then I have to duplicate the complete config, bindings, etc (the `...` above).

I'm pretty sure I can write some macro which does such a directory existence test and emits a `use-package` form with either `:ensure t` or `:load-path ...` but since I guess that's a common problem many of us are facing, there's probably some built-in solution already.  Is there?

**Comment by tsdh** [comment]
Well, for the time being, I've just written a simple macro which does the job.  Here it is:

```elisp
(defmacro th/use-package-or-checkout (checkout-dir pkg &rest plist)
  "Use package PKG with :load-path if CHECKOUT-DIR exists, else :ensure it."
  (let ((copy (cl-copy-list plist)))
    (while copy
      (when (memq (car copy) '(:ensure :load-path))
        (error "Macro th/use-package-or-checkout must not be used with %s" (car copy)))
      (setq copy (cddr copy))))
  (let ((ensure-or-load-path (if (file-directory-p checkout-dir)
                                 `(:load-path ,checkout-dir)
                               '(:ensure t))))
    `(use-package ,pkg
       ,@ensure-or-load-path
       ,@plist)))
```

**Comment by waymondo** [comment]
This is pretty cool. I have a similar setup for my `.emacs.d` for some packages I maintain and use. I'll probably try a modified version of this macro wrapper in my personal setup. I know @jwiegley is usually hesitant to add more keywords to `use-package` at this point, but if this use case is common to more setups, perhaps there is a cleaner way to add native support for this.

**Comment by npostavs** [comment]
Similar discussion in #190.

**Comment by tsdh** [comment]
Indeed, pretty much the same discussion except that I don't use the "global ensure option". Well, for the time being, I can easily live with my macro. But maybe use-package could do the same in case both :ensure and :load-path are given. I don't see anything that would speak against that because in case a package is installed via ELPA, the load path will be set automatically, so :load-path would not have a use.

**Comment by waymondo** [comment]
Yeah that might be the easiest way to support it: if both `:load-path` and `:ensure` are supplied, `:load-path` is used if the directory exists, otherwise `:ensure` is used. Can anyone think of any complications that might cause?

**Comment by waymondo** [comment]
This is now quite elegant after @raxod502's introduction of
`use-package-defaults` so I thought I’d share my new solution. Here's
a quick recap of my situation: 

I dedicate the folder `~/.emacs.d/lib/` for packages I actively
maintain and hack on. This folder is gitignored from my `~/.emacs.d/` repo,
since each package’s subfolder is its own repo. If I don’t have a
local `lib` version of a package downloaded, I want to fallback to the behavior of
`:ensure t`. Here's how you can do it by setting up a default handler for `:load-path`:

``` emacs-lisp
(eval-and-compile
  (defun local-package-load-path (name)
    (concat user-emacs-directory (format "lib/%s" (symbol-name name)))))

(setf (alist-get :load-path use-package-defaults)
      '((list (local-package-load-path name))
        (file-directory-p (local-package-load-path name))))

(use-package some-package-that-will-prefer-local-if-available
  :ensure t)
```

**Comment by raxod502** [comment]
I also was annoyed to no end by this problem. My approach was to write a new package manager to replace `package.el`, namely [`straight.el`](https://github.com/raxod502/straight.el), which draws recipes from MELPA but clones the original repos and runs the Elisp straight from the repositories. That way there is no difference between using packages from MELPA and actively developing packages—you use the same repository.

Unfortunately it's not yet stable (although I use it in my config), but it seems relevant to this issue so I thought I would mention it.

**Comment by raxod502** [comment]
Although there hasn't been an official release yet, I would say that [`straight.el`](https://github.com/raxod502/straight.el) is finally ready for use by other people. It has documentation, too. I'd recommend it as the best solution to this problem (why bother sometimes running from MELPA and sometimes from Git checkout, if you can always run straight from the source?).

**Comment by jwiegley** [comment]
@raxod502 Your `straight.el` docs are some of the most impressive I've ever seen. Would you be interested in writing a new `use-package` manual? :)

**Comment by raxod502** [comment]
It's something I have considered, yes. However, before doing that I would need to resolve a number of conceptual questions I have about the current implementation—for example, deferred installation needs to play nice with byte-compilation. I am currently experimenting with different approaches for handling this in [`with-feature`](https://github.com/raxod502/with-feature). The eventual outcome of that experiment will either be a new package which fixes these problems, or contributions to `use-package` which fix those problems. In the former case, the new package would have excellent documentation; in the latter case, I will hopefully be able to contribute similarly to `use-package`.

**Comment by bkhl** [comment]
> This is now quite elegant after @raxod502's introduction of `use-package-defaults` so I thought I’d share my new solution. Here's a quick recap of my situation:
> 
> I dedicate the folder `~/.emacs.d/lib/` for packages I actively maintain and hack on. This folder is gitignored from my `~/.emacs.d/` repo, since each package’s subfolder is its own repo. If I don’t have a local `lib` version of a package downloaded, I want to fallback to the behavior of `:ensure t`. Here's how you can do it by setting up a default handler for `:load-path`:
> 
> ```emacs-lisp
> (eval-and-compile
>   (defun local-package-load-path (name)
>     (concat user-emacs-directory (format "lib/%s" (symbol-name name)))))
> 
> (setf (alist-get :load-path use-package-defaults)
>       '((list (local-package-load-path name))
>         (file-directory-p (local-package-load-path name))))
> 
> (use-package some-package-that-will-prefer-local-if-available
>   :ensure t)
> ```

I needed to do almost exactly this but this snippet isn't working for me. It says `name` is undefined. Are you still using something like this and in that case what should it look like today?
