### ISSUE TITLE
Incompatible with Emacs 25

### ISSUE THREAD

**Issue by seagle0128** [jwiegley/use-package#383]
I am using Emacs 25.1 RC2 on Windows 7. When I install new packages with use-package and :ensure, new packages will added into init.el or .emacs automatically.
My question is: is there any method to disable this behavior? Thanks!

**Comment by thomasf** [comment]
What do you mean by "added into init.el"?  Package sources are not added into init.el, please show an example of what you mean.,

**Comment by fice-t** [comment]
If you mean that the variable `package-selected-packages` is forcibly copied to your init/custom file, then add this to your init file, right after your `(require 'package)`:

```elisp
(defun package--save-selected-packages (&optional value)
  "Set and save `package-selected-packages' to VALUE."
  (when value
    (setq package-selected-packages value))
  (unless after-init-time
    (add-hook 'after-init-hook #'package--save-selected-packages)))
```

The above just removes the `customize-save-variable` call. Hopefully this behaviour will be optional in future Emacs versions.

**Comment by seagle0128** [comment]
@fice-t Thanks! That's what I want. 
Close it.

**Comment by brontitall** [comment]
I realise this issue is closed, so I'm not sure how much good this comment will bring, but Emacs 25.1 has learned a new argument to `package-install`:

```
(package-install PKG &optional DONT-SELECT)
[...]
If called interactively or if DONT-SELECT nil, add PKG to
‘package-selected-packages’.
```

It would be nice if `use-package` could (perhaps optionally) use that argument, since it would avoid overriding emacs-supplied functions

**Comment by fice-t** [comment]
> It would be nice if use-package could (perhaps optionally) use that argument, since it would avoid overriding emacs-supplied functions

That wouldn't help for other cases such as `list-packages` that also automatically save the variable. The problem should be fixed on Emacs' end.

Though what could be a good idea is using that `DONT-SELECT` argument and have another `use-package` variable that unconditionally adds (but doesn't save it!) each package to `package-selected-packages` (instead of just when installing).
