### ISSUE TITLE
way to specify explict versions of packages

### ISSUE THREAD

**Issue by cburroughs** [jwiegley/use-package#386]
For those limited [1] repositories that support it I'd like to be able to pin to an explicit version, but just a repository.

[1] https://emacs.stackexchange.com/questions/14263/how-to-install-a-specific-version-of-package

**Comment by npostavs** [comment]
`package-pinned-packages` already exists. What are you asking for?

**Comment by cburroughs** [comment]
My understanding is that `package-pinned-packages` can pin to specific *archives*.  I am looking to pin to *versions*.

**Comment by npostavs** [comment]
Oh, you're right, I was mislead by the name. It seems impractical to implement this in use-package without implementing it package.el first though.

**Comment by jwiegley** [comment]
@npostavs Since I don't use or support the `package.el` integration, such changes will have to be submitted as PR, provided they have a copyright assignment on file.

**Comment by raxod502** [comment]
If you need more control over package installation, you probably want to use something like [`quelpa`](https://github.com/quelpa/quelpa) (with [`quelpa-use-package`](https://github.com/quelpa/quelpa-use-package)) or (when it becomes stable) [`straight.el`](https://github.com/raxod502/straight.el).
