### ISSUE TITLE
Make :disabled conditional, like :if, or change examples

### ISSUE THREAD

**Issue by bburns** [jwiegley/use-package#387]
From the example given in the README it would seem as if you could pass a value to the :disabled keyword, as with :if - 

> The :disabled keyword can turn off a module you're having difficulties with, or stop loading something you're not using at the present time:
> 
> (use-package ess-site
>   :disabled t
>   :commands R)

But the value is ignored - e.g. 

```
(use-package nonexistentpackagename
  :disabled nil)
```

evaluates with no error - all you actually need is the :disabled keyword.

So could it be made conditional like :if, or maybe the examples changed to reflect its actual implementation better? ie

> (use-package ess-site
>   :disabled
>   :commands R)

Thanks!

**Comment by jwiegley** [comment]
I like this suggestion.

**Comment by jwiegley** [comment]
`:disabled` ignores its value, if any is given.
