### ISSUE TITLE
Error when setting use-package-always-ensure to non-nil value

### ISSUE THREAD

**Issue by CSRaghunandan** [jwiegley/use-package#388]
Okay, this is weird.
I set `use-package-always-ensure` to `t` and I got errors with these built-in packages :- `dired`, `dired-x` and `elisp-mode`. For some reason use-package append a `-` after the package name and I got errors like so :- `error: Package dired- is unavailable` (after emacs tried to check in the available package repos : melpa, elpa, org)

Is this a bug ? It was easy to fix this by using `:ensure nil` for them packages. But reporting this just in case someone else runs into this problem.

**Comment by npostavs** [comment]
See also:

- http://emacs.stackexchange.com/questions/26810/why-doesnt-use-package-dired-work-for-me
- #364

**Comment by CSRaghunandan** [comment]
Ah now I get it why `use-package` failed for `dired` while it worked for other built-in packages. Thanks for the info. 

On a side note, how would I know a particular built-in package is non-`package.el` so that I can add `:ensure nil` to the `use-package` declarations before running into an error like this ?

**Comment by npostavs** [comment]
> On a side note, how would I know a particular built-in package is non-`package.el`

If `package-builtin-p` says `nil`.
```elisp
(package-built-in-p 'dired) ;=> nil
(package-built-in-p 'org) ;=> (org . [nil nil "Outline-based notes management and organizer"])
```

**Comment by CSRaghunandan** [comment]
wonderful. Thanks for the info. 
Closing the issue.
