### ISSUE TITLE
New installed packages are not added to package-selected-packages

### ISSUE THREAD

**Issue by thepreacher** [jwiegley/use-package#397]
Packages installed as part of the initial emacs setup are rightly added to `package-selected -packages`. However any subsequent package that I add is not added to `package-seleected-packages`. Therefore `packages-autoremove`, suggests to remove those packages. 

My work around at the moment is to delete the elpa folder and install everything afresh.

I have the following at the botton of the init.el file

```
  ;; Custome.el file location
  (setq custom-file (expand-file-name "custom-settings.el" user-emacs-directory))
  (load custom-file t)

  (provide 'init)
```

**Comment by cs-miller** [comment]
having the same problem.  sometimes packages are added to package-selected-packages, other times they are not, for no discernible reason.

**Comment by dgchurchill** [comment]
I had this issue. Moving the `(setq custom-file ...) (load custom-file)` statements to the top of my init file (i.e. before any `use-package` calls with `ensure`) fixed this for me and seems to work ok. The problem appears to be that if the package is installed before the custom-file location is set then the new value of `package-selected-packages` isn't saved, and then the value is lost when the custom file is loaded.

**Comment by notuntoward** [comment]
I'm not using the variable `custom-file `(it's set to nil) yet I also find that some packages installed by `use-package` don't make it into `package-selected-packages`.

**Comment by ArneBab** [comment]
I also see package-autoremove trying to remove packages installed with (use-package PKG :ensure t).
