### ISSUE TITLE
Interpretation of keyword args not sufficiently documented

### ISSUE THREAD

**Issue by dabrahams** [jwiegley/use-package#403]
Hi John!

For example, I read
```
:mode - form to be added to auto-mode-alist
```

So I wrote:
```lisp
:mode ("\\.\\(text\\|md\\|mkdn?\\|mmd\\|markdown\\)\\'" . markdown-mode))
```

Looked good to me, but it actually requires an alist:
```lisp
:mode (("\\.\\(text\\|md\\|mkdn?\\|mmd\\|markdown\\)\\'" . markdown-mode)))
```

And there are no examples of how to use `:mode` in any of the docs.  I know I've run into this before with other keywords. Please go through the docs for all of these keywords and root out these kinds of ambiguities!

Thanks,
Dave

**Comment by npostavs** [comment]
Both
```elisp
(use-package markdown
  :mode ("\\.\\(text\\|md\\|mkdn?\\|mmd\\|markdown\\)\\'" . markdown-mode))
```

and
```elisp
(use-package markdown
  :mode (("\\.\\(text\\|md\\|mkdn?\\|mmd\\|markdown\\)\\'" . markdown-mode)))
```

Expand to 
```elisp
(progn
  (unless
      (fboundp 'markdown-mode)
    (autoload #'markdown-mode "markdown" nil t))
  (ignore
   (add-to-list 'auto-mode-alist
		'("\\.\\(text\\|md\\|mkdn?\\|mmd\\|markdown\\)\\'" . markdown-mode))))
```

**Comment by dabrahams** [comment]
Well, the first way didn't appear to work for me, so it must have been a different problem I was observing (I had also quoted the `markdown` argument.  And this proves my point, actually: not having a clear description of what is allowed and what isn't, and how it's interpreted, allowed me to go down an unproductive alley trying to change something that had no real effect, and then report a bug, which wasted *your* time too!

**Comment by Silex** [comment]
There is this example in the README here https://github.com/jwiegley/use-package#modes-and-interpreters :

``` elisp
;; The package is "python" but the mode is "python-mode":
(use-package python
  :mode ("\\.py\\'" . python-mode)
  :interpreter ("python" . python-mode))
```

I agree examples are not real documentation tho.

**Comment by dabrahams** [comment]
The README is, AFAIK, not part of the installed package.  I looked in the docstrings and in the source file, where I know there to be some docs not in docstrings.

**Comment by npostavs** [comment]
Well the source [does say](https://github.com/jwiegley/use-package/blob/2.3/use-package.el#L38):
> `;; Please see README.md from the same repository for documentation.` 

(this was done in #78)

**Comment by dabrahams** [comment]
@npostavs If you feel that's truly sufficient, you should close  this bug.  Otherwise, what are we arguing about?

**Comment by npostavs** [comment]
I didn't think we were arguing, I just wanted to point out that the lack of detail in the source commentary is intentional. So if we decide to put the info back into the source, it should be seen as changing the old decision, not just a "bugfix".

**Comment by jwiegley** [comment]
The documentation is primarily in the README because this is what the new generation sees when they browse to the "Home Page" URL from MELPA, for example, which directs them to GitHub.  Having it in the source is somewhat cumbersome because it requires a different style of formatting, and it would be annoying to maintain two nearly identical documents.

Now, if I could get "pandoc" to format the README as an elisp comment, and then automatically update the content of `use-package.el` whenever it changes, that would be doable...

**Comment by dabrahams** [comment]
I'd turn the reader into an info document. As long as something gets installed with the package, I'll consider the problem handled

**Comment by jwiegley** [comment]
Well, that's actually the best answer on two counts: We could generate an HTML file easily from it; and we'll want Texinfo at some point anyway, once `use-package` becomes part of the Emacs distribution.  Thanks for the suggestion, Dave!

**Comment by jwiegley** [comment]
The docs will be rewritten for #365, which is also a requirement for upcoming inclusion into Emacs.

**Comment by jwiegley** [comment]
I'm going to close this issue, but will fulfill the request in the solution #365.
