### ISSUE TITLE
Prevent dependency from being loaded

### ISSUE THREAD

**Issue by quicknir** [jwiegley/use-package#404]
Hello,

I'd like to use `use-package` to load a package, while blocking its dependencies. Example: the `json-mode` package still has a dependency on `json-reformat`, even though that package has been incorporated into emacs. I'd like to get json-mode but prevent its `(require json-reformat)` from having any effect. Is this possible?

**Comment by npostavs** [comment]
> I'd like to get json-mode but prevent its `(require json-reformat)` from having any effect.

If you do `(provide 'json-reformat)` then the subsequent `(require 'json-reformat)` calls will do nothing. I think this will result in a broken `json-mode` though, https://github.com/gongo/json-reformat#important says

> From emacs 24.4 , `json-pretty-print` and `json-pretty-print-buffer` (similar specifications as `json-reformat-region`) was bundled.

That is, *equivalent* functions were incorporated into Emacs, but `json-mode` still calls the `json-reformat-region`. See also https://github.com/joshwnj/json-mode/issues/43

**Comment by quicknir** [comment]
@npostavs I noticed you also answered my magit question in the gitter a few days ago... thanks, you're a helpful guy/gal!

It seems like `json-mode` only uses `json-reformat` in its function `json-mode-beautify`. So my plan was just to unbind that function and instead bind pretty print. I will give `provide` a shot, thanks!
