### ISSUE TITLE
Can use-package load from git?

### ISSUE THREAD

**Issue by cswarth** [jwiegley/use-package#410]
Sorry to post support questions as issues but I did not see this addressed in the  README.
Is there any way to have use-package load a package from a git release or compressed tar file, e.g. [magit-2.8.0.tar.gz](https://github.com/magit/magit/releases/download/2.8.0/magit-2.8.0.tar.gz), the [magit 2.8.0 release](https://github.com/magit/magit/releases/tag/2.8.0)?

If not from git, will use-package detect when I have manually installed a package in my ~/.emacs.d directory and not load it again?  Or does use-package only know when packages are loaded by the package manager?

**Comment by Silex** [comment]
You have several options:

- use https://github.com/quelpa/quelpa to install the package that way use-package is used like for a normal `package-install` package
- untar the package yourself and play with `:load-path`

**Comment by vyp** [comment]
also see https://github.com/quelpa/quelpa-use-package

**Comment by Silex** [comment]
@vyp: ooooh, shiny

I'm not far from switching to quelpa!

**Comment by raxod502** [comment]
`quelpa-use-package` is great, you can keep using `use-package` like normal, and then when you want to install from source you just add `:quelpa t` to the relevant `use-package` form. Or `:quelpa (cool-package :fetcher github :repo ...)`.

**Comment by jwiegley** [comment]
This is rather beyond the purview of use-package, but there are extensions that might allow it, as mentioned.

**Comment by idanko** [comment]
If you use straight.el as a package manager, you can achieve what requested by something like:
```lisp
(use-package counsel-fzf-rg
  :straight '(counsel-fzf-rg
              :type git
              :host github
              :repo "idanko/counsel-fzf-rg.el")
  :config
  (defun counsel-fzf-rg:org ()
    (interactive)
    (counsel-fzf-rg "" org-directory))
  :bind (("C-c n f". counsel-fzf-rg:org)))
```
