### ISSUE TITLE
Loading a package after another one which doesn't provide itself

### ISSUE THREAD

**Issue by DamienCassou** [jwiegley/use-package#411]
I would like `use-package` to load [`anzu`](http://stable.melpa.org/#/anzu) only when `isearch` is loaded. I tried:

```emacs
(use-package anzu
  :after (isearch)
  :diminish anzu-mode
  :bind (("M-%" . anzu-query-replace)
         ("C-M-%" . anzu-query-replace-regexp))
  :config
  (progn
    (global-anzu-mode +1)
    (define-key isearch-mode-map [remap isearch-query-replace] #'anzu-isearch-query-replace)
    (define-key isearch-mode-map [remap isearch-query-replace-regexp] #'anzu-isearch-query-replace-regexp)))
```

but it doesn't work and I guess that's because `isearch` doesn't have any `(provide 'isearch)` line (I've just sent a patch to `bug-gnu-emacs`). Is there any solution from `use-package`?

**Comment by npostavs** [comment]
> I would like use-package to load anzu only when isearch is loaded. I tried:

`isearch` is preloaded, so "only when isearch is loaded" means always.
