### ISSUE TITLE
Installed packages are not added to package-selected-packages

### ISSUE THREAD

**Issue by thepreacher** [jwiegley/use-package#414]
When I perform a fresh install of my dot emacs config. All the packages that already exist in the config are installed and correctly added to `package-selected-packages`. However if I add new package(s) to my config and restart emacs say, the packages are installed but no entrie(s) are added to `package-selected-packages`. Therefore when I do `package-autoremove`, it lists all those subsequent package as not needed. 

I'm on emacs HEAD.

I refer to this issue [https://github.com/jwiegley/use-package/issues/353](url) which proposes a fix for the problem. However frankly I don't understand the solution. Something to do with using a non-standard version of package.el. Another link on that issue suggests that a commit has been added to use-package to fix the issue.

I'll appreciate the solution being made clearer to me. Thanks.

**Comment by npostavs** [comment]
The person who opened #353 had a version of package.el which didn't add to `package-selected-packages` when doing `(package-install <foo>)` was called, but did add when doing `(package-install <foo> t)`. This is opposite of how the package.el in current Emacs works.

I don't know exactly which versions this happened in, perhaps sometime in the 25.0.50 series. Assuming your emacs version is recent, you should not have this problem.

**Comment by thepreacher** [comment]
Thanks for the response. I'm using emacs HEAD which at the moment shows the major version as 26. Does it matter the location of the custom-file variable? Below is an excerpt of my init.el file:

```
;;----------------------------------------------------------------------------
;; Bootstrap config
;;----------------------------------------------------------------------------
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))
;(require 'init-utils)
;; Calls (package-initialize)
(require 'init-elpa)      ;; Machinery for installing required packages

;; Bootstrap `use-package'
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(eval-when-compile
  (require 'use-package))
(require 'diminish)
(require 'bind-key)

(require 'init-exec-path) ;; Set up $PATH
```

Thanks.

**Comment by npostavs** [comment]
I think that should work fine. Perhaps you can try setting a breakpoint in `package-install` to see why it's not changing `package-selected-packages`.

**Comment by thepreacher** [comment]
I'm closing this issue at the moment. In the mean time I downloaded and tried the personal emacs of some of the emacs big hitters who use `use-package` . Again all the initial packages that installed as part of the setup were added to `package-selected-packages`. As such package-autoremove brought up nothing. Then I added `use-package beacon :ensure t`. The package is installed alrigt but now `package-autoremove` brings it up a candidate for removal. I'ts begining to look to me as something local, because I can't imagine that such acomplished emacs users will put up with a problem like that if they also encountered it.

**Comment by npostavs** [comment]
> I can't imagine that such acomplished emacs users will put up with a problem like that if they also encountered it.

I wouldn't go that far. The `package-autoremove` feature is somewhat new, it's possible not that many people are making heavy use of it yet.
