### ISSUE TITLE
expansion of macros

### ISSUE THREAD

**Issue by holgerschurig** [jwiegley/use-package#416]
Hi,

I have a (simplified) use-package form like this:

     (use-package foo
        :if (not noninteractive)
        :config
        (defhydra ...))

The idea is that neither foo nor hydra should be pulled in if I run emacs with `--batch`. Unfortunately, this does only halfways work. Turns out that I always have hydra loaded (because `defhydra` macro) and also always powerline (because of `defpowerline` macro). Those macros are marked as autoload, so something always loads them, even when the `:if` clause evaluates to false.

I then tried to use `:disabled noninteractive`. The good news: now the `:config` form doesn't seem macro-expanded and hydra/powerline doesn't load. The bad news: the issue 387 hasn't been implemented so foo won't be loaded in any case.

(I'm on use-package 20161031.1025)

**Comment by jwiegley** [comment]
This is what it should be expanding to:

``` lisp
(when
    (not noninteractive)
  (require 'foo nil 'nil)
  (defhydra nil)
  t)
```

You're saying that the mere presence of the `defhydra` form causes hydra to be loaded?  Note that this is how it *must* be, unlike `:disabled` which compiles the code above to just `nil`.

**Comment by jwiegley** [comment]
@holgerschurig Note too that `use-package` declarations are normal Lisp, so you can do things like:

``` elisp
(unless noninteractive
  (use-package foo
    :config
    (defhydra ...))
```
