### ISSUE TITLE
installing auctex with use-package

### ISSUE THREAD

**Issue by DrWaleedAYousef** [jwiegley/use-package#417]
I use the (setq       use-package-always-ensure t). Then,
(use-package auctex)

gives me the following compilation error (although it compiles well using list-packages)

Debugger entered--Lisp error: (error "Required feature ‘auctex’ was not provided")
  #<subr require>(auctex nil t)
  funcall(#<subr require> auctex nil t)
  (with-no-warnings (funcall ad--addoit-function feature filename noerror))
  (setq ad-return-value (with-no-warnings (funcall ad--addoit-function feature filename noerror)))
  (prog1 (setq ad-return-value (with-no-warnings (funcall ad--addoit-function feature filename noerror))) (benchmark-init/end-measure parent should-record-p))
  (let ((parent (benchmark-init/begin-measure name (quote require)))) (prog1 (setq ad-return-value (with-no-warnings (funcall ad--addoit-function feature filename noerror))) (benchmark-init/end-measure parent should-record-p)))
  (benchmark-init/measure-around name (quote require) (setq ad-return-value (with-no-warnings (funcall ad--addoit-function feature filename noerror))) should-record-p)
  (let* ((name (symbol-name feature)) (already-loaded (memq feature features)) (should-record-p (lambda nil (and (not already-loaded) (memq feature features))))) (benchmark-init/measure-around name (quote require) (setq ad-return-value (with-no-warnings (funcall ad--addoit-function feature filename noerror))) should-record-p))
  (let (ad-return-value) (let* ((name (symbol-name feature)) (already-loaded (memq feature features)) (should-record-p (lambda nil (and (not already-loaded) (memq feature features))))) (benchmark-init/measure-around name (quote require) (setq ad-return-value (with-no-warnings (funcall ad--addoit-function feature filename noerror))) should-record-p)) ad-return-value)
  ad-Advice-require(#<subr require> auctex nil t)
  apply(ad-Advice-require #<subr require> (auctex nil t))
  require(auctex nil t)
  (not (require (quote auctex) nil (quote t)))
  (if (not (require (quote auctex) nil (quote t))) (ignore (message (format "Cannot load %s" (quote auctex)))))
  (progn (progn (require (quote package)) (use-package-ensure-elpa (quote auctex))) (if (not (require (quote auctex) nil (quote t))) (ignore (message (format "Cannot load %s" (quote auctex))))))
  eval((progn (progn (require (quote package)) (use-package-ensure-elpa (quote auctex))) (if (not (require (quote auctex) nil (quote t))) (ignore (message (format "Cannot load %s" (quote auctex)))))) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)

**Comment by DrWaleedAYousef** [comment]
Thanks so much, I found it; I just used:

(use-package auctex
  :defer t
  :ensure t)

Thanks

**Comment by jwiegley** [comment]
Note that this is a bit of a hack: It's using `use-package` to trigger a package installation, but then it never actually does anything.  I'm saying it's bad to do this, just that it's a little bit odd.

The problem is that the package name by which you install auctex, and the package name by which you load it (`tex-site` or just `tex`, depending), are different things.

In general, a `use-package` form that does nothing but `:defer t` is always suspicious.

**Comment by DrWaleedAYousef** [comment]
So what do you suggest? I am using LaTeX?

**Comment by jwiegley** [comment]
AucTeX and LaTeX are fine, you'd just need a more complex `use-package` statement to really integrate it well.  But if what you have works for you, that's all you need.

**Comment by shawkinaw** [comment]
@jwiegley Following on to your comment about defer:

> In general, a `use-package` form that does nothing but `:defer t` is always suspicious.

I have been reorganizing my `.emacs` file to use `use-package`, and have found it to be great. But I find myself needing to do lots of what you recommend against, e.g.

    (use-package swift-mode
      :defer t)

If I don't do that, all the packages load at startup and my startup time sucks. But I don't need to include `:mode` or any other such thing, because the package already does that. What are you thoughts?

**Comment by jwiegley** [comment]
Well, the thing is, you `swift-mode` declaration isn't doing anything.  It says: defer configuration until the module is loaded... but there's no configuration.  So it's has the same informational content as a comment saying that you're using `swift-mode`.

**Comment by shawkinaw** [comment]
Ah, interesting. I suppose I should have mentioned that I have `use-package-always-ensure` set, so that the line does make sure that the mode has been installed.
