### ISSUE TITLE
Use-Package with smex

### ISSUE THREAD

**Issue by sdban** [jwiegley/use-package#421]
Here is a MWE

<pre><code> 
(use-package smex

    :init (smex-initialize)
    :bind ("M-x"  .  smex))
</pre></code>

On starting I get a warning:
<pre><code>
Symbol's value as variable is void: personal-keybindings
</pre></code> 

With <code> --debug-init </code> option I get : 
<pre><code>
Debugger entered--Lisp error: (void-variable personal-keybindings)
add-to-list(personal-keybindings (("M-x") smex execute-extended-command))
</pre></code> 

However,  the following configuration works flawlessly: 
<pre><code> 
(use-package smex

:init (smex-initialize))

(setq smex-save-file "~/.emacs.d/smex-items")

(setq smex-history-length 3000)

(global-set-key (kbd "M-x") 'smex)

(global-set-key (kbd "M-X") 'smex-major-mode-commands)

;; Our old M-x :-
(global-set-key (kbd "C-c C-c M-x")  'execute-extended-command)

</pre></code>

I am using emacs-26.0.50.2

 *I am not 100% sure if this is a smex-issue or a use-package issue. I have seen smex used with use-package, for example [here](https://github.com/howardabrams/dot-files/blob/master/emacs.org).<sup>1</sup>*

<sup>1</sup> I think the  code for <code> : bind </code>  in that example might be slightly off.

**Comment by npostavs** [comment]
Do you compile your init file?

**Comment by sdban** [comment]
Yes. I  byte compile a file and then use load-file to load that byte compiled file in the init file.

**Comment by npostavs** [comment]
The problem is that `bind-key` is autoloaded but `personal-keybindings` is not. `bind-key` is macro, so when you compile it doesn't show up in the elc, and doesn't trigger the loading.

**Comment by sdban** [comment]
Thank you! Than explains the problem I have been having!

**Comment by npostavs** [comment]
Just for the record, putting `(require 'bind-key)` in init.el should make it work both compiled and uncompiled.

**Comment by sdban** [comment]
Thank You!
