### ISSUE TITLE
inode of init.el changes after use-package downloads any package

### ISSUE THREAD

**Issue by dmalyuta** [jwiegley/use-package#422]
Here are the first few lines of my `init.el` (found [here](https://github.com/dmalyuta/dotfiles/blob/master/.emacs.d/init.el)):
```
;; Top priority
(setq backup-by-copying t) ;; make sure Emacs doesn't break hard links (before doing anything else)
(setq make-backup-files nil) ;; stop creating backup ~ files

;; MELPA
(require 'package)
(setq package-enable-at-startup nil)
(setq package-check-signature nil)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(package-initialize)

;; boostrap 'use-package'
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(eval-when-compile
  (require 'use-package))
```

The rest of `init.el` uses use-package to auto-download and configure all the packages that I use. The huge problem is that whenever a package is missing and use-package accordingly downloads it, the inode of `init.el` changes - thus, if it was hard linked to another file, **this hard link is broken**.

## Example situation

Suppose Emacs is closed. I open terminal and run:
```
$ ls -i ~/.emacs.d/init.el
421954 /home/danylo/.emacs.d/init.el
```
So `421954` is the inode of the `init.el` file prior to doing anything. Now I purposefully delete the zenburn theme package from my `~/.emacs.d/elpa` folder and start Emacs. In the minibuffer I can see use-package download the theme from Melpa. Once use-package has done its thing, I go into the `*Messages*` buffer and at the very end I see the following two lines (among other output):
```
Saving file /home/danylo/.emacs.d/init.el...
Wrote /home/danylo/.emacs.d/init.el [2 times]
```
So for some reason, after use-package ran there is a save operation for `init.el` **which seems to happen automatically** (I didn't do anything apart from start Emacs). The terrible thing is that now:
```
$ ls -i ~/.emacs.d/init.el
421957 /home/danylo/.emacs.d/init.el
```
The inode has changed to `421957`! The hard link has been broken! Even when there is no hard link, the inode still changes... despite my effort to fix this in the first three lines of my `init.el` (shown above already):
```
;; Top priority
(setq backup-by-copying t) ;; make sure Emacs doesn't break hard links (before doing anything else)
(setq make-backup-files nil) ;; stop creating backup ~ files
```
Note that the hard link is *not* broken when I manually modify `init.el` and save it with C-x C-s. Somehow something different is going on in the save operation which, I suppose, use-package triggers after downloading any missing packages.

I really would like to see this fixed soon because a recent event has forced me to resort to hard linking my `~/.emacs.d/init.el` file to a file in another directory - and I cannot do this reliably so long as use-package breaks the hard link.

**Comment by npostavs** [comment]
> So for some reason, after use-package ran there is a save operation for init.el which seems to happen automatically

That seems odd, can you try putting `(setq debug-on-message "\\(Wrote\\|Saving\\).*init\\.el")` at the top of your init file and posting the backtrace?

**Comment by dmalyuta** [comment]
## use-package backtrace
Here is the backtrace you requested, in the case where use-package auto-downloads the missing Zenburn theme package (or any other package...), followed by these weird `init.el` one save and two write operations that change the inode:
```
Debugger entered--Lisp error: "Saving file /home/danylo/.emacs.d/init.el..."
  message("Saving file %s..." "/home/danylo/.emacs.d/init.el")
  save-buffer()
  custom-save-all()
  customize-save-variable(package-selected-packages (realgud zenburn-theme yaml-mode wgrep-helm use-package srefactor pdf-tools nyan-mode multiple-cursors mic-paren helm-swoop helm-projectile helm-gtags google-c-style flycheck-irony dired+ company-irony-c-headers company-irony auctex))
  package--save-selected-packages()
  run-hooks(after-init-hook delayed-warnings-hook)
  command-line()
  normal-top-level()
```
continue
```
Debugger entered--Lisp error: "Wrote /home/danylo/.emacs.d/init.el"
  write-region(nil nil "/home/danylo/.emacs.d/tmp3114nRs" nil "/home/danylo/.emacs.d/init.el" "~/.emacs.d/init.el" excl)
  basic-save-buffer-2()
  basic-save-buffer-1()
  basic-save-buffer(nil)
  save-buffer()
  custom-save-all()
  customize-save-variable(package-selected-packages (realgud zenburn-theme yaml-mode wgrep-helm use-package srefactor pdf-tools nyan-mode multiple-cursors mic-paren helm-swoop helm-projectile helm-gtags google-c-style flycheck-irony dired+ company-irony-c-headers company-irony auctex))
  package--save-selected-packages()
  run-hooks(after-init-hook delayed-warnings-hook)
  command-line()
  normal-top-level()
```
continue
```
Debugger entered--Lisp error: "Wrote /home/danylo/.emacs.d/init.el"
  write-region(nil nil "/home/danylo/.emacs.d/init.el" nil t "~/.emacs.d/init.el")
  basic-save-buffer-2()
  basic-save-buffer-1()
  basic-save-buffer(nil)
  save-buffer()
  custom-save-all()
  customize-save-variable(package-selected-packages (realgud zenburn-theme yaml-mode wgrep-helm use-package srefactor pdf-tools nyan-mode multiple-cursors mic-paren helm-swoop helm-projectile helm-gtags google-c-style flycheck-irony dired+ company-irony-c-headers company-irony auctex))
  package--save-selected-packages()
  run-hooks(after-init-hook delayed-warnings-hook)
  command-line()
  normal-top-level()
```
continue(end)

At the same time, here is the corresponding *Messages* output:
```
Saving file /home/danylo/.emacs.d/init.el...
Entering debugger...
Mark set
Continuing.
Wrote /home/danylo/.emacs.d/init.el
Entering debugger...
Mark activated
Continuing.
Wrote /home/danylo/.emacs.d/init.el
Entering debugger...
Mark activated
Continuing.
For information about GNU Emacs and the GNU system, type C-h C-a.
```

## C-x C-s backtrace

On the other hand, a regular C-x C-s (which leaves the inode unchanged!), has the following backtrace:

```
Debugger entered--Lisp error: "Saving file /home/danylo/.emacs.d/init.el..."
  message("Saving file %s..." "/home/danylo/.emacs.d/init.el")
  save-buffer(1)
  funcall-interactively(save-buffer 1)
  call-interactively(save-buffer nil nil)
  command-execute(save-buffer)
```
continue
```
Debugger entered--Lisp error: "Wrote /home/danylo/.emacs.d/init.el"
  write-region(nil nil "/home/danylo/.emacs.d/init.el" nil t "~/.emacs.d/init.el")
  basic-save-buffer-2()
  basic-save-buffer-1()
  basic-save-buffer(t)
  save-buffer(1)
  funcall-interactively(save-buffer 1)
  call-interactively(save-buffer nil nil)
  command-execute(save-buffer)
```
continue (end)

**Comment by dmalyuta** [comment]
Further info: it appears this problem doesn't happen in Emacs 24.5.1, where the "Saving" and two "Wrote" statements actually don't appear at all after use-package does the auto-download. The problem that this issue is about happens, however, for Emacs 25.1.

**Comment by npostavs** [comment]
Yup, I see what's happening. In Emacs 25, package.el saves the `package-selected-packages` variable by calling `custom-save-all` (via `custom-save-variable`) which let-binds `file-precious-flag`.

```
file-precious-flag is a variable defined in ‘files.el’.
Its value is nil

Documentation:
Non-nil means protect against I/O errors while saving files.
Some modes set this non-nil in particular buffers.

This feature works by writing the new contents into a temporary file
and then renaming the temporary file to replace the original.
In this way, any I/O error in writing leaves the original untouched,
and there is never any instant where the file is nonexistent.

Note that this feature forces backups to be made by copying.
Yet, at the same time, saving a precious file
breaks any hard links between it and other files.
```

I guess the easiest workaround would be to use a separate `custom-file` if you don't mind breaking hard links to that one.

**Comment by dmalyuta** [comment]
I see... well, I switched to using soft links in order to be more robust to these sorts of quirks. Should we consider the issue closed?
