### ISSUE TITLE
use-package-always-demand

### ISSUE THREAD

**Issue by vidagabor** [jwiegley/use-package#423]
Hi!

This might be a bit weird request from my side, but when I start Emacs I don't care how much time does it take to boot, but once it is done, I'd like all the code loaded and everything prepared to start working. I always add :demand t to use-package declarations to avoid delayed code execution and late surprises when it turns out that the given package is broken.

So I'm wondering on whether you could add use-package-always-demand custom variable to let me choose the default :demand "behaviour". Which means that I use quite a few use-package feature and I like the most the way how it makes init.el tidy.

**Comment by jwiegley** [comment]
That's a good idea, thank you.

**Comment by vidagabor** [comment]
Thank you!
