### ISSUE TITLE
a typo in use-package/README.md ?

### ISSUE THREAD

**Issue by QikeLi** [jwiegley/use-package#425]
Is a "." missing in  (bind-key "C-." 'ace-jump-mode).  It is located in the key binding section of  use-package/README.md

**Comment by npostavs** [comment]
No, it's correct. The `:bind` keyword takes conses, so the dot is needed there, but the `:init` keyword takes lisp forms. `(bind-key "C-." 'ace-jump-mode)` is a call to the `bind-key` macro.

**Comment by QikeLi** [comment]
Thanks!
