### ISSUE TITLE
:demand keyword needs to be put AFTER :bind

### ISSUE THREAD

**Issue by lurdan** [jwiegley/use-package#428]
In my case, when I put `:demand t` before `:bind`, expanded macro doesn't include `require` part (which `use-package-debug` shows).

Though I may be overlook usage, are there any requirements about keywords?

**Comment by anler** [comment]
Don't know exactly why but I had this:

```elisp
(use-package prelude
  :load-path "~/.emacs.d/core"
  :demand t
  :bind* (...)
  ...)
```

and now had to move the `demand` after the `bind*` in order to be able to *demand* the package

**Comment by greenonion** [comment]
This has been introduced in 9a4e5cbe3601361188a71bc37284af6e4adb68cc.

**Comment by jwiegley** [comment]
I've reverted this commit for the time being.

**Comment by jwiegley** [comment]
Should be fixed now.

**Comment by anler** [comment]
@jwiegley thanks!
