### ISSUE TITLE
Always checks package list when loading org

### ISSUE THREAD

**Issue by dstorrs** [jwiegley/use-package#434]
I have this in my .emacs:

(use-package org-mode
  :ensure t
  :mode "\\.org\\'"
  :bind (("C-c M-<" . org-move-subtree-to-top-of-file)
         ("C-c C-x h" . org-export-as-html)
         ("C-c t" . org-set-tags)
         ("C-c l" . org-store-link)
         ("C-c h" . org-hide-all)
         ("C-c a" . org-agenda)
         );bind                                                                                     
  );use-package org

I start emacs like this:

$ emacs foo.org

Emacs hangs for several seconds while it checks all the package archives, but then foo.org opens in org mode.

I don't have this issue with racket-mode or other packages.

I thought the package was named 'org', but when I change it to: (use-package org ...) there is no checking of the archives but files do not load up in org mode.

I know that org is a builtin and I assume that has something to do with it, but I'm not sure what.

**Comment by npostavs** [comment]
The package is named 'org', but the mode is 'org-mode', so you should do it like this (note also the doubled backslashes):
```elisp
(use-package org
  :ensure t
  :mode ("\\.org\\'" . org-mode) ; Redundant, Emacs has this by default.
  :bind (("C-c M-<" . org-move-subtree-to-top-of-file)
	 ("C-c C-x h" . org-export-as-html)
	 ("C-c t" . org-set-tags)
	 ("C-c l" . org-store-link)
	 ("C-c h" . org-hide-all)
	 ("C-c a" . org-agenda)))
```

**Comment by dstorrs** [comment]
That did the trick, thank you.
