### ISSUE TITLE
:after only works for the second argument.

### ISSUE THREAD

**Issue by tttuuu888** [jwiegley/use-package#435]
I tried `:after ` with two mode as below. (message-box is for test)
```
(use-package recentf
    :defer t  
    :after (eshell shell)  
    :config  
    (message-box "recentf config")  
    (recentf-mode t))
```

and it looks like `:after` works only for second argument. I tried
with the opposite order of 2 modes and also tried without parenthesis
but the result was same. 

My emacs version is 25.1.1 on Ubuntu 16.04
use-package version is use-package-20170218.132 from melpa.

**Comment by jwiegley** [comment]
Here's what your `use-package` declaration expands to:

``` emacs-lisp
(progn
  (eval-after-load 'shell
    '(eval-after-load 'eshell
       '(require 'recentf nil t)))
  (eval-after-load 'recentf
    '(progn
       (message-box "recentf config")
       (recentf-mode t)
       t)))
```

Can you explain the behavior you see, and the behavior you expected to see?

**Comment by tttuuu888** [comment]
I expected message "rectentf config" will pop up when I start either shell or eshell. But message only pops up when I start shell.

**Comment by npostavs** [comment]
According to 63459d40ed9cc70c476dd6fb5810c720bd5ac78f, this should do what you want:
```elisp
(use-package recentf
    :defer t  
    :after (:any eshell shell)  
    :config  
    (message-box "recentf config")  
    (recentf-mode t))
```

**Comment by tttuuu888** [comment]
I checked and it worked. Thanks a lot!
So, this was not a bug, right? I will close this issue. Thanks again.

**Comment by johnw42** [comment]
There is still a bug in the help page for use-package, which states

```
:after           Defer loading of a package until after any of the named
                 features are loaded.
```
