### ISSUE TITLE
:after doesn't work after update

### ISSUE THREAD

**Issue by Yevgnen** [jwiegley/use-package#440]
After update to the latest version, the :after keyword doesn't work any more.

A test snippet would be

```emacs-lisp
(package-initialize)

(require 'use-package)

(use-package company
  :ensure t
  :demand t
  :init
  (setq company-transformers '(company-sort-by-backend-importance company-sort-by-statistics))

  (use-package company-statistics
    :ensure t
    :after company
    :init 
    (print "==========")
    :config (company-statistics-mode)
    (print "^^^^^^^^^^^^^^^^^^")))
:
```

Got `"=========="` output on starting Emacs but no `"^^^^^^^^^^^^^^^^^^"`. Also a error `Symbol’s function definition is void: company-sort-by-statistics` alerts since `company-statistics` is no load and `(featurep 'company-statistics)' returns `nil`.

Any help will be appreciated!

**Comment by 4lex1v** [comment]
Macroexpand shows the following code:

```emacs-lisp
(eval-after-load 'magit-mode
    ''(require 'evil-magit nil t))
```

where `require` is quoted twice. Might this be a reason?

**Comment by ackalker** [comment]
@4lex1v I think you nailed it.
```elisp
ELISP> (featurep 'helm)
t
ELISP> (eval-after-load 'helm ''(message "test"))
(message "test")
ELISP> (eval-after-load 'helm '(message "test"))
"test"
```

**Comment by basil-conto** [comment]
@raxod502 has addressed this in #439.

**Comment by therockmandolinist** [comment]
@Yevgnen this can be closed as it's been solved.

**Comment by Yevgnen** [comment]
Thanks
