### ISSUE TITLE
Loading local package

### ISSUE THREAD

**Issue by seblemaguer** [jwiegley/use-package#441]
Hello,

sorry if these question has already been posted, I couldn't find it (maybe too tired :D). Assuming I have a package X.el in a directory X. Is it possible to use use-package to load this package ?

**Comment by waymondo** [comment]
On the README, you are looking for [:load-path](https://github.com/jwiegley/use-package#extending-the-load-path)

**Comment by seblemaguer** [comment]
Ah yes thanks a lot :)
