### ISSUE TITLE
add-hook syntax sugar

### ISSUE THREAD

**Issue by nickmccurdy** [jwiegley/use-package#444]
I find use-package's `bind-key` macro (and the related `:bind` keyword) very helpful for cleaning up duplicate configuration. Hooks also tend to get out of hand on me, especially since I often need to add multiple functions to one hook, or add one function to multiple hooks. I think it would be great to have an `add-hooks` macro with a `use-package` keyword, which could work similarly to the binding feature.

I created a [custom `add-hooks` macro](https://gist.github.com/nickmccurdy/cf7b2682047dedbacf946c19326960b2) (inspired by `bind-keys`) before I switched to `use-package`, which I'm still using to declare my hooks. It takes several cons pairs, where either the hook or function can be a single symbol or a list of symbols, in which case the pair will automatically apply to multiple functions and/or hooks. Here's an example:

```emacs
(add-hooks
 ;; Programming modes
 (prog-mode-hook . (flyspell-prog-mode linum-mode rainbow-mode))

 ;; Text modes
 (text-mode-hook . (flyspell-mode auto-fill-mode))

 ;; Clean whitespace when saving.
 (before-save-hook . whitespace-cleanup)

 ;; Use Emmet to complete CSS and HTML.
 ((css-mode-hook sgml-mode-hook) . emmet-mode)

 ;; Use Tern for JS analysis.
 (js-mode-hook . tern-mode)
```

The `use-package` keyword could look something like this, taking either a cons cell or a list of cells:
```emacs
(use-package emmet-mode
  :hooks
  ((css-mode-hook sgml-mode-hook) . emmet-mode))
```

**Comment by joewreschnig** [comment]
I was going to file a request for a related feature, which is that I can't find a way to combine autoloads and hooks safely, and I think this could potentially solve that too. (Unless it's already solvable - I only started using `use-package` yesterday.)

If I want an autoload of a package that only activates via a hook (for me, this is `flycheck-mode` and `rainbow-mode`), and `add-hook` within `:init`, then I have message spam every time the mode is activated if the package is not installed. But if I `add-hook` in `:config`, then it won't hook until I run the autoloading command explicitly.

With a special `:hooks`, `use-package` would have the information it needs to make the unloaded stub command quieter, or unhook it completely after the package isn't found.

**Comment by nickmccurdy** [comment]
I set all my hooks under `:config`, and I don't seem to have the same hook activation issue. However, I do use `:ensure` to install all third party packages, I wonder if that's causing my hooks to work properly.

For example, here's one of my `use-package` declarations which can successfully set up a hook even if the command wasn't installed previously:

```emacs
(use-package rainbow-mode
  :ensure
  :config
  (add-hook 'prog-mode-hook 'rainbow-mode))
```

**Comment by nickmccurdy** [comment]
In other news, my [`add-hooks`](https://github.com/nickmccurdy/add-hooks) package is now on [MELPA](https://melpa.org/#/add-hooks) and [MELPA Stable](https://stable.melpa.org/#/add-hooks).

I'm using it under `:config` to set up some of my more complex hooks, which is especially useful when a package introduces a minor mode which I want in multiple major modes. That being said, it would still be useful to have additional syntax sugar and assumptions for hook setup built into `use-package` (for example, using the package's name as the default `FUNCTION` for `add-hook`, similarly to `:mode`'s assumptions).

**Comment by joewreschnig** [comment]
If I understand `use-package`'s model, that works for you because nothing in that state makes it  deferred. So it works, but you are also loading rainbow mode even if you never use it. If instead it's using one of the deferring features, e.g. `:commands`:

```elisp
(use-package rainbow-mode
  :commands rainbow-mode
  :config
  (add-hook 'prog-mode-hook 'rainbow-mode))
```

It won't ever load, because `:config` won't run until one of the loading triggers - in this case, the command `rainbow-mode` - runs. Which it doesn't, because the hook also isn't added until it runs. But if I hook during `:init`, that's also no good because I don't know that the package will exist.

Giving higher-level control of hooking over to `use-package` would let it hook something during `:init` that reacts better if the package turns out not to exist once it first tries to trigger the load.

**Comment by nickmccurdy** [comment]
Thanks for the explanation, that clears up some of my confusion about lazy loading.

I think the `:hooks` keyword itself should add the hook immediately, enable `:defer`, and set up an autoload for the package. We could wrap hook functions in conditionals checking if the package exists to prevent "package not installed" errors (I believe setting the hook in advance anyway could prevent interdependency issues between packages).

**Comment by joewreschnig** [comment]
Appending `-hook` is fine; every normal hook should end in `-hook` and virtually every one does. But there are [a lot of useful hooks that aren't mode-specific](https://www.gnu.org/software/emacs/manual/html_node/elisp/Standard-Hooks.html), and also a few common multi-modal ones like `c-mode-common-hook`, which don't end in `-mode-hook`.

Other deferring keywords like `:mode`, `:interpreter`, and `:commands` also require an explicit `-mode` when it doesn't match the package name. I think fighting against the repetition of `-mode` in Emacs code is probably a Sisyphean task, and would prefer it to stay explicit. It's always harder to disable implicit behavior when you don't want it, and harder to keep compatibility if you need to back it out because of other concerns.

**Comment by nickmccurdy** [comment]
I agree, let's make only `-hook` implied in terms of naming hooks and functions. It's also easier to read since hook naming has a stronger standard and the hooks are always first, while the other assumptions were more ambiguous and would have some complicated edge cases.

I would still like the syntax to allow for multiple hooks in a pair, multiple functions in a pair, and multiple pairs. I think multiple pairs should have another pair of parens around them to mirror `:bind`'s syntax for one or more bindings.

**Comment by 4lex1v** [comment]
Guess it's too late to contribute to the discussion, but maybe my case could be considered as a form of a future improvement. My config [uses a very similar approach](https://github.com/4lex1v/emacs/blob/master/modules/essentials/upe-hooks/upe-hooks.el) described here, but in an inverted manner. Having a modularized approach to emacs' configuration, I've added a keyword `:hooks` that receives a list of functions to call when a given mode is loaded, i.e say there's a configuration to work with the language of your choice, which requires a list of packages to be loaded, hence i have:

```
(use-package scala-mode
  :hooks (4lex1v/fix-scala-fonts
          hs-minor-mode
          hideshowvis-enable
          yas-minor-mode
          company-mode))
```

This approach looks cleaner to me, cause if there's a need to drop this config, there's only one place i need to change, rather then traverse all other configs removing the hook.

**Comment by jwiegley** [comment]
The exact syntax you quoted above now works, it's just called `:hook` instead of `:hooks`, for the same reason that it's `:bind` instead of `:binds`.

**Comment by jwiegley** [comment]
If `:hook` had the reverse semantics, as you describe, how would you add to `text-mode-hook` or `prog-mode-hook`, which are far more common (at least, for me) than hooking one externally installed package into another.

**Comment by jwiegley** [comment]
Also, I tend to prefer that "more derived" packages reference the more basic ones, than the other way around.  That is, counsel should refer to ivy, not ivy to counsel.

**Comment by 4lex1v** [comment]
@jwiegley answering your question:

> how would you add to text-mode-hook or prog-mode-hook, which are far more common

The approach i use - wrapping with a `use-package`, e.g for [eshell](https://github.com/4lex1v/emacs/blob/master/modules/infra/install.el#L48). Haven't seen issues with this approach.

> Also, I tend to prefer that "more derived" packages reference the more basic ones, than the other way around. That is, counsel should refer to ivy, not ivy to counsel.

I see the rational behind this, that's what i had initially. Current configuration strives towards a more modular approach, i.e major mode configuration with all minor mode dependencies, but it's a personal preference. 

Anyway, thanks for taking your time considering my case 👍

**Comment by jwiegley** [comment]
Adding a private keyword, such as `:call`, would be trivial. If enough other people prefer that ordering, we could add it to `use-package`.

``` elisp
(use-package text-mode
  :call (flyspell-mode ace-jump-mode auto-fill-mode))
```

This would have the behavior that when `text-mode` is loaded (`:defer` is implicit here), those functions will be called.

**Comment by joewreschnig** [comment]
> The approach i use - wrapping with a use-package, e.g for eshell. Haven't seen issues with this approach.

`eshell` is a package, and a feature, and a file, so everything "just works". `package-install`, `load` / `require`, and `featurep` all want the same identifier.

`prog-mode` is a feature and a file but not a package, and `text-mode` is merely a file. The former has some annoying edge cases when mixed with `:ensure` since `package-install` doesn't quite do the right thing. The latter is unaddressable. You'd need to hang it off `simple` (a feature) or `emacs` (a feature and a package), and then the shorthand doesn't work anymore anyway.

**Comment by npostavs** [comment]
`(use-package "text-mode" ...)` should work.

**Comment by joewreschnig** [comment]
It "works" but it might not do what you expect.

- If you have `use-package-always-ensure` set to `t` (or set it to `t` explicitly), you'll try to `package-install` it, eventually producing an error about not finding a package named "text-mode-".

- Because no feature is provided, `text-mode.el`'s contents will be re-evaluated every time.

**Comment by npostavs** [comment]
> If you have use-package-always-ensure set to t (or set it to t explicitly), you'll try to package-install it, eventually producing an error about not finding a package named "text-mode-".

Use `:ensure nil`.

> Because no feature is provided, text-mode.el's contents will be re-evaluated every time.

Use `:defer t`.

**Comment by dieggsy** [comment]
@joewreschnig I'm not sure I follow. Eshell and text-mode are the same in this regard for me: both are features defined in some file that `provide`s them (also can double check with `(featurep text-mode)`, which returns `t`).  I need to make sure `:ensure` is set to `nil` for both.

**Comment by npostavs** [comment]
> (also can double check with (featurep text-mode), which returns t

That's new in Emacs 26 or so.

**Comment by dieggsy** [comment]
@npostavs ah, thanks for the clarification.

**Comment by nickmccurdy** [comment]
@jwiegley Thanks for all this work, I finally got around to migrating from my `add-hooks` package to `:hook` and I love the syntax!

On a related note about `add-hooks`: When I originally created the package I was inspired by `bind-key`, and I wanted a similar library that could be used to define hooks the same way with or without using `use-package` (just like what `bind-key` does for `global-set-key`). I wanted to implement my own third party `:hooks` keyword which basically has the same syntax, but would internally use `add-hooks` so that the syntax's implementation would be agnostic of the `use-package` codebase (I actually started a pull request for `use-package` with very similar syntax but ultimately couldn't figure out how to get it to work). This way any bugs or feature changes in `use-package` `:hook` syntax and the `add-hooks` function could be made once together for easier maintenance, and another alternative configuration management package could use the same hook resolution as `use-package` and `add-hooks` for modularity. Do you think it would be worth it if I refactored the `:hook` keyword to use the `add-hooks` package internally (just like `bind-key`) as long as I can keep it back compatible?
