### ISSUE TITLE
Feature request: Bisecting/Combinational testing to find bad package interactions.

### ISSUE THREAD

**Issue by psilord** [jwiegley/use-package#448]
Hello,

I find myself using a lot of packages and often they have some
subtle interaction between them that forces me to bisect (and/or do
combination testing) my emacs configuration in order to find it. Could
there be any support for this operation with use-package?

Maybe use-package could keep a side list of packages names in a file
that are enabled or disabled that overrides the actual init.el config
file settings. Then, it can update the list by systematically turning
things on and off in it until the problem is found (possibly by parsing a
new emacs command line arg for which use-package knows to look.

The current feature-set makes it hard because when disabling a package
the :disabled keyword disables it if it is present at all, as opposed to
:disabled t. This means I can't just have a big list of booleans at the top
of my init.el file that I can manually adjust to try and figure out the problem.
I have to go into my config file and comment in/out each :disabled which is
tedious.

Thank you!

**Comment by jwiegley** [comment]
Would `:if` work for you?

**Comment by psilord** [comment]
As long as `:if` allows an arbitrary elisp expression there,
I can build some infrastructure around it to perform the
bisection/combination work. Specifically, I have to be able to shut
down and restart emacs with the new set of packages I want to try. The
reason I was hoping for a use-package supported thing is that now I
have to keep extraneous data around detailing which packages should be
enabled outside of, and duplicating, the feature use-package provides.

But, it is probably good enough. Thank you!
