### ISSUE TITLE
Return non-nil if enabled and nil if disabled

### ISSUE THREAD

**Issue by Alexander-Shukaev** [jwiegley/use-package#450]
It would be very useful if the `use-package` macro would have returned `nil` if it is disabled (either with the `:disabled` keyword or as a result of the `:if` keyword, etc.) and something non-`nil` (perhaps its body code) otherwise.

**Comment by nickmccurdy** [comment]
I'm curious, what's your use case? Are you using it to conditionally run code based on a `use-package` call with `:if`?

**Comment by Alexander-Shukaev** [comment]
Exactly.  I need to know whether package was actually enabled/disabled to decide whether to, for example, run `autoload`ed function from that package or not, or reference `autoload`ed function from that package in some hook or not.  Why and how the package was disabled is an implementation detail irrelevant to the rest of the code, at it wants to know is whether it was explicitly disabled.

**Comment by jwiegley** [comment]
Note that it use to do this, but nowadays does not. It became difficult to ensure this is the case when keywords are allowed to be changed by the user. I had decided not to do it at all, but maybe it's worth reconsidering.

**Comment by Alexander-Shukaev** [comment]
In fact, in Emacs 25 and 26 series, I see that the return value of `use-package` can be used to identify whether it was disabled or not.  That is if it expands to something meaningful, it returns non-`nil`.  This is how I was able to identify it now and it works quite good.  However, what I noticed is that on Emacs 24, it does not work that way somehow (I don't remember exactly now but it's either always `nil` or non-`nil`).  I have no explanation for that difference so far.  Do you have any ideas?  And in any case, would you like to fix this change or you still didn't decide?  Thanks anyway!

**Comment by jwiegley** [comment]
Using use-package programmatically like this is not really part of its intended design, so I'm going to call it and say that such support, if it occurs in any Emacs version, is unintentional. It's not something I'm willing to put in the work to maintain across several versions.
