### ISSUE TITLE
Query on use-package declaration to load a theme

### ISSUE THREAD

**Issue by doolio** [jwiegley/use-package#454]
Firstly, I don't believe this is an `use-package` issue so please close if this is not the right place to raise this but I feel others would benefit in understanding the points raised. Secondly, excuse my Emacs Lisp and programming ignorance in general.

I had the following `use-package` declaration to load my theme of choice - `leuven`. I want to take advantage of the latest version rather than that which ships with stock Emacs. 

```
(use-package leuven
  :ensure leuven-theme                  ; equivalent to `:ensure t'
  :config                               ; should I use `:init' here instead?
  (load-theme 'leuven 'no-confirm))
``` 

This loaded the `leuven` theme successfully but would raise a message stating it could not be loaded. Using `:config` or `:init` resulted in the same outcome. So is one form better than the other here?

Now, I wrote the declaration this way because of my understanding of some of the subtleties of `use-package`. This understanding comes from this [SX Q&A](https://emacs.stackexchange.com/questions/17710/use-package-with-config-to-set-variables) and is outlined below. Admittedly my understanding could be plain wrong so please do point this out if that is the case. Specifically, my understanding of the difference between the feature-name and package-name. 

```
(use-package feature-name

      FEATURE-NAME is what goes in the (provide ..) line of a package. For
      org-mode, for example that line is (provide 'org).

  :mode ((file-regexp . major-mode))

      FILE-REGEXP is the regular expression for which you want a particular
      major mode to be enabled e.g. "\\.org\\".

      MAJOR-MODE is the name of the major mode that you want to enable
      (including the `-mode' part of the major mode name) e.g. org-mode. The
      form :mode (file-regexp) would only work if FEATURE-NAME and MAJOR-MODE
      are the exact same e.g. cperl-mode.

  :ensure package-name

      PACKAGE-NAME is what you see listed in the package list (M-x
      package-list-packages). If the PACKAGE-NAME and
      FEATURE-NAME are identical then this keyword value can simply be set to t
      - this will be the case for most use-package declarations.
``` 
You can see that I took `leuven` to be the "feature-name" (true?) of this theme and `leuven-theme` as the package-name which is true. Now, if I use the following declaration the theme is loaded successfully with *no* message stating it could not be loaded so this would appear to be the correct version. The only (real) difference is that I use the package-name in the first line.

```
(use-package leuven-theme
  :ensure t                             ; "feature-name" == package-name
  :config
  (load-theme 'leuven 'no-confirm))
```

I'm curious to understand the subtlety here. The only thing I can see that doesn't stand up to my understanding of declarations given above is that theme package `.el` files use `provide-theme` rather than `provide` that is in the case of the `leuven` theme file (`leuven-theme.el`) it has `(provide-theme 'leuven)` rather than `(provide 'leuven)`. 

Would this explain why my first declaration worked but had that error message whereas my second declaration just worked? In any case many thanks for this great package and your time.

**Comment by npostavs** [comment]
> I'm curious to understand the subtlety here. The only thing I can see that doesn't stand up to my understanding of declarations given above is that theme package `.el` files use `provide-theme` rather than `provide`

Yeah, that's the thing:

```
provide-theme is a compiled Lisp function in `custom.el'.

(provide-theme THEME)

Indicate that this file provides THEME.
This calls `provide' to provide the feature name stored in THEME's
property `theme-feature' (which is usually a symbol created by
`custom-make-theme-feature').
```

```
custom-make-theme-feature is a compiled Lisp function in `custom.el'.

(custom-make-theme-feature THEME)

Given a symbol THEME, create a new symbol by appending "-theme".
[...]
```

So `(provide-theme 'leuven)` does the same as `(provide 'leuven-theme)`. Also note that `require` searches for `provide`d features based on filenames, so a file called `leuven-theme.el` should always be providing the `leuven-theme` feature.

**Comment by doolio** [comment]
Thank you for the quick response and thorough explanation. This makes sense though I'm not sure of the rationale to introduce `provide-theme` for theme packages rather than using the existing `provide`. In any case, we can considered this closed.
