### ISSUE TITLE
How to use bind-key to properly map H-g to keyboard-quit?

### ISSUE THREAD

**Issue by priyadarshan** [jwiegley/use-package#455]
I use a lot the Hyper key, and I would like it to replicate `C-g` (`keyboard-quit`).

I tried to do this:

```
(bind-key "H-g" #'keyboard-quit)
```
When I do `C-h k`, Emacs says,
```
H-g runs the command keyboard-quit (found in global-map), which is an
interactive compiled Lisp function in ‘simple.el’.

It is bound to C-g, H-g.
```
But trying it, by opening the minibuffer with `M-x` and then doing `H-g`, it does not work: the minibuffer stays open.

If instead I use my current snippet (I believe from Emacs mailing list),
```
(global-set-key (kbd "H-g") (kbd "C-g"))
```

It works.

How to use bind-key to properly map `H-g` to `keyboard-quit`?

Thank you.

**Comment by jwiegley** [comment]
Perhaps try this:

``` elisp
(define-key key-translation-map (kbd "H-g") (kbd "C-g"))
```
