### ISSUE TITLE
Clarify supported Emacs versions

### ISSUE THREAD

**Issue by basil-conto** [jwiegley/use-package#457]
Commit 63459d40ed9cc70c476dd6fb5810c720bd5ac78f "Support multiple symbols passed to :after" of 2017-02-16 introduced the use of `pcase` in the expansion of the keyword `:after`.

So far, only `:pin` has required Emacs >= 24.4, as stated in the project's [`README.md`](https://github.com/jwiegley/use-package/blob/master/README.md#for-packageel-users).

I would, therefore, be grateful for clarification on the project's intended direction regarding backward compatibility:

1. Will support for Emacs 23 be dropped entirely?
2. If not, will support for certain features, such as the aforementioned `:pin` and `:after`, be dropped?

   In this case the README and ELPA header should be updated.
3. If all features (with the exception of `:pin`, due to `package.el` limitations IIUC) are to be supported, then I believe the use of `pcase` is a bug. I would be happy to provide a fix for this.
4. Are any of the above questions/decisions affected by the future [inclusion of `use-package` in Emacs](https://github.com/jwiegley/use-package/issues/282)?

**Comment by basil-conto** [comment]
Sorry, the README should be updated in both cases (1) and (2), whereas the ELPA header should only be updated in case (1), to indicate the dependence on Emacs 24.

**Comment by nickmccurdy** [comment]
According to `package-lint-current-buffer`, there are some other things that rely on Emacs 24.

```
error: You should depend on (emacs "24.3") if you need `user-error'.
error: You should depend on (emacs "24.3") if you need `user-error'.
error: You should depend on (emacs "24") if you need `pcase'.
error: You should depend on (emacs "24") if you need `condition-case-unless-debug'.
```

**Comment by jwiegley** [comment]
If anyone wants to provide a PR for supporting Emacs 23, that would be fine, otherwise I'm OK with 24.3 being the minimum version for now.
