### ISSUE TITLE
Can use-package be used to replace with-eval-after-load?

### ISSUE THREAD

**Issue by amosbird** [jwiegley/use-package#458]
```
(use-package helm
  :defer
  :config
      ......
)

vs

(with-eval-after-load 'helm
   .....
)
```

**Comment by jwiegley** [comment]
`use-package` is just a macro that expands to something equivalent to what you wrote above.  So, it can't replace what it itself depends on. :)  But it does offer a lot more features, and tries to be intuitive about not making you specify everything.

**Comment by amosbird** [comment]
Thanks! Um, why does   (bind-key "C-." 'ace-jump-mode) need to escape the command? This is inconsistent with :bind

**Comment by jwiegley** [comment]
Otherwise Lisp would attempt to evaluate it as a variable.  In the `:bind` case, we're in a macro invocation, so we control what gets evaluated.

**Comment by amosbird** [comment]
Ok, then why not make bind-key a macro?

**Comment by jwiegley** [comment]
Having the symbol be quoted in `bind-key` matches `global-set-key`.  I think it *was* a macro originally, then it got converted it to a function.  If you want the macro behavior `:bind` should be used. But I'd prefer to keep `bind-key` as a function.

**Comment by npostavs** [comment]
`bind-key` is currently a macro (that acts like a function). It should probably be changed to a function to make the code clearer.

**Comment by amosbird** [comment]
ok, is there a common consensus about when to use quoted symbols?

**Comment by jwiegley** [comment]
Ah, `bind-key` is a macro, so it is.

If it looks like a function call, I think quoted arguments are the least surprising.  If it's a special construction (such as `use-package` with its keyword arguments), then we can set the user's expectations.
