### ISSUE TITLE
Support unbind keys?

### ISSUE THREAD

**Issue by wyuenho** [jwiegley/use-package#460]
Although the bind-key package supports unbinding, use-package doesn't seem to support it. There are some packages that by default make a lot of duplicate key bindings or is just plain ridiculous, it would be nice if use-package supports it.

**Comment by basil-conto** [comment]
The standard way of unbinding keys in Emacs is to bind them to `nil`. The `:bind` keyword of `use-package` does, of course, support this. The only aspect of unbinding unsupported by the `:bind` keyword is removing the definition from the `bind-key.el`-specific variable `personal-bindings` in addition to binding the key to `nil`. This has the user-visible effect that `M-x describe-personal-keybindings` does not take such unbindings into account.

**Comment by wyuenho** [comment]
Ah thank you

**Comment by snowman** [comment]
```elisp
(use-package org
  :config
  (unbind-key "C-'" org-mode-map))
```

**Comment by basil-conto** [comment]
> The standard way of unbinding keys in Emacs is to bind them to `nil`.

FWIW, there is a new variation of this in Emacs 29.  From `C-h n`:

```
*** 'define-key' now takes an optional REMOVE argument.
If non-nil, remove the definition from the keymap.  This is subtly
different from setting a definition to nil (when the keymap has a
parent).
```

From `C-h f define-key RET`:

```
If REMOVE is non-nil, the definition will be removed.  This is almost
the same as setting the definition to nil, but makes a difference if
the KEYMAP has a parent, and KEY is shadowing the same binding in the
parent.  With REMOVE, subsequent lookups will return the binding in
the parent, and with a nil DEF, the lookups will return nil.
```
