### ISSUE TITLE
Support #'-syntax

### ISSUE THREAD

**Issue by luciferasm** [jwiegley/use-package#461]
The [function quote #'-syntax](https://stackoverflow.com/questions/16801396/when-should-emacs-function-syntax-be-used) adds the benefit of byte-compiler warnings when referring to non-defined functions. It's nice to catch typos or other errors at compile time rather than run-time, e.g:
`(global-set-key (kbd "C-a") #'foo) ;"Warning: the function ‘foo’ is not known to be defined."`

i) When byte-compiling with `bind-keys` directly, this syntax fails silently (which leads to a false sense of security):
`(bind-keys ("C-a" . #'foo)) ;fails silently (i.e. no warnings)`

ii) When byte-compiling with `use-package`, it just fails:
`(use-package company
  :bind (:map company-mode-map ("C-a" . #'foo))) ;"Error: Wrong type argument: listp, "C-a""`

It would be great if the #'-syntax would work as expected in both cases, or at least consistently fail like in case ii) in order to communicate that this syntax is not supported.

**Comment by basil-conto** [comment]
FWIW, I remember seeing some discussion about `bind-key`'s implementation as a macro vs function, and its intended switch to being a function. I can't seem to find this discussion now, maybe @npostavs recalls? If `bind-key` were a function, this would at least address point (i), no?

**Comment by npostavs** [comment]
> If `bind-key` were a function, this would at least address point (i) gratis, no?

I *think* the status of `bind-key` (singular) would make no difference to this behaviour of `bind-keys` (plural). I see a comment on `bind-keys-form` (helper function for `bind-keys`) which seems to be relevant:
```
(defun bind-keys-form (args)
...
  ;; jww (2016-02-26): This is a hack; this whole function needs to be
  ;; rewritten to normalize arguments the way that use-package.el does.
```

---
By the way, part of what makes it trickier to give clear error messages for this is that `("C-a" . #'foo)` is equivalent to `("C-a" . (function foo))` == `("C-a" function foo)`.

**Comment by jwiegley** [comment]
`(bind-keys ("C-a"  . 'foo))` causes silent problems too.

**Comment by jwiegley** [comment]
Note that all of the following are now allowed *by `use-package` `:bind`*, but not by `bind-keys`, which is a much harder change to make:

```
("C-a" . sym)
("C-a" . 'sym)
("C-a" . #'sym)
("C-a" . (lambda () (sym)))
("C-a" . '(lambda () (sym)))
("C-a" . #'(lambda () (sym)))
```
