### ISSUE TITLE
use-package with maxima

### ISSUE THREAD

**Issue by tpapp** [jwiegley/use-package#464]
I wonder if I could get some help to set up `maxima` in Emacs with `use-package`. The following lines work:
```emacs-lisp
(add-to-list 'load-path "/usr/share/emacs/site-lisp/maxima")
(autoload 'maxima-mode "maxima" "Maxima mode" t)
(autoload 'maxima "maxima" "Maxima interaction" t)
(setq auto-mode-alist (cons '("\\.ma[cx]" . maxima-mode) auto-mode-alist))
```
but when I try
```emacs-lisp
(use-package maxima
  :mode ("\\.ma[cx]" . maxima-mode))
```
it tries to download from ELPA/MELPA, where it is not available (it is available on most distributions, eg [maxima-emacs](https://packages.debian.org/jessie/maxima-emacs) on Debian/Ubuntu, or [bundled with Maxima](https://www.emacswiki.org/emacs/MaximaMode)).

**Comment by npostavs** [comment]
You have `use-package-always-ensure` set to `t`? Try
```elisp
(use-package maxima
  :ensure nil
  :load-path "/usr/share/emacs/site-lisp/maxima"
  :commands (maxima)
  :mode ("\\.ma[cx]" . maxima-mode))
```

**Comment by tpapp** [comment]
Indeed I have `(setq use-package-always-ensure t)`. Thanks for the help, and the very fast response, this works perfectly, so I am closing the issue.
