### ISSUE TITLE
Target several specified keymaps simultaneously?

### ISSUE THREAD

**Issue by luciferasm** [jwiegley/use-package#466]
I'm aware that `:bind*` overrides _all_ minor modes, but how do I target a few _specified_ minor modes only? E.g. the package `grep` is an extension of package `compile`, where `compilation-minor-mode-map` is the parent keymap to `grep-mode-map`. It therefore makes sense to target both of these keymaps simultaneously when customizing their key bindings (another similar example is the pair `lisp-interaction-mode-map` and `emacs-lisp-mode-map`). Two naive solutions could be:

**1)** In addition to providing a single keymap to `:map`, also allow a list of keymaps:

```
(use-package grep
    :config (use-package compile)
    :bind (:map (compilation-minor-mode-map grep-mode-map)
                ("u" . compilation-previous-error)))
```

Even if this would work, it's not optimal though, since it introduces the hazard of managing dependencies of packages. I.e. in order to target `compilation-minor-mode-map` and `grep-mode-map` at the same time, the example above uses nested use of `use-package` in order to ensure the availability of both packages. But these two packages doesn't really have that kind of hard-wired dependent relation to each other (i.e. why do I have to load `grep` if I only want to use `compile` package?). It would instead be preferable to treat them as the stand-alone entities that they really are. So maybe a better second approach could be:

**2)** Provide a common alist of key bindings to `:map`:

```
(defconst common-key-bindings-alist
    '(("u" . compilation-previous-error)))
(use-package compile
    :bind (:map compilation-minor-mode-map
                common-key-bindings-alist))
(use-package grep
    :bind (:map grep-mode-map
                common-key-bindings-alist))
```

Would this be possible to implement? Today I unfortunately have to copy'n'paste these common key bindings, but I suspect that the redundancy that it introduces will bite me in the future... It would be great if they instead could reside in one, and only one, place (e.g. in a defconst).

Also, just a sidenote, what exactly does it mean "to override all minor modes" (as stated in the docs for `:bind*`)? "All" at what point in time? If I have several sequential `use-package` statements that each introduce their own new keymaps, surely the first one will not override the key bindings in the last one I guess? Which is also something solution **2)** above would address.

**Comment by jwiegley** [comment]
If `compilation-minor-mode-map` is the parent keymap to `grep-mode-map`, won't binding there be inherited by `grep-mode-map`?

**Comment by jwiegley** [comment]
Overriding all minor modes means that even if a minor mode map binds the key, Emacs will only ever see the global (override) binding.

**Comment by jwiegley** [comment]
I think this is fairly rarely needed, and the change to `bind-key` is non-trivial, so I'm closing as "won't fix".
