### ISSUE TITLE
magic(-fallback)-mode-alist syntactic sugar

### ISSUE THREAD

**Issue by joewreschnig** [jwiegley/use-package#469]
Along the lines as `:mode` and `:interpreter` I'd like syntactic sugar for `magic-mode-alist` and `magic-fallback-mode-alist`. `:magic` is probably too generic a name; `:magic-mode` and `:magic-fallback-mode` seem better. I believe the syntax / normalizer could be identical to `:mode` other than the alist used.

**Comment by jwiegley** [comment]
I kind of like `:magic` and `:magic-fallback` actually.

**Comment by joewreschnig** [comment]
My (weak) objections to bare `:magic` are:

- "Magic" is non-nominal. `:mode`, `:commands`, etc. are all nouns, which gives you a hint what to put there. With `:magic` there's no indication of what, exactly, will be magically handled.
- There's also [another feature named "magic names" in Emacs](https://www.gnu.org/software/emacs/manual/html_node/elisp/Magic-File-Names.html), as well as the standard Unix `magic(5)`, both of which also have to do with deciding how to open files (though the latter, not so much in Emacs).
- There are probably dozens of extensions named "<feature> magic" or "magic <feature>". (Outline Magic, Magic Buffer, Magic LaTeX Buffer, Magic Requires in clj-refactor...) Alone it's almost a nonsense word at this point.

**Comment by joewreschnig** [comment]
In the absence of further feedback, the PR uses `:magic` and `:magic-fallback`.
