### ISSUE TITLE
Implement ':features' like el-get

### ISSUE THREAD

**Issue by conao** [jwiegley/use-package#470]
Nowadays, https://github.com/dimitri/el-get supports `:features` label.
This feature is require some extensions in same package.
If this feature implemented, write more simple setting code in use-package.

Like that in latest el-get, 
``` elisp
(el-get-bundle papaeye/emacs-navbar
  :features (emacs-navbar navbarx-elscreen navbarx-version navbarx-time)
  (setq navbar-item-list '(navbarx-version navbarx-time navbarx-elscreen))
  (navbar-mode)
  (display-time-mode)
  (navbar-revive-workaround))
```

This code means, 
- Download papaeye's `emacs-navbar` from github.
- Require `emacs-navbar` `navbarx-elscreen` `navbarx-version` `navbarx-time`

Same meanings by use-package
``` elisp
(use-package emacs-navbar
  :init (el-get-bundle papaeye/emacs-navbar)  ;; download from github
  :config
  (use-package navbarx-elscreen)
  (use-package navbarx-version)
  (use-package navbarx-time)

  (setq navbar-item-list '(navbarx-version navbarx-time navbarx-elscreen))
  (navbar-mode)
  (display-time-mode)
  (navbar-revive-workaround))
```

You should write like that, but it is not good for me. These setting code is too short.
``` elisp
(use-package emacs-navbar
  :init (el-get-bundle papaeye/emacs-navbar)  ;; download from github
  :config
  (use-package navbarx-elscreen)
  (use-package navbarx-time
    :config
    (display-time-mode))
  (use-package navbarx-version
    :config
    (setq navbar-item-list '(navbarx-version navbarx-time navbarx-elscreen)))
  (navbar-mode)
  (navbar-revive-workaround))
```

So I write this code like that.
``` elisp
(use-package emacs-navbar
  :init (el-get-bundle papaeye/emacs-navbar)  ;; download from github
  :features (navbarx-elscreen, navbarx-version, navbarx-time)
  :config
  (setq navbar-item-list '(navbarx-version navbarx-time navbarx-elscreen))
  (navbar-mode)
  (display-time-mode)
  (navbar-revive-workaround))
```

Do you mind implement this feature?

**Comment by jwiegley** [comment]
See my notes on `el-get` in #471

**Comment by conao** [comment]
I'm not going to compete with el-get but I'm inspired by that package.
I'm sorry, comparing use-package with el-get is just make easier to grasp the feature what I say.

`:features` label is useful for large package for example `elscreen`.
But I found the way to build the feature by myself like quelpa-use-package.
Thank you for your comment!
