### ISSUE TITLE
Download packages from github

### ISSUE THREAD

**Issue by conao** [jwiegley/use-package#471]
https://github.com/dimitri/el-get support download packages from many places like github, http link and so on.
(el-get supports methods in https://github.com/dimitri/el-get/tree/master/methods)

I cannot move to use-package completely for this feature.

It is true that this feature is depend on command `git`, but it is more convenient with use-package.

before
``` elisp
(use-package emacs-navbar
  :init (el-get-bundle papaeye/emacs-navbar)  ;; download from github
  :config
  (use-package navbarx-elscreen)
  (use-package navbarx-time
    :config
    (display-time-mode))
  (use-package navbarx-version
    :config
    (setq navbar-item-list '(navbarx-version navbarx-time navbarx-elscreen)))
  (navbar-mode)
  (navbar-revive-workaround))
```

after (`:features` label in #470)
``` elisp
(use-package emacs-navbar 
  :defer papaeye/emacs-navbar
  :features (navbarx-elscreen, navbarx-version, navbarx-time)
  :config
  (setq navbar-item-list '(navbarx-version navbarx-time navbarx-elscreen))
  (navbar-mode)
  (display-time-mode)
  (navbar-revive-workaround))
```

**Comment by joewreschnig** [comment]
You might want to check out [quelpa-use-package](https://github.com/quelpa/quelpa-use-package), which I use in conjunction with a macro (along with similar ones for GitLab and plain Git):

```elisp
(defmacro use-github-package (name repo &rest body)
  "Fetch package NAME from GitHub repository REPO, and use it.

Any forms appropriate for `use-package' may be passed in BODY."
  (declare (indent 2))
  `(use-package ,name
     :quelpa (,name :repo ,repo :fetcher github)
     ,@body))
```

**Comment by jwiegley** [comment]
Note that `use-package` does not intend to compete with `el-get`. I'm interested in how one configures packages, not how they are installed.  The `:ensure` support that does exist was written by others, but is not something I have any future plans for.

What would be nice is for `el-get`  to use `use-package` for configuration, so it could focus its energies on package management, and then I could delete `:ensure` support from `use-package`.  Installation and configuration are separate problems, each deserving its own package.

**Comment by conao** [comment]
@joewreschnig 
Good! I overlooked that package! I'll try it soon.

@jwiegley 
I'm not going to compete with `el-get` but I'm inspired by that package.
I'm sorry, comparing `use-package` with `el-get` is just make easier to grasp the feature what I say.

By the way, You are right, 

> Installation and configuration are separate problems, each deserving its own package.

But recently, since lunched `use-package`, a package installation may be unpretentiousness. (with `:defer` syntax.)

I would configure package distribute with only github like other packages.

**Comment by conao** [comment]
I read the past issue. My issue is duplicate with #410.
And I understand @jwiegley 's point. 

If your opinion was changed, include this feature please!
Close this issue.
