### ISSUE TITLE
Can use package be extended to do something like this?

### ISSUE THREAD

**Issue by eflanigan00** [jwiegley/use-package#475]
I think this would be of great value. Lots of people run emacs behind a firewall without an easy way to use melpa etc

https://emacs.stackexchange.com/questions/33627/how-to-generate-and-activate-autoloads-for-local-packages?noredirect=1#comment52013_33627

**Comment by nickmccurdy** [comment]
As far as I'm aware, no, but it doesn't need to. If you want to load local packages you should just be able to put them on Emacs' load path and use `use-package` without `:ensure`. If you're activately developing packages locally you should be able to make symlinks in your load path.

**Comment by eflanigan00** [comment]
Byte compiling and installing is an advantage because you know what is installed by using the emacs package manager. Using load path doesn't provide that. In my opinion emacs and `use-package` would be amazing if it could reference some melpa like recipes and install the packages.

**Comment by joewreschnig** [comment]
> `use-package` would be amazing if it could reference some melpa like recipes and install the packages.

This is what [use-package-quelpa](https://github.com/quelpa/quelpa-use-package) does.

**Comment by raxod502** [comment]
An alternative to quelpa-use-package which provides all of the same features and more (including `use-package` integration, of course) is [`straight.el`](https://github.com/raxod502/straight.el).

I'd say this is squarely outside the realm of `use-package` itself, though: it's clearly a job for the package manager, via `:ensure`.
