### ISSUE TITLE
document any/all features of `:after` keyword

### ISSUE THREAD

**Issue by liblit** [jwiegley/use-package#478]
In the help text for `use-package`, the `:after` keyword is claimed to “Defer loading of a package until after *any* of the named features are loaded.” (emphasis mine) However, I believe that it actually waits for *all* of the named features to be loaded. Consider the following example:

``` elisp
(use-package delayed
  :after a b c d)
```

Using `pp-macroexpand-last-sexp` we see that this turns into:

``` elisp
(eval-after-load 'd
  '(eval-after-load 'c
     '(eval-after-load 'b
	'(eval-after-load 'a
	   '(require 'delayed nil t)))))
```

This looks like it will only trigger once all of `a`, `b`, `c`, and `d` are loaded, which contradicts the documentation.

Either the documentation should be changed to match the implementation, or the implementation should be changed to match the documentation. Personally, I prefer the “any” interpretation, which would mean that the implementation is wrong. But perhaps others prefer the “all” interpretation that the implementation currently provides?

**Comment by liblit** [comment]
Further experimentation shows that one can get the “any” behavior by using `:after` multiple times:

``` elisp
(use-package delayed
  :after a
  :after b
  :after c
  :after d)
```

Using `pp-macroexpand-last-sexp` we see that this turns into:

``` elisp
(progn
  (eval-after-load 'a
    '(require 'delayed nil t))
  (eval-after-load 'b
    '(require 'delayed nil t))
  (eval-after-load 'c
    '(require 'delayed nil t))
  (eval-after-load 'd
    '(require 'delayed nil t)))
```

So it seems that `:after` can yield both “any” and “all” behaviors, depending on how it is used.  Perhaps the documentation can make this more clear?

**Comment by basil-conto** [comment]
@liblit Indeed, this relatively new feauture is currently undocumented, save for the commit message which introduced it: 63459d40ed9cc70c476dd6fb5810c720bd5ac78f

**Comment by liblit** [comment]
Nice! Thanks for pointing out this documentation, @basil-conto. Although not easy to discover, it certainly helps me out now that I know where to find it.

**Comment by jwiegley** [comment]
You can get the "any" behavior with the keyword `:any`:

``` elisp
    :after (:any a b c d)
```

The default is `:all` behavior, and so the documentation should be changed to reflect this.
