### ISSUE TITLE
Document :delight keyword in the README

### ISSUE THREAD

**Issue by Silex** [jwiegley/use-package#481]
:-)

ping @darkfeline

**Comment by joewreschnig** [comment]
I can do this, if it wouldn't be stepping on anyone's toes...

**Comment by Silex** [comment]
@joewreschnig: I don't think anyone will object

**Comment by joewreschnig** [comment]
I don't think the last example is very good; people are likely to get hung up on the `emacs` package, which isn't referred to much. But it's the only time in my init.el I delight two modes for one package; it's rare to even have two modes in a package, let alone want to delight both.

**Comment by Silex** [comment]
:+1: 

Closing, next comments will be on the PR
