### ISSUE TITLE
Binding to user-defined keymap

### ISSUE THREAD

**Issue by jabranham** [jwiegley/use-package#482]
I think I'm running into an inconsistency between `(bind-keys ...)` and the `:bind-keymap` argument of use-package. I'm currently loading multiple-cursors like this:

```
(use-package multiple-cursors
  :ensure t
  :demand t
  :commands (mc/edit-lines mc/mark-all-like-this)
  :config
  (bind-keys :prefix "C-c m c"
             :prefix-map multi-cursors-map
             ("l" . mc/edit-lines)
             ("n" . mc/mark-next-like-this)
             ("p" . mc/mark-previous-like-this)
             ("a" . mc/mark-all-like-this)))
```

But would like to defer the package loading. I thought that I could use `:bind-keymap` to set up the autoloads:

```
(use-package multiple-cursors
  :ensure t
  :commands (mc/edit-lines mc/mark-all-like-this)
  :bind-keymap   ("C-c m c" . multi-cursors-map)
  :bind
  (:map multi-cursors-map
        ("l" . mc/edit-lines)
        ("n" . mc/mark-next-like-this)
        ("p" . mc/mark-previous-like-this)
        ("a" . mc/mark-all-like-this)))
```

But this compains about multi-cursors-map not being defined in the package. The documentation of `use-package` is actually right here; it specifically states that :bind-keymap only binds to an auto-loaded keymap defined in the package. 

So I guess my question is: Is there currently a way to do what I'm attempting to do, and if not is it possible to modify `:bind-keymap` to create a prefix map that doesn't already exist?

**Comment by jwiegley** [comment]
This should work now, and even better, the `:commands` is unnecessary.

**Comment by jabranham** [comment]
This doesn't work for me. From emacs -q:

```
(add-to-list 'load-path "~/.emacs.d/lib/use-package")
(require 'use-package)

(use-package simple
  :bind-keymap ("C-t " . my/transpose-map)
  :bind
  (:map my/transpose-map
	("w" . transpose-words)))
```

results in a void-variable error for my/transpose-map

**Comment by jwiegley** [comment]
Is `my/transpose-map` defined in `simple`?

**Comment by jabranham** [comment]
No, it was my hope/wish that the :bind-keymap would set that up, similar in
how it can in (bind-keys ...)

**Comment by jwiegley** [comment]
Ah, I see. No, you'll have to add this:

```
  :init (defvar my/transpose-map (make-sparse-keymap))
```

**Comment by jwiegley** [comment]
(that might even have to be in the `:preface`)

**Comment by jwiegley** [comment]
@jabranham Actually, I had forgotten, this is the intended syntax for your use case:

``` elisp
(use-package simple
  :bind (:prefix-map my/transpose-map
         :prefix "C-t"
         ("w" . transpose-words)))
```

**Comment by jabranham** [comment]
Perfect, thanks a ton!
