### ISSUE TITLE
dynamically generate symbols for autoloading

### ISSUE THREAD

**Issue by CeleritasCelery** [jwiegley/use-package#485]
I know that the `:command` property should take a symbol or a list of symbols. Is there a way to dynamically create a list of symbols name beforehand and then pass them to `:commands` when use-package is called? I have not been able to get this to work.

**Comment by jwiegley** [comment]
``` lisp
(defun foo () ...)

`(use-package bar
    :commands ,(foo)
  )
```

**Comment by CeleritasCelery** [comment]
Thanks for you reply. Though that doesn't seem to work for me. The following
```lisp
(defun foo () 'realgud:perldb)

`(use-package realgud
    :commands ,(foo))
```
doesn't create an autoload for `realgud:perldb`. Is there something special I need to add to the body of `foo`?

**Comment by jwiegley** [comment]
hmm... you may need an `(eval ...)` around the backtick'd form.

**Comment by CeleritasCelery** [comment]
That worked! Thanks!
