### ISSUE TITLE
for keybinding, :bind and :config doesn't work for artist-mode 

### ISSUE THREAD

**Issue by introom** [jwiegley/use-package#486]
```
  (use-package artist-mode
    :ensure nil
    :bind (:map artist-mode-map
                ([s-mouse-1] . artist-mouse-choose-operation))
    :config
    (define-key artist-mode-map [s-mouse-1] #'artist-mouse-choose-operation))
```
Either the :bind nor the :config part will successfully bind the [s-mouse-1].

However, 
this works.
(with-eval-after-load "artist"
   (define-key artist-mode-map [s-mouse-1] 'artist-mouse-choose-operation))

**Comment by basil-conto** [comment]
I suspect this will work:

```elisp
(use-package artist
  :bind (:map artist-mode-map
              ([s-mouse-1] . artist-mouse-choose-operation)))
```

Note that `lisp/textmodes/artist.el` provides the feature `artist`, not `artist-mode`. See the Elisp Manual node on [Named Features](https://www.gnu.org/software/emacs/manual/html_node/elisp/Named-Features.html) for more information on this.

Furthermore, `(use-package foo :config (ignore))` and `(use-package "foo" :config (ignore))` effectively expand to `(with-eval-after-load 'foo (ignore))` and `(with-eval-after-load "foo" (ignore))`, respectively. See the Elisp Manual node on [Hooks for Loading](https://www.gnu.org/software/emacs/manual/html_node/elisp/Hooks-for-Loading.html) for a brief description of their differences.

**Comment by introom** [comment]
@basil-conto yes. my fault. long time not using use-package.
Thanks for your help.

**Comment by basil-conto** [comment]
@introom Glad to help. :)
