### ISSUE TITLE
use-package for built-in packages the right way

### ISSUE THREAD

**Issue by technician77** [jwiegley/use-package#491]
I'm not a coder but there seems to be a difference between built-in packages. Some are shown in `*Packages*` buffer like ediff and a lot are not. For example ediff is shown, ibuffer is not. My conclusion is that ibuffer is not a package in the strickter sense.

1. Can anyone expain why ibuffer.el (and many others) do not show up in `*Packages*` and others do?
2. I know people use `use-package ibuffer` but is this formally correct since it might not be a package in the strickter sense. Does the difference have any practical consequences on use-package usage?
3. Is it at all a good practice to use use-package on built-in packages?

I might be nitpicking here but knowing is better than using the "it-seems-to-work-why-bother-mode".

**Comment by npostavs** [comment]
ediff and ibuffer predate the introduction of package.el. I think ediff showing up in the `*Packages*` list is kind of an accident; it happens to have a `;; Version: 2.81.4` line which I guess is picked up by package.el.

`use-package` also predates package.el, so using it for non-package.el packages is fine and even expected. The package.el integration (i.e., `:ensure`) is more of an afterthought.

**Comment by vyp** [comment]
As far as I understand use-package is for features, not packages.

**Comment by basil-conto** [comment]
@vyp Thanks to the `:ensure` keyword, as @npostavs describes, `use-package` deals with both features and packages (in the `package.el` sense).

**Comment by therockmandolinist** [comment]
@technician77 as for whether it's good practice - why not? As others have said, use-package works for packages _and_ features (which includes built-in packages), and gives you a way to lazy load bindings/configuration for any given feature. For example, I have a fairly extensive ERC config that it wouldn't make much sense to load every time emacs starts up, so I configure it with use-package (and a couple `with-eval-after-load`s, which use-package uses under the hood anyway (well, it uses `eval-after-load`).

**Comment by technician77** [comment]
Thanks for all the replies. I'll migrate now "the rest" to use-package.
