### ISSUE TITLE
describe-personal-keybindings F-Keys Command and Comment not shown as links

### ISSUE THREAD

**Issue by technician77** [jwiegley/use-package#492]
Just look at the screenshot. Command and Comments are not formated as links if they are single  F-Keys.
Doesn't seem right to me.

Is it much work to enhance the sorting? F12 should be at the bottom. At least it would look nicer.

![image](https://user-images.githubusercontent.com/18722291/28997319-d1ce56a8-7a11-11e7-90e1-b6587ed8b26e.png)

**Comment by jwiegley** [comment]
There's no `key<` function, sadly. All I need is a better version of `string<`, if you have one to suggest.

I don't see any underlined links at all! It's not something I'm doing, but just part of `help-mode` apparently, so I don't know how to fix it on your end.
