### ISSUE TITLE
Add delight to Package-Requires

### ISSUE THREAD

**Issue by nickmccurdy** [jwiegley/use-package#493]
I noticed that the `Package-Requires` comment includes diminish but not delight, this looks like an accidental omission (unless I'm missing something). This should be easy to add if we can figure out the minimum required version of delight.

**Comment by drot** [comment]
Actually why not drop both `diminish` and `delight` from the dependencies. That way if the user picks `delight` instead of `diminish` he doesn't end up with a redundant package.

**Comment by nickmccurdy** [comment]
Good idea, but in that case we should check for the existence of `delight` using `fboundp` in its handler and figure out if we should change `(require 'diminish nil t)`.
