### ISSUE TITLE
Melpa / Elpa being contacted every time I start emacs

### ISSUE THREAD

**Issue by eastwood** [jwiegley/use-package#494]
Hi, I apologise if this is the incorrect forum, but I'm having issues when using use-package with emacs. I love the package, but every-time I start emacs it calls out to the MELPA and ELPA repositories for a long period of time. 

I assumed I've stuffed my configuration up, because I thought it would only do this the first time I needed to install packages.

Here's my config, is this something that use-package does, or have I ****** up?

**Comment by eastwood** [comment]
https://github.com/eastwood/config/blob/master/emacs.d/org-init.org &&
https://github.com/eastwood/config/blob/master/emacs.d/init.el

**Comment by nickmccurdy** [comment]
Have you tried `package-initialize` before setting `package-enable-at-startup`? Also double check that `package-refresh-contents` isn't being run each time. Nice Org config btw, I gotta try that myself.

**Comment by eastwood** [comment]
Thanks! Yea it's super useful for both reading + writing :) 
I have them in the reverse order. I'll try and change and report back.

For the moment, removing `:ensure t` from all packages, seemed to solve it, so I suspect this is something related to `use-package`

**Comment by eastwood** [comment]
Yea the order didn't change anything. I believe it has something to do with `:ensure t`. Removing them, sped things up considerably!

All good, I'll just have to add the global back when I install from scratch :)

**Comment by Silex** [comment]
I have the same problem... I'll see if I can find out why. It didn't happen in `25.1`, but it's happening since I upgraded to `25.2`.

**Comment by Silex** [comment]
Okay, I found out this happens because one of the package I want to install is not available anymore in MELPA. The package in question was `crontab-mode`.

An easy way to find out is to do `emacs --debug-init`

**Comment by eastwood** [comment]
Ah! Okay, I'll attempt to replicate your steps and report back. Thanks @Silex
