### ISSUE TITLE
The documentation does not mention how to install use-package

### ISSUE THREAD

**Issue by jbulow** [jwiegley/use-package#497]
There is no such package in melpa. Where to find it?

**Comment by jwiegley** [comment]
Based on http://cachestocaches.com/2015/8/getting-started-use-package/, it is in MELPA.

**Comment by nickmccurdy** [comment]
```emacs
(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("org" . "http://orgmode.org/elpa/")
                         ("gnu" . "https://elpa.gnu.org/packages/")))

(package-initialize)
(package-refresh-contents)
(package-install 'use-package)
```

**Comment by TeMPOraL** [comment]
Is this the recommended thing to put on top of one's .emacs? Because I've been reading through #219, and I see more complicated versions.

Anyway, it would be great to have an official "I have a fresh Emacs, I want to use use-package for my config, how do I start" guide officially in the README.

**Comment by nickmccurdy** [comment]
I read https://github.com/jwiegley/use-package/commit/f6dbfed2732c26e6631412bb865b55f99d0240ad. Since I install with `package-install`, would it be best to put that in `eval-when-compile` or before it?

**Comment by jwiegley** [comment]
I have no idea what difference that would make, can others answer?

**Comment by npostavs** [comment]
I believe the most correct would be to have it inside the `eval-when-compile`, just like where the `add-to-list` call is in the non-package.el example. Although if you don't compile your .emacs putting it before would have the same effect in practice.
