### ISSUE TITLE
Document `:defer-install` keyword

### ISSUE THREAD

**Issue by Silex** [jwiegley/use-package#498]
Both in the docstring and README.md

@raxod502: given you did most of the implementation, maybe you want to take a shot at this? I believe simply rewording the commit message of 53c70aff266fd3479ede22fbe275d09272e6bbae would work

**Comment by raxod502** [comment]
I'll get to it at some point. Thanks for pushing the issue; documentation is not a strong point of many of the current parts of `use-package`.

**Comment by Silex** [comment]
Yeah, I've opened around 3-4 of these tickets now. Whenever I encounter a undocumented keyword I make an issue, documentation is important, even if it is very minimalist.

**Comment by Silex** [comment]
Heck, I don't even know what `:defer-install` does but would this work?

```
defer-install: If true, installs the package only when necessary (when then package actually needs to be loaded). By default it is set to false. Also see variable package-always-defer-install.
```

**Comment by thomasf** [comment]
I would probably prefer if all or most of the readme was moved into the docstring.  It's annoying that all of the documentation isn't available from inside emacs.. 

Another solution could be to package the readme.md into the elpa package and add a use-package-readme function which just opens it in a read only buffer or something like that.

**Comment by Silex** [comment]
@thomasf: most packages uses the README for meaningful documentation. But sure, the docstring should also contain the basic explanations (e.g the keywords). I don't think it makes sense to show a lot of examples in the docstring (except maybe for the basic ones).

**Comment by thomasf** [comment]
yeah, info pages is the proper place for longer format documentation text inside of emacs so packaging the readme or converting it into info-formatted would work as well.

I don't subscribe to the idea having lots of documetation in readme for any kind of project, it's much better if the readme  just contain general description and project meta information and use a proper documentation system  for the rest, there is usually a defacto standard for documentation for most languages or situations.

**Comment by thomasf** [comment]
Even if only a simple markdown format is used it's it's usually good to separate them into README, INSTALL, HACKING, DOCS, INSTALL or something like that.

**Comment by Silex** [comment]
Oh, yeah for sure what you suggest would be even better... but first things first :smile: First *at least* get everything somewhat documented, then think about organisation... tho maybe having a nice organisation would increase interest into documenting things. Mmmh.

**Comment by raxod502** [comment]
Oh, let me be clear, I feel just as strongly about documentation as you do. For instance, look at the docs for my project [`straight.el`](https://github.com/raxod502/straight.el). The issue in this case is that I'm actually working on a [replacement for `use-package`](https://github.com/raxod502/with-feature) and therefore have issues related to `use-package` at a lower priority. But, I do promise to get to this.

By the way, that commit message you quoted was actually horribly out of date, since I later changed the approach. Sorry about that.

**Comment by alphapapa** [comment]
A thought: it seems to me that the UI would be clearer if `:defer-install` were replaced with something like `:ensure defer`, i.e.:
```el
(use-package package
   :ensure defer)
```
While `:ensure t` might be better described as:
```el
(use-package package
   :ensure immediate)
```
Although `:ensure` would probably be better named `:install`, so the examples would be like:
```el
(use-package package
   :install defer)
(use-package package
   :install immediate)
```

**Comment by raxod502** [comment]
I like how it looks. Unfortunately, I don't think that will work because we'd lose the ability to specify a custom package name:

```
(use-package tex-site
  :ensure auctex)
```

**Comment by alphapapa** [comment]
Well, I guess the non-package-name keywords could be quoted, i.e.
```
(use-package package
   :install :defer)
(use-package package
   :install :immediate)
```
Or if that seems too CL-like:
```
(use-package package
   :install 'defer)
(use-package package
   :install 'immediate)
```
That should disambiguate them from package names.

**Comment by raxod502** [comment]
What would be the equivalent of

```
(use-package tex-site
  :ensure auctex
  :defer-install t)
```

though?

**Comment by alphapapa** [comment]
Well, to me it seems like it should be:
```el
(use-package auctex
  :install 'immediate)
(use-package tex-site
  :install 'defer)
```
Or if you really want to keep one conditional to the other, something like:
```el
(use-package tex-site
  :install 'defer
  :needs auctex)
```
Because I find the combination of `:defer`, `:defer-install`, and `:ensure` a bit confusing, but maybe it's just me.

**Comment by vyp** [comment]
I think @alphapapa means

``` elisp
(use-package tex-site
  :install auctex 'defer)
```

? And I guess by default the second argument would be `'immediate`?

**Comment by alphapapa** [comment]
vyp's suggestion also seems reasonable, if you don't mind the mild ambiguity of the arguments to `:install` being free-floating.  I guess it could also work like:
```el
(use-package tex-site
  :install (auctex 'defer))
```

**Comment by raxod502** [comment]
The additional quoting seems a little nonstandard to me, but honestly any of the things proposed here would be fine with me. As long as there's a way to replicate all the current use cases.

@alphapapa 

```
(use-package auctex
  :install 'immediate)
(use-package tex-site
  :install 'defer)
```

that's different. It would install package `auctex` immediately and require the `auctex` feature, then require the `tex-site` feature from the nonexistent `tex-site` package. Whereas what we want is to require the `tex-site` feature from the deferred package `auctex`.

I don't disagree that `:ensure` maybe should be `:install`. Or maybe `:package`?

**Comment by alphapapa** [comment]
> It would install package auctex immediately and require the nonexistent auctex feature, then require the tex-site feature from the nonexistent tex-site package. Whereas what we want is to require the tex-site feature from the deferred package auctex.

I see, thanks.  I'm not familiar with these packages.

> I don't disagree that :ensure maybe should be :install. Or maybe :package?

I think using imperatives is clearer, since it causes action to be taken (i.e. it's not "packaging" anything).

**Comment by raxod502** [comment]
Yeah, `auctex` is weird like that. It was a bit eye-opening for me to realize that despite the name, `use-package` is centered around features, not packages. It's just that usually, the package name is the same as the feature name, and you can just pass `:ensure t` and use the default.

**Comment by vyp** [comment]
Yeah use-package should really be named use-feature in my opinion.
