### ISSUE TITLE
does :load-path support dir been calculated?

### ISSUE THREAD

**Issue by tastuteche** [jwiegley/use-package#500]
hello guys:
does :load-path support dir been calculated?
when I try:
(use-package speech-tagger
  :bind
  (("C-x 7 t" . speech-tagger-tag-dwim)
   ("C-x 7 c" . speech-tagger-clear-tags-dwim)
   )
  :defer t
  :load-path (expand-file-name "lib/speech-tagger/emacs" app-emacs-dir)
  )
got this error:
Debugger entered--Lisp error: (void-variable expand-file-name)
  symbol-value(expand-file-name)
  eval((symbol-value (quote expand-file-name)))
  (use-package-normalize-paths label (eval value))
  (let ((value (use-package-normalize-value label arg))) (use-package-normalize-paths label (eval value)))
  (cond ((and arg (or (symbolp arg) (functionp arg))) (let ((value (use-package-normalize-value label arg))) (use-package-normalize-paths label (eval value)))) ((stringp arg) (let ((path (if (file-name-absolute-p arg) arg (expand-file-name arg user-emacs-directory)))) (list path))) ((and (not recursed) (listp arg) (listp (cdr arg))) (mapcar (function (lambda (x) (car (use-package-normalize-paths label x t)))) arg)) (t (use-package-error (concat label " wants a directory path, or list of paths"))))
  use-package-normalize-paths(":load-path" expand-file-name t)

**Comment by asimpson** [comment]
:wave: I applied some formatting to your issue. I'm not sure I understand your question. What do you mean by "support dir"?

---

hello guys,
does `:load-path` support dir been calculated?
when I try:

```elisp
(use-package speech-tagger
  :bind  (
    ("C-x 7 t" . speech-tagger-tag-dwim)
    ("C-x 7 c" . speech-tagger-clear-tags-dwim)
  )
  :defer t
  :load-path (expand-file-name "lib/speech-tagger/emacs" app-emacs-dir))
```
got this error:
```
Debugger entered--Lisp error: (void-variable expand-file-name)
symbol-value(expand-file-name)
eval((symbol-value (quote expand-file-name)))
(use-package-normalize-paths label (eval value))
(let ((value (use-package-normalize-value label arg))) (use-package-normalize-paths label (eval value)))
(cond ((and arg (or (symbolp arg) (functionp arg))) (let ((value (use-package-normalize-value label arg))) (use-package-normalize-paths label (eval value)))) ((stringp arg) (let ((path (if (file-name-absolute-p arg) arg (expand-file-name arg user-emacs-directory)))) (list path))) ((and (not recursed) (listp arg) (listp (cdr arg))) (mapcar (function (lambda (x) (car (use-package-normalize-paths label x t)))) arg)) (t (use-package-error (concat label " wants a directory path, or list of paths"))))
use-package-normalize-paths(":load-path" expand-file-name t)
```

**Comment by vyp** [comment]
@asimpson asking if `:load-path` supports the directory being calculated, for example with `expand-file-name`.

**Comment by basil-conto** [comment]
@asimpson I believe @tastuteche is asking whether the `:load-path` keyword evaluates its value at runtime, as supported by his example.

The answer to this is no, though, as with all [macros](https://www.gnu.org/software/emacs/manual/html_node/elisp/Macros.html), the workaround is to [pass the quoted macro form to `eval`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Evaluation.html):

```el
(eval
 `(use-package speech-tagger
    :defer t
    :load-path ,(expand-file-name "lib/speech-tagger/emacs" app-emacs-dir)
    :bind (:map ctl-x-map
           ("7 t" . speech-tagger-tag-dwim)
           ("7 c" . speech-tagger-clear-tags-dwim))))
```

**Comment by basil-conto** [comment]
For anyone interested in a long discussion linking to and ever-so-slightly touching on some of the issues around static/dynamic `load-path` calculations, see #487.

**Comment by basil-conto** [comment]
See also the related issues #156 and #158.

**Comment by npostavs** [comment]
`use-package` allows wrapping in `lambda` for some keywords, I believe `:load-path` is on of those, so this should work:

```elisp
(use-package speech-tagger
  :defer t
  :load-path (lambda () (expand-file-name "lib/speech-tagger/emacs" app-emacs-dir))
  :bind (:map ctl-x-map
              ("7 t" . speech-tagger-tag-dwim)
              ("7 c" . speech-tagger-clear-tags-dwim)))
```
Although I think this evaluates at compile time, so you have to be careful about how `app-emacs-dir` is defined.

> See also the related issues #156

Note, this is from an older version of `use-package` when prefixing with a `,` worked, but this was replaced with the `lambda` syntax.

**Comment by basil-conto** [comment]
@npostavs Neat!
