### ISSUE TITLE
Install all packages declared with use-package from the command line

### ISSUE THREAD

**Issue by pwalsh** [jwiegley/use-package#501]
I'd like to be able to run a command to open emacs, install all packages, and then quit. I do not see how I can do this when I manage all my packages with use-packages. Is this possible?

**Comment by pwalsh** [comment]
Thanks @nickmccurdy 

I guess the part that is unclear to me is calling my "... use-package calls with :ensure".

**Comment by nickmccurdy** [comment]
https://github.com/jwiegley/use-package#for-packageel-users

**Comment by dieggsy** [comment]
Or if you don't want to `:ensure` every package, eval `(setq use-package-always-ensure t)` somewhere before loading the init file in `emacs -batch` (or just put it in your init if you'd like).

**Comment by nickmccurdy** [comment]
Another option is to use the `package-selected-packages` customize variable generated after running `use-package` forms.

**Comment by pwalsh** [comment]
oh, looks like for my use case, it is as simple as ...

`emacs --batch --eval '(load "~/.emacs.d/init.el")'`

**Comment by pwalsh** [comment]
thanks for help all.

**Comment by dieggsy** [comment]
@pwalsh you can get at it more directly with `emacs --batch --eval -l ~/.emacs.d/init.el`
