### ISSUE TITLE
:config not being evaluated after :bind

### ISSUE THREAD

**Issue by WorldsEndless** [jwiegley/use-package#505]
I have several highly-used packages that don't seem to be loading their :config parameters. An example line for one would be this: 

```
(use-package pdf-tools
  :ensure t
  :bind (:map pdf-view-mode-map
              ("G" . pdf-view-goto-page))
  :config
  (pdf-tools-install)
  (setq pdf-view-continuous t ; don't automatically jump to next page
        pdf-misc-print-programm "/usr/bin/lp"
        pdf-misc-print-programm-args '( ;"-d ODH_Workroom"
                                       "-o media=letter"
                                       "-o sides=two-sided-long-edge"))
  (add-hook 'pdf-view-mode-hook 'auto-revert-mode))
```

Despite this line, I now have to manually execute "pdf-tools-install" before my pdfs will open in pdf-tools. Likewise with other packagers, like GNUs, which fails to load the config file I tell it to load in my use-package :config. It seems to be related to my use of :bind, which is preventing the :config from being loaded. It seems to only happen when I'm using the `:bind (:map ... () ) form.` Help would be appreciated.

**Comment by npostavs** [comment]
The `:config` block will only loaded when the package is loaded. Does it help to add `:demand t`?

**Comment by WorldsEndless** [comment]
Ah. That :demand does it. I gather that packages with :bind defined have a different loading process than default use-packages, as I now see in the documentation; simply adding :bind parameters causes their config not to be loaded at startup, and I'm not sure when they would be loaded (e.g. PDF-Tools mentioned above isn't loaded on opening a PDF file, when I've put that line in :config). Thanks for your help; the problem was confusing to me. I had thought that autoloading was the default and didn't expect :bind to be changing load order, so adding a :bind to a previously working use-package statement produced unexpected behavior. Perhaps the readme can be clarified to warn about this.

**Comment by npostavs** [comment]
This is explained under "Notes about lazy loading" in the README: https://github.com/jwiegley/use-package#notes-about-lazy-loading
