### ISSUE TITLE
Using :ensure package with :pin pins the wrong package name

### ISSUE THREAD

**Issue by jabranham** [jwiegley/use-package#506]
The following:

```
(use-package ess-site  :ensure ess :pin melpa-stable)
```

Puts `ess-site` into `package-pinned-packages` instead of `ess`. I'd expect it to put `ess` into `package-pinned-packages` instead.

**Comment by tomterl** [comment]
The readme suggests the behavior you experience to be the correct one. Per the examples given, `:ensure t` ensures that ess-site will be installed, `:ensure ess` will do the same, as long as `ess` is a non-nil symbol -- or am I missing something?

**Comment by jabranham** [comment]
It's not ensure that's doing the wrong thing --- it's :pin. I'd like it to add the package that was :ensure'ed to `package-pinned-packages`, but instead it adds whatever package was in the `use-package` call.

**Comment by tomterl** [comment]
Ah - so `:pin` should pin both packages, not 'ess instead', but 'ess in addition to ess-site', that makes sense, indeed.

**Comment by jwiegley** [comment]
Can you show me what the macro-expanded code *should* look like for an example declaration?  I don't use either `:pin` or `:ensure`, so I want to get this right. Thanks.

**Comment by jabranham** [comment]
In between posting this bug and now, I've switched to borg instead of package.el, so this isn't directly applicable for me anymore (and thus I can't produce the expanded code). 

However, I think that a declaration like:

```
(use-package ess-site 
    :ensure ess
    :pin melpa-stable)
```

should result in an element like `(ess . "melpa-stable")` getting appended to `package-pinned-packages`. The current behavior is that `(ess-site . "melpa-stable")` gets added to `package-pinned-packages`.

**Comment by jwiegley** [comment]
@jabranham What about this case:

``` elisp
   (use-package ess-site 
     :ensure ess1
     :ensure ess2
     :ensure ess3
     :pin melpa-stable)
```

**Comment by jwiegley** [comment]
What we could do is add a new keyword, `:pinning`, just for overriding the decision of what name is pinned.

**Comment by jabranham** [comment]
I didn't realize you could `:ensure` different packages. Makes sense though.

I'm not sure that `:pinning` is needed. Couldn't we just pin `ess-site`, `ess1`, `ess2`, and `ess3` to `melpa-stable`?

Or maybe make that the default behavior, and provide `:pinning` in case it needs to be overridden (e.g. if `ess3` needs to be pinned to `melpa` instead of `melpa-stable`?)

**Comment by jwiegley** [comment]
Sounds reasonable to me, but I'd like to hear from others who are using the ensure functionality.

**Comment by jwiegley** [comment]
Pinging @kleinschmidt @tpapp @Silex @waymondo @raxod502 @purcell for thoughts/opinions.

**Comment by kleinschmidt** [comment]
I actually got rid of my use of multiple-`:ensure` in favor of explicitly `:require` (when I thought I was using it incorrectly) so I have no opinion here.  I also wasn't pinning anything.

**Comment by tpapp** [comment]
I am not using `:pin`, but if I wanted to `:ensure` a *different* package and make sure it is from a particular repo, I could imagine the syntax
```elisp
(use-package ess-site 
  :ensure (ess :pin melpa-stable))
```

**Comment by jwiegley** [comment]
I like that idea for syntax, @tpapp.

**Comment by jwiegley** [comment]
Two forms are now allowed: `:ensure PKG`, which overrides the current package name, and is allowed multiple times; and `:ensure (PKG :pin ARCHIVE)`, which pins a particular ensured package to a specific archive. `:ensure` no longer accepts a list (which was new behavior today anyway).
