### ISSUE TITLE
Update the README to mention the use-package sharing subreddit

### ISSUE THREAD

**Issue by escherize** [jwiegley/use-package#509]
Hello,

I love use-package. I was unaware of a way to share them with people I don't know (what could go wrong?) so I created this subreddit: https://www.reddit.com/r/use_package/

Please tell me what you think!

Thanks.

**Comment by jwiegley** [comment]
Huh, neat idea. I've subscribed and will follow. I agree this should be added to the README if it proves useful.

**Comment by jwiegley** [comment]
That subreddit seems to have stalled?

**Comment by escherize** [comment]
Yeah, it has.
