### ISSUE TITLE
Upgrade code to 2.0

### ISSUE THREAD

**Issue by biocyberman** [jwiegley/use-package#510]
I am trying to update this package: https://github.com/chrisbarrett/spacemacs-layers/blob/master/cb-use-package-extensions.el
It uses the old syntax of `use-package-normalize-pairs` that exists until this commit: b566b8cc
How do I rewrite it to fit the new `use-package-normalize-pairs` signature?

**Comment by biocyberman** [comment]
My current attempt like this:

```
(defun use-package-normalize/:evil-bind (name keyword args)
  (use-package-only-one (symbol-name keyword) args
    (lambda (label args)
      (use-package-normalize-pairs
       (lambda (k) (or (stringp k) (vectorp k)))
       (lambda (b) (or (symbolp b) (stringp b)))
       name label args))))
```

**Comment by npostavs** [comment]
> It uses the old syntax of use-package-normalize-pairs that exists until this commit: b566b8c

I guess you actually mean 7956d40eed57d6c06bef36ebc174cf57d934e30d.

cb-use-package-extensions.el currently passes `nil` for the `allow-string-cdrs` argument, so to stay equivalent your second lambda should be `(lambda (b) (symbolp b))` or just `#'symbolp`.

**Comment by biocyberman** [comment]
@npostavs Thanks. Yes you are right, b566b8c was the last commit before the function got changed on 7956d40 to the current form.
