### ISSUE TITLE
use-package doesn't export packages's autoloads

### ISSUE THREAD

**Issue by amosbird** [jwiegley/use-package#511]
I'm using `use-package` to load skew-mode. I did
```
(use-package skewer-mode
  :config
  (skewer-setup))
```
but it fails with void definition of `skewer-setup`. I can see there is a `skewer-mode-autoloads.el` in the package's root directory. Why does it not work?

**Comment by npostavs** [comment]
You called `package-initialize` too late maybe?

**Comment by amosbird** [comment]
Um, what do you mean by too late?

**Comment by npostavs** [comment]
> Um, what do you mean by too late?

Later than the call to `use-package`.

**Comment by amosbird** [comment]
Oh, i see. Thanks.
