### ISSUE TITLE
empty :commands field breaks underlying functions

### ISSUE THREAD

**Issue by CeleritasCelery** [jwiegley/use-package#512]
Reproduction steps:
eval the following sexp
```
(use-package nameless ;; any package will work
  :commands)
```
notice that the C source code function `forward-word` is no longer defined. (You can test it with `M-f`).

I came across this while implementing the solution in #485. if my code ever resolved to an empty list I would start to get weird behavior all over Emacs. Eventually I tracked it down to the bug I describe above. I would have assumed that having a field empty would do nothing, but it breaks Emacs.  Setting `:command` to an empty list has the same effect.

**Comment by npostavs** [comment]
> notice that the C source code function forward-word is no longer defined.

It's still defined, but it fails with error `forward-word: Symbol's function definition is void: nil`. Seems to be due the use-package form expanding to `(autoload #'nil "nameless" nil t)`. After evaluating that, `(fboundp nil)` returns `t`, so when `forward-word` finds `nil` in `find-word-boundary-function-table` it tries to funcall it.

Doing `(fset nil nil)` puts things back to normal.

**Comment by CeleritasCelery** [comment]
Indeed that does seem to fix it. I am impressed you debugged that so quickly.
