### ISSUE TITLE
:ensure-system-package keyword

### ISSUE THREAD

**Issue by waymondo** [jwiegley/use-package#516]
Hi @jwiegley,

I wrote this keyword plugin recently for ensuring certain system binaries exist with emacs `use-package` declarations:
https://github.com/waymondo/use-package-ensure-system-package

The first issue opened was to suggest reaching out to see if it was worthy of being included in `use-package` itself. I remember when I came up with [`use-package-chords`](https://github.com/waymondo/use-package-chords) you suggested trying the keyword plugin route, and it worked well and just exists out there on MELPA. I'm guessing that is still the preferred path going forward, especially given the fact this would introduce another package dependency, but I figured I would offer to create a PR for it if its deemed useable enough for the core package.

Or maybe a just list of plugins in the README for quick reference to potentially useful extensions would suffice?

https://github.com/waymondo/use-package-ensure-system-package/issues/1

**Comment by jwiegley** [comment]
I'd say keep it in a separate file, but I'd be happy to include any use-package extensions as part of the GitHub repository (and hence the distribution). If that works for you, let me know and I'll give you committer rights.

**Comment by waymondo** [comment]
Cool, yeah that would totally work for me. I've signed the Emacs copyright assignment forms and all as well.

**Comment by jwiegley** [comment]
@waymondo Feel free to push in when ready; if you could extend the docs too that would be great.

**Comment by waymondo** [comment]
Awesome, I will add and update the docs today or this weekend. And great job with the huge push of updates you've done this week!

**Comment by jwiegley** [comment]
If you'd like to add a new test too, that would be even better. :)  I'm trying to make sure every feature, and every meaningful combination of features, is being tested in a way that will catch future breakages. Already this effort has revealed numerous subtle bugs!

**Comment by waymondo** [comment]
Hi John, I didn't see your test suggestion until after I just pushed right now. I will add some tests this evening or sometime this week. Let me know if there's anything about the implementation or documentation you'd like me to change. Obviously feel free to assign any issue that comes up that is related to these files too.

**Comment by jwiegley** [comment]
@waymondo Thank you!  I'm going to be renaming the `up-*` files to `use-package-*`, so even if you see that, you don't need to change what you've added.
