### ISSUE TITLE
`:custom` keyword broken in newest commit to normalization

### ISSUE THREAD

**Issue by danzhu** [jwiegley/use-package#518]
I just pulled the newest commits and commit 660bca0391f09b5fdbf8c506746b9c26e6423684 changes the format of value for `:custom` keyword from e.g.
```
:custom
(nlinum-format " %d ")
(nlinum-highlight-current-line t)
```
to
```
:custom
((nlinum-format " %d ")
 (nlinum-highlight-current-line t))
```
Is this intended? The README file still refers to the old format, so if this is intended then perhaps it can be updated?
However I find the old format cleaner, so is there a reason behind the format change?

**Comment by jwiegley** [comment]
I'll change it to allow the old format.
