### ISSUE TITLE
Regression with company-mode

### ISSUE THREAD

**Issue by drot** [jwiegley/use-package#524]
Recent updates have introduced this warning being displayed while waiting for company completion:

![2017-11-29-215500_752x717_scrot](https://user-images.githubusercontent.com/85483/33398707-2a855730-d550-11e7-80fe-59d7c53761a6.png)

Reproduced with the following:
1. Starting with `emacs -Q` with `use-package` and `company` already installed
2. M-x `package-initialize`
3. M-x `global-company-mode`
4. Start typing halfway a `use-package` keyword and waiting for the company completion.

Tested with: `GNU Emacs 26.0.90 (build 1, i686-pc-linux-gnu, GTK+ Version 3.22.26) of 2017-11-26`

**Comment by npostavs** [comment]
This sounds vaguely familiar. Here's a repro without `company`:

`emacs -Q -L . -l use-package`

```elisp
(use-package bind-key
   :ens
```
Hit `C-M-i`.

**Comment by basil-conto** [comment]
This looks a lot (though I'm not 100% certain) like an error I've seen when performing in-buffer completion inside a `benchmark-run-compiled` form in, say, an `ielm` buffer. I'll get back to this if I can reproduce it.

**Comment by basil-conto** [comment]
Aha:

1. `emacs -Q` (I get similar results on versions 24.5, 25.2 and latest `master`)
2. ```el
   (benchmark-run-compiled 1
     (let ((foobarbaz 1))
       (+ foob
    ```
3. Result: `*Compile-Log*` buffer pops up with `Warning: reference to free variable ‘elisp--witness--lisp’` (in Emacs 24.5 it's `lisp--witness--lisp` instead).

If one evaluates `M-: (setq lexical-binding t) RET` between steps 1 and 2, the `*Compile-Log*` buffer complains about `Warning: Unused lexical variable ‘foobarbaz’` in addition to the aforementioned free variable warning.

Am I correct in suspecting these are manifestations of the same bug, possibly in `lisp/progmodes/emacs-lisp.el`, but probably unrelated to `use-package`?

**Comment by npostavs** [comment]
Basically, lisp completion expands macros in order to decide which what variables are bound. When expanding a macro causes side-effects, you get issues like this one. Last time it was #260.

See `elisp--local-variables`.

**Comment by basil-conto** [comment]
Ah, makes sense, thanks.

**Comment by jwiegley** [comment]
@npostavs Is this something not to be fixed in `use-package` then?

**Comment by npostavs** [comment]
I see that `elisp--local-variables` is already suppressing errors during macroexpansion, so it would probably make sense for it to suppress warnings as well. That would fix this issue.

**Comment by aaronjensen** [comment]
What ended up being the resolution on this?

**Comment by jwiegley** [comment]
This appears to be a macro expansion problem in Emacs, and not something I can address in `use-package`. I still have no resolution as of yet.

**Comment by npostavs** [comment]
See [Emacs Bug#29573](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=29573).
