### ISSUE TITLE
:ensure nil is now broken

### ISSUE THREAD

**Issue by tpapp** [jwiegley/use-package#526]
After  32b536f1b90428d288b217475eca78bc77705aea,  `:ensure nil` in `use-package` gives

```
Warning (initialization): An error occurred while loading ‘/home/tamas/.emacs.d/init.el’:

error: use-package: :ensure wants an optional package name (an unquoted symbol name)

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

**Comment by CSRaghunandan** [comment]
Also noticed the same error after updating use-package a few mins ago

**Comment by tpapp** [comment]
BTW, I no longer think that it was the commit I linked that breaks this.

Also, the problem occurs in some
```emacs-lisp
(use-package some-package
    :ensure nil)
```
statements that basically replace
```emacs-lisp
(require 'some-package)
```
Is this OK, or a misuse of `use-package`?

**Comment by Silex** [comment]
> Is this OK, or a misuse of use-package?

This is ok, it's the only way to override `use-package-always-ensure`

**Comment by tpapp** [comment]
I have bisected, and
```
a1c736f36dae12773e6caf06e547bb6eaaf57e09 is the first bad commit
commit a1c736f36dae12773e6caf06e547bb6eaaf57e09
Author: John Wiegley <johnw@newartisans.com>
Date:   Wed Nov 29 14:41:12 2017 -0800

    Allow :bind ("C-c C-c" . (lambda () (ding))) and #'(lambda ...)
    
    Fixes #333
    Fixes #461

:100644 100644 eb24d2396e3bee08306ab06a1aafde086f10e594 ca6c2a7ceed641e735c110955a091a15f578e3ec M      bind-key.el
:100644 100644 c52c3810439c960a634b769021170c7f9c06d878 830ca644990e0b9111f5f43463ab5b7fb73fed2e M      use-package-tests.el
:100644 100644 68c10f3d1758fd2eed947ceec75a8077c2b37405 2b5de46ca35d79b3bf5126a6f8e93330396cc09d M      use-package.el
```

**Comment by Silex** [comment]
Here is a link to the above commit: a1c736f36dae12773e6caf06e547bb6eaaf57e09

**Comment by oantolin** [comment]
That commit changes a bunch of occurences of `symbolp` to `use-package--non-nil-symbolp`. I don't know how many of those are correct, but the one in `use-package-normalize/:ensure` certainly isn't, because `:ensure nil` should be allowed.

The error message in that function is also short-sighted. It says: ":ensure wants an optional package name (an unquoted symbol name)". It should mention that besides a package name you can use `t` or `nil` (and, of course, the function should actually let you use them).

**Comment by Silex** [comment]
@jwiegley: summoning you here because this is a serious regression
