### ISSUE TITLE
[Question/Feature Request] Option for :custom after config time?

### ISSUE THREAD

**Issue by dieggsy** [jwiegley/use-package#528]
I'm not sure if this makes sense, but for some custom set options, it doesn't matter whether they are set before or after the package is loaded (I think - could be wrong about this?). In this case, it may be useful to have an additional keyword like `:custom` that runs after or at config time (`:custom-after` and `:custom-face-after`, or some modification under the `:custom` keyword?).

The only real reason is that this can keep init.el cleaner if you want to rely solely on the `:custom` mechanism. For example, if the standard value is a really long list and it doesn't matter whether the var is set before or after the package loads, it would be tedious to have to copy over the _whole_ initial list to the init file, where you could work with the original name/value of the variable if setting after the package loads.

e.g.

```emacs-lisp
(use-package eg
:custom
(eg-var '(default-1 default-2 default-3 default-4 ... my-addition)))
```
vs
```emacs-lisp
(use-package eg
:custom-after
(eg-var (cons 'my-addition eg-var)))
```
or something like

```emacs-lisp
(use-package eg
:custom
(:after
  (eg-var (cons 'my-addition eg-var))))
```

I get if this is a bit too niche, and I think it's simple enough to implement as an additional keyword on my own so i'm ok either way.

**Comment by jwiegley** [comment]
I'd suggest building this as a private keyword, and then see how useful it turns out to be for you.

**Comment by dieggsy** [comment]
Cool - just for future reference, would you accept a PR for something like this if it did turn out to be useful?
