### ISSUE TITLE
:hook for non-standard hook names

### ISSUE THREAD

**Issue by drot** [jwiegley/use-package#530]
Consider the following configuration:
```
;; Ediff restore window configuration
(use-package ediff-util
  :hook (ediff-after-quit-hook-internal . winner-undo))
```
This will apply `winner-undo` to `ediff-after-quit-hook-internal-hook` (appending the `-hook`) and thus will not work and we have to rely on the old `add-hook` way. Other non-standard hook that comes to mind is `TeX-after-compilation-finished-functions` which gets transformed into `TeX-after-compilation-finished-functions-hook`. Maybe we could drop the `-hook` appending part?

**Comment by jwiegley** [comment]
I sort of don’t like the -hook appending either, it’s a bit too magical.
I’ll remove that bit, or make it configurable.
