### ISSUE TITLE
Make bind-key optional

### ISSUE THREAD

**Issue by yyadavalli** [jwiegley/use-package#531]
Given that `diminish` and `delight` are now considered optional and not installed as dependencies, it would be nice to do the same for `bind-key`. A fully feautred alternative exists externally with `general-key` supporting `use-package`.

**Comment by jwiegley** [comment]
At least for now, `bind-key` is still too tightly integrated into the core functionality of `use-package` to be removed as easily as `:diminish` and `:ensure` were.  It can be done, but it won't happen as quickly.

Is there a particular use case for `general` that you like over `bind-key`?

**Comment by yyadavalli** [comment]
Thanks for the response.  
The main reason I prefer `general` is, I use `evil` and it has better integration for the various 'states'. I find it to be easier when binding to an arbitrary prefix in a keymap. It also has integration with `which-key`.

**Comment by jwiegley** [comment]
@yyadavalli This is now done in its own branch, `split-bind-key`. Can you please give it a try and see if it works for you?

**Comment by yyadavalli** [comment]
@jwiegley Awesome. It is working as expected. Thanks for the quick turnaround.

**Comment by yyadavalli** [comment]
The MELPA package still installs `bind-key` as dependency, I belive it should be removed from the package-requires here:
 
https://github.com/jwiegley/use-package/blob/8a82221a395619ba325a611b50938f6bbca0ebed/use-package.el#L10

**Comment by jwiegley** [comment]
Before doing so, realize that the vast majority of `use-package` users *do* use the `:bind` functionality, so I'm not so sure this one should be opt-in just yet.

**Comment by blak3mill3r** [comment]
Here is the commit dd13000588dac6f050e39324afe0c9f406e5ef8a

It's not clear to me reading the comments here, or the above commit, how I can do what @yyadavalli did (`use-package` + `general` without `bind-key`)

**Comment by blak3mill3r** [comment]
I think I get it now, sharing in case anyone else gets a little mystified, as I did:

The fix is that `use-package` no longer eagerly loads `bind-key` or has it as a package dependency, and since `general` integrates with `use-package` I can just start using `general` and when I stop using `bind-key` it will not be loaded.
