### ISSUE TITLE
:demand seems to have issues in the most recent version

### ISSUE THREAD

**Issue by terlar** [jwiegley/use-package#532]
I am running with the config:

```
(setq use-package-always-defer t
      use-package-always-ensure t)
```

And after the recent update I have started experiencing weird behavior and things not loading, I have boiled it down to have something todo with the `:demand` keyword. Some packages don't have any lazy-loading so I demand them to get them loaded. However it seems like the things with demand doesn't load.

I even tried having a package specifying some `:commands` and the autoloaded functions work, but if I put the `:demand` keyword on the same package, those autoloaded commands stop working.

Example:
```
(use-package counsel
  :commands
  (counsel-find-file
   counsel-recentf
   counsel-imenu
   counsel-bookmark
   counsel-M-x
   counsel-describe-function
   counsel-describe-variable
   counsel-describe-face
   counsel-esh-history
   counsel-grep-or-swiper))
```

vs.

```
(use-package counsel
  :demand t
  :commands
  (counsel-find-file
   counsel-recentf
   counsel-imenu
   counsel-bookmark
   counsel-M-x
   counsel-describe-function
   counsel-describe-variable
   counsel-describe-face
   counsel-esh-history
   counsel-grep-or-swiper))
```

**Comment by terlar** [comment]
Okay, that was not the full truth, seems it has to do with `:demand t` in combination with `:general`. This is something that has broken down with the newer version, but might not be a root issue in the main package.

**Comment by jwiegley** [comment]
Ah, I know what has happened. Let me add a customization variable for general to use to address this.

**Comment by jwiegley** [comment]
See e6761c4, which `general` can use to tie into use-package`s logic. Also, the communicating of commands to be autoloaded has changed. Rather than being passed as part of the "state", is now passed in another parameter. This is now the pattern to follow:

``` elisp
(defun use-package-handler/:bind
    (name keyword args rest state &optional bind-macro)
  (cl-destructuring-bind (nargs . commands)
      (use-package-normalize-commands args)
    (use-package-concat
     (use-package-process-keywords name
       (use-package-sort-keywords
        (use-package-plist-append rest :commands commands))
       state)
     `((ignore
        (,(if bind-macro bind-macro 'bind-keys)
         :package ,name ,@nargs))))))
```
