### ISSUE TITLE
`:commands` after `:init`?

### ISSUE THREAD

**Issue by seagle0128** [jwiegley/use-package#535]
I downloaded the latest build, and found the sequence of keywords was changed. Should `:commands` be after `:init`? I remember it was before. Please check.

BTW: there are quite a few bugs in the latest update :(

**Comment by jwiegley** [comment]
Can you clarify what you mean by ”:commands should be :init”, and also
what these bugs you’re seeing are?

**Comment by seagle0128** [comment]
For example, below doesn't work with the latest release, but did work before. 
The exception is `invalid function: dired-rainbow-define`. I think it's related to the sequence of keywords.

```elisp
(use-package dired-rainbow
   :commands dired-rainbow-define dired-rainbow-define-chmod
   :init (dired-rainbow-define dotfiles "gray" "\\..*"))
```

**Comment by jwiegley** [comment]
Thank you for the example, @seagle0128. I've fixed the ordering of keywords back to what it used to be, and added a test covering your use case.

**Comment by seagle0128** [comment]
Thanks for the quick fixing!
