### ISSUE TITLE
NOTICE: If use-package symbol or up-* files are missing after update

### ISSUE THREAD

**Issue by manute** [jwiegley/use-package#536]
Hi , after upgrade to the new version `use-package-20171203.1313` I have this error message on emacs startup : 

```
symbol's function definition is void: use-package
```

So it's like the package is not properly installed. 

My emacs init section for this is : 

```lisp
;; package-refresh-contents if fails
(require 'package)
(setq package-enable-at-startup nil)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))

(package-initialize)

;; Bootstrap `use-package'
(unless (package-installed-p 'use-package)
   (package-refresh-contents)
   (package-install 'use-package))
```

And for fixing that error I had to download a tag version of this pkg and do this : 
```lisp
 (eval-when-compile
   ;; Following line is not needed if use-package.el is in ~/.emacs.d
   (add-to-list 'load-path "~/.emacs.d/local/use-package")
   (require 'use-package))
```
Am I doing something wrong?

**Comment by julienXX** [comment]
I have the same issue, somehow package-list-package won't update to the latests use-package commits. I cloned use-package and copied the files in `~/.emacs.d/.cask/25.3/elpa/use-package-20171203.1313` and it works in the meantime.

**Comment by ekenberg** [comment]
Same thing here, broke after update this morning. I simply deleted the directory use-package-20171203.1313/ under my elpa-dir and restarted Emacs. Let's hope it gets fixed soon.

**Comment by Spdwal** [comment]
I update my spacemacs today, and when i opened it, I got an error, here is my error message
`
Debugger entered--Lisp error: (file-error "Cannot open load file" "No such file or directory" "up-core")
  require(up-core)
  eval-buffer(#<buffer  *load*-346650> nil "/home/spdwal/.emacs.d/elpa/use-package-20171203.1313/use-package.el" nil t)  ; Reading at buffer position 1691
  load-with-code-conversion("/home/spdwal/.emacs.d/elpa/use-package-20171203.1313/use-package.el" "/home/spdwal/.emacs.d/elpa/use-package-20171203.1313/use-package.el" nil t)
  require(use-package)
  spacemacs-bootstrap/init-use-package()
  funcall(spacemacs-bootstrap/init-use-package)
........
`
Hope to fix it soon.

**Comment by thomasf** [comment]
maybe related to https://github.com/jwiegley/use-package/issues/533 I havent read whats written there but this issue could be a duplicate.

**Comment by cryptomaniac512** [comment]
Have the same issue.

I clone this repository, checkout to tag 2.3 and install `use-package` from the `use-package.el` file (`package-install-file`) inside repository to temporary fix problem.

**Comment by f-koehler** [comment]
Going back to 2.3 might be a bit drastic. I use 4f483b6f5171819779cbc8836feeacacfef5ed55 which is a couple of days old and it works fine as far as I can tell.

**Comment by kaushalmodi** [comment]
@Spdwal [This works for now][1]

@thomasf It's already fixed on Melpa.. waiting for the next publish cycle of packages..

@cryptomaniac512 You don't need to go back that far.

@f-koehler Just a git clone of this repo and using the HEAD works (see above link).

[1]: https://github.com/jwiegley/use-package/issues/537#issuecomment-349001447

**Comment by jwiegley** [comment]
Please track https://github.com/melpa/melpa/pull/5167#issuecomment-348920874 for the upcoming resolution of this problem. Until then, I recommend using 4f483b6.
