### ISSUE TITLE
Need to update Melpa recipe? Failure to get up-*.el files.

### ISSUE THREAD

**Issue by kaushalmodi** [jwiegley/use-package#537]
After the latest update from Melpa (version 20171203.1313), I get:

```
Eager macro-expansion failure: (file-missing "Cannot open load file" "No such file or directory" "up-core") [2 times]
Warning (initialization): An error occurred while loading ‘/home/kmodi/.emacs.d/init.el’:

File is missing: Cannot open load file, No such file or directory, up-core
```

```
km²~/stow/:../dot-emacs.d/elpa_26/use-package-20171203.1313> ls                                                         
use-package-autoloads.el  use-package-pkg.el  use-package.el
```

Looks like the new `up-*.el` files are not downloaded.

**Comment by kaushalmodi** [comment]
Hmm, looks like the fix was merged on Melpa 5 hrs back ( https://github.com/melpa/melpa/pull/5167 ).. I guess it's just a waiting game. Feel free to close this issue once Melpa publishes use-package with that fixed recipe (if I don't get to that earlier).

**Comment by Atman50** [comment]
+1
use-package won't load because of missing package up-core for me.

**Comment by kaushalmodi** [comment]
@Atman50 To keep things working for now, 

- Delete all the `*.el` and `*.elc` in your `elpa/use-package-????????.????` directory
- Clone the use-package repo and copy all the `*.el` from there into that `elpa/use-package-????????.????` directory.
- Restart emacs

*Hopefully it might be just on the order of an hour or two before Melpa publishes `use-package` with that fix.*

**Comment by Atman50** [comment]
Yeah, got that done already, but thanks!

**Comment by jwiegley** [comment]
This is in the works and should be happening very soon. Please follow https://github.com/melpa/melpa/pull/5167#issuecomment-348920874 for updates.
