### ISSUE TITLE
Wrong type of argument error

### ISSUE THREAD

**Issue by endoffile78** [jwiegley/use-package#543]
I get this error on startup:

```
wrong-type-argument listp t
```

This happens will all `use-package` statements with `:ensure` and `:demand`, possibly others too. I've tried the git version too and it seems to have the same problem.

**Comment by jwiegley** [comment]
Can you show me one such statement?  Also, the output you see when you run `M-x pp-macroexpand-last-sexp` with point just after the closing paranthesis.

**Comment by endoffile78** [comment]
Example:

```
(use-package hydra
  :ensure)
```

Remoinving :ensure fixes it.

Result of `M-x pp-macroexpand-last-sexp`

```
(progn
  (use-package-ensure-elpa 'hydra 't 'nil)
  (let
	  ((use-package--warning5
		#'(lambda
			(keyword err)
			(let
				((msg
				  (format "%s/%s: %s" 'hydra keyword
						  (error-message-string err))))
			  nil
			  (ignore
			   (display-warning 'use-package msg :error))))))
	(condition-case-unless-debug err
		(if
			(not
			 (require 'hydra nil t))
			(ignore
			 (display-warning 'use-package
							  (format "Cannot load %s" 'hydra)
							  :error)))
	  (error
	   (funcall use-package--warning5 :catch err)))))
```

**Comment by jwiegley** [comment]
Excellent, fixing now.

**Comment by endoffile78** [comment]
Awesome thank you!
