### ISSUE TITLE
Seems to need a gensym function that does not exist in Emacs 25.2

### ISSUE THREAD

**Issue by oantolin** [jwiegley/use-package#547]
After recent update `use-package` seems to need a function `gensym` to be defined. A work around is to load `use-package` as follows:

```
(eval-when-compile
  (require 'cl-lib)
  (defalias 'gensym #'cl-gensym)
  (require 'use-package))
```

**Comment by dieggsy** [comment]
@oantolin this was just fixed, see https://github.com/jwiegley/use-package/commit/066d371c8648984639e167ae53eb1ca95cfa0098.

**Comment by oantolin** [comment]
Thanks, @dieggsy , that's good news.
