### ISSUE TITLE
Which files other than .el should be in the main MELPA package?

### ISSUE THREAD

**Issue by nickmccurdy** [jwiegley/use-package#549]
Right now, after https://github.com/melpa/melpa/pull/5167, I believe only `.el` files (except tests and `bind-key.el`) and `use-package.texi` are added to the main MELPA package. Do we want the `.texi` manual and should we add any other files like the `.org` version of the manual? Note that `:defaults`, which I'm using, includes `.texi` but not `.org` by default. I'm not exactly sure how an elpa package's `.texi` and `.org` files are usable outside manually opening the files from your `.emacs.d/elpa`, but it seems inconsistent to me.

**Comment by jwiegley** [comment]
The `use-package.org` is just source to generate `use-package.texi`, I'm not sure why people would want that version, but maybe they would.  The `.md' files should be added to the MELPA package, shouldn't they?

**Comment by kaushalmodi** [comment]
> Do we want the .texi manual

I believe we do want that if we want Melpa to generate .info files from those [[ref][1]].

> and should we add any other files like the .org version of the manual? 

Probably not.

> Note that :defaults, which I'm using, includes .texi but not .org by default.

That makes sense, as Melpa needs just the .texi files to generate the .info files.

> I'm not exactly sure how an elpa package's .texi and .org files are usable outside manually opening the files from your .emacs.d/elpa, but it seems inconsistent to me.

As mentioned earlier, the .texi help build .info files. And you don't need to navigate to that directory and then open them manually. Note that the `:defaults` include `dir` too (that's a file). `package-activate-1` in `package.el` detects the presence of the `dir` file in a package dir and auto-adds that package dir to the `Info-directory-list`. When I do `C-h v Info-directory-list`, I see:

```el
("/home/kmodi/usr_local/apps/6/emacs/emacs-26/share/org/info"
"/home/kmodi/.emacs.d/elpa_26/magit-20171202.439"
"/home/kmodi/.emacs.d/elpa_26/magit-popup-20171121.1110"
"/home/kmodi/.emacs.d/elpa_26/ivy-20171204.1113"
"/home/kmodi/.emacs.d/elpa_26/use-package-20171204.1703"
"/home/kmodi/.emacs.d/elpa_26/with-editor-20171127.635"
"/home/kmodi/usr_local/apps/6/emacs/26/share/info"
"/home/kmodi/stowed/share/info" "/home/kmodi/usr_local/6/share/info"
"/usr/share/info")
```

*Note all the awesome Info manuals created by all the awesome package devs!*  And so just by the act of installing `use-package`, I see its manual in the Top node of `M-x info` :)

![image](https://user-images.githubusercontent.com/3578197/33625996-5c70ea54-d9c7-11e7-8eee-126ba261e045.png)

[1]: https://github.com/melpa/melpa/blob/62271788f20919a741acb1e0477a823d300e55ee/package-build/package-build.el#L792

**Comment by jwiegley** [comment]
The Texinfo contents for use-package are just beginning (right now, it's just information copied from the README). Expect to see this content evolving rapidly once all the bugs quiet down.

**Comment by nickmccurdy** [comment]
@kaushalmodi Thanks for the detailed explanation! I figured something like this was going on but I wasn't sure since I had no idea how the `.texi` files were used before reading your comment.
