### ISSUE TITLE
Readme badges, melpa (stable) and possibly license

### ISSUE THREAD

**Issue by duianto** [jwiegley/use-package#554]
It might be useful to add some badges to the readme. To show the current melpa and melpa stable versions, and possibly the license.

The melpa badge [![MELPA](http://melpa.milkbox.net/packages/use-package-badge.svg)](http://melpa.milkbox.net/#/use-package) can be found here: http://melpa.milkbox.net/#/use-package
There are 3 different code choices: `html`, `markdown` and `org`. Since `use-package` has a `README.md` file, here's the markdown version:
```
[![MELPA](http://melpa.milkbox.net/packages/use-package-badge.svg)](http://melpa.milkbox.net/#/use-package)
```

The melpa stable badge: [![MELPA Stable](https://stable.melpa.org/packages/use-package-badge.svg)](https://stable.melpa.org/#/use-package) can be found here: https://stable.melpa.org/#/use-package
```
[![MELPA Stable](https://stable.melpa.org/packages/use-package-badge.svg)](https://stable.melpa.org/#/use-package)
```

#### Two other packages shows the license badge like this:

https://github.com/emacs-helm/helm <a href="http://www.gnu.org/licenses/gpl-3.0.txt"><img src="https://img.shields.io/badge/license-GPL_3-green.svg" alt="License GPL 3" /></a>
```
<a href="http://www.gnu.org/licenses/gpl-3.0.txt"><img src="https://img.shields.io/badge/license-GPL_3-green.svg" alt="License GPL 3" /></a>
```

https://github.com/emacs-evil/evil [![License: GPL v3](https://img.shields.io/badge/License-GPL%20v3-blue.svg)](https://www.gnu.org/licenses/gpl-3.0)
```
[![License: GPL v3](https://img.shields.io/badge/License-GPL%20v3-blue.svg)](https://www.gnu.org/licenses/gpl-3.0)
```

#### What should the license badge link to?
Helm opens the raw `.txt` http://www.gnu.org/licenses/gpl-3.0.txt
Evil opens it on the gnu page https://www.gnu.org/licenses/gpl-3.0

#### Should the version nr be shown with or without a `v`? And does the color matter?
The badge can be customized at the bottom of: https://shields.io/

#### How should they be ordered?
Helm has the license first: `license`, `melpa`, and `melpa stable`
Evil has the license last: `build passing`, `melpa`, `melpa stable`, and `license`

**Comment by dieggsy** [comment]
I'm all for the melpa badges, though note that github has its own (fairly informative) version of the license badge already, so that could be redundant.

It also may or may not be worth the trouble adding the badges to the github repo as there are plans to include this in emacs itself, see: https://github.com/jwiegley/use-package/issues/282

**Comment by duianto** [comment]
Your right, the license badge isn't needed.

The GPL-3.0 link to the right of commits, branches, releases, and contributors, opens https://github.com/jwiegley/use-package/blob/master/LICENSE which shows the same license text that the badge links to. But it also shows 3 columns: Permissions, Limitations, and Conditions, which makes it much easier to understand what the license means.
