### ISSUE TITLE
Handler for :bind not defined

### ISSUE THREAD

**Issue by kalkins** [jwiegley/use-package#555]
I've been using use-package without problems for some time, but today, when I tried setting it up on a new machine, I got this error:

`Error (use-package): Failed to parse package magit: use-package: Keyword handler not defined: use-package-handler/:bind`

My configuration of magit:

`
(use-package magit
  :bind ("M-m" . magit-status))
`

I got this error for all packages where I used the :bind keyword.

**Comment by Jesse-Millwood** [comment]
Same Problem here.

**Comment by exlee** [comment]
Same here. Just updated and looks like Melpa release is botched. It complains about :ensure and :bind keywords missing.

**Comment by cbourgeois** [comment]
Same issue here. Emacs 26.0.9 pretest on macOS Sierra.

**Comment by exlee** [comment]
I've noticed that installing package directly from master(first clone then use https://github.com/jwiegley/use-package#getting-started) resolves the issue. Probably just a bad luck release.

**Comment by kaushalmodi** [comment]
@kalkins @Jesse-Millwood @exlee @cbourgeois 

FWIW, I don't see this issue.

I just updated `use-package` from Melpa and the installed version is **20171204.1703**. What is your `use-package` version? How are you installing it?

I tried to eval the snippet that @kalkins posted but I don't see that error. By putting the cursor at the end of that form and doing `M-x pp-macroexpand-last-sexp`, I get:

```el
(let
    ((use-package--warning445
      #'(lambda
          (keyword err)
          (let
              ((msg
                (format "%s/%s: %s" 'magit keyword
                        (error-message-string err))))
            nil
            (ignore
             (display-warning 'use-package msg :error))))))
  (condition-case-unless-debug err
      (progn
        (unless
            (fboundp 'magit-status)
          (autoload #'magit-status "magit" nil t))
        (ignore
         (bind-keys :package magit
                    ("M-m" . magit-status))))
    (error
     (funcall use-package--warning445 :catch err))))
```

For people getting this issue, what are your use-package versions and what does `pp-macroexpand-last-sexp` yield?

**Comment by exlee** [comment]
I've removed loading of use-package from GitHub's master branch and installed through `install-package` version **20171204.1703** and once again it's failing for me.

I'm using Emacs Carbon:
`GNU Emacs 25.3.3 (x86_64-apple-darwin13.4.0, Carbon Version 157 AppKit 1265.21) of 2017-09-28`

So in summary:
- Installed by install-packages from Melpa - **failing**
- Installed through git clone - **working without a problem**

😄

**Comment by cbourgeois** [comment]
I have the same use-package version, installed from melpa.

The following snippet with `M-x pp-macroexpand-last-sexp` gives the mentionned errors:

'(use-package counsel
  :bind
  (("M-y" . counsel-yank-pop)
   :map ivy-minibuffer-map
   ("M-y" . ivy-next-line-and-call)))
'

**Comment by Jesse-Millwood** [comment]
@kaushalmodi 
I installed it through the built in package manager in Emacs 25.1
This is it says for the version: 
```
use-package is an installed package.

     Status: Installed in ‘use-package-20171204.1703/’ (unsigned). Delete
    Version: 20171204.1703
    Summary: A configuration macro for simplifying your .emacs
   Requires: emacs-24.3, bind-key-2.4
   Homepage: https://github.com/jwiegley/use-package
   Keywords: dotemacs startup speed config package 
Other versions: 20171204.1703 (melpa).
```
When I do `M-x pp-macroexpand-last-sexp` at the end of 
```
(use-package windmove
  :bind (("C-S-j" . windmove-left)
	 ("C-S-l" . windmove-right)
	 ("C-S-i" . windmove-up)
	 ("C-S-k" . windmove-down)))
``` 
I get `nil` in the `*Pp Macroexpand Output*` buffer and this in the `Warnings` buffer
```
Error (use-package): Failed to parse package helm-projectile: use-package: Keyword handler not defined: use-package-handler/:bind
Error (use-package): Failed to parse package magit: use-package: Keyword handler not defined: use-package-handler/:bind
Error (use-package): Failed to parse package windmove: use-package: Keyword handler not defined: use-package-handler/:bind
Error (use-package): Failed to parse package multiple-cursors: use-package: Keyword handler not defined: use-package-handler/:bind
Error (use-package): Failed to parse package helm: use-package: Keyword handler not defined: use-package-handler/:bind
Error (use-package): Failed to parse package org: use-package: Keyword handler not defined: use-package-handler/:bind
Warning (use-package): Unrecognized keyword: :ensure
Error (use-package): Failed to parse package helm-flyspell: use-package: Keyword handler not defined: use-package-handler/:bind
Error (use-package): Failed to parse package ranger: use-package: Keyword handler not defined: use-package-handler/:bind
Error (use-package): Failed to parse package helm-cscope: use-package: Keyword handler not defined: use-package-handler/:bind
Warning (use-package): Unrecognized keyword: :ensure
Error (use-package): Failed to parse package pdf-tools: use-package: Keyword handler not defined: use-package-handler/:bind
Error (use-package): Failed to parse package windmove: use-package: Keyword handler not defined: use-package-handler/:bind
```

**Comment by kaushalmodi** [comment]
@cbourgeois Very odd indeed.. `pp-macroexpand-last-sexp` on that gives me:

```el
(let
    ((use-package--warning457
      #'(lambda
          (keyword err)
          (let
              ((msg
                (format "%s/%s: %s" 'counsel keyword
                        (error-message-string err))))
            nil
            (ignore
             (display-warning 'use-package msg :error))))))
  (condition-case-unless-debug err
      (progn
        (unless
            (fboundp 'counsel-yank-pop)
          (autoload #'counsel-yank-pop "counsel" nil t))
        (unless
            (fboundp 'ivy-next-line-and-call)
          (autoload #'ivy-next-line-and-call "counsel" nil t))
        (ignore
         (bind-keys :package counsel
                    ("M-y" . counsel-yank-pop)
                    :map ivy-minibuffer-map
                    ("M-y" . ivy-next-line-and-call))))
    (error
     (funcall use-package--warning457 :catch err))))
```

I have updated [my earlier comment][1] with more debug info (how I load `use-package` and my emacs version).

[1]: https://github.com/jwiegley/use-package/issues/555#issuecomment-349361187

**Comment by kaushalmodi** [comment]
@exlee @cbourgeois @Jesse-Millwood 

Aha! I also have 

```el
(require 'bind-key)
```

See if adding that to your config takes care of this issue.

**Comment by cbourgeois** [comment]
Adding 
`(require 'use-package)` 
fixed it.

I am not sure why it was not in my .emacs in the first place. Thanks for the time spent on this.

**Comment by Jesse-Millwood** [comment]
yep adding `(require 'use-package)` fixed it for me. 
I too am wondering why it was not in my .emacs in the first place!

**Comment by exlee** [comment]
Resolved this for me as well. Oddly, didn't have explicit `(require 'use-package)` as well. I guess it worked earlier on (package-initialize) and must had stopped initializing at some point...

**Comment by kaushalmodi** [comment]
Oh well, that at least helped clean up my config [a little bit][1] 😄 

[1]: https://github.com/kaushalmodi/.emacs.d/commit/c94159fa90e085bbfe8d5d88397fc284344968ac

**Comment by jwiegley** [comment]
I see what has happened. Before, `use-package` had an autoload cookie, and `use-package-handler/:bind` was defined in the same file as `use-package`, so using one would define the other.

As of yesterday, the bind-key related functionality is in its own module, and doesn't yet have an autoload cookie. So you were finding `use-package` automatically, but not the `:bind` handler.

I'll add the cookie, but yes, requiring the `use-package.el` module (which contains a require for `use-package-bind-key.el`) will also fix the problem in the interim.

**Comment by lbkvu** [comment]
I also encountered the following problem
```
Error (use-package): Failed to parse package magit ... (that ... is different from you)
```
If you check with **list-packages** for the version of magit, it may not be in the form of YYYYMMDD.XXX, but may be in the form of X.Y.Z.

X.Y.Z means you installed the Stable MELPA version.
YYYYMMDD.XXX is the MELPA version.

You need to remove all Stable MELPA version. Restart Emacs and let use-package to auto download & install the version from MELPA (use `:ensure t` option).

Hope it help.
