### ISSUE TITLE
Remove add-on packages from Melpa recipe for use-package

### ISSUE THREAD

**Issue by kaushalmodi** [jwiegley/use-package#559]
Hello,

Currently, add-on packages also get downloaded into the `use-package` package dir installed via Melpa by package.el.

So I see the add-on packages in the add-on package dir as well as in use-package dir:

```
/home/kmodi/.emacs.d/elpa_26/use-package-chords-20170717.1152/use-package-chords hides /home/kmodi/.emacs.d/elpa_26/use-package-20171204.1703/use-package-chords
/home/kmodi/.emacs.d/elpa_26/bind-chord-20170717.1152/bind-chord hides /home/kmodi/.emacs.d/elpa_26/use-package-20171204.1703/bind-chord
```

The solution is to not have multiple Melpa recipes containing the same .el files. I'll submit a PR to Melpa shortly that tries to fix this. Please review it.

**Comment by jwiegley** [comment]
@kaushalmodi `use-package-chords` and `use-package-system-packages` are going to be distributed with `use-package`. Do you still think they should be separate recipes?  They are add-on features, like the contents of the `contrib` directory in Org-mode, for example.

**Comment by kaushalmodi** [comment]
Also copying @waymondo here.

I don't know how to present this better, but.. the "distribution" and "deploying" of the packages need to be dealt here separately. If you clone the Org repo, all the packages in the contrib/ directory do not get built by default. You can choose which packages when the `contrib/` to pull into your `load-path` by setting `ORG_ADD_CONTRIB` var in the `local.mk` file:

```
ORG_ADD_CONTRIB = org-eldoc ox-extra org-mime
```

i.e. user gets to handpick which packages to load.

Similarly both `use-package-chords` and `use-package-system-packages` are "distributed" by `use-package`.. but every user might not want to install those when they do `(package-install 'use-package)`. (Example: A user could not be using the `key-chord` package, and so they wouldn't need the `use-package-chords` package.)

Additionally, with the way how it is, these 3 packages will be installed twice.. once by their own recipes and second time by the `use-package` recipe.. so they cannot live in 2 recipes at the same time. *I do not have the `use-package-system-packages` package installed, so that doesn't show up in the shadowed paths list I pasted above.*

Also at the moment, `use-package` does not `require` `use-package-chords` and `use-package-system-packages`.. so there's no need to download them as part of the `use-package` package.

What do you guys think?

**Comment by jwiegley** [comment]
I agree with @kaushalmodi, everyone installing `use-package` does not need the optional `chords` or `system-packages` add-ons.

**Comment by jwiegley** [comment]
Closing here, until there is something to be done in the use-package repository to address this.

**Comment by waymondo** [comment]
Yes, I also agree the extensions should be installed specifically by user choice. I will update the docs using `:ensure t` to illustrate this.
