### ISSUE TITLE
:preface and :if

### ISSUE THREAD

**Issue by DamienCassou** [jwiegley/use-package#560]
According to documentation, I thought that `:preface` could be used to define variables used inside `:if`. However, this code:

```emacs
(use-package notmuch
  :preface (setq-default notmuch-command (executable-find "notmuch"))
  :if notmuch-command))
```

generates this

```emacs
(when
    (symbol-value 'notmuch-command)
  (eval-and-compile
    (setq-default notmuch-command
                  (executable-find "notmuch")))
  (let
      ((use-package--warning286
        (function
         (lambda
           (keyword err)
           (let
               ((msg
                 (format "%s/%s: %s" 'notmuch keyword
                         (error-message-string err))))
             nil
             (ignore
              (display-warning 'use-package msg :error)))))))
    (condition-case-unless-debug err nil
      (error
       (funcall use-package--warning286 :catch err)))))
```

This doesn't work because `notmuch-command` does not exist before it is defined. Am I doing something wrong?

**Comment by jwiegley** [comment]
Quite right, it's now fixed.

It caused me to release a subtlety: Using `:requires` will cause definitions made in `:preface` to not be seen by the byte-compiler. `:if` does not have this effect, since it now happens after `:preface`. I'll note this subtle difference in the docs.

**Comment by jwiegley** [comment]
Actually, what about `:if` tests that compare againts things like `system-type`, checking for Windows or Linux?  I'm going to keep `:if` after the `:preface`, since that's how things used to be,  we may need a new `:pre-if` that happens before the `:preface`. Yet since no one has ever asked for this, it can wait.

**Comment by DamienCassou** [comment]
John Wiegley <notifications@github.com> writes:
> Actually, what about `:if` tests that compare againts things like
> `system-type`, checking for Windows or Linux?


this kind of tests probably don't require :preface so I'm not
frightened.

> I'm going to keep `:if` after the `:preface`, since that's how things
> used to be,

good

> we may need a new `:pre-if` that happens before the `:preface`

there might be some use cases for it but pay attention that adding
something brings more good than bad. There are always workarounds for
missing keywords. The more features you add, the more difficult it is
for you to maintain the code and for the user to understand how to
properly use the package. I fear that use-package is already quite
complex. You probably don't want to make use-package Turing-complete
:-).

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by jwiegley** [comment]
Good point. Also, one can always say:

``` elisp
(when (eq system-type 'darwin)
  (use-package ...))
```
