### ISSUE TITLE
Bind keyword no longer supports a single cons cell

### ISSUE THREAD

**Issue by nickmccurdy** [jwiegley/use-package#566]
`:bind` used to work with a cons cell or an alist of cons cells, now it only allows an alist of cons cells. A workaround is to add an extra set of parentheses around the cons cell. Ideally, this should either be fixed or added to breaking changes.

```emacs
(use-package browse-at-remote
  :ensure
  :bind ("C-c r" . browse-at-remote))
```

> Error (use-package): Failed to parse package browse-at-remote: Wrong type argument: listp, browse-at-remote

**Comment by jwiegley** [comment]
Strange, it macro-expands to this for me:

``` elisp
(progn
      (use-package-ensure-elpa 'foo '(t) 'nil)
      (unless (fboundp 'browse-at-remote)
        (autoload #'browse-at-remote "foo" nil t))
      (ignore
       (bind-keys :package foo ("C-c r" . browse-at-remote))))
```

**Comment by nickmccurdy** [comment]
I don't byte compile, could that make a difference?

**Comment by jwiegley** [comment]
This test isn't for a byte-compiled init file.  Can you macroexpand your definition using `M-x pp-macroexpand-last-sexp` on the closing paren?

**Comment by nickmccurdy** [comment]
For anyone else with this issue see https://gitter.im/use-package/Lobby
