### ISSUE TITLE
requiring a package

### ISSUE THREAD

**Issue by seblemaguer** [jwiegley/use-package#569]
Hello,

I have a naive, and possible idiotic, question and I possibly missed the answer on the documentation. Let's assume I have 2 packages: p1 and p2. p2 needs p1 to run. For what I understand, if I use the keyword `requires` and p1 is not available p2 is not going to load. However, I would like that if p1 is not available emacs throws an error saying that p2 can't be loaded as p1 is not available:
  1. does it make sense?
  2. is it possible? and if yes how?

Thanks a lot.

**Comment by jwiegley** [comment]
```
(use-package p1)

(if (featurep 'p1)
  (use-package p2)
  (error "Cannot load p2: p1 not available"))
```

`use-package` strives to load what can be loaded, rather than to enforce a set of packages having been loaded. But since this is all just Lisp, you can add whatever logic you want around the `use-package` declarations.
