### ISSUE TITLE
Allow general to power `:bind`, `:bind-keymaps`, etc.

### ISSUE THREAD

**Issue by jwiegley** [jwiegley/use-package#570]
Pinging @noctuid

It shouldn't be difficult to provide an alternative to `use-package-bind-key.el` that uses [general](https://github.com/noctuid/general.el) to power the underlying keybinding functionality.  It would be a matter of changing the macro-expanded call of `bind-key` to `general-define-key`, and then to translate use-package's keywords into names and arguments accepted by general:

- `:map` KEYMAP
- `:prefix-docstring` STRING
- `:prefix-map` SYMBOL
- `:prefix` STRING
- `:filter` SEXP
- `:menu-name` STRING

Some of these have direct correlates, except that `:prefix-map SYMBOL` turns into `:keymaps '(SYMBOL)' on the general side.

**Comment by jwiegley** [comment]
Or maybe even more comprehensively: Just create a `bind-key` macro that expands to the equivalent `general-define-key` invocation, making general a complete drop-in replacement for users of bind-key.

**Comment by noctuid** [comment]
What would be the use case for having general act as a drop-in replacement for bind-key?

**Comment by jwiegley** [comment]
To migrate away from bind-key in the most painless way possible. One less thing for me to test, document, maintain, since you seem to be going strong at it.

**Comment by jwiegley** [comment]
Looking at the docs, I also prefer the syntax and succinctness of `bind-key`, so I'd prefer to use that syntax as a layer over general, the way you're doing yourself with `general-def`.

**Comment by jwiegley** [comment]
Closing this as an issue. If you have any further interest, please e-mail me.

**Comment by noctuid** [comment]
There are a lot of things that I've been planning to work on once I have more time, but I could work on this at some point in the future. I can email you then about it.

**Comment by jwiegley** [comment]
There's no hurry, `bind-key` does what I need it to do, but it's grown ugly over the years and need some renovation. I thought may that renovation could be just replacing the guts with general. Ping me when you have time, and if this sounds interesting to you.
