### ISSUE TITLE
Error : Symbol’s function definition is void: lexical-let  

### ISSUE THREAD

**Issue by tttuuu888** [jwiegley/use-package#571]
First of all, thanks a lot for this great package.

I have this error since recent update.

> Error (use-package): helm/:catch: Symbol’s function definition is void: lexical-let

The way to reproduce this error is simple like below.

```
(require 'use-package)  
(use-package helm  
    :after (:any ido dired))
```

**Comment by jwiegley** [comment]
Hi, thanks for the report. Which version of Emacs are you on?

**Comment by jwiegley** [comment]
This should fix it.

**Comment by tttuuu888** [comment]
Thanks for quick feedback but unfortunately it is still same.
I am using Emacs version 25.3.1
The error is gone when I added  "(require 'cl)" by myself though.

**Comment by jwiegley** [comment]
How are you installing use-package? Are you sure the one you're using has commit 398b55a, and has been re-byte-compiled?

And to be sure, that you don't have `use-package-verbose` set to `errors`.

**Comment by tttuuu888** [comment]
I tested with a way like I replaced use-package directory in .emacs.d/elpa to git cloned use-package and compiled .el files by pressing B from dired.

Looks like this error does not occur in my desktop pc but only my ARM server pc.
The exact version of emacs in my server is "GNU Emacs 25.3.1 (armv7l-unknown-linux-gnueabihf) of 2017-09-13"
Maybe this has to with how I compiled and installed emacs on my server.

**Comment by jwiegley** [comment]
It could be.  The change in 398b55a pre-expands the call to `lexical-let` so that it can't appear in the resulting execution.

**Comment by jwiegley** [comment]
Hmm... maybe this isn't enough though.

**Comment by jwiegley** [comment]
I see the deeper problem now, it will take more work to solve.

**Comment by jwiegley** [comment]
@tttuuu888 Can you try again with fd6424c?

**Comment by tttuuu888** [comment]
I just tested again. Now the error has gone.
Thanks a lot!

**Comment by jwiegley** [comment]
Thank you for finding it! This was a subtle bug, and a good one to have fixed.
