### ISSUE TITLE
No more :require?

### ISSUE THREAD

**Issue by DamienCassou** [jwiegley/use-package#572]
I have this configuration snippet:

```emacs
(use-package auth-password-store
  :after auth-source
  :init
  (progn
    (setq auth-sources '(password-store))))
```

Using latest commit from use-package, there is no more  generated `require` call in the expansion:

```emacs
(progn
  (defvar use-package--warning142
    (function
     (lambda
       (keyword err)
       (let
           ((msg
             (format "%s/%s: %s" 'auth-password-store keyword
                     (error-message-string err))))
         (ignore
          (display-warning 'use-package msg :error))))))
  (condition-case-unless-debug err
      (eval-after-load 'auth-source
        '(condition-case-unless-debug err
             (progn
               (setq auth-sources
                     '(password-store)))
           (error
            (funcall use-package--warning142 :init err))))
    (error
     (funcall use-package--warning142 :catch err))))
```

A previous version of use-package used to generate a `require` call:

```emacs
(progn
  (condition-case-unless-debug err
      (progn
        (setq auth-sources
              '(password-store)))
    (error
     (ignore
      (display-warning 'use-package
                       (format "%s %s: %s" "auth-password-store" ":init"
                               (error-message-string err))
                       :error))))
  (eval-after-load 'auth-source
    '(require 'auth-password-store nil t)))
```

**Comment by jwiegley** [comment]
I'm seeing this:

``` elisp
(eval-after-load 'auth-source
  '(progn
     (progn
       (setq auth-sources
             '(password-store)))
     (require 'auth-password-store nil nil)))
```

What version are you using?

**Comment by jwiegley** [comment]
Or, with default settings:

``` elisp
(progn
  (defvar use-package--warning4
    (function
     (lambda
       (keyword err)
       (let
           ((msg
             (format "%s/%s: %s" 'auth-password-store keyword
                     (error-message-string err))))
         (ignore
          (display-warning 'use-package msg :error))))))
  (condition-case-unless-debug err
      (eval-after-load 'auth-source
        '(progn
           (condition-case-unless-debug err
               (progn
                 (setq auth-sources
                       '(password-store)))
             (error
              (funcall use-package--warning4 :init err)))
           (if
               (not
                (require 'auth-password-store nil t))
               (ignore
                (display-warning 'use-package
                                 (format "Cannot load %s" 'auth-password-store)
                                 :error)))))
    (error
     (funcall use-package--warning4 :catch err))))
```

**Comment by DamienCassou** [comment]
I think this comes from `use-package-always-defer` which is set to `t`. I tried with latest commit in master and Emacs 26.

**Comment by jwiegley** [comment]
Yes, this is the meaning of `:defer t`: that loading of the module is going to happen by some other means, usually an autoload. But if you explicitly ask for deferral, without any autoload scenarios present, then the require is expected to come from outside.

Here's the test showing your results:

``` elisp
(ert-deftest use-package-test/572 ()
  (let ((use-package-always-defer t))
    (match-expansion
     (use-package auth-password-store
       :after auth-source
       :init
       (setq auth-sources '(password-store)))
     `(eval-after-load 'auth-source
        '(setq auth-sources '(password-store))))))
```

**Comment by DamienCassou** [comment]
Am I right that the meaning of `:after` changed then? IIUC, the current definition 

```emacs
(use-package b
  :after a
  [...])
```

is:

> prevent setting up package `b` until package `a` is loaded

whereas the definition I had in mind and which seems to be reflected by former expansions is:

> set up package `b` as soon as `a` is loaded

The difference being that in the second definition, use-package is responsible for loading `b` whereas in the new definition, something else should load `b`.

If you agree, could you please clarify documentation or tell me I can work on a PR?

**Comment by DamienCassou** [comment]
This is related to #575.

**Comment by jwiegley** [comment]
It means "set up package b as soon as a is loaded", except that you used `:defer t`.

**Comment by jwiegley** [comment]
@DamienCassou For clarity, can you show me both what you'd like to say, and what you'd want it to expand to? I'm not sure yet what you want `:defer t` to mean in this context.

**Comment by DamienCassou** [comment]
I've fixed my configuration in https://github.com/DamienCassou/emacs.d/commit/b5ba7a7ca489ee691a15aca22d0242b257314254. Does this seem reasonable?

I never thought about the interplay between `:after` and :defer` or, in my case, `use-package-always-defer`. For me, using `:after` meant "load `b` as soon as `a` is loaded", regardless of `use-package-always-defer`. And it looked like the expansion worked following my understanding as shown in this [ticket's first message](https://github.com/jwiegley/use-package/issues/572#issue-280018093).

I think that the new version of use-package is doing the correct thing but this seems to be backward incompatible. Thus my request to update the documentation saying, during the introduction of `:after`, something like:

> Pay attention that if you set `use-package-always-defer`to `t` with the `:after` keyword, you still need to specify a way for the depending package to be loaded: e.g., through `:bind`. Loading of the depended package, specified after the `:after` keyword, won't magically load the depending package. As such, `:after` specifies a list of dependencies and not a trigger to load the depending package.

**Comment by jwiegley** [comment]
It's been added to the docs, and will get a better treatment after I write the upcoming section on deferred loading. This is a use case I haven't tried before, which explains why it didn't register why your declarations were having no effect. Thanks for the clarification!
