### ISSUE TITLE
:after and :defer t do not work together.

### ISSUE THREAD

**Issue by tttuuu888** [jwiegley/use-package#575]
Looks like :after is ignored when :defer t is used.

I am not sure if this is intended but,
Below code does not show message even if i start ido or dired.

```
(use-package helm
    :defer t
    :after (:any ido dired)
    :config
    (message "test. helm start"))
```

However, below code shows test message as I expected if I press C-c d keys.

```
(use-package helm
    :defer t
    :bind ("C-c d" . helm-mini)
    :config
    (message "test. helm start"))
```

and :commands, :mode also work fine with :defer t. 

Upper code began to not work from 418e90c commit.
I was able to find this out because I explicitly use :defer t for every packages even if I have :bind, :mode, :after or :commands.

Emacs version I tested on is GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 2.24.30) of 2017-09-12

If this was intended change, maybe this is a good time to simplify my setting with removing :defer t parts.

Thanks.

**Comment by jwiegley** [comment]
This is an intended change.  Here's what your first code expands to:

``` elisp
(progn
      (defvar use-package--loaded2 nil)
      (defvar use-package--result2 nil)
      (defvar use-package--next2
        #'(lambda nil
            (if use-package--loaded2 use-package--result2
              (setq use-package--loaded2 t use-package--result2
                    (eval-after-load 'helm
                      '(progn
                         (message "test. helm start")
                         t))))))
      (eval-after-load 'ido
        '(funcall use-package--next2))
      (eval-after-load 'dired
        '(funcall use-package--next2)))
```

As you can see, because of the explicit `:defer t`, it's waiting for all three packages to be loaded before it does anything.

In the second case, you have a keybinding which will trigger an autoload, thus permitting the final package to load and your config block to be run:

``` elisp
(progn
      (unless (fboundp 'helm-mini)
        (autoload #'helm-mini "helm" nil t))
      (eval-after-load 'helm
        '(progn
           (message "test. helm start")
           t))
      (ignore
       (bind-keys :package helm ("C-c d" . helm-mini))))
```

**Comment by tttuuu888** [comment]
Oh now I got it. 
I should have tried expanding it.
Thank you!
