### ISSUE TITLE
bind-keymap to local keymap?

### ISSUE THREAD

**Issue by drot** [jwiegley/use-package#586]
Something like this:

```
(use-package dired-filter
  :ensure t
  :bind-keymap (:map dired-mode-map
                     ("r" . dired-filter-mark-map)))
```

**Comment by jwiegley** [comment]
What is the question?

**Comment by jwiegley** [comment]
If you just change `:bind-keymap` above to `:bind`, it should do what you're expecting, if I've understood you.

**Comment by drot** [comment]
Sorry for the late reply, bad idea posting this before sleep.
The changed example doesn't work anymore (used to before the updates):

```
(use-package dired-filter
  :ensure t
  :bind (:map dired-mode-map
                     ("r" . dired-filter-mark-map)))
```

This fails with the following message when pressing <kbd>r</kbd> in `dired`:

`command-execute: Autoloading file /home/drot/.emacs.d/elpa/dired-filter-20171010.204/dired-filter.elc failed to define function dired-filter-mark-map`

So I thought that `:bind` lost the ability to bind keymaps with the recent updates.

Furthermore, with the following snippet:
```
(use-package dired
  :defer t
  :config
  (setq dired-recursive-deletes 'top)
  (setq dired-recursive-copies 'always))

(use-package dired-async
  :ensure async
  :delight '(:eval (when (eq major-mode 'dired-mode) " aS"))
  :bind (:map dired-mode-map
              ("E c" . dired-async-do-copy)
              ("E r" . dired-async-do-rename)
              ("E s" . dired-async-do-symlink)
              ("E h" . dired-async-do-hardlink)
              ("E m" . dired-async-mode)))
```
`dired-async-*` binds won't get bound in `dired` until I remove `:defer t` from the `dired` declaration. That is, pressing <kbd>C-x d</kbd> to get into `dired` and then pressing <kbd>E</kbd> will message: `E is undefined`

Using a `bind-key` example to override this:

`(bind-key "r" dired-filter-mark-map dired-mode-map)`

will of course signal a warning at startup:

`Symbol's value as variable is void: dired-mode-map`

**Comment by jwiegley** [comment]
Ah, on the first example, I see what you're trying to do now: You want a deferred binding of a *autoloaded keymap* into another keymap. I'll have to think on this more and get back to you tomorrow.

As for the latter, what if you use `:after dired` in your `dired-async` declaration, and keep the `:defer t` in `dired`?

**Comment by drot** [comment]
`:after dired` works for the 2nd example, thanks.

**Comment by rileyrg** [comment]
Is there a solution to this

```
(use-package dired-filter
  :ensure t
  :bind (:map dired-mode-map
                     ("r" . dired-filter-mark-map)))

```

Or is it simply a wrong approach?

from : https://github.com/Fuco1/dired-hacks

`(define-key dired-mode-map (kbd "some-key") dired-filter-map)
`

thank you for any pointer to correct use-package translation of this.
