### ISSUE TITLE
:ensure-system-package can use a better way to install package

### ISSUE THREAD

**Issue by stardiviner** [jwiegley/use-package#587]
I'm using Arch Linux, hope it install package with option `--noconfirm`.

**Comment by waymondo** [comment]
:ensure-system-package uses [`system-packages`](https://github.com/jabranham/system-packages/) to do the installing. You can customize its package manager command for installing before your `use-package` declarations with the keyword. If you think that should be a baked in customization option, you can open an issue on that packages repo.
