### ISSUE TITLE
Idiomatic way to set up a minimal init.el with use-package and diminish?

### ISSUE THREAD

**Issue by debajit** [jwiegley/use-package#588]
I'd like to know if there is a good / recommended way to set up use-package with diminish?

(I looked at your .emacs repository, but it is very large. I'd like just a minimal configuration)

Additionally, if you could add this to the README for use-package, that we be a big help :)

**Comment by nickmccurdy** [comment]
I believe you're looking for [Diminishing and delighting minor modes](https://github.com/jwiegley/use-package#diminishing-and-delighting-minor-modes). Basically, you just add `:diminish` to the appropriate `use-package` forms after installing `diminish` separately (you should probably install it interactively or above your `use-package` forms using `package-install`).
