### ISSUE TITLE
Catching errors during macro expansion

### ISSUE THREAD

**Issue by justbur** [jwiegley/use-package#589]
I don't know if this is possible, but it seems like it should be. 

use-package is good at catching errors in package configuration, so that a bad package config doesn't prevent loading the rest of the init.el file. However, if you make a mistake in using the keywords functions like `use-package-only-one` throw errors during macro expansion that abort execution of the init file. Try this for example

```elisp
(use-package ediff
  :defer t
  ;; :config
  (setq my-var t))
```

My feeling is that such an error in the use-package declaration should be caught and disable that declaration with a message, allowing the remainder of the init file to be processed, perhaps depending on the value of `use-package-verbose` and/or `debug-on-error`. 

I'm using an Emacs 26 pretest version (26.0.90) on macos to test this. Thanks.

**Comment by jwiegley** [comment]
This seems to work for me. If I evaluate what you have, I see the following in the `*Warnings*` buffer:

```
Error (use-package): Failed to parse package ediff: use-package: :defer wants exactly one argument
```

What do you have `use-package-verbose` set to? And are you starting your Emacs with `--debug-init` by any chance?

**Comment by justbur** [comment]
If I do

  1. `emacs -Q`
  2. `M-x package-initialize`
  3. eval the provided s-exp in the scratch buffer

I get

```
Debugger entered--Lisp error: (error "use-package: :defer wants exactly one argument")
  signal(error ("use-package: :defer wants exactly one argument"))
  error("use-package: %s" ":defer wants exactly one argument")
  use-package-only-one(":defer" (t (setq my-var t)) use-package-normalize-value)
  use-package-normalize/:defer(ediff :defer (t (setq my-var t)))
  use-package-normalize-plist(ediff (:defer t (setq my-var t)) nil use-package-merge-keys)
  use-package-normalize-keywords(ediff (:defer t (setq my-var t)))
  #f(compiled-function (name &rest args) #<bytecode 0x40524c35>)(ediff :defer t (setq my-var t))
  macroexpand((use-package ediff :defer t (setq my-var t)) nil)
  macroexp-macroexpand((use-package ediff :defer t (setq my-var t)) nil)
  macroexp--expand-all((use-package ediff :defer t (setq my-var t)))
  macroexpand-all((use-package ediff :defer t (setq my-var t)))
  eval-sexp-add-defvars((use-package ediff :defer t (setq my-var t)))
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

This is the latest melpa version of use-package.

**Comment by jwiegley** [comment]
What about after doing this: `(setq use-package-verbose t use-package-expand-minimally nil)`. Also, which version of use-package are you using?

**Comment by justbur** [comment]
Same result with those variables set. 

I just cloned the master branch to be sure. I was using the latest melpa version earlier. 

I stepped through the expansion with `debug-on-entry` and got the same result. Is there a way to control how errors are handled in macro expansion somehow?

**Comment by jwiegley** [comment]
Does this test work on your machine:

``` elisp
(ert-deftest use-package-test/589 ()
  (let ((use-package-verbose t)
        (use-package-expand-minimally t)
        debug-on-error
        warnings)
    (flet ((display-warning (_ msg _) (push msg warnings)))
      (progn
        (macroexpand-1
         '(use-package ediff :defer t (setq my-var t)))
        (should (= (and (> (length warnings) 0)
                        (string-match ":defer wants exactly one argument"
                                      (car warnings))) 44))))))
```

**Comment by justbur** [comment]
That passes for me

**Comment by jwiegley** [comment]
Ok, then we need to find out why your errors are not being trapped by `condition-case-unless-debug` on your side. That is only supposed to happen if `debug-on-error` is non-nil.

**Comment by justbur** [comment]
OK, I have more info, but I'm still a little lost. 

I learned there's a `eval-expression-debug-on-error` variable that was causing me some confusion, so I set that to nil. 

I'm now getting the message as you do, but if I put one of these examples in my init.el file loading hangs for me, which is what caused me to go down this path in the first place. 

I tried this which I think provides the key clue
```elisp
(macroexpand-1
  '(use-package ediff
     :defer t
     (setq my-var t)))
```
From that I get
```elisp
(use-package "Failed to parse package ediff: use-package: :defer wants exactly one argument" :error nil)
```
and now there's a recursion problem, because expanding that once more gives
```elisp
(use-package "Failed to parse package Failed to parse package ediff: use-package: :defer wants exactly one argument: use-package: Unrecognized keyword: :error" :error nil)
```

I don't completely understand this yet, but it seems to me that the problem stems from the return value of your `condition-case-unless-debug`.

If I change it to 

```elisp
        (condition-case-unless-debug err
            (use-package-core name args)
          (error
           (display-warning
            'use-package
            (format "Failed to parse package %s: %s"
                    name (error-message-string err)) :error)
           (use-package-core name (setq args (cons :disabled args)))))
```

I don't have the infinite recursion any more. 

Hopefully that's enough to go off of.

**Comment by jwiegley** [comment]
What if you used this instead:

``` elisp
(condition-case-unless-debug err
    (use-package-core name args)
  (error
   (ignore
    (display-warning
     'use-package
     (format "Failed to parse package %s: %s"
             name (error-message-string err)) :error))))
```

**Comment by justbur** [comment]
That seems better. It also fixes one other problem that I noticed just now which is `display-warning` returns `t` when the `condition-case` statement should return a list for `use-package-concat`. Otherwise, it's possible that `macroexp-progn` can receive just `t` and throw an error.

**Comment by Luis-Henriquez-Perez** [comment]
Hi, I think I'm having a similar issue as justbur. 

As I type a keyword into a `use-package`, I get errors. As an example I'd be typing in the following with my cursor represented as `|` and as I try to add in a colon for the `:init` keyword I'd get this error: 'Error (use-package): Failed to parse package magit: use-package: :commands wants a symbol, or list of symbols' multiple times.

`(use-package magit
  :commands (magit-status)
  |
  :config
  (evil-set-initial-state ))`

 I've read through this issue but I still don't understand what the solution is. I've made sure that variables like `debug-on-error` and `eval-expression-debug-on-error` are nil. 

@jwiegley is the code you gave with `condition-case-unless-debug` something I should add to my copy of use-package?
