### ISSUE TITLE
:hook doesn't respect the package not being available...

### ISSUE THREAD

**Issue by mdorman** [jwiegley/use-package#591]
So it seems to me the contract that `use-package` makes with its user is that if the specified package isn't available, the content of the `(use-package)` statement won't be run, and thus nothing adverse will happen.  That doesn't seem to be true for `:hook`.

The most cut-down example I can give is given a `hook-error.el`:
```
(package-initialize)
(eval-when-compile
  (require 'use-package))
(use-package nonexistent
  :hook lisp-mode)
```
If you run `emacs -nw -q -l hook-error.el` and poke around a bit---deleting buffers other than `*Messages*` is generally enough for me---you will eventually see a message like `run-hooks: Cannot open load file: No such file or directory, nonexistent`.

This wouldn't necessarily be such a big deal, except the way I found this was I had a couple of `flycheck` add-ons that were present on my home machine, but not on my work machine, configured like:
```
(package-initialize)
(eval-when-compile
  (require 'use-package))
(use-package flycheck
  :config
  (global-flycheck-mode))
(use-package nonexistent
  :hook (flycheck-mode . nonexistent-hook))
```
Suddenly emacs was dead in the water, because flycheck would try to load the nonexistent code, and fail, and fall over. 🙁

It seems to me like this feature needs something akin to some of the more exotic `:bind` operators, in that it needs to install its *own* hook, that will do the appropriate require, and eat the error?

**Comment by jwiegley** [comment]
`use-package` doesn't make that sort of contract, since it would violate one of its primary goals: to improve the speed of load time as much as possible. Doing a library search through most directories in `load-path` for every single package could kill that performance in some environments.

What you can do yourself for one `use-package` form is this:

``` elisp
(use-package nonexistent
     :if (locate-library "nonexistent")
     :hook lisp-mode)
```

If you'd like this to be the default behavior throughout use-package (i.e., establish the contract), you can customize `use-package-defaults` and add an entry that looks like this:

``` elisp
(:if (lambda (name _) `(locate-library ,name)) t)
```

Note that you'll have to be using at least commit 2f9bcb5 for this to work.

**Comment by nickmccurdy** [comment]
Personally I just use `:ensure` and MELPA so I don't have to keep track of what packages to install, I agree with @jwiegley that it's probably the best the way it is now.

**Comment by cpitclaudel** [comment]
One issue with this solution is that it will still confuse the byte-compiler:

    Cannot load nonexistent: (file-missing "Cannot open load file" "No such file or directory" "nonexistent")

**Comment by cpitclaudel** [comment]
It's due this part:

```
    ;; If byte-compiling, pre-load the package so all its symbols are in
    ;; scope. This is done by prepending statements to the :preface.
    (when (bound-and-true-p byte-compile-current-file)
      (setq args
            (use-package-plist-append
             args :preface
             (use-package-concat
              (mapcar #'(lambda (var) `(defvar ,var))
                      (plist-get args :defines))
              (mapcar #'(lambda (fn) `(declare-function ,fn ,name-string))
                      (plist-get args :functions))
              `((eval-when-compile
                  (with-demoted-errors
                      ,(format "Cannot load %s: %%S" name-string)
                    ,(when (eq use-package-verbose 'debug)
                       `(message ,(format "Compiling package %s" name-string)))
                    ,(unless (plist-get args :no-require)
                       `(unless (featurep ',name-symbol)
                          (load ,name-string nil t))))))))))
```

It looks like use-package loads the package unconditionally when byte-compiling, even if it has an `:if` that says it shouldn't be loaded.
