### ISSUE TITLE
 Make use-package-report respect use-package-minimum-reported time

### ISSUE THREAD

**Issue by dieggsy** [jwiegley/use-package#594]
Title pretty much says it. Is this possible?

**Comment by dieggsy** [comment]
Hmm, I guess the title is misleading since it'll _report_ everything - I guess I'm looking for an option to increase the precision on the time reported - right now, I can't see times smaller than 0.01

**Comment by jwiegley** [comment]
I actually don't know what you're requesting. Can you please elaborate? Maybe show an example of what you see now, and what you expected to see?

**Comment by dieggsy** [comment]
It seems like if a package `foo` takes 0.009 s or less to load, it will not be reported:
```
| foo | Configured | [Date] | 0.00 |
```
I'd expect for example:
```
| foo | Configured | [date] | 0.009 | 
```

**Comment by skangas** [comment]
> It seems like if a package `foo` takes 0.009 s or less to load, it will not be reported correctly:
> 
> ```
> | foo | Configured | [Date] | 0.00 |
> ```
> 
> I'd expect for example:
> 
> ```
> | foo | Configured | [date] | 0.009 | 
> ```

I guess there's also a rounding error, as `0.009` should really be displayed as `0.01` with a two digit precision.

Would a new option to customize the precision of this display cover your use case?

**Comment by dieggsy** [comment]
Fixing rounding and adding an option for (or increasing the default) precision seem like reasonable things. However I no longer need or use this. Feel free to handle the issue as you see fit.
