### ISSUE TITLE
Macros within use-package declarations not expanded

### ISSUE THREAD

**Issue by SwiftLawnGnome** [jwiegley/use-package#613]
I hope this hasn't already been mentioned or documented as intended functionality, I looked around and didn't see any mention of it. 
It seems that macros within use-package forms are not expanded. I have this little macro:
```
(defmacro set-mode-name (mode string)
  `(add-hook ',(make-symbol (concat (symbol-name mode) "-mode-hook"))
	     (lambda () (setq mode-name ,string)) t))
```
And when I put `(set-mode-name emacs-lisp "ELisp")` in the :config or :init block and pp-macroexpand-last-sexp the whole use-package form, it remains as written in the expansion. Since I have this macro in a file I require in eval-when-compile, it doesn't do anything when I start Emacs. Should/could these macros be expanded when compiled?

**Comment by npostavs** [comment]
> And when I put (set-mode-name emacs-lisp "ELisp") in the :config or :init block and pp-macroexpand-last-sexp the whole use-package form, it remains as written in the expansion.

I'm not sure about the actual issue, but this is not a good test for it: `pp-macroexpand-last-sexp` uses `macroexpand-1` so it only expands the outermost macro.

**Comment by SwiftLawnGnome** [comment]
Ahh I did not know that, that's good to know. 
The problem is that when I load the byte compiled file the macro does nothing. I just tried setting emacs-lisp-mode-hook to nil and loading the compiled file and it did not add the hook. And, inspecting the byte code, it actually *is* expanded. So I'm actually really not sure why this isn't working.

**Comment by dieggsy** [comment]
@SwiftLawnGnome Can you provide more info as to what you're trying to do/what your setup is? (I have macros that work just fine in `:config` or `:init` blocks). Can you give an example use-package declaration that isn't doing what you want it to?

**Comment by SwiftLawnGnome** [comment]
Sure. Here's what I was originally referring to:
```
(use-package elisp-mode
  :defines emacs-lisp-mode-hook
  :bind
  (:map emacs-lisp-mode-map
	("C-M-<backspace>" . backward-kill-sexp)
	:prefix "C-c"
	:prefix-map my-elisp-mode-prefix-map
	("b" . emacs-lisp-byte-compile)
	("C-b" . emacs-lisp-byte-compile-and-load)
	("M" . emacs-lisp-macroexpand))
  :config
  (set-mode-name emacs-lisp "ELisp")
  :init
  (use-package eldoc
    :hook (emacs-lisp-mode . eldoc-mode)
    :diminish eldoc-mode))
```
(I cut out some irrelevant bits, but I can post the whole use-package declaration if it might be helpful). In the byte code, there is `[add-hook #:emacs-lisp-mode-hook #[nil "\301\211\207" [mode-name "ELisp"] 2] t]` so the macro _seems_ to have expanded properly, yet loading the file does not actually add that hook. This is also true for other macros I've defined in a my-subr.el[c] file and placed in a use-package form. I don't recall this being a problem in the past, but sometimes I don't notice things.

**Comment by npostavs** [comment]
> `#:emacs-lisp-mode-hook`

Oh this is an uninterned symbol. You should be using `intern` instead of `make-symbol` in your macro.

**Comment by SwiftLawnGnome** [comment]
AHHH thank you! I had a nagging feeling it could just be my amateur understanding of Lisp.
