### ISSUE TITLE
Ztree key bindings

### ISSUE THREAD

**Issue by rchar01** [jwiegley/use-package#622]
Hello,
I tried to set key bindings to ztree (dir and diff), but it does not work after the emacs startup.
`f8 `and `C-f8` works but not the navigation keys. When I eval my init.el after starting ztree all keys are working correctly.
My init:
```
(use-package ztree
  :bind (("<f8>"   . ztree-dir)
         ("C-<f8>" . ztree-diff)
         :map ztree-mode-map
         ("n" . next-line)
         ("p" . previous-line)
         :map ztreedir-mode-map
         ("f" . ztree-dir-narrow-to-dir)
         ("b" . ztree-dir-widen-to-parent)))
```

Pleas help.

**Comment by rchar01** [comment]
I also tried (with the same effect) `with-eval-after-load` but it works only with:
```
(require 'ztree)
(define-key ztree-mode-map "n" 'next-line)
(define-key ztree-mode-map "p" 'previous-line)
```
but I don't want to load the ztree package at Emacs startup.
Any ideas?

**Comment by Silex** [comment]
You could move the `define-key` in the `:config` section of use-package, that way it happens after ztree loads.

I guess ztree defines its map in a weird way that overwrites whatever you defined in `:bind`, but I'm not familiar with mode-maps enough.

**Comment by jwiegley** [comment]
I'd use this:

``` elisp
(use-package ztree
  :defer 5
  :bind (:map ztree-mode-map
              ("n" . next-line)
              ("p" . previous-line)))
```
