### ISSUE TITLE
package availability for emacs 25

### ISSUE THREAD

**Issue by vbsteja** [jwiegley/use-package#623]
Hi,it seems the package is not available for emacs 25, are there any plans to support use-package on emacs25?
Thanks.

**Comment by dieggsy** [comment]
It _is_ available for emacs 25 - do you have melpa in your package repositories? 

https://melpa.org/#/getting-started

**Comment by vbsteja** [comment]
Hi, thanks for the reply. i do have melpa, installed but getting the following error while trying to install use-package.

Contacting host: melpa.org:443
package-install-from-archive: https://melpa.org/packages/use-package-20171226.1104.tar: Not found
Mark set

Thanks.

**Comment by vbsteja** [comment]
However a package-refresh-contents did solve the issue, thanks for the wonderful package.
