### ISSUE TITLE
Show expanded code

### ISSUE THREAD

**Issue by kode9** [jwiegley/use-package#626]
Hello,

Is there any way to (manually) display the expanded code of a `use-package` expression ?

Commit 418e90c39a removed the `use-package-debug` option, and IIRC I could do `C-x C-e` and it would show me the expanded code in a buffer.

As I understand it the _new_ `debug` choice of `use-package-verbose` do the same thing but only when an error append.
A workaround is to explicitly throw an error, e.g `(use-package diminish :config (error "expand-me"))`.

Maybe there could be a `use-package-eval` function that would evaluate and show the expanded code at point ?

Also there still is a mention of this behavior here https://github.com/jwiegley/use-package/blame/master/README.md#L893
I can correct it if needed and I'm not mistaken on what's happening.

Thanks for this awesome package.

**Comment by npostavs** [comment]
`M-x pp-macroexpand-last-sexp` works for any macro.

**Comment by kode9** [comment]
Oh, excellent ! Pardon my lack of elisp knowledge, I searched things like `use-package*expand*` but didn't think there was a built-in function for that.

Still I think the README section as to be reworded ?

Thanks

**Comment by dieggsy** [comment]
Would also recommend looking into the [macrostep](https://github.com/joddie/macrostep) package. Really nice.

**Comment by andschwa** [comment]
Thanks @npostavs, I updated the readme with this as `Ctrl-F debug` still yielded the obsolete variable.
