### ISSUE TITLE
Statistics sorting broken

### ISSUE THREAD

**Issue by nickmccurdy** [jwiegley/use-package#630]
## Reproduction
1. Add `(setq use-package-always-ensure t)` to Emacs init.
2. Restart Emacs.
3. `M-x use-package-report`
4. Switch buffefrs to `*use-package report*`
5. `C-c ^` using any column.

## Expected
Entire column sorts all rows of the table.

## Actual
`1 lines sorted, based on column N` is displayed in minibuffer where N is the
column number, but nothing is actually sorted.

## Environment
- use-package 20180206.1414
- Org 8.2.10
- Emacs 25.3

**Comment by jwiegley** [comment]
This is an Org problem, it can't be solved in use-package.

**Comment by nickmccurdy** [comment]
This is making statistics difficult for me to use because I can't find packages that are taking significant amounts of time on startup. Do you have any advice on what could cause this or what I should try troubleshooting with? Is my version of Org too old?

**Comment by jwiegley** [comment]
You could ask Org to export the table to CSV, and then use external tools.  But I would have expected `C-c ^` to work, actually.

**Comment by dieggsy** [comment]
`C-c ^ N` does it for me here. I'm using org-mode from git master though.

@nickmccurdy have you considered something like [esup](https://github.com/jschaf/esup) (it had been having some problems a while ago, but recently it's worked fro me.

**Comment by nickmccurdy** [comment]
Fixed in https://github.com/jwiegley/use-package/pull/642.
