### ISSUE TITLE
Question about the correct form of using use-package

### ISSUE THREAD

**Issue by rchar01** [jwiegley/use-package#631]
I am interested in the correct form of using the use-package.
The following two examples do not generate error, but which form is correct?
Does this have any impact on Emacs start time?
```elisp
;; a)
(use-package js2-mode 
  :delight (js2-mode "JavaScript")
  :mode ("\\.js\\'" . js2-mode)
  :interpreter ("node" . js2-mode))

;;b)
(use-package js2-mode 
  :delight js2-mode "JavaScript"
  :mode "\\.js\\'"
  :interpreter "node")
```

**Comment by nickmccurdy** [comment]
I think they're equivalent. For example, use-package normalizes key pair values to default to the current mode. The resulting macros should be about the same, and I'd expect little to no performance difference.

**Comment by rchar01** [comment]
Thanks.
I have used `M-x pp-macroexpand-last-sexp` command, the generated code is the same in both cases.
