### ISSUE TITLE
Warning during compilation

### ISSUE THREAD

**Issue by rchar01** [jwiegley/use-package#634]
When I try to compile my init.el it receives a warning `the following functions may not be defined in the runtime environment: Ido-mode`. 

Is there something wrong with my configuration?

I use this:
```elisp
(use-package ido
  :init
  (progn
    (setq ido-enable-flex-matching t)
    (setq ido-everywhere t)
    (setq ido-max-file-prompt-width 8)
    (setq ido-max-prospects 8)
    (ido-mode 1)))
```

**Comment by jwiegley** [comment]
You can put the `setq` statement in the `:init` block, but the call to `ido-mode` must go into a `:config` block, since that's the only way to be sure it will have been loaded before the call.

**Comment by rchar01** [comment]
Thanks for the advice.

**Comment by rchar01** [comment]
I moved the code as you wrote to ": config" but it did not help.
Warning appears as before.
```elisp
(use-package ido
  :init
  (progn
    (setq ido-enable-flex-matching t)
    (setq ido-everywhere t)
    (setq ido-max-file-prompt-width 8)
    (setq ido-max-prospects 8))
  :config
    (ido-mode 1))
```

**Comment by rchar01** [comment]
Thanks, I haven't used this command before.
