### ISSUE TITLE
Unexpected behaviour of :if

### ISSUE THREAD

**Issue by franburstall** [jwiegley/use-package#637]
I have the following stanza in my init.el:

    (use-package helpful
        :if (> emacs-major-version 24)
        :ensure t)

What I expected: no attempt to install package helpful on emacs-24.

What I got: failed attempt to install package helpful (which needs 25.1 or better).

Commentary: macro-expanding the stanza, I see that the use-package-ensure-elpa form occurs before the when form that wraps everything else. 

Is this what is intended?

**Comment by raxod502** [comment]
It's known, but whether it is intended is up for debate. See discussion:

* https://github.com/jwiegley/use-package/issues/523
* https://github.com/jwiegley/use-package/issues/496
* https://github.com/jwiegley/use-package/issues/608

**Comment by franburstall** [comment]
Thank you @raxod502 : that is helpful.  Following #523 (of which this is a duplicate) and the advice given there, I shall adjust `use-package-keywords` to give `:if` priority

`(setq use-package-keywords (cons :if (delq :if use-package-keywords)))`

and close this issue.
