### ISSUE TITLE
Possible to `:bind` non-string?

### ISSUE THREAD

**Issue by Oliveiras** [jwiegley/use-package#640]
I'm trying to concentrate keybinding layout in one file and use-package calls in other file, like this:

-- file: keys-layout-1.el --
```
(setq jump-to-definition-key "C-d")
```

-- file: config-pkgs.el --
```
(use-package dumb-jump
  :config (dumb-jump-mode t)
  :bind (jump-to-definition-key . dumb-jump-go))
```

But `:bind` expects a string.
Is there a way do to that?

**Comment by jwiegley** [comment]
No, this is not possible. However, you can use backquote and `macroexpand` to transform the `use-package` declaration to do whatever you want.
