### ISSUE TITLE
use-package-report does not work

### ISSUE THREAD

**Issue by rchar01** [jwiegley/use-package#644]
After using the `M-x use-package-report`:
```
mapcar: Symbol’s function definition is void: hash-table-keys
```

There are warnings after update to 20180308.1445 version:
```

In use-package-statistics-status:
use-package-core.el:970:27:Warning: reference to free variable ‘statistics’

In use-package-statistics-last-event:
use-package-core.el:979:44:Warning: reference to free variable ‘statistics’

In use-package-statistics-time:
use-package-core.el:986:40:Warning: reference to free variable ‘statistics’

In end of data:
use-package-core.el:1586:1:Warning: the function ‘hash-table-keys’ is not
    known to be defined.
```

**Comment by DamienCassou** [comment]
That's my fault. I'm taking care of it (I got bitten by the fact that use-package-core doesn't use lexical binding). Which version of Emacs are you using?

**Comment by DamienCassou** [comment]
Can you please try PR #645.

**Comment by rchar01** [comment]
I use `GNU Emacs 25.3.1 (x86_64-unknown-cygwin, GTK+ Version 3.22.20)
 of 2017-09-11`.

**Comment by rchar01** [comment]
`M-x use-package-report` works after adding `(require' subr-x) `.

**Comment by DamienCassou** [comment]
I think the ticket should be reopened now that the fix has been reverted
