### ISSUE TITLE
Use lexical-binding

### ISSUE THREAD

**Issue by DamienCassou** [jwiegley/use-package#648]
Why isn't use-package using lexical-binding for all files?

I volunteer to fix this if desired.

**Comment by jwiegley** [comment]
Someone else did this, and it completely broke my startup. I'm very much open to making this change, we just need to be cautious, and discover what might bite people making the switch, and how they can diagnose and fix the problem that may occur.

Also, we should release the current `master` as 2.4 and wait until after that to make a change like this. Things are pretty stable now.

**Comment by jabranham** [comment]
@DamienCassou I took a crack at this and still have all the changes. It shouldn't be too hard to rebase and submit a PR. I was waiting til after the 2.4 release.

You can see the previous PR in #617

**Comment by jabranham** [comment]
@DamienCassou - I just cleaned everything up. If you want to take it for a spin, you can find a it here: #657
