### ISSUE TITLE
Makefile use a different EMACS for compiling than Travis

### ISSUE THREAD

**Issue by DamienCassou** [jwiegley/use-package#650]
Travis configures the `EMACS` environment variable to point to the Emacs binary file but Makefile.lisp uses the `emacs` in the `PATH` instead. This is not the same.

**Comment by tarsius** [comment]
Do you know with what version Emacs started to set only `INSIDE_EMACS` but not `EMACS` to communicate to a subprocess that it was running inside Emacs?

**Comment by DamienCassou** [comment]
I have no clue.

**Comment by npostavs** [comment]
NEWS.25 says:
```
* Incompatible Lisp Changes in Emacs 25.1
...
** 'M-x shell' and 'M-x compile' no longer set the EMACS environment variable.
```
