### ISSUE TITLE
Trouble with hooks

### ISSUE THREAD

**Issue by wpcarro** [jwiegley/use-package#656]
I'm wondering why these two snippets are producing different results. I was under the impression that they would be isomorphic to each other. Would love any insights here that might deepen my `use-package` knowledge.

### Number 1

```elisp
(use-package term
  :bind (:map term-raw-map
              ("M-x" . nil))
  :config
  (setq explicit-shell-file-name "/bin/zsh")
  (add-hook 'term-mode-hook (disable linum-mode)))
```

### Number 2

```elisp
(use-package term
  :hook (term-mode . (disable linum-mode))
  :bind (:map term-raw-map
              ("M-x" . nil))
  :config
  (setq explicit-shell-file-name "/bin/zsh"))
```

Snippet number two prevents my Emacs from loading properly. I get the following error message:

```
Error in post-command-hook (global-linum-mode-check-buffers) (wrong-number-of-arguments ...)
```

The `disable` macro comes my my `macros.el` and looks like this:

```elisp
(defmacro disable (mode)
  "Helper for disabling MODE. Useful in `add-hook' calls."
  `#'(lambda nil (,mode -1)))
```

**Comment by jwiegley** [comment]
`:hook (term-mode . (disable linum-mode))` expands to `(add-hook 'term-mode-hook '(disable linum-mode)))`.  If you want to expand a macro here, you'll need to warp the whole thing in a backquote and then anti-quote the use of the disable macro.

**Comment by wpcarro** [comment]
@jwiegley forgive my Elisp -- or more broady LISP -- ignorance, but is this what you're recommending?

```elisp
:hook (term-mode . `,(disable linum-mode))
```

**Comment by jwiegley** [comment]
It would need to be larger in scope:

``` lisp
(macroexpand
 `(use-package term
    :bind (:map term-raw-map
                ("M-x" . nil))
    :config
    (setq explicit-shell-file-name "/bin/zsh")
    (add-hook 'term-mode-hook ,(disable linum-mode))))
```

**Comment by skangas** [comment]
I think @jwiegley answered this question, so I'm closing this issue.
