### ISSUE TITLE
Why does :custom sometimes override :defer?

### ISSUE THREAD

**Issue by jabranham** [jwiegley/use-package#664]
With the following configuration file:

```emacs-lisp
(add-to-list 'load-path "/path/to/use-package")
(setq use-package-compute-statistics t)
(require 'use-package)

(use-package erc
  :defer t
  :config
  (setq erc-server "irc.freenode.net"))
```

`M-x use-package-report` says `erc` is initialized, as I would expect. However, if we change the declaration to:

```emacs-lisp
(add-to-list 'load-path "/path/to/use-package")
(setq use-package-compute-statistics t)
(require 'use-package)

(use-package erc
  :defer t
  :custom
  (erc-server "irc.freenode.net"))
```

and restart Emacs, then it is reported as configured. What's weirder is that this depends on the variable. So while customizing `erc-server` causes erc to be loaded, customizing `erc-port` does not.

**Comment by jwiegley** [comment]
I'd look at the difference between the macro expansions, to factor out `use-package` in your analysis. Maybe `custom-set-variables` is doing something interesting here.

**Comment by jabranham** [comment]
Thanks, that helped. 

Since `customize-set-variable` calls `custom-load-symbol`, which in turn calls `(get 'erc-server 'custom-loads)` which returns `(erc-backend)`, it looks like customizing that variable goes ahead and loads the whole thing. 

I'll go ahead and close this since it's not a use-package problem.
