### ISSUE TITLE
Smoother conditional binding

### ISSUE THREAD

**Issue by mookid** [jwiegley/use-package#666]
Thanks for the great work on use-package!

As far as I can tell, to bind a key conditionally to some variable, one need to either:

+ use define-key / bind-key... in the init part
+ use nested invocations of use-package

The first solution is basically being back to not using the package.

The second solution looks like the following:

``` emacs-lisp
(use-package ivy
     :bind
   (("C-M-y" . counsel-yank-pop))
   :init
   (use-package ivy
       :if window-system
       :bind
       ("C-z" . counsel-switch-to-shell-buffer)))
```

which seems to macroexpand reasonably nicely, but it feels like a workaround (the nested invocations look ugly, even if it should never nest more than that). 

Is it there any way I am missing? Is the snippet I pasted the recommended way to achieve that?

**Comment by waymondo** [comment]
What you proposed works and seems reasonable.

If you don't like the nesting, you can simply just have two separate declarations:

```
(use-package ivy
  :bind
  ("C-M-y" . counsel-yank-pop))

(use-package ivy
  :if window-system
  :bind
  ("C-z" . counsel-switch-to-shell-buffer))
```
Or you could wrap all your conditional `window-system` config:

```
(use-package ivy
  :bind
  ("C-M-y" . counsel-yank-pop))

(when window-system
  (use-package ivy
    :bind
    ("C-z" . counsel-switch-to-shell-buffer))
  ...)
```
