### ISSUE TITLE
How to specify APPEND/LOCAL flags to add-hook in :hook?

### ISSUE THREAD

**Issue by zzamboni** [jwiegley/use-package#668]
First of all, thank you for `use-package`! I've been restructuring more and more of [my Emacs config](https://github.com/zzamboni/dot-emacs/blob/master/init.org) to properly use the different `use-package` features. Among other things, my Emacs load time has decreased dramatically.

One thing I couldn't figure out is if it's possible to specify the [append or local flags](https://www.gnu.org/software/emacs/manual/html_node/elisp/Setting-Hooks.html#Setting-Hooks) of the `add-hook` function. For example, can the following hook be specified using the `:hook` section?

```emacs-lisp
(add-hook 'after-save-hook #'org-hugo-export-wim-to-md-after-save :append :local)
```

Thanks in advance.

**Comment by nickmccurdy** [comment]
I don't think so, but it seems useful.

**Comment by jwiegley** [comment]
No, the `:hook` feature is very basic in order to avoid supporting a complex syntax. I recommend adding such calls to `add-hook` in your `:init` section.

**Comment by zzamboni** [comment]
Fair enough, and a good principle IMO. I just wanted to make sure I want missing something :) I had been using use-package in a very basic way so far (package name + :config code for the most part), but I've been restructuring in the last few days and trying to use more of the supported keywords.

**Comment by skangas** [comment]
> No, the `:hook` feature is very basic in order to avoid supporting a complex syntax. I recommend adding such calls to `add-hook` in your `:init` section.

So this is not something that we want to do, and I'm therefore closing this issue now.
