### ISSUE TITLE
Suggestion: mention that `[remap foo]` works in `:bind`/bind-key

### ISSUE THREAD

**Issue by andschwa** [jwiegley/use-package#670]
I couldn't find any mention of this in the readme or documentation, but because of this fact about `bind-key`:

> KEY-NAME may be a vector, in which case it is passed straight to
`define-key'.

Using `[remap foo] . #'my-foo` works just fine for `bind-key` (and consequently also `:bind). This is great, because the following works as intended:

```
(use-package company
  :bind ([remap dabbrev-expand] . #'company-complete)
  :config (global-company-mode))
```

Instead of having to remember that I'm rebinding `M-/`.

Do you think this has a place in the readme or the documentation of `bind-key.el`? If not, at least this issue is now searchable 😄 

Edit: now that I know what to look for, I'm finding other issues. Still, it'd be nice to mention in docs.

**Comment by jwiegley** [comment]
Sounds like a very good addition to the README, as well as the commentary in `bind-key.el`.
