### ISSUE TITLE
hook: Add check for -mode suffix automatically

### ISSUE THREAD

**Issue by floli** [jwiegley/use-package#672]
Hello,
the code 
```
(use-package org-bullets
  :ensure t
  :hook (org-mode . org-bullets-mode))
```
works just fine. However, I expected

```
(use-package org-bullets
  :ensure t
  :hook org-mode)
```
fails with
```
(org-bullets org-ref-org-menu #[0 "ÀÁÂÃÄ$" [add-hook change-major-mode-hook org-show-block-all append local] 5] #[0 "ÀÁÂÃÄ$" [add-hook change-major-mode-hook org-babel-show-result-all append local] 5] org-babel-result-hide-spec org-babel-hide-all-hashes org-bullets-mode visual-line-mode)
```

So it seems, that use-package expects the activation function to be called exactly like the mode and does not try to append `-mode` to it.

Wouldn't it be wise to try for `org-bullets-mode` in this case?

Or am I mistaken on that?

**Comment by CeleritasCelery** [comment]
I came here to say the same thing. The majority of modes don’t include the word “mode” in package name.

**Comment by CeleritasCelery** [comment]
I came across the general package which provides the `:ghook` keyword. It is smart enough to infer the `-mode` for the function name but can’t infer the `-hook` for the hook name. Go figure 😕

**Comment by noctuid** [comment]
> I came across the general.el package which provides the :ghook keyword. It is smart enough to infer the -mode for the function name but can’t infer the -hook for the hook name. Go figure confused

It was an [intentional design decision](https://github.com/emacs-magus/satch.el#note-on-hook-shorthand).  If someone really wants it, I can make the shorthand opt-in.
