### ISSUE TITLE
Using use-package without using packages

### ISSUE THREAD

**Issue by nickgarber** [jwiegley/use-package#675]
Is it possible to use `use-package` to manage configuration generically, without operating on a particular package?

It looks like maybe this is already possible? (Example from documentation)
```
;; Completely hide visual-line-mode and change auto-fill-mode to " AF".
(use-package emacs
  :delight
  (auto-fill-function " AF")
  (visual-line-mode))
```

I think of `use-package` forms as roughly analogous to [unit files](https://www.freedesktop.org/software/systemd/man/systemd.unit.html). They handle registering the load-path, dependencies, key-bindings, hooks, pre-/post- configs, and so forth. 

`use-package` provides great tooling for keeping configuration organized, even when not directly involving a package manager.

**Comment by raxod502** [comment]
Note that `use-package` does not operate on packages in the `package.el` sense, but rather on features (which are also sometimes called packages).

The example you quoted seems like the correct way to manage this, to me, given that the `emacs` feature is already provided at Emacs startup.

Did you have a particular question, apart from whether this is the right approach?

**Comment by nickgarber** [comment]
I'd never seen that note about `use-package` operating on features explicitly stated and it adds a good note of clarity.

It seemed like maybe `emacs` was special-cased for this purpose, but I can now appreciate a bit more of the mechanisms at play.

So that answers my question around "is this possible?", but gives rise to another one ...

Is it possible to chain use-package macros together in a kind of dependency tree. Maybe this is an odd-looking question but I'm already doing something sorta similar, though markedly less clever. I can sense some opportunity to latch onto use-package to improve what I'm already doing anyway but the way to do that isn't fully clear to me.

**Comment by raxod502** [comment]
You can certainly put one `use-package` form inside another. People do that all the time, e.g. this example from the README:

```elisp
(use-package color-moccur
  :commands (isearch-moccur isearch-all)
  :bind (("M-s O" . moccur)
         :map isearch-mode-map
         ("M-o" . isearch-moccur)
         ("M-O" . isearch-moccur-all))
  :init
  (setq isearch-lazy-highlight t)
  :config
  (use-package moccur-edit))
```

Is that what you mean?

---

You should really think of `(use-package foo ...)` as `(with-eval-after-load 'foo ...)` with extra features. That helps me reason about its appropriate usage.

**Comment by nickgarber** [comment]
What I'd really like to do is modularize my config into discrete units that
are provided as named features and then coerce these units into the
expressive and completeness and simplicity of the use-package form.

If this is possible and sane, I'd next like to know if it's possible to use
this organizational approach for multiple use-package forms in a single
file?

Thanks very much for your illuminating responses. Appreciate it!

**Comment by raxod502** [comment]
Could you perhaps give an example of what you mean? [My configuration](https://github.com/raxod502/radian/blob/7462aa6e0f52c49ed0fd340b7fed8d2075f7cc67/radian-emacs/radian-text.el) is modularized into discrete units which are provided as named features, but it's not clear to me how `use-package` would be relevant. Unless you were thinking of using the modularized approach without having a different file for each module? In that case, I think you would be better served with a custom macro, like (warning, untested):

```elisp
(defmacro use-config (name &rest body)
  `(progn
     ,@body
     (provide ',name)))
```

You could possibly also include some error handling, like `use-package` does. But things like `:init`, `:config`, etc. are very closely tied to manipulating the handling of an externally defined feature. A `use-package` form for your own configuration seems like it would be degenerate.

**Comment by MetroWind** [comment]
My understanding of what @nickgarber wanted is to have `(use-package some-package)` even when `some-package` doesn't exists.

This is useful when I have some functions defined in my init file, and I want to manage them in a modular way. For example, I have some functions that me manipulating text:

    (defun f1 …)
    (defun f2 …)

And I have some other functions to… I don't know, manipulating windows and frames:

    (defun g1 …)
    (defun g2 …)

It would be useful to group them into `use-package`s so that I can toggle them and have dependencies among them:

    (use-package my-text-functions
      :init
      (defun f1 …)
      (defun f2 …))

And

    (use-package my-ui-functions
      :init
      (defun g1 …)
      (defun g2 …))

Can `use-package` do that in some way?

**Comment by jwiegley** [comment]
Does `:no-require` do what you need?

**Comment by raxod502** [comment]
@MetroWind If you really want to have custom feature names for your modules, and dependencies between them, then why not just use features and modules and `require` like usual? What advantage is gained by using `use-package` for this?

**Comment by nickgarber** [comment]
I've happily settled on using the `emacs` feature to bypass the require/packaging operation, but it sounds like `:no-require` is an equally good, (maybe better?) alternative.

Going back several years now I've been splitting up my configs into separate files under `~/.emacs.d/etc/init.d`, (with their backing packages in submodules at `~/.emacs.d/mnt/git/package-name-here`), and presented each one as a feature. The idea being to handle dependencies and configs in one place and provide a nice handle on enabling a feature so that my `init.el` is just a simple collection of `(require 'load-mode__package-name-here)`'s.

At some point I realized the files I was creating were a worse version of a `use-package` macro so have been reforming them into a `use-package` macro and a "custom" feature name in a `provide` sexp.

The key for me was to understand that the `use-package` names refer first to features and then packages - and that the `emacs` feature is safe to use as a wrapper name for misc configs. 

In retrospect I realize I was asking for the ability to declare/override features using `use-package` macros - sort of an inversion of the normal use. You might imagine this as looking something like:
```
(use-package erc
  :provide (erc nicks-example-erc-configs)
  :init (require 'erc)
  :config
  (erc-madeup-config-var t))
```

... but as I said, I'm quite happy with the available options now that I understand them better.

Really appreciate all the great tooling! Thank you @jwiegley, @raxod502, and @MetroWind !
