### ISSUE TITLE
use-package-ensure-system-package always prompt for installation

### ISSUE THREAD

**Issue by azzamsa** [jwiegley/use-package#677]
`:ensure` in use-package is very convenient. It prompts for package installation when package doesn't exist.

But `use-package-ensure-system-package` always prompt for distribution package installation every time I start emacs. Which is annoying.

Is this come by design ? Can we tell `use-package-ensure-system-package`  if the last time it tried to install, the package already installed ?

**Comment by waymondo** [comment]
If the binary is installed and known to Emacs's `exec-path`, you won't get the prompt to install the package. As mentioned in the [README](https://github.com/jwiegley/use-package#use-package-ensure-system-package), `exec-path-from-shell` is a good package to sync your shell's environment with Emacs, but you can customize `exec-path` directly as well.

**Comment by azzamsa** [comment]
Before I followed Debian package name. https://packages.debian.org/stretch/silversearcher-ag

``` elisp
(use-package helm-ag
  :ensure t
  :ensure-system-package silversearcher-ag
  :defer 4
  :diminish helm-ag-mode
  :bind ("C-c a" . helm-ag))
```

I have to cancel the prompt every time I start emacs. 

Seconds ago. I want to change the name to match the binary. `which silversearcher-ag` doesn't give me a result. It turns out the binary name was ag.

Changed `:ensure-system-package silversearcher-ag` to `:ensure-system-package ag` . Solved the problem. The annoying prompt disappeared.

PS: *I'm also confused. when to call it silversearcher/ag, it seems like mercurial/hg*

Thanks for this integration.

**Comment by avocadoras** [comment]
@waymondo I have this same issue but when I try to install python modules, specifically with jedi.
I have this 
```
(use-package company-jedi
  :after company
  :ensure-system-package
  ((jedi . "pip install jedi")
   (virtualenv . "pip install virtualenv"))
  :ensure t
  :init (add-to-list 'company-backends '(company-jedi :with company-yasnippet)))
``` 
but I still get a message that the package is already installed. Keep in mind, I am using pyenv, but this should not be an issue?
