### ISSUE TITLE
support for evil bindings

### ISSUE THREAD

**Issue by DarkWingMcQuack** [jwiegley/use-package#679]
currently using `:bind` is not nice to use for evil bindings.
It would be nice to have keywords such as `:bind-evil-normal`, `:bind-evil-visual`, `bind-evil-leader`, to nicly support lazy loading and keybindings with evil.

**Comment by Townk** [comment]
I know this is not a solution to your question, but I use [general](https://github.com/noctuid/general.el) to all my bindings, and it provides a `:general` keyword to `use-package` where I can define my keybindings to all modes.

For instance:

```elisp
(use-package counsel
  :general
  ("M-x" 'counsel-M-x)
  (:states '(normal visual)
   :prefix my/leader-key
   "fr" 'counsel-recentf))
```

**Comment by biocyberman** [comment]
@Townk Which version of use-package starts to support general? I tried with use-package version 20180314.1143 which is installed automatically by spacemacs (0.200.13), and it does not work:
`
Error (use-package): Failed to parse package org: use-package: Unrecognized keyword: :general`

My use-package is something like this:

 ```elisp
 (use-package org
    :demand 5
    :init
    (spacemacs/declare-prefix "o" "org")

    :general
    ("ob" . org-iswitchb)
    ("oc" . org-clock-goto)
    ("ok" . org-capture)
    ("ol" . org-store-link)
    ("oL" . org-insert-link)
    ("os" . org-search-view)

    (:keymaps org-mode-map
              ("C-c C-." . org-time-stamp-inactive)
              ("M-p" . org-metaup)
              ("M-n" . org-metadown)
              ("C-c c" . org-columns))

    (:keymaps org-mode-map
              :state normal
              ("RET" . org-return))
```

**Comment by dieggsy** [comment]
@biocyberman you need to install the general.el package as well, which provides the `:general` keyword. All use-package supports is custom keywords (which may be provided by another package, the user, etc.)

**Comment by biocyberman** [comment]
Got it. Thanks @dieggsy

**Comment by skangas** [comment]
The solution here seems to be to use the `general` package.

As for supporting `evil` key bindings, I think this is outside the scope of use-package and would be better implemented as a separate package adding the suggested `use-package` keywords.

**Comment by skangas** [comment]
I've tentatively marked this as `wontfix`.
