### ISSUE TITLE
use-package bind-keymap does not work well with guide-key

### ISSUE THREAD

**Issue by phenix3443** [jwiegley/use-package#685]
guide-key config:
```
(use-package guide-key
  :ensure t
  :config
  (setq guide-key/guide-key-sequence t)

  (setq guide-key/highlight-command-regexp
        '("rectangle"
          ("register" . font-lock-type-face)
          ("bookmark" . "hot pink")))

  (setq guide-key/idle-delay 0.5)
  (setq guide-key/recursive-key-sequence-flag t)
  (setq guide-key/popup-window-position 'bottom)
  (guide-key-mode 1)
  )
```

smartparents config:
```lisp
(use-package smartparens-config
  :ensure smartparens
  :commands (sp-beginning-of-next-sexp)

  ;; this config , the guide-key does not show the prompt correctly
  :bind-keymap ("C-c s" . smartparens-mode-map)
  :bind
  (:map smartparens-mode-map
        ("c" . sp-beginning-of-next-sexp))

  ;; this config, the guide-key show the prompt correctly
  ;; :bind
  ;; (:prefix-map smartparens-mode-map
  ;;              :prefix "C-c s"
  ;;              ("c" . sp-beginning-of-next-sexp))

  )
```

when i use smartparent,  i press C-c , but use the first config, the guide-key does not prompt correctly, 
![_001](https://user-images.githubusercontent.com/1721532/40877993-c104560e-66bc-11e8-9cf8-e462994b8ac3.png)

the second config is correct.
![_002](https://user-images.githubusercontent.com/1721532/40878010-fcf29662-66bc-11e8-9e67-da1a95ec6e2b.png)

**Comment by ysmolsky** [comment]
guide-key is broken in Emacs > 24.5: https://github.com/kai2nenobu/guide-key/issues/49
Also it is not maintained anymore as stated by the author. I suggest not to waste time with it.

**Comment by phenix3443** [comment]
@ysmolsky  thank you for your  answer, now i use which-key instead for guide key
