### ISSUE TITLE
Keyword for prettify symbols mode

### ISSUE THREAD

**Issue by mgttlinger** [jwiegley/use-package#687]
I often find myself defining custom `prettify-symbols-alist`s for different programming modes together with hooks for loading them.

It would be nice if `use-package` would have something like `:prettify` allowing a nice bundeled syntax for defining and loading that `alist`.
```elisp
(use-package haskell-mode
  :ensure t
  :prettify (("->" . ?→)
             ("=>" . ?⇒)))
```

Is this something which would fit into `use-package`?

**Comment by jwiegley** [comment]
This would be quite easy to add and maintain as a separate add-on package. See `use-package-bind-key` for an example of how to do so.
