### ISSUE TITLE
New :hook semantics

### ISSUE THREAD

**Issue by Kwarrtz** [jwiegley/use-package#691]
Based on what I've gleaned from the documentation, the `:hook <base>` command, when called without explicitly specifying the command to be added, will expand to `:hook (<base> . <package-name>)`. This works fine in some circumstances, however, in my experience, the far more common pattern is `:hook (<base> . <package-name>-mode)`, at least in the case of packages that do not already have `mode` in their name. To me, this seems like the more useful default behavior. Could this behavior be added, e.g. in a new command?

**Comment by alphapapa** [comment]
I agree that it feels a bit confusing, but I'd settle for `:hook` being in `use-package`'s docstring, so I wouldn't have to open a browser to here to look at the readme.  :)
