### ISSUE TITLE
Don't configure a package if not installed?

### ISSUE THREAD

**Issue by MetroWind** [jwiegley/use-package#693]
What's the best way to not configure a package if it's not installed?

Suppose I have this in my `.emacs.el`:

    (use-package web-mode
      :mode "\\.html?$"
      :config
      ;; some setqs...
      )

If I don't have web-mode installed, the `:config` part will never trigger, but looks like the `:mode` setting is still done. So if I try to open a HTML file, it will complain about cannot loading web-mode. Ideally, it would be best that if web-mode is not installed the whole `use-package` call is disabled. I suppose I can put a `:if (package-installed-p 'web-mode)` there, but that only works if web-mode is installed through elpa (I'm not sure, is that true?). It could also be slower than necessary (again I'm not sure. Is it slow?). Is there a better way?

**Comment by waymondo** [comment]
The `:if (package-installed-p 'web-mode)` method you've described seems reasonable, and will simply look for the presence of the package regardless of the package archive it was installed with.

Do you have a specific reason you don't want to just use `:ensure t` in this case?

**Comment by skangas** [comment]
I think you should use `:if (locate-library "web-mode")`, or `:if (or (locate-library "web-mode") (package-installed-p 'web-mode))`. Perhaps we should add some notes to that effect to the documentation.

**Comment by skangas** [comment]
I've now added such an example to the use-package manual: https://git.savannah.gnu.org/cgit/emacs.git/commit/?h=emacs-29&id=a17a6036dd4549514c7cecc7cdd93a571bf57ece

This change will be a part of the use-package shipped with Emacs 29. I'm therefore closing this issue.

**Comment by monnier** [comment]
I don't really understand why people want to use `locate-library` here (seems costly to me), but FWIW I think the better test here is `:if (fboundp 'web-mode)`.
