### ISSUE TITLE
error "use-package: Unrecognized keyword: :chords

### ISSUE THREAD

**Issue by poulpoulsen** [jwiegley/use-package#694]
Hello,
i use emacs 26 on windows 8.1 64bit.

After melpa update i got the following error:
Debugger entered--Lisp error: (error "use-package: Unrecognized keyword: :chords")
  signal(error ("use-package: Unrecognized keyword: :chords"))
  error("use-package: %s" "Unrecognized keyword: :chords")
  use-package-normalize-plist(avy (:chords (("jj" . avy-goto-char-timer) ("jl" . avy-goto-line) ("jw" . avy-goto-word-1))) nil use-package-merge-keys)
  use-package-normalize-plist(avy (:ensure t :chords (("jj" . avy-goto-char-timer) ("jl" . avy-goto-line) ("jw" . avy-goto-word-1))) nil use-package-merge-keys)
  use-package-normalize-keywords(avy (:ensure t :chords (("jj" . avy-goto-char-timer) ("jl" . avy-goto-line) ("jw" . avy-goto-word-1))))
  #f(compiled-function (name &rest args) "Declare an Emacs package by specifying a group of configuration options.\n\nFor full documentation, please see the README file that came with\nthis file.  Usage:\n\n  (use-package package-name\n     [:keyword [option]]...)\n\n:init            Code to run before PACKAGE-NAME has been loaded.\n:config          Code to run after PACKAGE-NAME has been loaded.  Note that\n                 if loading is deferred for any reason, this code does not\n                 execute until the lazy load has occurred.\n:preface         Code to be run before everything except `:disabled'; this\n                 can be used to define functions for use in `:if', or that\n                 should be seen by the byte-compiler.\n\n:mode            Form to be added to `auto-mode-alist'.\n:magic           Form to be added to `magic-mode-alist'.\n:magic-fallback  Form to be added to `magic-fallback-mode-alist'.\n:interpreter     Form to be added to `interpreter-mode-alist'.\n\n:commands        Define autoloads for commands that will be defined by the\n                 package.  This is useful if the package is being lazily\n                 loaded, and you wish to conditionally call functions in your\n                 `:init' block that are defined in the package.\n\n:bind            Bind keys, and define autoloads for the bound commands.\n:bind*           Bind keys, and define autoloads for the bound commands,\n                 *overriding all minor mode bindings*.\n:bind-keymap     Bind a key prefix to an auto-loaded keymap defined in the\n                 package.  This is like `:bind', but for keymaps.\n:bind-keymap*    Like `:bind-keymap', but overrides all minor mode bindings\n\n:defer           Defer loading of a package -- this is implied when using\n                 `:commands', `:bind', `:bind*', `:mode', `:magic',\n                 `:magic-fallback', or `:interpreter'.  This can be an integer,\n                 to force loading after N seconds of idle time, if the package\n                 has not already been loaded.\n:after           Defer loading of a package until after any of the named\n                 features are loaded.\n:demand          Prevent deferred loading in all cases.\n\n:if EXPR         Initialize and load only if EXPR evaluates to a non-nil value.\n:disabled        The package is ignored completely if this keyword is present.\n:defines         Declare certain variables to silence the byte-compiler.\n:functions       Declare certain functions to silence the byte-compiler.\n:load-path       Add to the `load-path' before attempting to load the package.\n:diminish        Support for diminish.el (if installed).\n:delight         Support for delight.el (if installed).\n:custom          Call `customize-set-variable' with each variable definition.\n:custom-face     Call `customize-set-faces' with each face definition.\n:ensure          Loads the package using package.el if necessary.\n:pin             Pin the package to an archive." #<bytecode 0x148781d>)(avy :ensure t :chords (("jj" . avy-goto-char-timer) ("jl" . avy-goto-line) ("jw" . avy-goto-word-1)))
  macroexpand((use-package avy :ensure t :chords (("jj" . avy-goto-char-timer) ("jl" . avy-goto-line) ("jw" . avy-goto-word-1))))
  internal-macroexpand-for-load((use-package avy :ensure t :chords (("jj" . avy-goto-char-timer) ("jl" . avy-goto-line) ("jw" . avy-goto-word-1))) nil)
  eval-buffer(#<buffer  *load*-499545> nil "c:/Users/Held/emax/emax.el" nil t)  ; Reading at buffer position 9143
  load-with-code-conversion("c:/Users/Held/emax/emax.el" "c:/Users/Held/emax/emax.el" nil nil)
  load("c:/Users/Held/emax/emax.el" nil nil t)
  load-file("c:/Users/Held/emax/emax.el")
  org-babel-load-file("c:/Users/Held/emax/emax.org")
  eval-buffer(#<buffer  *load*> nil "c:/Users/Held/.emacs" nil t)  ; Reading at buffer position 2712
  load-with-code-conversion("c:/Users/Held/.emacs" "c:/Users/Held/.emacs" t t)
  load("~/.emacs" t t)
  #f(compiled-function () #<bytecode 0x1000c02e9>)()
  command-line()
  normal-top-level()

Any infos about that?
Is this a new issue?

Regards
Poul

**Comment by waymondo** [comment]
It seems you are trying to use `(use-package-chords)` without having loaded it. Try adding `(use-package use-package-chords)` to your init before any package declarations with the `:chords` keyword.

**Comment by poulpoulsen** [comment]
Hello,
i check it out, but unfortunately no change.
Someone suggest to put :chords at the beginning of the declaration, but also with that no other result.
For now i comment out my chords.
Sad :-(

Thanks

**Comment by waymondo** [comment]
Are you ensuring that `use-package-chords` is installed? Try:

```
(use-package use-package-chords
  :ensure t)
```

**Comment by nanounanue** [comment]
I have the same problem, the suggestion from @waymondo  didn't solve the problem

**Comment by waymondo** [comment]
Is `(use-package use-package-chords :ensure t)` set before any calls to `use-package` forms using the `:chords` keyword? Is `use-package-chords` installed?

**Comment by benide** [comment]
I also have this problem. I had already made sure of everything you mentioned. @poulpoulsen and @nanounanue, did either of you figure it out?

**Comment by benide** [comment]
It turns out my problem was not the same as @poulpoulsen, as mine arose from Emacs 27. I actually don't know why this fixed it for me, but adding `(setq package-enable-at-startup nil)` to my `early-init.el` worked.

**Comment by kkhan01** [comment]
Hey, this is an old issue, but I just encountered it and I was able to fix it with `demand`:
```lisp
(use-package key-chord
  :demand t
  :custom
  (key-chord-two-keys-delay 0.05)
  :config
  (key-chord-mode t))

(use-package use-package-chords
  :demand t)

(use-package hydra
  :custom
  (hydra--work-around-dedicated nil)
  (hydra-is-helpful t)
  (hydra-hint-display-type 'lv)
  (lv-use-separator nil)
  :chords
  ("ao" . hydra-leader/body))

(use-package pretty-hydra)
```
Hopefully that helps someone else.
