### ISSUE TITLE
please consider a new release version

### ISSUE THREAD

**Issue by bymoz089** [jwiegley/use-package#700]
Some people rather use release versions than latest development versions.
The current development version is, in view of features, pretty far away from latest release.
So please consider a new release.

**Comment by sboosali** [comment]
any update on releasing `2.4`?

**Comment by sondr3** [comment]
Just hit this snag when trying to move some packages to Melpa Stable, `use-package` from Melpa Stable isn't compatible with the latest `delight`, which is a bummer. Sorry to bother you @jwiegley.

**Comment by jwiegley** [comment]
I've pushed the tag for `2.4`.

**Comment by benf-portable** [comment]
> I've pushed the tag for 2.4.

Thanks!
‘use-package’ version 2.4 is now (2019-03-19) [the default at melpa-stable](https://stable.melpa.org/#/use-package), so I think this issue is resolved. Close it?
