### ISSUE TITLE
:bind does not seem to support mouse bindings

### ISSUE THREAD

**Issue by tger** [jwiegley/use-package#701]
I'm trying to do sth like this:
```
(use-package cider-mode
  :bind (("C-<mouse>-1" . cider-find-var-at-mouse)
	 ("C-down-<mouse>-1" . nil)))
```
but I get this when evaluating: 

`Error (use-package): cider-mode/:catch: C- must prefix a single character, not <mouse>-1`

I tried without the angle brackets as well, same result. Is binding mouse events unsupported?

**Comment by npostavs** [comment]
The `-1` needs to be inside the angle brackets. Try looking at the notation Emacs uses when you do <kbd><kbd>f1</kbd> <kbd>k</kbd></kbd> *mouse-click*.

**Comment by tger** [comment]
Ah yes, when I put the _C_ inside the brackets as well it works. (`<C-mouse-1>`)
Cheers!
