### ISSUE TITLE
:custom doesn't seem to work with custom setters

### ISSUE THREAD

**Issue by alphapapa** [jwiegley/use-package#702]
Hi,

It seems that the `:custom` keyword's expansion doesn't work with `defcustom`s that have custom `:set` setters.  For example:
```el
(use-package magit-todos
  :custom ((magit-todos-depth 25)
           (magit-todos-keywords '("TODO"))))
```
That expands to:
```el
(progn
  (defvar use-package--warning93
    #'(lambda
        (keyword err)
        (let
            ((msg
              (format "%s/%s: %s" 'magit-todos keyword
                      (error-message-string err))))
          (display-warning 'use-package msg :error))))
  (condition-case-unless-debug err
      (progn
        (customize-set-variable 'magit-todos-depth 25 "Customized with use-package magit-todos")
        (customize-set-variable 'magit-todos-keywords
                                '("TODO")
                                "Customized with use-package magit-todos")
        (if
            (not
             (require 'magit-todos nil t))
            (display-warning 'use-package
                             (format "Cannot load %s" 'magit-todos)
                             :error)))
    (error
     (funcall use-package--warning93 :catch err))))
```
That calls `customize-set-variable` before the package is loaded, so the custom setter for `magit-todos-keywords` is not yet loaded.

Wrapping those calls in `with-eval-after-load` seems to fix it, like this:
```el
(progn
  (defvar use-package--warning93
    #'(lambda
        (keyword err)
        (let
            ((msg
              (format "%s/%s: %s" 'magit-todos keyword
                      (error-message-string err))))
          (display-warning 'use-package msg :error))))
  (condition-case-unless-debug err
      (progn
        (with-eval-after-load 'magit-todos
          (customize-set-variable 'magit-todos-depth 25 "Customized with use-package magit-todos")
          (customize-set-variable 'magit-todos-keywords
                                  '("TODO")
                                  "Customized with use-package magit-todos"))
        (if
            (not
             (require 'magit-todos nil t))
            (display-warning 'use-package
                             (format "Cannot load %s" 'magit-todos)
                             :error)))
    (error
     (funcall use-package--warning93 :catch err))))
```

**Comment by alphapapa** [comment]
If this change looks appropriate, I can send a PR implementing it.

**Comment by slippycheeze** [comment]
The correct fix would be for the code to avoid `customize-set-variable`, which doesn't work, and prefer to use one of `customize-set-variables`, or `customize-theme-set-variables`, which do correctly handle stashing the value away so that when `defcustom` runs it will be applied using the `:set` or `:initialize` stanza.

I'd personally think that `(customize-set-variables ...)`, which is a wrapper for `(customize-theme-set-variables 'user ...)`, is the appropriate choice: these are user-specified customizations, so should be applied there.

The alternative would be that `use-package` calls `deftheme` for a custom theme it owns, which it can activate and layer below user but above anything else, and then assigns these in that theme.

However, that adds significant complexity for, I think, minimal gain: if someone is going to the trouble of writing custom stanzas in their init file like this, they probably don't want to fuss much with disabling only the parts set by `use-package` and not by other customize layers.

I think the real confusion comes from the fact that `customize-set-variable` is part of the editing suite, and so assumes that the `defcustom` form must have been evaluated in order to show the edit screen.  That frees it from handling "assignment before definition" complexity, which the normal custom process has to handle.

That is: your analysis is correct, but your resolution probably isn't, since it works around the misuse of a method that probably shouldn't be publicly used the way it is.  Using the correct interface will solve this without either `eval-on-load` or demand-loading the package if custom settings are asserted.

**Comment by alphapapa** [comment]
@slippycheeze I guess you mean `custom-set-variables`?  Thanks, I wasn't aware of that.  Looking at the docstring, it sounds like it's probably the best solution.

**Comment by slippycheeze** [comment]
FWIW, here is my reimplementation of :custom that uses `custom-set-variables`, and which generates configuration matching what the native custom system does in the save file.

@jwiegley I do have appropriate papers on file through my employer for this being integrated into core Emacs, which I understand this package is either destined for, or already delivered.

```elisp
(define-advice use-package-handler/:custom
    (:override (name keyword args rest state) use-custom-set-vars -100)
  "Unfortunately, `use-package` chose `customize-set-variable` for their
custom implementation.  That never calls the custom variable setter
unless the package was already loaded.  `custom-set-variables` contains
all the logic to defer processing until the package loads."
  (debug)
  (use-package-concat
   ;; one extra level deep, because concat.
   `((custom-set-variables
      ,@(-map (lambda (form)
		(list 'quote (list (first form)
                                   (second form)
                                   nil nil  ; now, request
                                   (format "dp+use-package(%s):%s:%s:%s: %s"
                                           name
                                           (let ((file (buffer-file-name)))
                                             (if file (abbreviate-file-name file) "-"))
                                           (or (line-number-at-pos) 1)
                                           (1+ (or (current-column) 0))
                                           (or (third form)
                                               "set programatically")))))
              args)
      (use-package-process-keywords name rest state)))))
```

**Comment by alphapapa** [comment]
@slippycheeze Since that uses advice, I guess you mean that as an example of fixing it in a user's config rather than merging that into use-package?  (BTW, for advice you should generally use `advice-add`, according to the manual.)

It would be a bit easier to follow if you used backquoted list forms in the lambda instead of `(list 'quote (list ...`.  :)

**Comment by slippycheeze** [comment]
Nah, that is an "override" advice.  Replace it with a boring ordinary defun if you want, same effect.

I ... think your manual is perhaps a little out of date, incidentally.  The nadvice system, of which this is an example, is definitely the recommended version now.  However, part of the reason I posted the code dump that works for me, and not a patch, is that I have not made any effort to, eg, make sure this is compatible back before Emacs 25, and I don't know what the policy here is about that.

Plus I never thought `\`'(...)` was easier to read, and `\`(quote (...))` seems to lose some of the advantage. ;)

**Comment by alphapapa** [comment]
> I ... think your manual is perhaps a little out of date, incidentally. The nadvice system, of which this is an example, is definitely the recommended version now. 

https://www.gnu.org/software/emacs/manual/html_node/elisp/Advising-Named-Functions.html#Advising-Named-Functions

The manual isn't clear about when to use `define-advice` instead of `advice-add`, but it appears to be mainly intended for defining anonymous-yet-named advice.  To me, the signature is harder to follow than `advice-add`, but it's up to you.

**Comment by alphapapa** [comment]
@jwiegley Friendly ping.  :)

**Comment by jwiegley** [comment]
@alphapapa Hi, is there a PR for this work?

**Comment by skangas** [comment]
> The correct fix would be for the code to avoid `customize-set-variable`, which doesn't work, and prefer to use one of `customize-set-variables`, or `customize-theme-set-variables`, which do correctly handle stashing the value away so that when `defcustom` runs it will be applied using the `:set` or `:initialize` stanza.

This is what use-package is doing these days:

```
(use-package foo
  :custom (foo . nil))
```

Expands to:

```
(progn
  (let
      ((custom--inhibit-theme-enable nil))
    (unless
        (memq 'use-package custom-known-themes)
      (deftheme use-package)
      (enable-theme 'use-package)
      (setq custom-enabled-themes
            (remq 'use-package custom-enabled-themes)))
    (custom-theme-set-variables 'use-package
                                '(foo nil nil nil "Customized with use-package foo")))
  (require 'foo nil nil))
```

As it seems like this has been resolved, I'm closing this issue. Please report back if I'm missing something, and we can reopen. Thanks.

**Comment by alphapapa** [comment]
@skangas Thank you for your work on use-package!
