### ISSUE TITLE
Download PR of package installed via use-package

### ISSUE THREAD

**Issue by thisch** [jwiegley/use-package#708]
I would like to test a PR of an emacs package, which I've installed/configured using use-package. I've never done this before, so please forgive me if this feature request does not make sense. 

Maybe there is already a way to do that using the package.el infrastructure. WDYT about adding support for downloading PR can be added to use-package?

**Comment by jwiegley** [comment]
@thisch Hi Thomas, interesting idea but that's really out of scope for what `use-package` does. It never "reaches out to the network", like package.el does.  You might suggest it to the author of straight.el, though, which is built on top of use-package.
