### ISSUE TITLE
hook not working properly with LaTeX-mode-hook

### ISSUE THREAD

**Issue by Salompas** [jwiegley/use-package#712]
The following does not work:
```
(use-package latex-extra
  :ensure t
  :hook (LaTeX-mode-hook . latex-extra-mode))
```
But this one works:
```
(use-package latex-extra
  :ensure t
  :init (add-hook 'LaTeX-mode-hook #'latex-extra-mode))
```
From the readme they are supposed to be equivalent, but it is not working for this case. Notice that the name of the package and the name of the mode do not coincide, like in the examples of the readme.

**Comment by Salompas** [comment]
Again, another failure on my part.
It does work, but I was passing `:hook` the wrong symbol, instead of `LaTeX-mode-hook`, it should have been `LaTeX-mode`.
Fixing the code above:
```
(use-package latex-extra
  :ensure t
  :hook (LaTeX-mode . latex-extra-mode))
```

**Comment by dieggsy** [comment]
@Salompas also check out `use-package-hook-name-suffix`:

```
use-package-hook-name-suffix is a variable defined in ‘use-package-core.el’.
Its value is "-hook"

Documentation:
Text append to the name of hooks mentioned by :hook.
Set to nil if you don’t want this to happen; it’s only a
convenience.

You can customize this variable.
```
