### ISSUE TITLE
:bind does not accept `nil` as the binding, and cannot otherwise unbind keys

### ISSUE THREAD

**Issue by slippycheeze** [jwiegley/use-package#715]
In porting some older configuration to `use-package`, I discovered that a couple of my statements were (obscurely) blowing up the macro.  It turns out the cause was this (cut-down) change:

```elisp
;; unbind insert/overwrite toggle, because the later is extremely rarely what I want
(define-key global-map [(insert)] nil)
;; which became, for demonstration purposes, this:
(use-package emacs :bind ([(insert)] nil))
```

...and that caused an error because `nil` is not an acceptable form while normalizing the :bind expression:

```
Error (use-package): Failed to parse package emacs: use-package: emacs wants arguments acceptable to the `bind-keys' macro, or a list of such values
```

In my opinion, this should be supported, especially as that absolutely *is* a valid `bind-key` form, and will result in the expected outcome.  In fact, `unbind-key` is literally a macro that simply passes a `nil` for the binding, plus the code to record that into the personal keymap tracker: https://github.com/jwiegley/use-package/blob/master/bind-key.el#L193

**Comment by CyberShadow** [comment]
I think the correct syntax is: `:bind ([(insert)] . nil)`

**Comment by jwiegley** [comment]
Or just `:bind ([(insert)]))`, since `(a . nil)` is equivalent to `(a)`.

**Comment by slippycheeze** [comment]
Thanks, I think that is my bad, appreciated.
