### ISSUE TITLE
Programmatic package installation

### ISSUE THREAD

**Issue by holocronweaver** [jwiegley/use-package#718]
Similar to #182, I wish to programmatically install a list of packages using `use-package`. 

How can this be done? If it can't currently be done, is it possible to make it work?

Use case: I am trying to add `use-package` to Prelude, which relies on package lists and on-the-fly package installation when certain file extensions are encountered.  Having to convert this to explicit use-package declarations for each package will significantly bloat the code for no benefit. I would much rather use a package install function as is currently done in Prelude, and replace `package-install` with `use-package`. The goal is to make Prelude use whatever backend `use-package` is configured with, whether that be `straight.el` or `package`.

**Comment by holocronweaver** [comment]
I know that use-package is a wrapper over package managers. You may have missed my edits, please my updated issue description which now includes a use case.

Also let me clarify what I am trying to do with an example from the ticket I linked:

```
(defvar my-packages '(auto-compile
                       better-defaults
                       smex
                       fiplr
                       discover
                       yafolding
                       helm
                       org))

(dolist (p my-packages)
  (use-package p))

=> Error (use-package): Could not load package p
```

I need something like this to work for integrating `use-package` with `Prelude`.

**Comment by sboosali** [comment]
use-package can install packages with the `:ensure` keyword (see https://jwiegley.github.io/use-package/keywords/ ). but it's better to think about it as a wrapper around `require` (elisp import statement). just use `package-install` (which is built into emacs).


can we close this issue?

**Comment by holocronweaver** [comment]
Can't use `package-install` for this use case, please read above.

**Comment by sboosali** [comment]
have you tried `:ensure` (see link above). with `:pin`, if you need a specific repository.

**Comment by holocronweaver** [comment]
Not sure I follow. I need to be able to call `use-package` in a loop on a list of packages.

**Comment by sboosali** [comment]
`(use-package p)` is like `(require 'p)`, just do that if you want
configure your installed packages by looping over a list of symbols.

otherwise, if you want to install them too, rather than just loading and
are considering them, you have to use one of the things I mentioned.

**Comment by skangas** [comment]
I think the answer here is the same as the one in https://github.com/jwiegley/use-package/issues/182#issuecomment-83226802: this is simply outside the scope of the `use-package` macro.

> I want to programmatically install and configure packages, and the hope is that `use-package` can do this in a package-manager agnostic way so that Prelude users can configure `use-package` to use whatever manager they want (`package.el`, `straight.el`, etc., whatever plugs into use-package). That way Prelude itself can be package manager agnostic.

To integrate more neatly with use-package, I would do something like:

```
(defvar my-packages '(auto-compile
                       better-defaults
                       smex
                       fiplr
                       discover
                       yafolding
                       helm
                       org))
(dolist (p my-packages)
  (funcall use-package-ensure-function p))
```

I'm therefore closing this issue as `wontfix`.
