### ISSUE TITLE
Hook not working with C-mode

### ISSUE THREAD

**Issue by RomeuG** [jwiegley/use-package#719]
Hi.

I am trying to do this, to execute `rainbow-delimiters-mode` only on c-mode:

```
(use-package rainbow-delimiters
  :defer t
  :hook (c-mode . rainbow-delimiters-mode))
```

But for some reason it is not working. If I change `c-mode` for `prog-mode`, everything works fine, but that is something I do not want to do.

Anything wrong? Something I should change?

**Comment by jwiegley** [comment]
You don't need `:defer t` in your example, it's implied by `:hook`.

Not sure why `c-mode` isn't being hooked.  Try `c-mode-common`?

**Comment by RomeuG** [comment]
Well, that is it!
It is c-mode-common indeed. I have no idea why. Anyways, it is working now.
Thanks for your time.
