### ISSUE TITLE
Does `provide` conflict with `use-package`?

### ISSUE THREAD

**Issue by ccqpein** [jwiegley/use-package#722]
Hi, I just start to use `use-package` yesterday. However, it looks like my config not works well. 

Here is my `init.el`

```elisp
(require 'package)
(dolist (url '(("melpa" . "https://melpa.org/packages/")
               ("melpa-stable" . "http://stable.melpa.org/packages/")))
  (add-to-list 'package-archives url t))
(dolist (path '("~/.emacs.d/elpa" "~/.emacs.d/plugins/" "~/.emacs.d/lisp/"))
  (add-to-list 'load-path path))
(setq package-enable-at-startup nil)
(package-initialize)
(eval-when-compile (require 'use-package))
(require 'init-treemacs)
```

And here is my init-treemacs file in .emacs.d/lisp/

```elisp
(use-package treemacs
  :ensure t
  :init (bind-key "C-x M-d" treemacs)
  :custom (treemacs-width 25))
(provide 'init-treemacs)
```

When I start Emacs, `treemacs` looks like not be loaded.

1. C-x M-d does not work
2. I start `treemacs` manually, and `treemacs-width` is not 25

Do I miss some important part? 

Thank you

**Comment by jwiegley** [comment]
Can you please try this form:

``` lisp
(use-package treemacs
  :ensure t
  :bind ("C-x M-d" . treemacs)
  :custom (treemacs-width 25))
```

**Comment by ccqpein** [comment]
Thank you jwiegley. Your resolution works. Forgive me I am a newbee of your use-pacakage. I have several questions about my issues.

1. Why `:init` is not work for my situation? I thought `:init` will run anyway. So if I use `:init`, I have to use `:commands` too, is it right?
2. Is it because that `:init` make package has not been loaded, let all `:custom` arent loaded neither?

Thank you

**Comment by jwiegley** [comment]
I *think* that your `:init` version would have had to have been `:init (bind-key "C-x M-d" #'treemacs)`. Otherwise, there was nothing else wrong with it.

**Comment by ccqpein** [comment]
You are right. It works. Thanks
