### ISSUE TITLE
add-hook leads to errors with company-mode

### ISSUE THREAD

**Issue by titaniumbones** [jwiegley/use-package#734]
Copying over from my erroneous report in company-mode/company-mode#842.  I'm getting an error on startup that I'm having trouble tracking down, and am wondering if you can help me figure out where it comes from.  

I initialize company with use-package: 

```
(use-package company
      :ensure t
      :hook
      (after-init . 'global-company-mode) )
```
I would expect that the value of `after-init-hook` would now include `global-company-mode` , but instead it looks like this:

(#[0 "\303\211\235\203\0\304\"\301\305!\210\210	\205\0\306 \210\307\211\207" [command-line-args desktop-save-mode inhibit-startup-screen "--no-desktop" delete 0 desktop-read t] 4] global-emojify-mode company global-flycheck-mode x-wm-set-size-hint tramp-register-archive-file-name-handler table--make-cell-map)
```
Several of these are mysterious to me but the only one that errors out is `company` which gives the following (called manually here):

```
Debugger entered--Lisp error: (error "Autoloading file /home/matt/.emacs.d/elpa/company-20181012.2220/company.elc failed to define function company")
  (company)
  eval((company) nil)
  eval-expression((company) nil nil 127)
  funcall-interactively(eval-expression (company) nil nil 127)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

`pp-macroexpand-last-sexp` gives

```
(progn
  (use-package-ensure-elpa 'company
                           '(t)
                           'nil)
  (defvar use-package--warning115
    #'(lambda
        (keyword err)
        (let
            ((msg
              (format "%s/%s: %s" 'company keyword
                      (error-message-string err))))
          (display-warning 'use-package msg :error))))
  (condition-case-unless-debug err
      (progn
        (unless
            (fboundp 'company)
          (autoload #'company "company" nil t))
        (add-hook 'after-init-hook #'company)
        (add-hook 'quote-hook #'company)
        (add-hook 'global-company-mode-hook #'company))
    (error
     (funcall use-package--warning115 :catch err))))
```

Any idea what might be causing this? looks like it might be similar to #731. Thanks!

Matt

**Comment by jpkotta** [comment]
You probably just need to remove the quote on the function: `(after-init . global-company-mode)`.  The examples don't have quotes, and no quotes is consistent with the `:bind` syntax.

**Comment by rprimus** [comment]
Wed Dec  5 15:38:51 GMT 2018

@titaniumbones 

Whenever experiencing (strange) problems, it helps to remove all byte-compiled  (`.elc`) files:
```
cd ~/.emacs.d && find . -name '*.elc' -delete
```

**Comment by skangas** [comment]
There has been no further updates here within 4 years, so I'm going to go ahead and assume that the above fixed it. I'm therefore closing this issue.

Please report back if this is still an issue, and we can reopen. Thanks.
