### ISSUE TITLE
:pin keyword doesn't work with autoloading

### ISSUE THREAD

**Issue by jpkotta** [jwiegley/use-package#737]
Using Emacs 26.1, use-package 2.4.

Minimal init.el:

```
(setq package-user-dir (expand-file-name
                        (format "elpa-test")
                        user-emacs-directory))

(package-initialize)
(setq package-archives '(("melpa-stable" . "http://stable.melpa.org/packages/")
                         ("melpa" . "http://melpa.org/packages/")
                         ("gnu" . "http://elpa.gnu.org/packages/")))

(use-package no-littering
  :pin melpa
  )
```

Fails with "Error (use-package): Failed to parse package no-littering: use-package: Unrecognized keyword: :pin".  Adding a `(require 'use-package)` fixes it.  I notice that my `use-package-autoloads.el` doesn't have anything related to `:pin`.

**Comment by skangas** [comment]
I think it's expected on old versions of Emacs that you either need to run `(require 'use-package)` or `(package-activate)` before using use-package. So please do that.
