### ISSUE TITLE
:defer nil and :demand t 

### ISSUE THREAD

**Issue by nyraghu** [jwiegley/use-package#738]
I may be mistaken, but :defer nil and :demand t seem to have the same effect.  Is that correct? I didn't see anything in the documentation that mentions it.

**Comment by nyraghu** [comment]
So :defer nil doesn't override :commands foo, etc., whereas :demand t does.  Thanks for the explanation.

**Comment by Silex** [comment]
@nyraghu: not sure what happens if you have `:commands` AND `:defer nil`. To me it does not make a lot of sense, I guess that yeah it might behave the same as `:demand t` but I would not count on it.
