### ISSUE TITLE
:custom with variables that are not loaded immediately

### ISSUE THREAD

**Issue by mgttlinger** [jwiegley/use-package#741]
For example `mu4e` has the customizable variable `mu4e-bookmarks` that is not available when the customizations are run but rather loaded later causing the `use-package` call to fail. 
A similar situation is customizing `org-format-latex-options` which needs a `require 'ox-latex` beforehand.

What is the best way to deal with this situation where you want to customize a variable that becomes available only after a `require` call?

**Comment by a13** [comment]
>mu4e-bookmarks is a variable defined in ‘mu4e-vars.el’.

```
(use-package mu4e-vars
  :defer t
  :custom
  (mu4e-bookmarks …))

```

**Comment by mgttlinger** [comment]
That works perfectly, Thanks
