### ISSUE TITLE
inject hooks are not added

### ISSUE THREAD

**Issue by LeOtaku** [jwiegley/use-package#742]
When I put
```lisp
(setq use-package-inject-hooks t)
```
in my emacs configuration, no pre/post-init hooks are added to any of my `use-package` declarations, even though the variables documentation clearly states this should be the case.

> If non-nil, add hooks to the ‘:init’ and ‘:config’ sections.
In particular, for a given package ‘foo’, the following hooks
become available:
>
> ‘use-package--foo--pre-init-hook’
  ‘use-package--foo--post-init-hook’
  ‘use-package--foo--pre-config-hook’
  ‘use-package--foo--post-config-hook’

**Comment by jwiegley** [comment]
You didn't compile your `init.el` before enabling this, did you?

What happens if you expand the `use-package` macro using `M-: pp-macroexpand-last-sexp RET` with cursor just after the closing paren of the macro invocation?

**Comment by LeOtaku** [comment]
Unfortunately I seem to have missunderstood the way emacs hooks work. The hooks actually were being run, but not explicitly defined. I did not know that one coud symply `add-hook` to an unset variable to make it into a valid hook.

Im sorry for any confusion this might have caused.
