### ISSUE TITLE
Emacs Package QuickStart Feature

### ISSUE THREAD

**Issue by jsirex** [jwiegley/use-package#747]
I'm not a pro in emacs so it is not obvious for me: does this new feature `package-quickstart` conflicts with `use-package` or they can co-exist?

Probably docs should be updated in that case..

**Comment by Ergus** [comment]
They can coexist with no issues, I have them. You just need to remember to update the quickstart file `M-x package-quickstart-refresh` if you do important changes in the init config, but that's general, no use-package's specific.

**Comment by jsirex** [comment]
I'm a bit confused with packages' autoload vs use-packages' load-on-demand.
If all auto-load code is concatenated into single file will load-on-demand just "load all" or use-package will ignore?

PS. Really noob in how use-package magic is working. On other hand, still noob in emacs/lisp
