### ISSUE TITLE
support functions in :custom

### ISSUE THREAD

**Issue by dsvensson** [jwiegley/use-package#748]
To modify the `defcustom` of `ivy-rich` according to:

https://github.com/Yevgnen/ivy-rich#1312-add-icons-for-ivy-switch-buffer

...it seems that you have to add the whole list, as it would otherwise overwrite it. After looking around I found this blog post which uses `plist-put` to modify the variable:

https://github.com/SuzumiyaAoba/prologue/blob/master/content/posts/2019-01-01--ivy/index.md#ivy-rich

This is however not possible, as `:custom` only take constant values if I understand correctly.

Would it be a good idea to have something like:

    `(somedefcustom ,(somecall-producing-value))

...or that's just crazy-talk?

**Comment by jwiegley** [comment]
In that case, you might want to just call some Lisp code from a `:config` block, rather than extend the syntax further...

**Comment by dsvensson** [comment]
Yep, that works too. Just thought it would be nice to have all the config in one place per package.

**Comment by dsvensson** [comment]
But there's also fairly common use-case of setting dynamic paths, such as...

    (custom-set-variables
      `(flycheck-go-errcheck-executable ,(concat go-projectile-tools-path "/bin/errcheck")))

...and similar, but yeah, your comment still applies. Matter of taste.
