### ISSUE TITLE
How can I properly defer pdf-tools?

### ISSUE THREAD

**Issue by alienbogart** [jwiegley/use-package#755]
#### Runtime Environment ####

- MX Linux 18
- GNU Emacs 27.0.50
- Evil version 1.2.14
- [.emacs.d](https://github.com/mrbig033/dotfiles/tree/master/emacs/emacs_default)
- [packages](https://github.com/mrbig033/dotfiles/blob/master/emacs/emacs_default/packs.el)
- use-package: 20181119.2350
- pdf-tools: 20190129.1822

#### Issue ####

With the configuration,

```
(use-package pdf-tools
  :defer t
  :init
  (add-to-list 'auto-mode-alist '("\\.pdf\\'" . pdf-view-mode)))
```

I get the following error whenever I try to open a PDF file:

`File mode specification error: (void-function pdf-view-mode)`

If I remove the deferring it opens PDFs normally, but I get a huge loss in performance. Other modes work fine with deferring, what's going on here?

**Comment by conao3** [comment]
Please try `:mode` instead of `:init`.
```elisp
(use-package pdf-tools
  :mode ("\\.pdf\\'" . pdf-view-mode))
```

**Comment by skangas** [comment]
@conao3 answered this question, so I'm closing this issue now.
