### ISSUE TITLE
Transient integration

### ISSUE THREAD

**Issue by matthew-piziak** [jwiegley/use-package#762]
Today I can use `:bind`, or I can use `:hydra` through the use of [use-package-hydra](https://gitlab.com/to1ne/use-package-hydra), but I can't yet incorporate the excellent [transient](https://github.com/magit/transient/issues) package. @tarsius  Do you think this is an integration worth pursuing? If so, do you think the contribution would best be made to `use-package`, `transient`, or a third-party glue package like `use-package-hydra`?

**Comment by matthew-piziak** [comment]
Come to think of it this might be a silly question since I can use the `:bind` attribute to bind the top-level transient and then put the definition in the `:config`. Closing for now but feel free to reopen if you think it's worth it.

**Comment by tarsius** [comment]
I don't see a need for this either.

**Comment by matthew-piziak** [comment]
Great, thanks for the sanity check. :)

By the way, transient is finding its way into my configuration organically and neatly so far. Creating custom commands is easy and so is augmenting upstream ones. It's what I imagined that hydra would be but in my opinion transient is more powerful and user friendly. Thank you!
