### ISSUE TITLE
Invalid slot name

### ISSUE THREAD

**Issue by sjLambda** [jwiegley/use-package#763]
I started getting this error. How do I debug? Is this use-package or magit error? 
=============
Error (use-package): magit/:catch: Invalid slot name: "#<transient-prefix transient-prefix-1fe19c5ca1c0>", :incompatible
Error (use-package): magit/:catch: Invalid slot name: "#<transient-prefix transient-prefix-1fe19c1330bc>", :incompatible
=============

Magit line in my init is:
(use-package magit)

I deleted *.elc files and regenerated them, didn't fix.

I'm using, fyi:
magit              20190426.1457
GNU Emacs 27.0.50 (build 1, x86_64-apple-darwin15.6.0, NS appkit-1404.47 Version 10.11.6 (Build 15G22010))

**Comment by jwiegley** [comment]
Can I see the entire `use-package` declaration that you have for `magit`?

**Comment by sjLambda** [comment]
> Can I see the entire use-package declaration that you have for magit?

Sure: 
-----------------------------------
#+begin_src emacs-lisp
(use-package magit
  :ensure t
  :init 
  (setq magit-refresh-verbose nil)
  (setq magit-git-debug nil)
  :config
  (use-package magit-popup :ensure t)
  (use-package git-commit :ensure t)
  (use-package with-editor :ensure t))
#+end_src

Elsewhere in my init I also have these lines affecting magit:

#+begin_src emacs-lisp
;; for ido support
(setq magit-completing-read-function 'magit-ido-completing-read)
#+end_src

#+begin_src emacs-lisp
(use-package eshell
  :init
  ;;<snip>many lines unrelated to magit </snip>
  (add-hook 'eshell-mode-hook (lambda ()
    (eshell/alias "gd" "magit-diff-unstaged")
    (eshell/alias "gds" "magit-diff-staged"))))
#+end_src

-----------------------------------

END

**Comment by jwiegley** [comment]
I don't see anything wrong with these `use-package` declarations. The other thing you can try is to expand the macros, which will definitely take `use-package` out of the equation.

**Comment by sjLambda** [comment]
Okay, an update and a reason to cose this issue:

I recompiled emacs from the latest trunk cleanly and the problem disappeared. The only diffs I saw were a flurry of magit updates that may have fixed a small typo or something that may have fixed my issue. So I'm closing the issue. 

Thanks for looking into it.
