### ISSUE TITLE
Q: is there a way to know if a binding is valid other than trying it?

### ISSUE THREAD

**Issue by luckysori** [jwiegley/use-package#764]
Setting a binding to a non-existent function does not trigger an error when the code is executed:

``` elisp
(use-package real-package
  :bind (("C-x t" . 'non-existent-function)))
```

This means the only way to know if a binding is valid is to try it. Is there a way to know it beforehand?

May not be so problematic for bindings, but the same happens when customising variables or when configuring:

```elisp
(use-package real-package
  :custom (garbage t)
  :config (setq asdf nil))
```

**Comment by aiguofer** [comment]
Have you tried `M-x describe-personal-keybindings`?

**Comment by jwiegley** [comment]
There isn't really a way to know, since those bindings could be invalid until some later condition that you happen to know will happen by then.

That said, it shouldn't be terribly hard to write a linter for early discovery of issues like this.

**Comment by skangas** [comment]
> There isn't really a way to know, since those bindings could be invalid until some later condition that you happen to know will happen by then.
> 
> That said, it shouldn't be terribly hard to write a linter for early discovery of issues like this.

If someone wants to work on such a linter, please submit a PR. For now, I don't see that we will make any progress with this issue so I'm closing it.
