### ISSUE TITLE
:bind now doesn't work as before

### ISSUE THREAD

**Issue by 0xk175un3** [jwiegley/use-package#766]
```
(use-package expand-region
  :ensure t
  :commands er/expand-region
  :bind ("C-c i" . er/expand-region))
```

now this code doesn't work and cause error
```
Error (use-package): expand-region/:catch: Key sequence C-c i starts with non-prefix key C-c
```
And this issue is for all :bind in my config.
What happened? And how to fix it?

**Comment by kkhan01** [comment]
Copying that exactly, it seems to work fine for me. 

I doubt this is a use-package issue as no changes seem to be made recently (I would guess you've been using this for a while as you said *now*). So, this means there must be a difference in our configs...

I think something is already bound to `C-c` in your config. Try using `C-h k` `C-c` to see what if it is. This error usually means that the prefix is bound to something, so it'd be impossible to have a sequence after that (ie `C-c` will execute some command and the `i` is never reached in this case). You can read a little about it [here](http://emacslife.com/read-lisp-tweak-emacs/beginner-3-make-things-more-convenient.html).
