### ISSUE TITLE
Unable to recognize :ensure_system_package keyword

### ISSUE THREAD

**Issue by alecvn** [jwiegley/use-package#781]
I have the following in my config file:

    (use-package use-package-ensure-system-package :ensure t)
    (use-package blacken
        :ensure t
        :ensure_system_package (black . "pip3 install black"))

but it produces the following error:

`Error (use-package): Failed to parse package blacken: use-package: Unrecognized keyword: :ensure_system_package`

**Comment by waymondo** [comment]
The keyword is dasherized, not underscored: `:ensure-system-package`.
