### ISSUE TITLE
use-package-inject-hooks {pre,post}-config not run if :config block not present

### ISSUE THREAD

**Issue by jjlee** [jwiegley/use-package#785]
This is very similar to https://github.com/jwiegley/use-package/issues/250 -- but that was years ago, and this issue is specifically about config, not init.

The use-package docs for `use-package-inject-hooks` say:

    NOTE: These hooks are run even if the user does not specify an
    `:init' or `:config' block, and they will happen at the regular
    time when initialization and configuration would have been
    performed.

That seems to be untrue for `:config`.  use-package master has this code in `use-package-handler/:config` (https://github.com/jwiegley/use-package/blob/4fa73b1/use-package-core.el#L1471):

    (if (or (null arg) (equal arg '(t)))
        body
      (use-package-with-elapsed-timer
       (format "Configuring package %s" name-symbol)
       (funcall use-package--hush-function :config
                (use-package-concat
                 (use-package-hook-injector
                  (symbol-name name-symbol) :config arg)
                 body
                 (list t)))))

If there is no `:config`, it seems in my case anyway `arg` is indeed `(t)` and `use-package-hook-injector` never runs.  I'm not sure if this is a doc bug or a code bug -- I'm hoping the latter, because as a spacemacs user, that would stop me falling back to `with-eval-after-load` when `spacemacs|use-package-add-hook` "doesn't work" (this is the function spacemacs exposes for users to add these use-package inject hooks).  I'd try to make a PR, but I'm not sure what the intent of that if test above is?

I can reproduce the issue by adding a `:post-config` inject hook using recent spacemacs `develop` branch (https://github.com/syl20bnr/spacemacs/commits/3747afb), which is using `use-package` 20190529.2040.  Here's the use-package declaration:

https://github.com/syl20bnr/spacemacs/blob/3747afb/layers/+source-control/git/packages.el#L49

That gets called after my use of `spacemacs|use-package-add-hook` in my personal config, which successfully adds `use-package--evil-magit--post-config-hook`.  It looks like this:

    (defun jjl/pre-init-evil-magit ()
      (message "### jjl/pre-init-evil-magit")
      (spacemacs|use-package-add-hook evil-magit
        :post-config
        (message "### jjl/pre-init-evil-magit post-config")
        (spacemacs/set-leader-keys
          "gb" 'magit-blame)
        )

The spacemacs use-package declaration for that package has no :config property.  If I add a `:config` that just does `(progn nil)`, my post-config hook does get run (I see the second `message` output above).  That seems to be contrary to the docs.

I suspect this will be confusing a lot of "naive" spacemacs users who (like me until an hour ago) have not figured out what's going on here.

**Comment by jwiegley** [comment]
It would be a code bug if these hooks do not fire in the absence of a `:config` block.

**Comment by stianse** [comment]
Just wanted to share that I ran into the exact same issue and spent an hour trying to understand why it didn't work, in particular since issue #250 and the docs said that it should.

**Comment by jjlee** [comment]
Agh. Thanks for the encouragement, I said I would fix this and have not, sorry -- I do still intend to but can't promise when :-(  Of course if somebody else wants to do it, they shouldn't let that stop them :-)

**Comment by emacs18** [comment]
I too ran into this after learning that SPC l b  in spacemacs did not work which is supposed to allow me to select buffers within current layout, i.e., a persp-mode workspace.  For now I'm going to try the following patch (only for my own use) which seems to work after few minutes of testing.  Obviously I will revert this once proper fix is in place.

```diff
$ git diff
diff --git a/use-package-core.el b/use-package-core.el
index c18877d..0b45249 100644
--- a/use-package-core.el
+++ b/use-package-core.el
@@ -1468,7 +1468,7 @@ no keyword implies `:all'."
     (use-package-concat
      (when use-package-compute-statistics
        `((use-package-statistics-gather :config ',name nil)))
-     (if (or (null arg) (equal arg '(t)))
+     (if nil ;; (or (null arg) (equal arg '(t)))
          body
        (use-package-with-elapsed-timer
            (format "Configuring package %s" name-symbol)
$ ```

**Comment by emacs18** [comment]
On further testing, above hack does not seem to work. I\'m not sure what
happened. Perhaps I had other fixes as well when I tested this before.
So for now I just modified spacemacs to with `with-eval-after-load`
rather than tring to have some setup code be executed via use-package
\"hook injector\" feature.

**Comment by jjlee** [comment]
I guess @syl20bnr might want to be aware of this

**Comment by jwiegley** [comment]
Open to any patches from spacemacs users who can vouch for the fix.

**Comment by jjlee** [comment]
I am a spacemacs user and I have not run into any problems with the patch applied yet.  However, I've asked other spacemacs users on this issue if they can help test it: https://github.com/syl20bnr/spacemacs/issues/13545
So I'll keep my vouch in reserve for a bit :-)

**Comment by syl20bnr** [comment]
Thank you for fixing this, makes sense that the pre/post hooks are always executed in the context of Spacemacs and I don’t see any bad side effects from this change.

**Comment by jjlee** [comment]
Happy to vouch for my own patch now @jwiegley  :-)

To be super clear: I expect there are some spacemacs user configs which will break with this merged, but only because there will be hooks that people added in their personal config that were never called, and their untested code may break when use-package starts calling it.
