### ISSUE TITLE
Error (use-package): Cannot load package-is-not-really-a-package

### ISSUE THREAD

**Issue by ppareit** [jwiegley/use-package#786]
The following code is not working:

```elisp
(use-package prettify-symbols-mode
  :init
  (setq prettify-symbols-unprettify-at-point 'right-edge))
```
Yet, simply adding a hook makes it work:

```elisp
(use-package prettify-symbols-mode
  :init
  (setq prettify-symbols-unprettify-at-point 'right-edge)
 :hook
 emacs-lisp-mode)
```
I think that the problem is that prettify-symbols-mode is part of emacs but is defined in prog-mode. Most packages are started with :ensure to load them from a repo. Yet, I like to configure buildin 'packages' of emacs in the same way I configure other packages.
I realise that I can just do the setq outside of a use-package. But I wonder if it would not be nicer if the above use-package also worked, maybe with an option.

**Comment by thomasf** [comment]
why not `(use-package prog-mode ...)` ? It's very misleading to read the configuration if you specify the wrong feature in the use-package definition.
