### ISSUE TITLE
Can I use keywords to address Emacsclient frames?

### ISSUE THREAD

**Issue by alienbogart** [jwiegley/use-package#789]
I'd like to have some packages that are only available on graphical Emacs frames,
including Emacsclients but **not** the command line. `:when window-system` doesn't seem to do the job. Is there a way to achieve what I want?

Some packages should be only available on graphical Emacs frames, and this should include frames created by the daemon. `:if window-system` doesn't seem to do the job, as it creates all sorts of problems. Is there a syntax that achieves what I want?

**Comment by skangas** [comment]
Could you please show an example of an offending use-package declaration? AFAICT, :when window-system should do the job, but maybe I'm missing something.

**Comment by doolio** [comment]
I believe something like the following should achieve what OP wants:

```emacs-lisp
(use-package foo
  :when (or (memq window-system '(mac ns x))
            (unless (memq system-type '(ms-dos windows-nt))
              (daemonp)))
  :init (setq foo-variable t)
  :config (foo-mode 1))
```
