### ISSUE TITLE
:esnure nil shows Warning if package not present

### ISSUE THREAD

**Issue by samangh** [jwiegley/use-package#802]
I have:

```lisp
(use-package magit
  :ensure t
  :bind ("C-x g" . magit-status))

;; If forge is installed, load it
(use-package forge
  :ensure nil)
```

My assumption is that if package `forge` is not installed, then use-package should just skip that entry. However, instead use-package throws the following error:

```
Error (use-package): Cannot load forge
```

This is accompanied by the message `Loading package forge...done (0.143s)` in the `*Messages*` buffer.

If I completely remove the  `use-package forge` entry, all is good -- I get no errors and there is no message  in `*Messages*`.

**Comment by samangh** [comment]
This is true for any arbitary package. For example,

```lisp
(use-package ag
  :ensure nil)
```
Shows:
```
Error (use-package): Cannot load ag
```
If pacakge `ag` is not installed. 

Please ignore me if this is intented behaviour. Note tha I have the `use-package-verbose` variable set to true.

**Comment by thomasf** [comment]
That is the intended behavor.  
`:ensure nil` just tells use-package not to try to install the package which can be used with features that are provided within emacs itself or if you have the files in your `.emacs.d`

I think there might be a feature that does what you want but I don't use it and I don't remember if it's included in use package or an extension someone has written.

**Comment by conao3** [comment]
agree with @thomasf. It is intended behavior.
If you want to configure only package installed, you can write specific condition to do using `:if`.
```elisp
(ppp-macroexpand
 (use-package forge
   :ensure nil))
;;=> (progn
;;     (use-package-ensure-elpa 'forge '(nil) 'nil)
;;     (require 'forge nil nil))


(ppp-macroexpand
 (use-package forge
   :if (package-installed-p 'forge)
   :ensure nil))
;;=> (progn
;;     (use-package-ensure-elpa 'forge '(nil) 'nil)
;;     (when (package-installed-p 'forge)
;;       (require 'forge nil nil)))
```
The second one, `require` statement in `when` body, it is just ignored if not `forge` is not installed.
