### ISSUE TITLE
Add examples to use-package docstring

### ISSUE THREAD

**Issue by yantar92** [jwiegley/use-package#807]
The current docstring for `use-package` does not have information about keyword options format. It is especially important since keyword options do not have the same format for different keywords (i.e. `:bind` requires `(key . command)`, while `:custom` expect `(variable value)`). For now, I find myself looking into the github readme every time I need to add a keyword I do not use often.

**Comment by conao3** [comment]
use-package is a big DSL, insert examples into docstring is not a good idea, I think.
use-package has info, so you can read `M-x info` anytime you want.

(But I am not an avid Emacser, search GitHub I want to read some documentation. or use `macroexpand`)

**Comment by yantar92** [comment]
> you can read M-x info anytime you want.

I did not know about this. It is indeed a better way than polluting docstring. Thanks!
