### ISSUE TITLE
unbind-key from describe-personal-keybindings

### ISSUE THREAD

**Issue by aspiers** [jwiegley/use-package#81]
It would be great to be able to press `k` from a line in the `*Personal Keybindings*` buffer in order to `unbind-key` for the binding on that line.  (However #74 will need to be fixed before this is fully effective.)

**Comment by jwiegley** [comment]
Right now keybindings are described in a `*Help*` buffer, so adding this keystroke for convenient unbinding would be more than I think it's worth (creation of a mode, etc.), not to mention that the effect would not persist in any way.
