### ISSUE TITLE
bind-key: using a prefix that gets redefined by a package

### ISSUE THREAD

**Issue by novoid** [jwiegley/use-package#811]
Hi,
I'd like to know how to handle this situation properly:
[My emacs config](https://github.com/novoid/dot-emacs/blob/master/config.org) is structured like this:
```
[...]
<calling use-package>
[...]

(require 'bind-key)
(bind-keys
 :prefix-map my-map
 :prefix-docstring "My own keyboard map"
 :prefix "C-c C-,"
 ("-" . text-scale-decrease)
 ("+" . text-scale-increase)
 )

[...]
    (bind-key "y" 'my-yank-windows my-map)
    (bind-key "fm" 'flyspell-mode my-map)
[...]
<org mode>
[...]
         (bind-key "w" '(lambda () (interactive) (wttrin-query "graz")) my-map)
         (use-package bm
           :bind (:map my-map ("8" . bm-toggle))
           :bind (:map my-map ("9" . bm-previous))
           :bind (:map my-map ("0" . bm-next))
           )
[...]
```

Therefore: I'm using my own personal map for my personal keyboard bindings in order to avoid binding conflicts all over my config file. I use my-map all over my config: before and after the Org mode sections.

Everything was fine until with Org mode version 9.2, `C-c C-,` got mapped to `org-insert-structure-template`. Now, **Org "overwrites" the mapping**. I don't care about `org-insert-structure-template`, I just want to modify my config such that I may keep using my-map.

I know that `(org-defkey org-mode-map (kbd "C-c C-,") nil)` kills this binding. But I don't assume that there is a clean solution with keeping my method and trying to re-bind my binding after Org was loaded.

So: **is there a clean way of "reserving" a binding or re-binding it** after it has been modified by Org?

**Comment by a13** [comment]
does something like this help?

```
(use-package bind-key
  :ensure t
  :bind (:prefix-map my-map
         :prefix-docstring "My own keyboard map"
         :prefix "C-c C-,"
         ("-" . text-scale-decrease)
         ("+" . text-scale-increase))
  :after org)
```

**Comment by novoid** [comment]
Hi @a13, yes this helps a lot.
Thanks for pointing me to the `:after` keyword!
