### ISSUE TITLE
new release (e.g. 2.5)?

### ISSUE THREAD

**Issue by thkoch2001** [jwiegley/use-package#818]
Would you like to tag a new release for inclusion in distros, e.g. Debian?
Release 2.4 was on Nov 26, 2018 and a lot changed since than, e.g. the inclusion of use-package-ensure-system-package.el

Thank you!

**Comment by aadcg** [comment]
GNU Guix users would be happy to get a new release too.

**Comment by Gahamelas** [comment]
When about to install it on Emacs: "Status: Available Obsolete from melpa -- Install", even after updating the library. Any ideas? Is this package still active?

**Comment by thkoch2001** [comment]
ping?

**Comment by abcdw** [comment]
@jwiegley yep, it's true, people have to use untagged version in their distros to get updates. Can you create a 2.5 release please.

AFAIK people often use this https://github.com/jwiegley/use-package/tree/4fb1f9a68f1e7e7d614652afc017a6652fd029f1 commit. Maybe it's a good candidate for 2.5?

**Comment by jwiegley** [comment]
I have tagged `2.4.1` and updated all the relevant files. Distributions can use caa92f1d64fc25480551757d854b4b49981dfa6b as their newest release version.

**Comment by abcdw** [comment]
Super cool thank you!)
