### ISSUE TITLE
Trigger load based on function

### ISSUE THREAD

**Issue by seblemaguer** [jwiegley/use-package#823]
Hello,

as far as I understand using `:commands` load the package by adding an autoload. So, if I am correct, the functions listed in the field `:commands` should be from the package itself or a package depending on it. For example, let's consider the following listing:

```elisp
  (use-package erc
    :ensure t
    :commands (erc-start-or-switch)
    :bind ("<S-f2>" . erc-start-or-switch)
    ;; ....)

  (use-package erc-colorize
    :ensure t
    :after erc
    :commands (erc-start-or-switch)
    ;; ...)
```

and I assume that the function `erc-start-or-switch` calls the function `erc`.

Here is what I understand:
  - the first line `:commands (erc-start-or-switch)` is useless as the function `erc` is already declared as autoload by the package `erc`.
  - the second line `:commands (erc-start-or-switch)` is misleading as it will not load `erc-colorize` but `erc`.

If I am correct with the previous statements, I have one additional question: how can I condition the load of `erc-colorize` when the function `erc-start-or-switch` is called?

Thanks a lot

**Comment by conao3** [comment]
`:after erc` doesn't help you? I think `(erc-colorize)` -> (autoload) `(require 'erc) -> (eval-after-load) `(require 'erc-colorize)`.

**Comment by seblemaguer** [comment]
Hello,

thanks a lot for your answer. I completely forgot about this issue. I forgot how I solved it but I don't have this problem anymore. Maybe `:after erc` was already helping me :D
