### ISSUE TITLE
Migrate to GitHub Actions

### ISSUE THREAD

**Issue by sergeyklay** [jwiegley/use-package#826]
Hello,

I propose migrate CI process to GitHub Actions. This seems more reasonable when the project code, as well as continuous integration depend only on GitHub.

I have an example for you to show how simple it is: https://github.com/sergeyklay/bnf-mode/blob/master/.github/workflows/build.yml

Let me know if it is acceptable and I'll send a PR.

**Comment by skangas** [comment]
Please send a PR, thanks in advance.

**Comment by skangas** [comment]
We are now using GitHub actions, so I'm closing this. Thanks.
