### ISSUE TITLE
Can use package achieve such a function?

### ISSUE THREAD

**Issue by EvanMeek** [jwiegley/use-package#832]
I use 'use package' to define a key for a plug-in, and I want to provide a "descirbe" for it. How can I do this?

This is my configuration case:
![definekey](https://user-images.githubusercontent.com/27056033/79693184-c97a5200-829b-11ea-9011-9be9733340f7.png)

I want to change "global flycheck mode" to other information

**Comment by a13** [comment]
If you use `which-key` it's possible to name a prefix-map for that

```el
(use-package link-hint
  :ensure t
  :bind
  (("<XF86Search>" . link-hint-open-link)
   ("S-<XF86Search>" . link-hint-copy-link)
   :map mode-specific-map
   :prefix-map link-hint-keymap
   :prefix "l"
   ("o" . link-hint-open-link)
   ("c" . link-hint-copy-link)))
```
