### ISSUE TITLE
how make "whick-key" lazy loading ?

### ISSUE THREAD

**Issue by zhangjie2012** [jwiegley/use-package#833]
My config :

``` emacs-lisp
(use-package which-key
  :pin melpa
  :ensure t
  :hook (prog-mode . which-key-mode)
  :config
  (which-key-setup-minibuffer)
  )
```

why I open emacs, will load which key ?  `:hook` not  loading util  one `prog-mode` ?

**Comment by obar** [comment]
If you have any defaults around, your scratch buffer is in `emacs-lisp-mode`, which derives from `prog-mode`. Your hook would get called. Is that why which-key loads immediately for you?

**Comment by mplscorwin** [comment]
Potentially relivant: We can change the mode used for *scratch* by customizing/setting  
  `lisp-interaction-mode`

**Comment by obar** [comment]
@mplscorwin I think you mean setting `initial-major-mode`, which has the initial value of `lisp-interaction-mode`.

**Comment by mplscorwin** [comment]
You are absolutely right!
