### ISSUE TITLE
Example in README showing delight and projectile has performance issue

### ISSUE THREAD

**Issue by honnix** [jwiegley/use-package#835]
I could not think of a good way to work on a PR, so creating an issue instead.

This is what REAME says regarding `delight` and `projectile`:
```emacs
;; Remove the mode name for projectile-mode, but show the project name.
(use-package projectile
  :delight '(:eval (concat " " (projectile-project-name))))
```
However this under certain circumstances would have serious performance issue, and in my case for a file under go module `<some/path>/go/pkg/mod/`. The cursor becomes super laggy while CPU is busy computing `projectile-project-name` (according to profiler), because I guess mode-line is refreshed/reevaluated for each cursor move?

A better way to do this kind of customisation I believe is ~https://docs.projectile.mx/en/latest/configuration/#mode-line-indicator~ https://docs.projectile.mx/projectile/configuration.html#mode-line-indicator

**Comment by honnix** [comment]
@jwiegley Have you got time to take a look at this? Thanks.

**Comment by jwiegley** [comment]
It should be easy to do a per-buffer caching of the projectile name:

```lisp
(defvar buffer-project-project-name nil)

;; Remove the mode name for projectile-mode, but show the project name.
(use-package projectile
  :delight '(:eval (concat " " (or buffer-project-project-name
                                   (setq buffer-project-project-name
                                         (projectile-project-name))))))
```

**Comment by jwiegley** [comment]
However, I don't use `delight`, so I'm not sure how well this interacts with it.

**Comment by honnix** [comment]
I can already get decent performance with the following config. I guess per-buffer caching is not required.

```emacs
(use-package projectile
  :ensure t
  :bind-keymap ("s-p" . projectile-command-map)
  :init
  (setq projectile-completion-system 'ivy
        projectile-mode-line-function '(lambda () (format " [%s]" (projectile-project-name))))
  :config
  (projectile-mode +1))
```
This is also what projectile suggests. However as you see this does not use `delight` and that was why I wasn't sure how to work on a PR.

**Comment by chee** [comment]
@honnix i think that example is mean more as an example of how to use delight, than how to use projectile :)

**Comment by honnix** [comment]
@chee Yeah that is true. I was just trying to find a way out so folks will not get hit by the performance issue as I did.

**Comment by chee** [comment]
maybe there should be a repo of use-package snippets for people to share good base use-package config for various packages. it took a while for me to get projectile and eaf right, for instance. late night `benchmark-init` vibes

**Comment by honnix** [comment]
> a repo of use-package snippets for people to share good base use-package config

That sounds great. @jwiegley What do you think?

**Comment by jwiegley** [comment]
I think that's a fantastic idea, @honnix! The only issue is making sure that they're all up to date and actually work. :)

**Comment by honnix** [comment]
That almost sounds like a luxury problem to have, so not a bad thing. :) I think if it gets bootstrapped, people will start contributing and sending PRs to make things more or less up to date. Depending on how this is done, adding CI is also possible.

**Comment by jwiegley** [comment]
Good point. I'm all for it! Want to start us off?

**Comment by honnix** [comment]
@jwiegley Yes! I will think about possible ways going forward and propose them here first. @chee If you have already got thoughts around this, please leave them here. :)

**Comment by honnix** [comment]
@jwiegley Would you like to create a repo under your account? Something like `use-package-examples` might work. I can fork, add things and start a PR.

**Comment by jwiegley** [comment]
@honnix Done!

**Comment by skangas** [comment]
I have now fixed this example in the use-package manual that will be released as part of Emacs 29: https://git.savannah.gnu.org/cgit/emacs.git/commit/?h=emacs-29&id=5b640f0abd3f83449e8780ce8060eb723574986b

I'm therefore closing this issue.
