### ISSUE TITLE
use-package-ensure-system-package.el is not download from melpa

### ISSUE THREAD

**Issue by jeafleohj** [jwiegley/use-package#837]
I installed "use-package" with melpa and the file "use-package-ensure-system-package.el" is not found in the installation folder. And when I put the following command:
```elisp
(use-package use-package-ensure-system-package)
```
The version that is downloaded is the old one that is in the author's original repository when in fact it should be use the file that is in this repository.

**Comment by waymondo** [comment]
The version on MELPA is 0.2, which is the version that is contained in this repository:
http://melpa.org/packages/use-package-ensure-system-package-20180913.1501.el
https://github.com/jwiegley/use-package/blob/master/use-package-ensure-system-package.el

The version [here](https://github.com/waymondo/use-package-ensure-system-package/blob/master/use-package-ensure-system-package.el) is 0.1. 

Perhaps you are confused by the URL in the package header pointing to the old repository?

**Comment by jeafleohj** [comment]
Yes, that was what confused me and I thought the links are wrong. Thanks for clarifying my doubts
