### ISSUE TITLE
Function might not be defined at runtime - transitive require

### ISSUE THREAD

**Issue by chasecaleb** [jwiegley/use-package#838]
I'm really confused about what is going on with the byte compiler in this situation:

```emacs-lisp
(eval-and-compile
  (add-to-list 'load-path (expand-file-name "lib/borg" user-emacs-directory))
  (require 'borg)
  (if (file-exists-p borg-gitmodules-file)
      (borg-initialize)
    (dolist (drone (borg-clones))
      (borg-activate drone))))

(eval-when-compile
  (require 'use-package)
  (setq use-package-expand-minimally byte-compile-current-file))
;; For testing macro expansion
(setq byte-compile-current-file t)

(use-package spaceline-segments
  :config
  (spaceline-compile '(()) '(())))
```
The above gives a flycheck warning: `the function ‘spaceline-compile’ might not be defined at runtime. (emacs-lisp)`.

Whereas if I replace the `use-package` form with the expansion of it (from `macroexpand-all`) I don't get a warning:
```emacs-lisp
(progn
  (quote nil)
  (require (quote spaceline-segments) nil nil)
  (spaceline-compile (quote (nil)) (quote (nil)))
  t)
```
Do you have any idea what is going on here? I've spend a decent amount of time reading through the Elisp info manual regarding functions, loading, and byte-compiling and I still can't figure out why this behaves the way it does. I'm on the current master HEAD for `use-package`, `spaceline`, and `borg`.

**Comment by belak** [comment]
Yeah, I've been getting this too! I was really wondering what was going on.

**Comment by jwiegley** [comment]
Try adding `:functions spaceline-compile` to the use-package declaration.

**Comment by jwiegley** [comment]
Also, what the macro expands to at compile-team is not necessarily the same as what you'll get from `macroexpand-all`, as described by this comment in `use-package-core.el`:

```
    ;; If byte-compiling, pre-load the package so all its symbols are in
    ;; scope. This is done by prepending statements to the :preface.
```

**Comment by chasecaleb** [comment]
I'm sorry, I got distracted by life and forgot about this. Thank you @jwiegley. I didn't know that about `macroexpand-all`, I think that explains my confusion.
