### ISSUE TITLE
:custom-face cannot :inherit?

### ISSUE THREAD

**Issue by ianpan870102** [jwiegley/use-package#841]
This seems to be a long standing problem, that is, not being able to use the inherit attribute in the custom-face macro.

One example would be, instead of **this**:

```emacs-lisp
(use-package doom-themes
  :custom-face
  (default                      ((t (:foreground "#aabbbb")))) ; brighter default
  (font-lock-variable-name-face ((t (:foreground "#aabbbb")))) ; brighter default
  :config
  (load-theme 'doom-solarized-dark t))
```

I'd like to write **this**:

```emacs-lisp
(use-package doom-themes
  :custom-face
  (default                      ((t (:foreground "#aabbbb")))) ; brighter default
  (font-lock-variable-name-face ((t (:inherit default))))      ; brighter default
  :config
  (load-theme 'doom-solarized-dark t))
```

Is this possible?

**Comment by a13** [comment]
inherits work for me
```el
:custom-face
(ivy-current-match ((t (:inherit 'hl-line))))
```

It's even possible to inherit from itself

**Comment by ianpan870102** [comment]
@a13  Very weird.. I did it your way and when I inspect the face of `ivy-current-match` with `counsel-face`, I get `'hl-line` under the `Inherit` property. So far so good, but when I click on the `'hl-line` value of the property it brings me to a help buffer of an undefined face. Removing the quote in front of `'hl-line` makes little difference. It still gives me an undefined face.

### Counsel-face

<img width="634" alt="Screenshot 2020-08-25 at 00 13 14" src="https://user-images.githubusercontent.com/36686900/91069353-e10d8100-e667-11ea-8462-ce1719b23c2f.png">


### After clicking on `'hl-line`

<img width="633" alt="Screenshot 2020-08-25 at 00 13 28" src="https://user-images.githubusercontent.com/36686900/91069380-e8cd2580-e667-11ea-8064-604d07e301ea.png">

**Comment by ianpan870102** [comment]
Issue solved, probably due to an early bug that is now fixed.
