### ISSUE TITLE
loading fails for latest version of emacs-git

### ISSUE THREAD

**Issue by kpbochenek** [jwiegley/use-package#842]
Error code is:
```
(setq tabulated-list-format
        ;; The sum of column width is 80 characters:
        #[("Package" 25 t)
          ("Status" 13 t)
          ("Last Event" 23 t)
          ("Time" 10 t)])
  (tabulated-list-init-header))
```
Error:
```
Debugger entered--Lisp error: (invalid-read-syntax "Invalid byte-code object")
  read(#<buffer  *load*-898483>)
```

(you can paste mentioned code to fresh latest emacs and eval it)

**Comment by conao3** [comment]
This error unrelated to `use-package`, I think.

**Comment by kpbochenek** [comment]
I haven't noticed this syntax so far, what does `#[..]` means?

**Comment by kpbochenek** [comment]
Also for others hitting this problem, one workaround to move forward is to comment:
`(define-derived-mode use-package-statistics-mode tabulated-list-mode ...)`
in `use-package-core.el`

**Comment by nahuel** [comment]
> I haven't noticed this syntax so far, what does `#[..]` means?

Is a way to enter a byte-code objects: https://www.gnu.org/software/emacs/manual/html_node/elisp/Byte_002dCode-Objects.html

**Comment by yanite** [comment]
thank you @kpbochenek  your are right

**Comment by conao3** [comment]
Yes, the patch is good. Sorry @arichiardi, my comment was actually unrelated.

**Comment by Silex** [comment]
What I don't understand is that this line is two (!) years old https://github.com/jwiegley/use-package/blame/0ba3071cda77957822bfe3e58009375f395777f4/use-package-core.el

This means it was broken for two years?

**Comment by kpbochenek** [comment]
Yes

Fixed by https://github.com/jwiegley/use-package/pull/843
