### ISSUE TITLE
FR: way to autoload non-interactive functions/macros

### ISSUE THREAD

**Issue by aspiers** [jwiegley/use-package#851]
I looked for a convenient equivalent to `:commands` which creates the autoloaded function(s) as non-interactive (so that they don't pollute `M-x` completion from `counsel-M-x`, `amx`, etc.) but couldn't find one.  I know I can achieve this manually, e.g.

```
(use-package org-crypt
  :requires org
  :ensure nil
  :defer t
  :init
  (autoload 'org-crypt-use-before-save-magic "org-crypt"))
```

but it would be much nicer if I could write:

```
(use-package org-crypt
  :requires org
  :ensure nil
  :functions org-crypt-use-before-save-magic)
```

**Comment by aspiers** [comment]
Just realised this applies to macros too.

**Comment by aspiers** [comment]
... so maybe the keyword should be `:autoloads` rather than `:functions`.

**Comment by conao3** [comment]
How about?
```elisp
(use-package org-crypt
  :commands org-crypt-use-before-save-magic)
```

It should generate autoload statement that you want

```elisp
(setq use-package-expand-minimally t)
;;=> t

(macroexpand-1
 '(use-package org-crypt
    :commands org-crypt-use-before-save-magic))
;;=> (unless (fboundp 'org-crypt-use-before-save-magic)
;;     (autoload #'org-crypt-use-before-save-magic "org-crypt" nil t))
;;   nil
```

**Comment by aspiers** [comment]
That's what I already tried, and as described above it created an interactive autoload.  The whole point of this issue was to find an alternative which doesn't pollute the list of interactive commands which can be completed after `M-x`.  Having said that, it seems from your macroexpand and from checking my running emacs that maybe this problem was already fixed, because I don't see the issue any more.  Very odd.

**Comment by conao3** [comment]
Oh, sorry I misunderstood your issue. I showed `use-pacakge` generates *interactive* autoload so you do `M-x`, you should see the command (but the function is not interactive)

I think, there is no keyword that you want.
Maybe PR to org-crypt to add `;;;###autoload` comment if you want to autoload...?

**Comment by aspiers** [comment]
[**@conao3**](https://github.com/conao3) commented on [February 22, 2021 4:04 PM](https://github.com/jwiegley/use-package/issues/851#issuecomment-783481749 "2021-02-22T16:04:43Z - Replied by Github Reply Comments"):
> Oh, sorry I misunderstood your issue. I showed `use-pacakge` generates *interactive* autoload so you do `M-x`, you should see the command (but the function is not interactive)

Right, that is exactly the issue.

> I think, there is no keyword that you want.

I'm not sure - look at the expansion you shared:

> ;;     (autoload #'org-crypt-use-before-save-magic "org-crypt" nil t))

The arguments for `autoload` are:

> (autoload FUNCTION FILE &optional DOCSTRING INTERACTIVE TYPE)

so apparently it is creating a non-interactive autoload here?

> Maybe PR to org-crypt to add `;;;###autoload` comment if you want to autoload...?

Oh yeah good point, I suppose individual packages should be responsible for creating correct autoloads.

**Comment by conao3** [comment]
No, we define org-crypt-use-before-save-magic as a interctive one.
```
(autoload #'org-crypt-use-before-save-magic "org-crypt"    nil       t)
(autoload FUNCTION                          FILE &optional DOCSTRING INTERACTIVE TYPE)
```
Here is a good news, `org-crypt-use-before-save-magic` is autoloaded in org HEAD.
please install ratest org, this issue should be resolved.

https://code.orgmode.org/bzg/org-mode/src/master/lisp/org-crypt.el#L307-L312
```elisp
;;;###autoload
(defun org-crypt-use-before-save-magic ()
  "Add a hook to automatically encrypt entries before a file is saved to disk."
  (add-hook
   'org-mode-hook
   (lambda () (add-hook 'before-save-hook 'org-encrypt-entries nil t))))
```

**Comment by aspiers** [comment]
[**@conao3**](https://github.com/conao3) commented on [February 22, 2021 4:38 PM](https://github.com/jwiegley/use-package/issues/851#issuecomment-783505204 "2021-02-22T16:38:06Z - Replied by Github Reply Comments"):
> No, we define org-crypt-use-before-save-magic as a interctive one.
> ```
> (autoload #'org-crypt-use-before-save-magic "org-crypt"    nil       t)
> (autoload FUNCTION                          FILE &optional DOCSTRING INTERACTIVE TYPE)
> ```

Whoops, I can't count :laughing:  No wonder I was getting confused.

> Here is a good news, `org-crypt-use-before-save-magic` is autoloaded in org HEAD.
> please install ratest org, this issue should be resolved.
> 
> https://code.orgmode.org/bzg/org-mode/src/master/lisp/org-crypt.el#L307-L312
> ```elisp
> ;;;###autoload
> (defun org-crypt-use-before-save-magic ()
>   "Add a hook to automatically encrypt entries before a file is saved to disk."
>   (add-hook
>    'org-mode-hook
>    (lambda () (add-hook 'before-save-hook 'org-encrypt-entries nil t))))
> ```

Great, thanks!

Do you think this is a valid feature request for other cases, or should packages always define the autoloads themselves?

**Comment by conao3** [comment]
> Do you think this is a valid feature request for other cases, or should packages always define the autoloads themselves?

This is a valid feature request for other cases, but *I think*, PR `;;;###autoload` comment should help other users too, I recommend this way.
or, we should define `:commands*` to generate no-interactive one.

**Comment by conao3** [comment]
With this patch, you can use `commands*` keyword.
```diff
add-commands-keyword 3499c1e897f70c584a02ef63af75fdc82668bd0e
Author:     Naoya Yamashita <conao3@gmail.com>
AuthorDate: Tue Feb 23 02:49:18 2021 +0900
Commit:     Naoya Yamashita <conao3@gmail.com>
CommitDate: Tue Feb 23 02:49:18 2021 +0900

Parent:     a7422fb Merge pull request #910 from minad/improved-unbind
Merged:     add-commands-keyword master
Contained:  add-commands-keyword
Follows:    2.4 (65)

add commands* keyword

commands* is similar to :command but this generate autoload
statement as *no-interactive* function.

1 file changed, 23 insertions(+)
use-package-core.el | 23 +++++++++++++++++++++++

modified   use-package-core.el
@@ -94,6 +94,7 @@
     ;; Any other keyword that also declares commands to be autoloaded (such as
     ;; :bind) must appear before this keyword.
     :commands
+    :commands*
     :init
     :defer
     :demand
@@ -1309,6 +1310,28 @@ meaning:
       (delete-dups arg)))
    (use-package-process-keywords name rest state)))
 
+;;;; :comands
+
+(defalias 'use-package-normalize/:commands* 'use-package-normalize/:commands)
+
+(defun use-package-handler/:commands* (name _keyword arg rest state)
+  (use-package-concat
+   ;; Since we deferring load, establish any necessary autoloads, and also
+   ;; keep the byte-compiler happy.
+   (let ((name-string (use-package-as-string name)))
+     (cl-mapcan
+      #'(lambda (command)
+          (when (symbolp command)
+            (append
+             (unless (plist-get state :demand)
+               `((unless (fboundp ',command)
+                   (autoload #',command ,name-string))))
+             (when (bound-and-true-p byte-compile-current-file)
+               `((eval-when-compile
+                   (declare-function ,command ,name-string)))))))
+      (delete-dups arg)))
+   (use-package-process-keywords name rest state)))
+
 ;;;; :defer
 
 (defalias 'use-package-normalize/:defer 'use-package-normalize-predicate)
```
```elisp
(macroexpand-1
 '(use-package org-crypt
    :commands* org-crypt-use-before-save-magic))
;;=> (progn
;;     (unless (fboundp 'org-crypt-use-before-save-magic)
;;       (autoload #'org-crypt-use-before-save-magic "org-crypt"))
;;     (require 'org-crypt nil nil))
```

**Comment by aspiers** [comment]
Nice!  Thanks a lot!

**Comment by aspiers** [comment]
#917 was merged, so this is now resolved. Thanks a lot @conao3 and @jwiegley!
