### ISSUE TITLE
:after declarations aren't working when given a list

### ISSUE THREAD

**Issue by dadinn** [jwiegley/use-package#852]
I have the following declaration:

```
(use-package geiser
  :after (paredit company)
  :bind
  (("C-c g r" . run-geiser)
   ("C-c g c" . geiser-connect))
  :hook
  (geiser-mode . company-mode)
  (geiser-repl-mode . paredit-mode))
```

Also the referenced paredit and company declarations are here for completeness:

```
(use-package paredit
  :hook
  (lisp-mode . paredit-mode)
  (scheme-mode . paredit-mode)
  (emacs-lisp-mode . paredit-mode)
  :init (show-paren-mode))

(use-package company
  :bind
  (("TAB" . company-indent-or-complete-common))
  :custom
  (company-idle-delay 0)
  (company-minimum-prefix-length 1)
  (company-selection-wrap-around t)
  :config
  (company-tng-configure-default))
```

The issue is that `:after` clause does not work correctly, it blocks the loading of the `geiser` declaration, specifically the bindings.

**Comment by dadinn** [comment]
Oh, I also have these declarations in my `init.el`, not sure if they are relevant:
```
(custom-set-variables
 '(use-package-always-ensure t)
 '(use-package-always-pin "melpa-stable"))
```

**Comment by a13** [comment]
:bind and :hook imply :defer, so you should :demand the packages

**Comment by dadinn** [comment]
Can you please clarify on which package the :bind, :hook, or :defer, causes this, and which package declaration I should be placing the `:demand t` declaration on? 

Is it the `geiser`, the `paredit`, or the `company` package declaration?

**Comment by dadinn** [comment]
The issue I have is that "C-c g r" binding is not set, and it fails to execute the `run-geiser` command, as I would expect.

**Comment by dadinn** [comment]
Ok, got it working! I had to add `:demand t` to the for the `company` package declaration. This solved the problem with the bindings for `geiser`

**Comment by skangas** [comment]
This was resolved, so I'm closing this issue.
