### ISSUE TITLE
:hook not equivalent to :init (add-hook ...

### ISSUE THREAD

**Issue by jstaursky** [jwiegley/use-package#853]
So this works often but I noticed for certain packages I need to use 
```elisp
  (use-package rtags
    :init (add-hook 'c++-mode-hook #'rtags-start-process-unless-running)
    )
```

instead of

```elisp
  (use-package rtags
    :hook (c-mode c++-mode)
    :config #'(rtags-start-process-unless-running)
    )
```
otherwise I end up with `File mode specification error: (error Autoloading file .../rtags.elc failed to define function rtags)`

**Comment by mkleehammer** [comment]
I'm seeing this with org.

**Comment by MorganJamesSmith** [comment]
I'm not sure how rtags works, but 
```
  (use-package rtags
    :hook (c-mode))
```
is equivalent to
```
  (use-package rtags
    :init (add-hook 'c-mode-hook #'rtags-mode))
```

If you'd like your hook to be like this
```
(add-hook 'c++-mode-hook #'rtags-start-process-unless-running)
(add-hook 'c-mode-hook #'rtags-start-process-unless-running)
```
then you should use 
```
  (use-package rtags
    :hook ((c-mode c++-mode) . #'rtags-start-process-unless-running)))
```

**Comment by jstaursky** [comment]
Right so in the link you attached, I'm not sure if your realizing this but it says exactly what this issue is reporting. Your suggested solution does work but what I am saying is that the link you attached says that they should be equivalent but they are not (one works, the other doesn't)

**Comment by jstaursky** [comment]
Okay so looking back at my original issue (it was a while ago) I guess what I am really trying to say is that I do not understand why
```elisp
  (use-package rtags
    :hook (c-mode c++-mode)
    :config #'(rtags-start-process-unless-running)
    )
```
is not equivalent to 
```elisp
  (use-package rtags
    :hook ((c-mode c++-mode) . rtags-start-process-unless-running)))
```

Since the `:config` is supposed to be run after package becomes initialized.
I guess there is no promise anywhere for it to work like that but I still find that to be a bit confusing.

**Comment by MorganJamesSmith** [comment]
I think I see your confusion. You belive the hook will load the package and then run the config section. This is not the case. The hook is simply some semantic sugar that wraps up the add-hook function. The add-hook function takes two arguments: the hook, and the function to add to the hook. If you don't provide a function to add to the hook, use-package assumes that you mean a function which is the same as the package name (as this is common). The error message you received initally is letting you know that there is no function "rtags".

**Comment by jstaursky** [comment]
Okay thank you for clearing that up! I'll go ahead and close the issue.
