### ISSUE TITLE
c-mode: Wrong type argument: stringp, (require . info)

### ISSUE THREAD

**Issue by jimpo** [jwiegley/use-package#860]
I am on OSX 10.14.6 using Emacs for OSX 27.1.

When I run `c-mode`, I get the error "Wrong type argument: stringp, (require . info)`

## Steps to reproduce

I have cleared my whole `.emacs.d` and except for a new `init.el` which looks like:

```lisp
;; https://melpa.org/#/getting-started
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

;; https://github.com/jwiegley/use-package#getting-started
(eval-when-compile (require 'use-package))
```

- Open Emacs
- Emacs installs use-package
- Close Emacs
- Reopen Emacs
- `M-x c-mode` (or open a ".c" file)
- See error: `Wrong type argument: stringp, (require . info)`

**Comment by songsanli** [comment]
It seems that Emacs 27.1-1 has fixed this bug.

https://emacsformacosx.com/download/emacs-builds/Emacs-27.1-1.changes

**Comment by jimpo** [comment]
Thanks @songsanli!

I have confirmed that the new release fixes the issue.
