### ISSUE TITLE
Remove custom-set-variable 3rd argument?

### ISSUE THREAD

**Issue by conao3** [jwiegley/use-package#861]
Recently, `use-package` doesn't expand `custom-set-variable` 3rd argument for specified `:custom` keyword.
```emacs-lisp
(pp
 (macroexpand-1
  '(use-package comint
     :custom
     (comint-prompt-regexp "^")
     (comint-buffer-maximum-size 20000 "Increase comint buffer size.")
     (comint-prompt-read-only t "Make the prompt read only."))))
;;=> (progn
;;     (funcall
;;      (or
;;       (get 'comint-prompt-regexp 'custom-set)
;;       #'set-default)
;;      'comint-prompt-regexp "^")
;;     (funcall
;;      (or
;;       (get 'comint-buffer-maximum-size 'custom-set)
;;       #'set-default)
;;      'comint-buffer-maximum-size 20000)
;;     (funcall
;;      (or
;;       (get 'comint-prompt-read-only 'custom-set)
;;       #'set-default)
;;      'comint-prompt-read-only t)
;;     (require 'comint nil nil))
```
I can't find `"Increase comint buffer size."` and `"Make the prompt read only."` in expanded form.
It used to be output as `custom-set-variable` argument and could be seen in `M-x customize`.
It also seems that the default comment of `customized with use-package` is no longer printed.
This was useful for not changing variables managed by use-package in `M-x customize`.

**Comment by jwiegley** [comment]
I won't have time to look this week, if anyone can chime in with some knowledge that would be great!

**Comment by tzz** [comment]
@conao3 I think #881 will preserve the comment by reverting to the old function call. Could you try it?
