### ISSUE TITLE
Byte-compilation doesn't work ("malformed function" and "wrong type argument" for :bind)

### ISSUE THREAD

**Issue by dmalyuta** [jwiegley/use-package#864]
The beginning of my `~/.emacs.d/init.el` file looks like this:

```
;; MELPA
(require 'package)
(setq package-enable-at-startup nil)
(setq package-check-signature nil)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(add-to-list 'package-archives '("elpy" . "https://jorgenschaefer.github.io/packages/"))

;; boostrap 'use-package'
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(use-package windmove
  ;; move cursor between windows
  :demand
  :bind
  (("C-<left>" . windmove-left)
   ("C-<right>" . windmove-right)
   ("C-<up>" . windmove-up)
   ("C-<down>" . windmove-down)))

... more stuff ...
```

I am trying to byte compile my `init.el` file. I execute the following in the terminal, sinde the `~/.emacs.d/` directory:

```
$ emacs --batch --eval '(byte-compile-file "init.el")'
```

The output is:

```
In toplevel form:
init.el:59:1:Warning: ‘("C-<left>" . windmove-left)’ is a malformed function
init.el:59:14:Warning: reference to free variable ‘windmove’
init.el:62:3:Error: Wrong type argument: sequencep, windmove-right
```

Basically, the very first key binding definition fails... and there is also some sort of warning about a free variable. How do I properly byte-compile the `init.el` file - even for the above very simple example (imagine there's nothing else to the `init.el` file)?

**Comment by a13** [comment]
Why do you guys compile init.el while using use-package?

**Comment by dmalyuta** [comment]
Is one not supposed to compile `init.el` when using `use-package`? Is that functionality not possible?

**Comment by a13** [comment]
of course you it's possible, I'm asking of curiosity, since to my experience it doesn't speed up loading at all

**Comment by dmalyuta** [comment]
I guess my question is more out of curiosity for why this error comes up, and whether it is a symptom of me doing something wrong in my `init.el`

**Comment by a13** [comment]
Does

```
(eval-when-compile
  (require 'use-package))
```
help?

**Comment by a13** [comment]
Works for me, at least from dired

**Comment by dmalyuta** [comment]
If I use the following `init.el`:

```
;; MELPA
(require 'package)
(setq package-enable-at-startup nil)
(setq package-check-signature nil)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(add-to-list 'package-archives '("elpy" . "https://jorgenschaefer.github.io/packages/"))

;; boostrap 'use-package'
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(eval-when-compile
  (require 'use-package))

(use-package windmove
  ;; move cursor between windows
  :demand
  :bind
  (("C-<left>" . windmove-left)
   ("C-<right>" . windmove-right)
   ("C-<up>" . windmove-up)
   ("C-<down>" . windmove-down)))
```

Then I get the following byte compilation error:
```
$ emacs --batch --eval '(byte-compile-file "init.el")'

In toplevel form:
init.el:13:13:Error: Cannot open load file: No such file or directory, use-package
```

**Comment by conao3** [comment]
Please see @a13 [comment](https://github.com/jwiegley/use-package/issues/864#issuecomment-682109129).

> Does
> 
> ```
> (eval-when-compile
>   (require 'use-package))
> ```
> 
> help?

**Comment by dmalyuta** [comment]
I did add the suggested statement in my last reply... There is an error `Cannot open load file`, like I posted.

**Comment by a13** [comment]
Looks like a `load-path` issue

**Comment by dmalyuta** [comment]
It seems the issue goes away if I compile from inside Emacs using `M-x byte-compile-init-dir`. How come the terminal version then isn't working?

**Comment by rprimus** [comment]
Fri Aug 28 11:13:11 BST 2020

> init.el:13:13:Error: Cannot open load file: No such file or directory, use-package

As @a13 mentioned, `use-package` is not found in your `load-path`.
To show this, add the following before the `eval-when-compile` expression:

```elisp
(message "current load-path: %s" load-path)
```
and run `emacs --batch -l init.el`

You'll see that `use-package` is not in the `load-path`.
To include it, `(package-initialize)` needs to be run.
Include this in the `eval-when` expression:
```elisp
(eval-when-compile
  (package-initialize)
  (require 'use-package))
```

There should be no problems now when running the batch command.

**Comment by skangas** [comment]
As others have explained, this is a `load-path` issue. If use-package was installed with `package-install`, things should work automatically. If using an older version, try adding `(package-initialize)` to your init file.
