### ISSUE TITLE
Flymake reports an error on require.

### ISSUE THREAD

**Issue by grolongo** [jwiegley/use-package#865]
Hello, despite having a functional use-package, Flymake reports an error on the line:

`(eval-when-compile (require 'use-package))`

Error message mentions: `"Cannot open load file: No such file or directory, use-package"`

Is this normal? I'm using the official GNU Emacs 27.1 build on Windows 10.

**Comment by conao3** [comment]
I don't see it, but please check some flycheck variables to find use-package. https://www.flycheck.org/en/latest/languages.html#emacs-lisp
one point, you use `eval-when-compile` to `require`, so Emacs should find `use-package` in compiler time.

**Comment by skangas** [comment]
It seems like this is an issue with `flymake`, so I'm closing this.
