### ISSUE TITLE
More flexible override of package search path

### ISSUE THREAD

**Issue by nordlow** [jwiegley/use-package#867]
I would like the `:load-path` option to either 

- change so that it prepends to the `load-path`
- or a new variant of the key named, say, `:load-path-prepended`
- or a new key, say `:load-dir` or `:load-file` that controls where the package to load is located.

I need this in order to override potentially other installed (ELPA) packages with the same name.

**Comment by skangas** [comment]
> I would like the `:load-path` option to either
> 
>     * change so that it prepends to the `load-path`
> 
>     * or a new variant of the key named, say, `:load-path-prepended`
> 
>     * or a new key, say `:load-dir` or `:load-file` that controls where the package to load is located.
> 
> 
> I need this in order to override potentially other installed (ELPA) packages with the same name.

I'm not sure, I understand this request, as `:load-path` just calls `add-to-list`, which is already documented to add it to the beginning of the list:

```
If ELEMENT is added, it is added at the beginning of the list,
```

Does that somehow not work correctly for you?

**Comment by nordlow** [comment]
> I'm not sure, I understand this request, as `:load-path` just calls `add-to-list`, which is already documented to add it to the beginning of the list:
> 
> ```
> If ELEMENT is added, it is added at the beginning of the list,
> ```
> 
> Does that somehow not work correctly for you?

Ahh, I missed that. I'm closing this for now. Thanks anyway.
