### ISSUE TITLE
Just a a couple of question

### ISSUE THREAD

**Issue by Ergus** [jwiegley/use-package#868]
1) I see that `leaf` is in elpa.. If john is one of the emacs maintainers why `use-packages` is not in elpa too?
2) Are there any plans to move `use-packages` into vanilla?

**Comment by MorganJamesSmith** [comment]
Elpa and Emacs require contributors assign their copyright to the FSF before code is accepted. See this issue for more information: https://github.com/jwiegley/use-package/issues/282

**Comment by skangas** [comment]
Yes, we are working on adding it to `emacs.git`.
