### ISSUE TITLE
Update the Info page

### ISSUE THREAD

**Issue by DSMasterson** [jwiegley/use-package#869]
At the very least, include a URL to this page in the Info page so that people can read the whole README.

**Comment by DSMasterson** [comment]
However, it would be much nicer if the README was converted to Info documentation.

I have installed use-package-20201110.2133 off of melpa.org/packages.  The internal comment in use-package.el suggests this is 2.4.1.  The Info document, though, has a copyright of 2012-2017 with no version number, so I can't tell when it was written.  It seems to match the use-package.texi file in the code here and, thus, appears quite out of date.

Could you use Pandoc to convert the README.md file to an Org file that replaces use-package.org and then use Org to export that file into Texinfo?

**Comment by skangas** [comment]
The manual has been rewritten in texinfo: https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=98e54f597e11fa760553bf7b12d8ebb388b5a488

I'm therefore closing this issue.
