### ISSUE TITLE
Does a ":load-path" declaration require to be follow by a keyword? 

### ISSUE THREAD

**Issue by cwagner2046** [jwiegley/use-package#871]
The declaration ":load-path ..." does not seem to like being followed by a declaration
without keyword. In the steps to reproduce given below, is the observation made in
step 2 the expected one, and why so? Thanks.
 
# Steps to reproduce:
1. add this to your .emacs initialisation file (or equivalent):
   (use-package cmuscheme48
     :load-path ("/usr/local/share/scheme48")
     (autoload 'run-scheme "cmuscheme48" "Run an inferior Scheme process." t)
     :init
     (setq scheme-program-name "scheme48"))
2. Start Emacs
    Observe the error message "Error (use-package): Failed to parse package cmuscheme48: use-package: :load-path wants a directory path, or list of paths".
3. Replace the aforementioned declaration by:
   (use-package cmuscheme48
     :load-path "/usr/local/share/scheme48"
     :init
     (setq scheme-program-name "scheme48")
     (autoload 'run-scheme "cmuscheme48" "Run an inferior Scheme process." t))
4. Repeat step 3
    Observe that no problem is reported.

**Comment by a13** [comment]
```
(use-package cmuscheme48
  :load-path ("/usr/local/share/scheme48")
  (autoload 'run-scheme "cmuscheme48" "Run an inferior Scheme process." t)
  :init
  (setq scheme-program-name "scheme48"))
```

this declaration is not valid, I can't even understand what are you trying to achieve

```
(use-package cmuscheme48
  :load-path "/usr/local/share/scheme48"
  :init
  (setq scheme-program-name "scheme48")
  (autoload 'run-scheme "cmuscheme48" "Run an inferior Scheme process." t))
```
this one is

What's the problem, doc?

**Comment by a13** [comment]
`M-x pp-macroexpand-last-sexp` is your friend

**Comment by skangas** [comment]
More information was requested, but none was provided within 2 years. I'm therefore closing this issue now.
