### ISSUE TITLE
Better version of unbind-key which really deletes bindings

### ISSUE THREAD

**Issue by minad** [jwiegley/use-package#884]
@jwiegley Would it be possible to provide a version of `bind-key/unbind-key` which removes the bindings instead of only overwriting them with `nil`? If `bind-key` is passed `nil` as argument, it could call `unbind-key`.

The following function seems to work. It is derived from https://github.com/tarsius/keymap-utils/blob/master/keymap-utils.el by @tarsius.

~~~ elisp
(defun remove-key (key &optional map)
  (setq map (or map global-map)
        key (if (vectorp key) key (vconcat (kbd key))))
  (define-key map key nil)
  ;; Split M-key in ESC key
  (setq key (mapcan (lambda (k)
                      (if (and (integerp k) (/= (logand k ?\M-\0) 0))
                          (list ?\e (logxor k ?\M-\0))
                        (list k)))
                    key))
  ;; Delete single keys directly
  (if (= (length key) 1)
      (delete key map)
    ;; Lookup submap and delete key from there
    (let* ((prefix (vconcat (butlast key)))
           (submap (lookup-key map prefix)))
      (unless (keymapp submap)
        (error "Not a keymap for %s" key))
      (when (symbolp submap)
        (setq submap (symbol-function submap)))
      (delete (last key) submap)
      ;; Delete submap if it is empty
      (when (= 1 (length submap))
          (remove-key prefix map)))))
~~~

**Comment by minad** [comment]
@jwiegley Would you accept a PR adding this version of `remove-key` as a replacement of `unbind-key`? It seems you require the fsf copyright assigment in order to contribute to this repository? I am asking also because of my other PRs #878 and #879.

**Comment by jwiegley** [comment]
Yes, I'd be happy to accept it once the copyright assignment is made.

**Comment by minad** [comment]
Thank you for your answer. I will finish the copyright assignment and create a PR.

**Comment by minad** [comment]
I finished the assignment, the PR is in #910.
