### ISSUE TITLE
Failed to install use-package from a clean emacs 27.1 startup

### ISSUE THREAD

**Issue by xuzhao9** [jwiegley/use-package#896]
After starting up emacs 27.1 with "-q" option, I run the following commands:

```
(require 'package)
(add-to-list 'package-archives `("melpa" . , "https://melpa.org/packages/"))
```
Then I run package-install use-package. Emacs shows it fails to install use-package 20201110.2133, error message:
Wrong type argument: stringp, use-package

A full paste of backtrace is here: https://pastebin.com/QjzByWzb

**Comment by jlokier** [comment]
It's not `use-package`, and you're not doing anything wrong. I'm seeing a lot of packages failing to update today, with the same error and similar backtrace.

Seems the `$NAME-pkg.el` files in *recent* packages have:

    (define-package NAME "VERSION" .... )

but all older versions and packages have:

   (define-package "NAME" "VERSION" ... )

The symbol `NAME` instead of the string `"NAME"` produces the error message.

**Comment by wkmanire** [comment]
It's not use-package that is the problem as was mentioned in other linked issues. This seems to be an issue with the package files in Melpa. If you go into your elpa file and find use-package-pkg.el you will see this:

```
(define-package use-package "2.4.1" "A configuration macro for simplifying your .emacs"
  '((emacs "24.3")
    (bind-key "2.4"))
  :commit "caa92f1d64fc25480551757d854b4b49981dfa6b" :authors
  (("John Wiegley" . "johnw@newartisans.com"))
  :maintainer
  ("John Wiegley" . "johnw@newartisans.com")
  :keywords
  ("dotemacs" "startup" "speed" "config" "package")
  :url "https://github.com/jwiegley/use-package")
;; Local Variables:
;; no-byte-compile: t
;; End:
```

Add double-quotes around `use-package` and it will work as normal. You'll need to repeat this for any other packages that you install with use-package that report the same issue. :/ Seems to be impacting both MELPA and MELPA-stable, indicates lack of proper testing or continuous integration on the part of MELPA. Hope they do something about this as far as a long term fix. Can't believe that both MELPA-stable and MELPA would be broken for the same reason at the same time.

**Comment by alphapapa** [comment]
> This seems to be impacting both MELPA and MELPA-stable which indicates lack of proper testing or continuous integration on the part of MELPA.

You can see in the recent MELPA commits that the CI is indeed failing since the commit that introduced the bug.  However, it's easy to overlook that little red X.  I'm sure the bug will be fixed soon.

**Comment by xuzhao9** [comment]
Thank everybody for the detailed explanation! Hope it will help others who also meet this problem. Since the root cause is unrelated with use-package, I will close the issue.

**Comment by alphapapa** [comment]
@wkmanire I may be reading it wrong, but it looks like that `sed` command will match package definitions for which the name is already a string.

**Comment by wkmanire** [comment]
> @wkmanire I may be reading it wrong, but it looks like that `sed` command will match package definitions for which the name is already a string.

There are two expressions, the first one says "Skip lines that already have the quotes". The second one does the edit. I used this myself and it seems to not have broken anything. If you do find a problem please let me know and I'll update my comment with the correction.

**Comment by alphapapa** [comment]
Thanks, I'm not an expert on the finer points of `sed`.  :)
