### ISSUE TITLE
compile error on use-package-pkg.el

### ISSUE THREAD

**Issue by pdagosto** [jwiegley/use-package#898]
OS: CentOS7
emacs version: 24.3.1

**Error Message**

define-package: Invalid function: ("John Wiegley" . "john@newartisans.com")

**Contents of use-package-pkg.el**

```
(define-package "use-package" "20201110.2133" "A configuration macro for simplifying your .emacs"
  '((emacs "24.3")
    (bind-key "2.4"))
  :commit "caa92f1d64fc25480551757d854b4b49981dfa6b" :authors
  (("John Wiegley" . "johnw@newartisans.com"))
  :maintainer
  ("John Wiegley" . "johnw@newartisans.com")
  :keywords
  ("dotemacs" "startup" "speed" "config" "package")
  :url "https://github.com/jwiegley/use-package")
;; Local Variables:                                                                                                                                                                           
;; no-byte-compile: t                                                                                                                                                                         
;; End:   
```

**Comment by conao3** [comment]
Why do you compile `*-pkg.el` file when  `;; no-byte-compile: t` is specified?

**Comment by pdagosto** [comment]
All I did was ask the emacs package installer to install the package. The compilation was performed automatically by emacs.

**Comment by conao3** [comment]
Please tell me(us) the step to reproduce?

**Comment by conao3** [comment]
Also, backtrace is very useful for this kind of bug report.

**Comment by pdagosto** [comment]
I already told you the step - install the package with the package manager. That's all I did.

**Comment by alphapapa** [comment]
Emacs 24.3 is almost 8 years old.  I don't know what's causing this problem, but few packages maintain compatibility going back 8 years, and few maintainers would be interested in spending the time to investigate software that old.  It's just not a good use of their time.  So you should probably upgrade Emacs.  It's not hard to do.

**Comment by skangas** [comment]
So we recommend upgrading to Emacs 25.1, and I'm closing this as wontfix. Thanks.
