### ISSUE TITLE
What happens if have multiple same (use-package PACKAGE_NAME ...) list?

### ISSUE THREAD

**Issue by snowman** [jwiegley/use-package#901]
Because I use someone else config like https://github.com/seagle0128/.emacs.d, which provided `init-treemacs.el`, which defines:

```elisp
(use-package treemacs
  :commands ...
  :bind ...
  :config  ...)
```

How could i add my own config with same package `treemacs` but without change `(use-package treemacs ...)` inside `init-treemacs.el` file?

**Comment by thomasf** [comment]
It will just be evaluated multiple times individually. So having `:disabled t` on one doesn't affect the other one at all. Order of execution might be important if you for example `:bind` the same keys to different commands.

**Comment by snowman** [comment]
Thanks for the answer :heart: 🎉 🥳 :partying_face: :tada:
