### ISSUE TITLE
Unknown theme ‘use-package’

### ISSUE THREAD

**Issue by aaronjensen** [jwiegley/use-package#902]
The recent theme changes broke byte compiled configs when you do not require `use-package` while compiled (as is the intention, if I understand correctly). It took forever to figure out what the problem was because I thought that no way there was a theme called `use-package` so I assumed a byte compiler error or something I did.

I tried with https://github.com/jwiegley/use-package/pull/899 and it does not help.

It might be worth reverting the change until it can be properly addressed. I'm happy to help test patches.

```
Debugger entered--Lisp error: (error "Unknown theme ‘use-package’")
  signal(error ("Unknown theme ‘use-package’"))
  error("Unknown theme `%s'" use-package)
  custom-theme-set-variables(use-package (display-line-numbers-grow-only t nil nil "Customized with use-package display-line-numbers"))
  byte-code("\3051\227\0\306\30\307\310\311\"\210)\312\313!\204\31\0\314\313\315\306\316$\210\317\320\313\"\210\321\301!\203\217\0\322\323\1!\203/\0\211\2022\0\324\1!..." [custom--inhibit-theme-enable leader-key-default-map global-map personal-keybindings use-package--warning209 (debug error) nil custom-theme-set-variables use-package (display-line-numbers-grow-only t nil nil "Customized with use-package display-line-numbers") fboundp global-display-line-numbers-mode autoload "display-line-numbers" t add-hook after-init-hook boundp "T n" vectorp read-kbd-macro key-description lookup-key assoc add-to-list define-key eval-after-load display-line-numbers #f(compiled-function () #<bytecode -0xdb4ea066cfbedaf>) :catch aj-config/init-el-start-section "Jump around" straight-use-package avy] 11)
```

**Comment by alexarice** [comment]
I get a similar error since the theme change. When I open emacs the warnings buffer is filled with the following.
```
Error (use-package): auctex-latexmk/:catch: Unknown theme ‘use-package’
Error (use-package): company/:catch: Unknown theme ‘use-package’
Error (use-package): doom-modeline/:catch: Unknown theme ‘use-package’
Error (use-package): flycheck/:catch: Unknown theme ‘use-package’
Error (use-package): ivy/:catch: Unknown theme ‘use-package’
Error (use-package): lsp-haskell/:catch: Unknown theme ‘use-package’
Error (use-package): merlin/:catch: Unknown theme ‘use-package’
Error (use-package): neotree/:catch: Unknown theme ‘use-package’
Error (use-package): nix-mode/:catch: Unknown theme ‘use-package’
Error (use-package): projectile/:catch: Unknown theme ‘use-package’
Error (use-package): rjsx-mode/:catch: Unknown theme ‘use-package’
Error (use-package): smartparens/:catch: Unknown theme ‘use-package’
Error (use-package): smooth-scrolling/:catch: Unknown theme ‘use-package’
Error (use-package): tex/:catch: Unknown theme ‘use-package’
Error (use-package): yasnippet/:catch: Unknown theme ‘use-package’
```
#899 also does not fix the error for me though everything works fine on version 2.4.1

**Comment by wanghaiqiangk** [comment]
I also met the same problem and tried #899 but no good.

When I inspect my config and I find I'm using `eval-when-compile` to load use-package.

```el
(eval-when-compile
  (require 'use-package))
```

I forgot the exact reason why I wrote like this. But after removing `eval-when-compile` and recompiling again, the errors disappear.

If this is also your case, try #889 + removing `eval-when-compile`

**Comment by aaronjensen** [comment]
Right, removing that works around the problem. The problem is that you should be able to use eval-when-compile but you can’t any longer.

**Comment by Walheimat** [comment]
Not sure if this is the reason, but changing themes now resets all customization using `:custom` keyword.

**Comment by tzz** [comment]
> Right, removing that works around the problem. The problem is that you should be able to use eval-when-compile but you can’t any longer.

Hi @aaronjensen and others commenting!

https://github.com/jwiegley/use-package/pull/899 specifically did `eval-and-compile` to work around the issue you've raised and I can't replicate the issue. Can you please provide a test case with `emacs -q` or even as a use-package test?

Thank you.

**Comment by aaronjensen** [comment]
@tzz I don't have a repro for you right now and I just tested 899 again. I believe the problem is that in the scenario I am describing, `use-package` is *not* required from our byte compiled config. That means it would be impossible for it to declare a theme. Specifically, use-package is required inside a `eval-when-compile`, which means that any themes it declares won't be there when the compiled file is evaluated.

I don't know what your config looks like, but try wrapping your `(require 'use-package)` in an `(eval-when-compile)` and byte compiling your config. Because `use-package` is entirely macros, this used to work fine (and is mentioned in the docs). But now, because it is expected a theme exists in order for those macros to be functional, they are not functional.

In order to fix this, I believe you need to ensure the theme is declared and enabled *in* the macro itself. This means doing it N times, once per `use-package` use, so you'd need to wrap it in a variable check, I would guess. Something like:

```el
(defvar use-package--theme-enabled)
(when (not use-package--theme-enabled)
  (deftheme use-package)
  (enable-theme 'use-package)
  (setq custom-enabled-themes (remq 'use-package custom-enabled-themes))
  (setq use-package--theme-enabled t))
```

**Comment by aaronjensen** [comment]
Oh, and for what it's worth, I would actually prefer that this entire custom theme behavior be opt-in or at least allow me to turn it off. I write my custom file to a tmp file so I don't actually care at all if use-package pollutes it. And, if I recall correctly, the times I opened that file I don't recall seeing any of the custom set variables from use-package in it. It seems like quite a hack to use a custom theme and remove it from the enabled themes just to do this. I don't understand it and I don't trust it, so I don't want it in my config. I've already spent considerable time trying to track down the issue introduced with it and it adds zero value for me.

It would be unfortunate if I was finally able to upgrade use-package once this issue is resolved only to run into things like https://github.com/jwiegley/use-package/issues/902#issuecomment-770754725 and who knows what else.

**Comment by tzz** [comment]
#907 attempts to address the issues raised here.

> I don't have a repro for you right now

@aaronjensen without a recipe or, even better, a test to reproduce an issue, resolving it by people who can't reproduce it will take much longer.

> Not sure if this is the reason, but changing themes now resets all customization using `:custom` keyword.

@Walheimat  I believe this issue is not the reason, and #899 (now merged) attempts to address what you're reporting.

> I write my custom file to a tmp file so I don't actually care at all if use-package pollutes it.

Unfortunately that's not the default Emacs behavior and thus the great majority of Emacs users are affected by double saving of variables.

> It seems like quite a hack to use a custom theme and remove it from the enabled themes just to do this.

Thank you for the feedback. We discussed this at length over many weeks in #881 #861 #856 #850 and concluded that custom themes were the best choice. I've attempted to make it possible to avoid the custom theme in #907 and would appreciate your review and comments there.

**Comment by aaronjensen** [comment]
> #907 attempts to address the issues raised here.

Thank you, I can confirm that it fixes both issues (i.e. it works when the theme is enabled for byte compiled configurations and it allows me to disable the behavior entirely).

> Unfortunately that's not the default Emacs behavior and thus the great majority of Emacs users are affected by double saving of variables.

Right. And for my own edification, the problem with double saving is that there ends up being two authorities? Does the use-package macro win or do the saved variables win? It seems like if the use-package macro wins, this is more of an aesthetic issue than anything, but I certainly don't have all the context. I do appreciate the links to the previous issues.

It is worth considering what the default behavior is. It seems like this addresses a problem for folks that use `:custom` *and* set custom variables using the customize interface. For anyone that doesn't do both, it is extra complexity that can cause subtle issues and it is surprising behavior. No one expects themes to be used in this way.

Thanks again for the fix.

**Comment by tzz** [comment]
> Thank you, I can confirm that it fixes both issues (i.e. it works when the theme is enabled for byte compiled configurations and it allows me to disable the behavior entirely).

Wonderful, we'll merge when it's approved.

> Right. And for my own edification, the problem with double saving is that there ends up being two authorities? Does the use-package macro win or do the saved variables win? It seems like if the use-package macro wins, this is more of an aesthetic issue than anything, but I certainly don't have all the context. I do appreciate the links to the previous issues.

I think duplicate settings are always dangerous. At best they are ignored, but the potential for confusion and accidental activation is always going to be there. So I don't think this is an aesthetic issue like indentation or directory layouts for example. But there's more discussion in the issues and PRs I linked, and it's certainly not a black and white distinction.

**Comment by tzz** [comment]
@aaronjensen  #907 has been merged, please close this issue or let me know what else needs to be fixed. Thank you.

**Comment by aaronjensen** [comment]
Thanks!
