### ISSUE TITLE
FIle extension specific configs within a single mode

### ISSUE THREAD

**Issue by danieljamesross** [jwiegley/use-package#911]
Hello,

I can't find the asnwer to this, any help greatly appreciated.

How can I set the `:config` or `:hook` of a `use-package` instance so that it's behaviour is dependant on a file extension?

For example:

I want to use `web-mode` with `.html` and `.tsx` files. I also want `web-mode` to load a minor mode _only_ when `.tsx` files are opened. Something like the following:

```lisp
(use-package web-mode
  :ensure t
  :mode (("\\.tsx$"     . web-mode)
	 ("\\.html$"    . web-mode))
  :hook (unless (html-file-p) (setup-my-minor-mode)))
```

What is the equivalent syntax for my made-up function `html-file-p`? Is this the way to do this or is there a better way?

Thanks in advance!

**Comment by conao3** [comment]
First, your sample use-package is correct?
```
(setq use-package-expand-minimally t)
;;=> t

(macroexpand
 '(use-package web-mode
    :ensure t
    :mode (("\\.tsx$"     . web-mode)
	   ("\\.html$"    . web-mode))
    :hook (unless (html-file-p) (setup-my-minor-mode))))
;;=> (progn
;;     (use-package-ensure-elpa 'web-mode '(t) 'nil)
;;     (unless (fboundp 'web-mode) (autoload (function web-mode) "web-mode" nil t))
;;     (add-hook 'unless-hook (function web-mode))
;;     (add-hook 'html-file-p-hook (function web-mode))
;;     (add-hook 'setup-my-minor-mode-hook (function web-mode))
;;     (add-to-list 'auto-mode-alist '("\\.tsx$" . web-mode))
;;     (add-to-list 'auto-mode-alist '("\\.html$" . web-mode)))
```
there's no `unless-hook` I think.

**Comment by danieljamesross** [comment]
Hey, thanks for replying. I know that the elisp I provided is incorrect. I'm looking for help to implement something _like_ it, i.e. mimic the functionality. I want to be able to conditionally load hooks based on the filetype.

**Comment by conao3** [comment]
I think there're no keyword, so we can this use normal lambda hook at find-file-hook.
```elisp
(use-package web-mode
  :ensure t
  :mode (("\\.tsx$"     . web-mode)
	 ("\\.html$"    . web-mode))
  :hook (find-file . (lambda (elm)
                       (unless (string-match "\\.html$" (buffer-file-name))
                         (setup-my-minor-mode)))))
```
(this use-package should work, but I haven't tested yet)

**Comment by danieljamesross** [comment]
Oh this is exactly what I was looking for. Thank you very much. Will test and report back. I will close the issue though.

Many thanks!
