### ISSUE TITLE
Question: can you pin specific versions / tags ?

### ISSUE THREAD

**Issue by PeterMosmans** [jwiegley/use-package#913]
Hi,

Thanks for use-package, great extension!
This is more of a question (or feature request) than 'issue', but can you pin specific versions or tags of packages?
For instance can you specify something like
```
(use-package helm
:pin "melpa-stable:3.7.0"
)
```
to ensure that version `3.7.0` published on melpa-stable is installed?

Thanks!

**Comment by conao3** [comment]
use-package is not a package manager/downloader, it can't.
You may like [el-get](https://github.com/dimitri/el-get) and use-package integrator, [use-package-el-get](https://github.com/edvorg/use-package-el-get)

**Comment by skangas** [comment]
@conao3 answered the question, so I'm closing this issue. Thanks.
