### ISSUE TITLE
Does use-package appliy :custom before or after the package is loaded?

### ISSUE THREAD

**Issue by philip-bl** [jwiegley/use-package#923]
Hi. I want to customize a variable. I want to determine its value programmatically from its default value proposed by the package's author. To do this, I want to use `:custom`. However, use-package's documentation doesn't tell me if it executes `:custom` before or after the package is loaded. Please improve the documentation by writing the answer to this question in it.

**Comment by conao3** [comment]
Actually, you don't need to care about it. Your customizations will be successfully reflected and retained, whether before or after the package is loaded.
This is not a use-package, but a defcustom specification, so it is better to read its documentation.

**Comment by skangas** [comment]
@conao3 answered the question here, so I'm closing this issue. Thanks.
