### ISSUE TITLE
Clarify use of :hook with only the name of a hook provided

### ISSUE THREAD

**Issue by hugonobrega** [jwiegley/use-package#924]
In the readme, one of the examples for adding a hook for loading a package is
```elisp
(use-package ace-jump-mode
  :hook prog-mode)
```
As I understand it, this use of `:hook` with just the name of the hook to add to (well, minus the `-hook`) will only work under certain conditions, for example when the package name coincides with a function defined by the package (as in the case of `ace-jump-mode` and its own minor mode). It is that function that is added to the specified hook.

I suggest adding a sentence clarifying this to the readme. Since I don't know the exact set of conditions for this to work, I thought it would be better to create this issue rather than a PR as that would be likely to be incomplete.

**Comment by skangas** [comment]
I believe this is already documented in the new use-package manual, that will be in the version of use-package distributed with Emacs 29: https://git.savannah.gnu.org/cgit/emacs.git/commit/?h=emacs-29&id=98e54f597e11fa760553bf7b12d8ebb388b5a488

I'm therefore closing this issue.

**Comment by muello** [comment]
Unfortunately, that documentation (in the linked commit) has had me confused for a while. The relevant sentence reads "The ‘:hook’ keyword will also assume that the name of the function you want to add is the same as the package name with ‘-mode’ appended to it."

To me this suggests that the function we want to add in the example is "company-mode" ("company" with "-mode" appended), whereas the example code tries to load a function named "company".

I'm looking at 4.3 Hooks. Am I perhaps missing something?
