### ISSUE TITLE
Confused by something in the Readme.md

### ISSUE THREAD

**Issue by verslyfr** [jwiegley/use-package#932]
The README.md indicates the following code causes the key binding to be done in **helm-mode-map**, but the keymap name appears to be **helm-command-map**. This change in the names of the map has me confused. Is it a typo, or can an explanation be added how we go from helm-command-map to helm-mode-map?

README.md Snippet
--- 
 
``` elisp
(use-package helm
  :bind (:map helm-command-map
         ("C-c h" . helm-execute-persistent-action)))
```

The effect of this statement is to wait until `helm` has loaded, and then to
bind the key `C-c h` to `helm-execute-persistent-action` within Helm's local
keymap, `helm-mode-map`.

**Comment by matta** [comment]
It is just a typo in the README. It binds to `helm-command-map` as written in the code sample.

Try `M-x pp-macroexpand-last-sexp` with the cursor at the end of a `use-package` form to see what it expands to.

**Comment by skangas** [comment]
This seems to have been fixed, so I'm closing this issue now.
