### ISSUE TITLE
About the usage of `:commands` and `:hook`.

### ISSUE THREAD

**Issue by hongyi-zhao** [jwiegley/use-package#937]
I want to know if the following two settings are equivalent.

```emacs-lisp
(use-package company-lsp :commands company-lsp)
```
and

```emacs-lisp
(use-package company-lsp)
(require 'company-lsp)
```
Regards,
HY

**Comment by thomasf** [comment]
If you are using the default use-package settings they are not equal.

`(use-package company-lsp :commands company-lsp)`  does not require the package since `:commands` makes it lazy load when that command is invoked.

The corresponding basic plain Emacs LISP expression would be:

```el
(unless
    (fboundp 'company-lsp)
  (autoload #'company-lsp "company-lsp" nil t))
```

```(use-package company-lsp)``` already requires the company-lsp feature so the additional `(require ...)` does nothing.

**Comment by hongyi-zhao** [comment]
Thank you for clarification. Then how to simplify/enhance the following code snippet in order to take full advantage of use-package's capabilities and features:
```emacs-lisp
(use-package company)
(add-hook 'after-init-hook 'global-company-mode)

(use-package yasnippet :commands yasnippet)
(yas-reload-all)
(add-hook 'prog-mode-hook #'yas-minor-mode)
```

**Comment by doolio** [comment]
The following forms should do what you want:

```
(use-package company
  :hook (after-init . global-company-mode))
```

```
(use-package yasnippet
  :commands yasnippet      ;; Only necessary if a package does not already define an autoload for the specific command
  :hook (prog-mode . yas-minor-mode))
```

**Comment by hongyi-zhao** [comment]
By saying something is a command, it means that is defined `interactive`. But this thing is not defined with `interactive`, can I still use `:commands` on it?

**Comment by doolio** [comment]
I believe you can but there would be little point in doing so in that case.

**Comment by doolio** [comment]
No, my understanding is that `:commands` creates an autoload if one does not exist already. And an autoload speeds up the loading of the package when it is eventually loaded.

**Comment by skangas** [comment]
It seems like the support questions here were answered (thanks all). I'm therefore closing this issue now.
