### ISSUE TITLE
Dependent packages installation with one use-package command.

### ISSUE THREAD

**Issue by hongyi-zhao** [jwiegley/use-package#940]
Say, I want to install a package A, which in itself dependent on other packages, B and C. In this case, how to install them all in one use-package command?

Regards,
HY

**Comment by doolio** [comment]
Firstly, `use-package` is not a package manager rather it simplifies package configuration. I presume you are using the `:ensure` keyword in your `use-package` forms to use `package.el` to install packages. If so then installing package A will also install its dependencies B and C.

```
(use-package A
  :ensure t)
```

**Comment by skangas** [comment]
This support question was answered, so I'm closing this issue now.
