### ISSUE TITLE
Installing a package from a local directory

### ISSUE THREAD

**Issue by fakedrake** [jwiegley/use-package#942]
I would like to create a directory in my configuration called something like `~/.emacs.d/packages/` and I would like `use-package` to look there for packages before going for other sources. I would even be happy if I could use a keyword like `:local-package path/to/local/package` to achieve the same result. Is there such a feature available and if not could someone give me a general direction on how to implement it? 

Thanks

**Comment by progfolio** [comment]
I suggest reading up on Emac's load-path.
If you wish to extend the load-path on a per-package basis, see:
https://github.com/jwiegley/use-package#extending-the-load-path

If you want to do it globally, that's something you should probably set up prior to your use-package declarations.
There are numerous resources on doing that, e.g.

https://stackoverflow.com/questions/7322246/adding-subdirectories-to-load-path

**Comment by skangas** [comment]
This question was answered, so I'm closing this issue now.
