### ISSUE TITLE
Executing `describe-function` in `use-package-autoloads/:bind*` results in *Help* asking for making a bug report

### ISSUE THREAD

**Issue by rdrg109** [jwiegley/use-package#952]
# Introduction

This is a **bug report**, but I think this have to do with Emacs instead of `use-package`. However, I'm creating this issue just in case I'm wrong.

# Reproduce this bug

To reproduce this bug, follow these steps

1. Don't load the package.
2. Execute `(describe-function 'use-package-autoloads/:bind*)`
3. The `*Help*` buffer shows the following message

```
use-package-autoloads/:bind* is an alias for
‘use-package-autoloads-mode’, which is not defined.  Please make a bug
report.

Not documented.
```

# Personal thoughts

I'm not sure whether this is relevant enough for creating an issue, but I'm creating this post just in case anyone else want to report the same issue.

**Comment by skangas** [comment]
This is a general problem with Emacs, not with `use-package` itself. If you want to open a bug report about it, please email `bug-gnu-emacs@gnu.org`. I'm therefore closing this bug.
