### ISSUE TITLE
keybind with macro issue

### ISSUE THREAD

**Issue by 354651432** [jwiegley/use-package#953]
I want to rebind `backward-up-list` to my function generate by a macro ,but it tell me `(error "use-package: web-mode wants arguments acceptable to the `bind-keys' macro, or a list of such values")`
here is my code
```emacs lisp
(defmacro web-mode-rebind-key(src dst)
  `(lambda()
	(interactive)
	(let ((point (point)))
	  (unless (ignore-errors (,src) t)
	  (goto-char point)
	     (,dst)))))

(use-package web-mode
  :mode ("\\.html\\'" "\\.vue\\'")
  :custom
  (tab-width 2)
	:bind (:map web-mode-map
	([remap backward-up-list] . (web-mode-rebind-key backward-up-list web-mode-element-parent))))
```

and if possible ,I want to generate `cons`es use macro , so I can omited second `backward-up-list`

**Comment by matta** [comment]
In this case `:bind` is probably not the right tool. It is intended to make simple calls to `bind-key` easier. In particular, it makes the assumption that the commands bound actually come from the package itself (in this case `web-mode`). You want something different: you want to define new commands.

I think it would be better to just do what you want to do in a `:config` form. That is plain lisp code that is executed after the package is loaded. You could start by making a single `defun` that set up `web-mode` exactly as you like, and then calling it in a `:config` form. That would be easier to debug.

**Comment by Thaodan** [comment]
I noticed something similar I tried to bind a hydra with bind key it didn't work because no function could be defined.

```
Debugger entered--Lisp error: (error "Autoloading file /home/bidar/.emacs.d/lib/gnus-notes/gnus-notes-org.el failed to define function gnus-notes-org-handle-email")
  command-execute(gnus-notes-org-handle-email)
```

**Comment by skangas** [comment]
The answer here is to use `:config`, so I'm closing this bug.
