### ISSUE TITLE
Inconsistent form indentation with local maps

### ISSUE THREAD

**Issue by memeplex** [jwiegley/use-package#957]
Compare

```elisp
  :bind (("x" . x)
         :map local-map
         ("y" . y)))
```

to

```elisp
  :bind (:map local-map
              ("y" . y)))
```

The inconsistent indentation happens when you only have local bindings so then `:bind` clause starts with `:map`.

I understand the specific indentation rules are defined by use-package.

**Comment by doolio** [comment]
Yes, I notice the same inconsistency but resolved it as follows:

```
  :bind (nil
         :map local-mode-map
         ("y" . y)))
```

That is be explicit that you are not configuring any global bindings. Hope that helps.

**Comment by skangas** [comment]
Closing this as a duplicate of #887. The recommended workaround for now is to add a space, like so:

```
(use-package foo
  :bind ( :map local-map
          ("y" . y)))
```
