### ISSUE TITLE
Linter shows weird errors for use-package

### ISSUE THREAD

**Issue by memeplex** [jwiegley/use-package#958]
I cannot understand what's going on here:

![image](https://user-images.githubusercontent.com/2845433/136840031-0c9182a0-8da6-4849-bf66-492532338808.png)

I don't know a lot about macros, but maybe some kind of syntax descriptor or whatever provided by use-package is wrong. Or the expansion itself, although the code performs as expected, it's just the linter that goes nuts about it.

**Comment by doolio** [comment]
Try:

```
(use-package avy-jump
  :ensure avy
  :bind (("C-;" . avy-goto-char-2)
         ("C-:" . avy-goto-line)))
```

**Comment by skangas** [comment]
It seems like the above reply resolved this, so I'm closing this issue now.
