### ISSUE TITLE
documentation request: Highlight `:demand`

### ISSUE THREAD

**Issue by paaguti** [jwiegley/use-package#972]
Currently, the `:demand` keyword is mentioned in a note. It took me quite some time to figure out that
1) it existed
2) it did what I needed it to do.

I suggest you include it in the same section where you describe `:load-path`
I have moved some personal elisp code to local packages and I struggled to get one of my packages unconditionally loaded until I stumbled upon the note.

**Comment by skangas** [comment]
This has been fixed in the new use-package manual, now merged into Emacs itself: https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=98e54f597e11fa760553bf7b12d8ebb388b5a488

I'm therefore closing this issue.
