### ISSUE TITLE
Evaluating use-package sexp returns nil

### ISSUE THREAD

**Issue by kirk86** [jwiegley/use-package#982]
Hi, I have the following sexp in my init.el

```
(use-package transient
   :ensure t
   :demand t)
```
evaluating it `C-x C-e` returns nil.

Any ideas why, shouldn't it download and install the package?

**Comment by jasonhemann** [comment]
@kirk86, evaluating that sexp in my init.el gives a non-nil result. I assume you've tried this from a near-minimal variant of your init.el, yes?

**Comment by skangas** [comment]
More information was requested, but none was given within 2 months, so I'm closing this bug. Please report back if you can provide more information. Thanks.
