### ISSUE TITLE
Build error on https://jwiegley.github.io/use-package/

### ISSUE THREAD

**Issue by PRESFIL** [jwiegley/use-package#983]
Travis stopped reassembling the site with documentation, for a very long time ;)

> Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

**Comment by skangas** [comment]
Thanks for the report.

I believe we are planning to deprecate the documentation on that site, so I don't think there's any need to fix it.  I'm therefore closing this bug.
