### ISSUE TITLE
Docs missing an example of adding multiple regexp for the same mode

### ISSUE THREAD

**Issue by jasonhemann** [jwiegley/use-package#996]
Right now the docs for the `:mode` keyword show how to add a single regexp to the `auto-word-alist` but don't show how to add multiple regexps.

1. I could imagine wanting to add with a single `:mode` keyword arg several different regexps that all should be added to a single mode.
2. I could imagine wanting a shorthand, say, if the package name _is_ the name of the mode, I should still get to succinctly list the regular expressions. 
3. I think I could imagine a given package defining two modes, so that two different regular expressions would match two different modes, and you'd want to/need to specify which mode goes with which regexp. 

At least at present, I can't find any of those examples listed in the `:mode` documentation.

**Comment by doolio** [comment]
Does the following not work for you?

```emacs-lisp
(use-package foo
  :mode ("\\.bar\\'"
         "\\.baz\\'"))
```

This simple example associates files with extensions `.bar` or `.baz` with `foo-mode` provided by the `foo` package.

**Comment by jasonhemann** [comment]
Ah. I have no doubt that would work. Adding an example like that to the documentation would close this issue for me

**Comment by skangas** [comment]
This has been fixed in the new use-package manual, now merged into Emacs itself: https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=141fe8b827399057e2f854cd5e6b0c148c5fe12b

I'm therefore closing this issue.
