### ISSUE TITLE
Change repository to use a fork

### ISSUE THREAD

**Issue by tobiasBora** [jwiegley/use-package#999]
Because of [this issue](https://github.com/syl20bnr/spacemacs/issues/15541) I need to change the location of the sources of the `auctex-latexmk` package to use a fork. Unfortunately I can't find any way to specify the address of a fork in `use-package`. Do you know how I could work it out? It would be great to have something like:
```
(use-package auctex-latexmk
  :ensure t
  :location (recipe :fetcher github :repo "smile13241324/auctex-latexmk")
  :config
  (auctex-latexmk-setup)
  (setq auctex-latexmk-inherit-TeX-PDF-mode t))
```  
as spacemacs.

**Comment by parona-source** [comment]
Using straight.el with use-package would have that functionality

https://github.com/radian-software/straight.el#integration-with-use-package
https://github.com/radian-software/straight.el#git-backend

**Comment by tobiasBora** [comment]
Nice, thanks!
